### ISSUE TITLE
使 `Admin` 能夠宣告偏好的 Data Directory

### ISSUE THREAD

**Issue by garyparrot** [skiptests/astraea#1043]
先前 Blocking 版本的 `Admin` 有 `declarePreferredDir` 的功能能使用

https://github.com/skiptests/astraea/blob/b971381754c46b7936e98354f6a0540d508666ec/common/src/main/java/org/astraea/common/admin/Builder.java#L669-L709

不過現在 Async 版本的 Admin 沒有這個功能。缺乏這個功能會讓 `RebalancePlanExecutor` 原本能一口氣做好的搬移(資料透過網路直接複製到對的資料夾)變成要實際移動所有資料兩次(資料透過網路複製到某個 Broker 喜歡的資料夾，然後再從那個資料夾移動到對的資料夾)

應該將這個實用的功能塞回 Async Admin

**Comment by garyparrot** [comment]
@chia7712 我發現 `SyncReplicaMigrator` 的 interface 還存在 codebase 內，只是沒有用上，我們後面還會透過這個界面來操作 replica 嗎？還是我們打算把所有相關的函數都直接實作在 `Admin` 上。

如果是後者的話我就直接把這個函數放到 `Admin` 的 interface 上。

**Comment by chia7712** [comment]
> 原本能一口氣做好的搬移(資料透過網路直接複製到對的資料夾)變成要實際移動所有資料兩次(資料透過網路複製到某個 Broker 喜歡的資料夾，然後再從那個資料夾移動到對的資料夾)

如果是指要一次搬移到“指定節點上的指定目錄“，不用透過declarePreferredDir，可以用以下流程取代：

1. admin#moveToBrokers (先開始移動到指定節點)
2. admin#waitCluster (確定都開始移動了)
3. admin#moveToFolders (移動到指定目錄)

上述的 1) and 3) 雖然在中間會有一小段的資料浪費（放到非預期的目錄），但這個成本應該不會太高
