### ISSUE TITLE
Apache開源專案開發與分散式系統資料串流 作業說明

### ISSUE THREAD

**Issue by chia7712** [skiptests/astraea#105]
這個議題用來搜集課程的github帳號與名字對應，麻煩同學們留言以下資訊
1. 姓名
2. 專案網址 (GitHub project)

# 作業一：KIP報告

1. 每個人負責報告一項Kafka Improvement Proposal
1. 報告時間為課程最後兩個禮拜
1. 每個人有15~20分鐘的時間分享
1. 分享方式不拘，投影片、寫板書、說唱都跳都可
1. 報告順序為隨機

學生 | KIP | Link
-- | -- | --
吳威廷 | KIP-788 | https://cwiki.apache.org/confluence/display/KAFKA/KIP-788%3A+Allow+configuring+num.network.threads+per+listener
孫祥鈞 | KIP-773 | https://cwiki.apache.org/confluence/display/KAFKA/KIP-773%3A+Differentiate+consistently+metric+latency+measured+in+millis+and+nanos
宋可易 | KIP-764 | https://cwiki.apache.org/confluence/display/KAFKA/KIP-764%3A+Configurable+backlog+size+for+creating+Acceptor
張君如 | KIP-748 | https://cwiki.apache.org/confluence/display/KAFKA/KIP-748%3A+Add+Broker+Count+Metrics
方竫泓 | KIP-735 | https://cwiki.apache.org/confluence/display/KAFKA/KIP-735%3A+Increase+default+consumer+session+timeout
李仲恩 | KIP-734 | https://cwiki.apache.org/confluence/display/KAFKA/KIP-734%3A+Improve+AdminClient.listOffsets+to+return+timestamp+and+offset+for+the+record+with+the+largest+timestamp
李政憲 | KIP-709 | https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=173084258
林宥駒 | KIP-707 | https://cwiki.apache.org/confluence/display/KAFKA/KIP-707%3A+The+future+of+KafkaFuture
汪宗諺 | KIP-700 | https://cwiki.apache.org/confluence/display/KAFKA/KIP-700%3A+Add+Describe+Cluster+API
王懿宸 | KIP-699 | https://cwiki.apache.org/confluence/display/KAFKA/KIP-699%3A+Update+FindCoordinator+to+resolve+multiple+Coordinators+at+a+time
簡志瑋 | KIP-691 | https://cwiki.apache.org/confluence/display/KAFKA/KIP-691%3A+Enhance+Transactional+Producer+Exception+Handling
葉怡君 | KIP-679 | https://cwiki.apache.org/confluence/display/KAFKA/KIP-679%3A+Producer+will+enable+the+strongest+delivery+guarantee+by+default
邱楚盦 | KIP-673 | https://cwiki.apache.org/confluence/display/KAFKA/KIP-673%3A+Emit+JSONs+with+new+auto-generated+schema
鄧智懋 | KIP-612 | https://cwiki.apache.org/confluence/display/KAFKA/KIP-612%3A+Ability+to+Limit+Connection+Creation+Rate+on+Brokers
鄭育丞 | KIP-608 | https://cwiki.apache.org/confluence/display/KAFKA/KIP-608+-+Expose+Kafka+Metrics+in+Authorizer
陳冠廷 | KIP-604 | https://cwiki.apache.org/confluence/display/KAFKA/KIP-604%3A+Remove+ZooKeeper+Flags+from+the+Administrative+Tools
陳洛翔 | KIP-599 | https://cwiki.apache.org/confluence/display/KAFKA/KIP-599%3A+Throttle+Create+Topic%2C+Create+Partition+and+Delete+Topic+Operations
魏連興 | KIP-590 | https://cwiki.apache.org/confluence/display/KAFKA/KIP-590%3A+Redirect+Zookeeper+Mutation+Protocols+to+The+Controller
黃智垣 | KIP-586 | https://cwiki.apache.org/confluence/display/KAFKA/KIP-586%3A+Deprecate+commit+records+without+record+metadata
黃牧恩 | KIP-606 | https://cwiki.apache.org/confluence/display/KAFKA/KIP-606%3A+Add+Metadata+Context+to+MetricsReporter

# 作業二：使用kafka producer寫程式餵資料給kafka叢集

程式所需參數:
1. --brokers: kafka broker的位址
2. --topic: 目標topic
3. --records: 資料筆數
4. --recordSize: 每一筆資料的大小

下方是一個範例:
```
java -jar your_jar --brokers 192.168.10.2:11111 --topic chia --records 10000 --recordSize 1000
```

資料內容規定:
1. key必須為字串格式，內容為"key-第幾筆的編號"，例如"key-000000"
2.  value必須為字串格式，內容為"value-第幾筆的編號"，例如"value-000000"
3. 換言之，key and value都是唯一！！！

評分方式：
1. 速度越快越高分
2. 資料格式不對則0分
3. 資料筆數不對則0分
4. 資料大小誤差太大(超過50%)的話則0分
5. 請在個人repo的release page中提供可執行的jar檔，以最新release為準

快速建立kafka叢集:

1. `git clone https://github.com/skiptests/astraea`
1. `cd astraea`
1. `./docker/start_zookeeper.sh`
    - 此腳本會利用docker建立單一節點的zookeeper service
    - 並且會提供用來建立(kafka) broker的腳本指令
1. `./docker/start_broker.sh zookeeper.connect=192.168.50.178:19227`
    - 此指令重複執行可增加叢集的節點數量

**Comment by idoleat** [comment]
簡志瑋 https://github.com/idoleat/FeedKafka

**Comment by AxotZero** [comment]
陳洛翔 https://github.com/AxotZero/Kafka-HW1-Feeder

**Comment by garyparrot** [comment]
李政憲 https://github.com/garyparrot/KafkaGoBrrr

**Comment by chinghongfang** [comment]
方竫泓 https://github.com/chinghongfang/kafkaProduce

**Comment by chungen0126** [comment]
李仲恩 https://github.com/chungen0126/kafka-homework.git

**Comment by hm575830** [comment]
魏連興 https://github.com/hm575830/Kafka_Producer_HW.git

**Comment by crowttt** [comment]
陳冠廷 https://github.com/crowttt/kafka_producer.git

**Comment by qoo332001** [comment]
孫祥鈞 [https://github.com/qoo332001/kafkahomework](https://github.com/qoo332001/kafkahomework)

**Comment by wycccccc** [comment]
王懿宸 https://github.com/wycccccc/Performance-KafkaProduce.git

**Comment by Libazhe** [comment]
吳威廷 https://github.com/Libazhe/Kafka_producer

**Comment by huang-me** [comment]
黃牧恩 https://github.com/huang-me/kafka_Producer

**Comment by eddie9712** [comment]
汪宗諺 [https://github.com/eddie9712/Kafka_producer-consumer_example](https://github.com/eddie9712/Kafka_producer-consumer_example)

**Comment by eecheng87** [comment]
鄭育丞 https://github.com/eecheng87/Kafka-producer

**Comment by steinsgateted** [comment]
林宥駒 https://github.com/steinsgateted/kafkahw.git

**Comment by harryteng9527** [comment]
鄧智懋 https://github.com/harryteng9527/KafkaHomework

**Comment by chia7712** [comment]
@crowttt 不好意思，最新版的程式碼有一個狀況（see https://github.com/crowttt/Kafka_Producer_HW/issues/1)，請在禮拜一下午六點前修正完成，以利打分數，謝謝

**Comment by chia7712** [comment]
@Libazhe 不好意思，現在的release jar並非可執行的檔案，因為你是用maven打包程式碼，可否請你參考https://maven.apache.org/plugins/maven-shade-plugin/examples/includes-excludes.html 來重新包裝uber jar？謝謝

**Comment by chia7712** [comment]
@huang-me 不好意思，能發麻煩你建立好uber jar檔後上傳到release page，請在禮拜一下午六點前修正完成，以利打分數，謝謝

**Comment by chia7712** [comment]
@eddie9712 不好意思，程式在解析輸入參數有一個狀況 (https://github.com/eddie9712/Kafka_producer-consumer_example/issues/1 )，請在禮拜一下午六點前修正完成，以利打分數，謝謝

**Comment by chia7712** [comment]
@steinsgateted 麻煩在禮拜一下午六點前上傳über jar到release page，以利打分數，謝謝
