### ISSUE TITLE
Remove preferredLeaderElection from Balancer

### ISSUE THREAD

**Issue by chia7712** [skiptests/astraea#1055]
這是一個討論用的議題：

我們現在把"運行 preferred replicas election"綁定在balancer上面，但是該行為必須等到 preferred replicas 完成同步後才可以執行，這個要求會導致執行 balance plan 卡在一個”已知但未定“的時間上，這會導致後續的流程出狀況

或許，我們並不需要手動去呼叫選舉，kafka 本來就有執行緒會定時巡邏並觸發 leader election，我們可以把這個工作留給 kafka 就好

**Comment by chia7712** [comment]
@garyparrot 你覺得呢？

**Comment by garyparrot** [comment]
> 我們現在把"運行 preferred replicas election"綁定在balancer上面，但是該行為必須等到 preferred replicas 完成同步後才可以執行，這個要求會導致執行 balance plan 卡在一個”已知但未定“的時間上

我感覺副作用只有會執行比較久，這個應該是可以接受的。
如果是擔心執行比較久的話，我們也可以提出 preferred replica election 然後就直接結束，不等 leadership 更換完成

> 這會導致後續的流程出狀況

想問會出什麼狀況

> 或許，我們並不需要手動去呼叫選舉，kafka 本來就有執行緒會定時巡邏並觸發 leader election，我們可以把這個工作留給 kafka 就好

我原本預期計劃執行完之後叢集就會反映他先前計算出來的結果。
如果改成這種執行方式，使用者會覺得怪怪的，明明計劃已經完成但是叢集卻沒有反映出應有的結果。

自動選舉只有在 `auto.leader.rebalance.enable` 是 `true` 的時候會生效，如果使用者有私下改成 `false` 的話這部分可能會有問題。

**Comment by chia7712** [comment]
> 我們也可以提出 preferred replica election 然後就直接結束，不等 leadership 更換完成

如果 preferred leader replica 是新加入的那就必須等到 sync 完成，否則發出請求會收到錯誤

> 想問會出什麼狀況

這是個“已知但時間未定”的行為，會導致後續的流程都必須配合這個可能執行很久的操作。例如，web apis 會一直卡在”balance plan 執行中“，而不是"replica同步中“，前者給人的感覺是我們的balancer有bugs、後者是預期的行為。又或者 GUI 這邊必須多一個畫面來查看執行中的balance plan

> 如果改成這種執行方式，使用者會覺得怪怪的，明明計劃已經完成但是叢集卻沒有反映出應有的結果。

如我前面提到，balancer plan執行完成 和 資料同步完成 應該是拆開的兩個動作，如果這兩個動作合在一起，我們會無法辨識出執行的階段，進而產生上述的尷尬狀況

> 自動選舉只有在 auto.leader.rebalance.enable 是 true 的時候會生效，如果使用者有私下改成 false 的話這部分可能會有問題。

這個通常不會有人設定成 false，我覺得不需要特別去考慮這種稀有案例

**Comment by garyparrot** [comment]
> 例如，web apis 會一直卡在”balance plan 執行中“，而不是"replica同步中“，前者給人的感覺是我們的balancer有bugs、後者是預期的行為。

我一直都覺得同步操作是 Balance Plan 的一部分流程，所以我不覺得這是一種 bug。我個人感覺是 Balancer 結束，使用者就要看到負載平衡的效果，如果 Balancer 結束我沒有看到負載便得平衡，反而有一堆 Reassignment 的流量在系統裡面飄，每個節點的吞吐量因為成本而上升，這時我會感覺 Balancer 把我的叢集搞砸了。

而且如果把等待和 Balance 的操作抽離的話，我們以後會沒辦法做 Batch 型的 RebalancePlanExecutor。

**Comment by chia7712** [comment]
> 反而有一堆 Reassignment 的流量在系統裡面飄，每個節點的吞吐量因為成本而上升，這時我會感覺 Balancer 把我的叢集搞砸了。

就算我們把兩個動作綁在一起，使用者還是會看到這個過程。現在要討論的重點是`RebalancePlanExecutor`這個角色到底要負擔哪些責任？究竟是只要執行 plan？還是同時要等所有資料同步完成？

> 如果把等待和 Balance 的操作抽離的話，我們以後會沒辦法做 Batch 型的 RebalancePlanExecutor。

請問一下這邊的 batch 是指什麼？

**Comment by garyparrot** [comment]
> 就算我們把兩個動作綁在一起，使用者還是會看到這個過程。現在要討論的重點是RebalancePlanExecutor這個角色到底要負擔哪些責任？究竟是只要執行 plan？還是同時要等所有資料同步完成？

我先前的設計是這兩個都是他的責任。至於各自實作可能可以有自己的好處。像下面提到的 Batch

>> 如果把等待和 Balance 的操作抽離的話，我們以後會沒辦法做 Batch 型的 RebalancePlanExecutor。
>>
> 請問一下這邊的 batch 是指什麼？

現在的 `StraightPlanExecutor` 在遇到大量搬移的情況下會有問題。

比如有 100 個搬移要做，他會立刻調度這 100 個搬移，這 100 多個搬移會去競爭有限的硬體資源。這個競爭可能會導致每個搬移的進度都落後，始得某些搬移永遠都沒辦法完成（輸入速度 > 複製速度）。

所以我想說以後可以推出一個 `BatchPlanExecutor`，他不會一次調度所有的搬移，他會知道一次調度多少搬移才算是適當，一次調度一部分的任務，這一批做完了調度其他的進來做。為了做到這件事情，他會需要等待既有的資料同步完成。

**Comment by chia7712** [comment]
> 比如有 100 個搬移要做，他會立刻調度這 100 個搬移，這 100 多個搬移會去競爭有限的硬體資源。這個競爭可能會導致每個搬移的進度都落後，始得某些搬移永遠都沒辦法完成（輸入速度 > 複製速度）。
所以我想說以後可以推出一個 BatchPlanExecutor，他不會一次調度所有的搬移，他會知道一次調度多少搬移才算是適當，一次調度一部分的任務，這一批做完了調度其他的進來做。為了做到這件事情，他會需要等待既有的資料同步完成。

我們討論過這個題目，這個題目也真實存在。但這個題目是否要用這個方式來處理還有待討論，現在這個解法等同於讓 executor 的責任變得很大，也就是除了執行以外，它還要身兼監控、流量控管等等，已經變成把一個main class 放在一個方法裡面。這樣會導致這個又貴又久的方法幾乎無法跟其他方法方法，因為只要一呼叫就會是個無底洞，這樣在APIs設計上不是一個好的方式

離題來說，這個題目比較適合的解法應該是我們如何把它拆分，而不是試著一個方法做完，例如我們可以用 move cost + 多次 balance 來處理

**Comment by garyparrot** [comment]
> 離題來說，這個題目比較適合的解法應該是我們如何把它拆分，而不是試著一個方法做完，例如我們可以用 move cost + 多次 balance 來處理

要這樣做也行

我剛剛看了一下 `auto.leader.rebalance.enable` 的觸發是有條件的，除了預設 300 秒一次之外還包含有該節點要有 10% 的 leader imbalance，前面的條件在時間夠久之後一定會觸發，但後面的條件就不一定了。有沒有可能 Balancer 跑完之後 auto leader rebalance 永遠都不會發生

**Comment by chia7712** [comment]
> 除了預設 300 秒一次之外還包含有該節點要有 10% 的 leader imbalance，前面的條件在時間夠久之後一定會觸發，但後面的條件就不一定了。有沒有可能 Balancer 跑完之後 auto leader rebalance 永遠都不會發生

由於 reassign 時如果 leader 已經被排除了，也是會觸發選舉，換言之，現在這個案例要發生要同時滿足兩個條件：
1. 原本的leader依然存在assignment
2. 我們移動的leader比例/節點 <= 10%

我們的balancer應該不至於做的量少到這個程度，而且如果最後真的遇到上述了個條件都滿足，我們最後可以在web/gui 上提供手動觸發選舉，因爲該功能我們本來就要提供，為了那些手動做reassignment的使用者

**Comment by garyparrot** [comment]
> 我們最後可以在web/gui 上提供手動觸發選舉

套用修改之後原先程式的責任最後應該會落到操作的人（未來做實驗的我）身上。我可以預期我為了讓 CostFunction 衡量出來的結果 100% 反映到圖表上，我一定要去檢查 preferred leader election 有沒有動作。

不過如果這樣做可以讓其他使用者用的開心，那我就無所謂了，我想我們能移除那個等待

**Comment by chia7712** [comment]
> 套用修改之後原先程式的責任最後應該會落到操作的人（未來做實驗的我）身上。我可以預期我為了讓 CostFunction 衡量出來的結果 100% 反映到圖表上，我一定要去檢查 preferred leader election 有沒有動作。

如我前面提到的，我想討論的是APIs設計，並不是指最後呈現的結果。我們把兩個動作拆開，並不代表最後呈現balancer的時候就完全不能去做等待，這是完完全全兩件不一樣的事情，我們不可以混為一談。"就好比你把所有方法都塞在一個main裡面，我說應該要拆成各種方法，再去組成原本的main，這樣其他拆開的方法也可以在其他地方使用“，這句話並不是說我們就不能用該些方法寫出一個main。

> 不過如果這樣做可以讓其他使用者用的開心，那我就無所謂了，我想我們能移除那個等待

觸發 election是一個功能，要在balancer上加上“等待所有資料”也是一個方法，這在我們把它拆開後會成為彈性，而不是“不能”

總之，要盡量避免把事情混為一談，不然很容易歪掉 :(

**Comment by chia7712** [comment]
> 但沒有看到任何關於 preferred leader 選舉的完整配套方案，看起來目前最後一手是在 Web/GUI 上面提供手動觸發的功能，請使用者自己處理這個極端狀況。

就如上面提到的，APIs 的討論是說我們不要把「兩個動作合併在一個方法裡面」，但是假如使用者在操作GUI or web時，希望「可以等到全部replicas都同步完」，我們可以「提供選項讓他們去選」。

假設我們讓 Executor 只負責「執行plan」後，接下來後續的調整有幾個：

1. Web APIs 提供一個query 讓使用者可以指定 balance 是否要做 leader election，並且在文件強調說這個要求的副作用
2. Web APIs 新增一隻方法讓使用者可以單獨下election，並且在 reassignment 文件中要提及這件事情

**Comment by chia7712** [comment]
@garyparrot #1059 中依然保持你提出讓`RebalancePlanExecutor`會持續到 leader re-election 的方案，該PR只是增加了一個 timeout的參數，讓呼叫者可以去控制什麼時候可以結束等待 data sync or election，這是一個折衷的方案讓使用者不會卡在一個無窮等待、同時讓願意等到的使用者可以傳入一個夠長的等待
