### ISSUE TITLE
採買設備討論

### ISSUE THREAD

**Issue by harryteng9527** [skiptests/astraea#1077]
此 issue 用來討論目前的節點數是否能滿足實驗需求

## 實驗目標
調查**負載不平衡的分配**會導致 consumer group 整體吞吐量下降

Kafka 目前提供的 assignors 會以不同的觀點去分配 partitions ，但目的都是盡量平均分配 partition 給 consumer group 內的 members。 雖分配給 consumer group 內 consumer instance 的 partition 數量相同，但可能因為每個 partition 的**負載不同**導致 consumer 之間雖然分配相同數量的 partitions 卻被分配了不同的負載。

我目前所定義的負載是：
1. producer send 資料給 partition 的速率 or
2. partition 還未被消費完的 records 數

## 實驗環境
借用 @chinghongfang  的叢集，共六台，皆為 12 代的規格
* 3 台 broker
    * 10 Gb 網卡
* 2 台 consumer
    * 2.5 Gb 網卡
* 1 台 producer
    * 10 Gb 網卡

叢集內共兩個 topics ，每個 topic 有 2 個 partitions ，所以 3 台 brokers 中會有 1 台有 2 個 partitions，如下圖。
![cluster diagram](https://user-images.githubusercontent.com/90374678/199742602-faae37a7-ab28-410e-b4eb-0c00dc43f336.png)

## 實驗方法
以下是我實驗的步驟

1. 刻意為不同的 partition 製造不同流量
可以利用專案內的工具 - Performance tool 的 `--throughput` 與 `--specify.partitions` 來達成。 
2. 測試 consumers 在**分配相同 partition 數量的情境下**，負載相同與不相同的整體吞吐量差異，如下圖：
    * **負載相同** - Consumer 1 與 2 都分配了 200 MB/s 輸入流量的負載
![數量相同且負載相同](https://user-images.githubusercontent.com/90374678/199741757-aa85da22-1b9c-405e-b874-fdd218853215.png)

    * **負載不相同** - Consumer 1 要消費較多資料，因為 Topic A 與 B 的 partition 0 都有 150 MB/s 的資料量要處理
![數量相同但負載不均](https://user-images.githubusercontent.com/90374678/199741511-1a8ef33e-dc67-4e09-98ab-e93abe07e91b.png)

## 數據採集
消費速率的收集方式是利用 Prometheus 去採集 JMX metrics ，在串接 Grafana 呈現圖表

## 測試數據
因為實驗滿多次的，有把叢集重啟，所以之前實驗的圖沒了，但有紀錄整體吞吐量：
* 不平衡的負載分配，整體的吞吐量 : 280 MB/s 上下浮動
* 平衡的負載分配，整體的吞吐量 : 295 ~ 315 MB/s 上下浮動

## 實驗上遇到的問題
1. partition 的分佈影響到消費速率 - 在測試時，發現 2 個 partitions 放在同一台 broker 會遇到消費速率下降的問題，我當時的解決方式是讓 2 個 producer send 50 MB/s 的流量到這 2 個 partitions 上，這樣比較測得到 `吞吐量差異`
2. 執行太多 producers 影響到 consumer 端的效能 - 在還沒將執行 consumer host 的網卡換到 2.5Gb 時，是開啟三個 consumers 來做實驗，而為了製造輸入流量不平衡的情況，會在每個 consumer host 上執行若干個 producers 滿足不同的輸入流量負載 

目前實驗上遇到的問題我只有想到這兩個，之後若還有想到還會再補上。

## 昨天會後的討論

因昨天學長說可以利用
1. 預先打資料到 broker 
2. replica 端的 throttle 來限制 consumer 讀取資料的速率，但沒有看到 replica 端要如何 throttle 速率，只有 client 端的 [quotas](https://kafka.apache.org/documentation/#quotas) 。

****

所以可能要再多一台電腦當 broker 

在麻煩學長撥空來討論看看是不是`設備不夠`，還是是我的實驗設計有問題，謝謝學長

**Comment by chia7712** [comment]
@garyparrot 你有提到想做 rack 層級的 balancer，這個想法能再多分享一點嗎

**Comment by garyparrot** [comment]
> 你有提到想做 rack 層級的 balancer，這個想法能再多分享一點嗎

Rack Awareness 下 Consumer 有機會向 Follower Replica 索取資料，流量的方向會和沒有 Rack Awareness 不太一樣

不過那部分是 Cost Function 的議題，和我接下來要做的東西無關。

**Comment by chia7712** [comment]
> 不過那部分是 Cost Function 的議題，和我接下來要做的東西無關。

可能我的記憶有誤，不過你似乎是說這是 linked那套沒弄的題目，而你想做到balancer 上面

**Comment by garyparrot** [comment]
> 不過你似乎是說這是 linked那套沒弄的題目

他們有沒有做我不確定，至少這段沒寫在 Readme 上。我有次想進去看 source code 但被阻止了

> 而你想做到balancer 上面

對，我剛剛記憶拿腦袋卡住，廣義來說這是我的題目範圍之一

**Comment by chia7712** [comment]
> 我有次想進去看 source code 但被阻止了

如果這是題目的話且有時間的話，那就去看一下

**Comment by chia7712** [comment]
@chinghongfang 你的部分呢？如果就 metrics 要討論成本的話，有需要補上更多設備來增加負載量嗎

**Comment by chinghongfang** [comment]
> 如果就 metrics 要討論成本的話，有需要補上更多設備來增加負載量嗎

我覺得還不用，現在還想不到增加設備的用途，現在還是夠用的。

**Comment by qoo332001** [comment]
有關balancer組的設備採買，經過我們討論後目前有討論出兩個方案

* 叢集一樣一起使用，加購4~6台效能不用那麼好的機器，1台12port以上的switch，網路有10G，硬碟只要一個(裝os)，用來當client端，會有這個方案主要是有下面幾個原因
  * 我們跑實驗的時間都不用長期占用機器，因此輪流用是沒問題的(目前還沒有遇到搶機器的問題)
  * 目前 @garyparrot 的實驗用法會是4台broker,2台client或是5台broker,1台client，目前主要的缺點是Client端沒辦法給到足夠的寫入流量，以及沒辦法完整的用到這些叢集的效能，所以才會想要補一些比較普通的機器來當client端，讓這六台都可以當節點
  * 成本估計的實驗硬體要求不會很高，主要是要有一台有力的client端來對叢集的硬體資源上限做測試就足夠
  * 這個方案成本估計的實驗: 
    *  會有一台client裝Balancer，負責用來測硬體上限(可用頻寬)
    *  其餘的client(加買的普通機器)當producer
    *  6台原有的機器當節點
* 購入一組與目前一樣規模的叢集，一人使用一組，優點如下:
  * 一人使用一組叢集，較方便在任何時候跑實驗
  * 需要更大規模的實驗的時候，叢集也可以共用
  * 這個方案成本估計的實驗 : 
    *  會有一台機器裝Balancer，負責用來測硬體上限(可用頻寬)，
    *  一台機器用來當producer，重點主要會在搬移以及搬移成本，所以producer一台應該就足夠
    * 最後4台當節點

**Comment by chia7712** [comment]
> 叢集一樣一起使用，加購4~6台效能不用那麼好的機器，1台12port以上的switch，網路有10G，硬碟只要一個(裝os)，用來當client端，會有這個方案主要是有下面幾個原因

這個方案聽起來不錯，只要你們可以互相協調，並聯成一個大叢集可以讓你們做更有規模的實驗。

@chinghongfang @harryteng9527 你們要否也考慮走一樣的模式？考量實驗室空間，我們就建2個大叢集？你們可以討論彼此使用時間

**Comment by harryteng9527** [comment]
> 並聯成一個大叢集可以讓你們做更有規模的實驗。

聽起來不錯

我跟 @chinghongfang 討論過後覺得可以多買一個 16 port 以上的 switch，若未來需要規模較大的實驗時可以兩個叢集串起來。但是平常在使用的時候可以自己擁有一個叢集。

我目前應該想再擴充 4 台電腦，而 @chinghongfang 不需要再多添購機器

**Comment by harryteng9527** [comment]
以下討論之後採買的設備要使用的硬碟，目前**只有看 PCIe 3.0 的 SSD**。

依照通路來分類硬碟:  `原價屋`、`欣亞`、`網路上隨便看到的 SSD` 
| 原價屋            | 欣亞                 | 在原價屋、欣亞沒看到，看網路上有看到的型號 |
| ----------------- | -------------------- | ------------------------------------------ |
| XPG SX8200Pro 1TB |   Solidigm 670P 1TB    | SK hynix's Gold P31 1TB                    |
| WD SN570 1TB      | MSI SPATIUM M390 1TB    | Samsung 970 EVO 1TB                        |
|  Samsung 980 1TB   |  |                 Solidigm P41 Plus                           |

目前叢集所用的 **SX8200Pro** 在sequential steady state write 的表現大概維持在 1000 MB/s ，所以未來叢集擴充時要採買的硬碟應該要能贏 or 與目前的 SSD 效能持平，下面先列出最後比較出來的效能結果。

SK hynix's Gold P31 > Samsung 970 EVO > SX8200Pro >= MSI Spatium M470 > WD SN570 > Samsung 980

下面為每個硬碟別人實測出來的圖與文章連結

## 原價屋

### XPG SX8200Pro 1TB
目前叢集所使用的 SSD，寫一段時間後會降到 1000 MB/s 左右

![image](https://user-images.githubusercontent.com/90374678/208359264-13c9b9ec-ff0c-4937-87be-b1e4f74a46ee.png)

[SX8200Pro 的速率](https://www.tomshardware.com/reviews/adata-xpg-sx8200-pro-ssd,5955-3.html)可以與表上的 **Samsung 970 EVO** 相比較，寫入的速率會慢一些些


### WD SN570 1TB
[SN570](https://www.tomshardware.com/reviews/wd-blue-sn570-review/2) 在 Sustained sequential write 的情境下表現位居中下，如圖中**紅線表示**

![image](https://user-images.githubusercontent.com/90374678/208360167-9c1b3e6a-24c3-4f8d-980b-8687bec20c8e.png)


### Samsung 980 1TB
[Samsung 980](https://www.tomshardware.com/reviews/samsung-980-m2-nvme-ssd-review/3)長時間使用的效能表現會先下滑，之後在提昇一點點，最後穩定在 500 MB/s 。 可看下圖**紅色的線**

![image](https://user-images.githubusercontent.com/90374678/208361913-d68abc2f-7f38-4b8c-8bcb-564f5baa0b71.png)

## 欣亞

### Solidigm 670P 1TB
[670P](https://sports.yahoo.com/solidigm-p41-plus-ssd-review-143121376.html)看 ptt 的討論好像不怎麼推，也沒有在網路上看到 1TB 容量的 SSD 實驗，只有看到 2TB 的實驗。 可看下圖**橙色的線**，長時間運行下的效能下降滿多的

![image](https://user-images.githubusercontent.com/90374678/208361417-355fb7ab-0fd5-4b05-8bb3-c40e99481b27.png)

### MSI SPATIUM M390 1TB
[MSI SPATIUM M390](https://www.tomshardware.com/reviews/msi-spatium-m470-review/2)長時間寫入的表現會維持在 1000 MB/s ，與目前叢集所使用的差不多。 如下圖**紅色的線**

![image](https://user-images.githubusercontent.com/90374678/208363145-4e793149-d919-4904-916b-40f88f54d746.png)

## Others
這邊的硬碟是在看 [tomshardware](https://www.tomshardware.com/reviews/best-ssds,3891.html) 的 best SSDs 看到的

### SK hynix's Gold P31
[SK hynix's Gold P31](https://www.tomshardware.com/reviews/sk-hynix-gold-p31-m2-nvme-ssd-review/3)的寫入掉下去之後蠻穩定的在 1500 MB/s ，用久了還會上升到快 2000 MB/s。 如下圖**紅色的線**

![image](https://user-images.githubusercontent.com/90374678/208363544-f22d6d08-d391-47df-a07a-9df30bd910d4.png)

### Samsung 970 EVO 1TB
[Samsung 970](https://www.tomshardware.com/reviews/samsung-970-evo-plus-ssd,5608-3.html)的 sustained sequence write 大約維持在 1200 MB/s 左右。圖擷取上面 XPG SX8200Pro 的圖，下圖**黃色線**為此硬碟的效能表現

![image](https://user-images.githubusercontent.com/90374678/208359264-13c9b9ec-ff0c-4937-87be-b1e4f74a46ee.png)

**Comment by chia7712** [comment]
@harryteng9527 感謝整理，那看來我們還是維持原樣買一樣的硬碟好了，用過最安心

**Comment by chia7712** [comment]
硬體已經下訂，所以關閉此議題
