### ISSUE TITLE
(單機) Support to export/import topic data

### ISSUE THREAD

**Issue by chia7712** [skiptests/astraea#1093]
這個工具提供一個常見的方式來備份資料，預期完成的功能如下：

- [ ] 實作可將 Stream<Record> 放到 folder ，包含：
1. 可指定 partition 和 offset 範圍
1. 資料將會依照 partition 建置各別資料夾
1. 各個 partition 資料夾下的檔案可設定建議大小
1. 檔案格式如下：

**head**
```
[version code (2bytes)]
```
**record**
```
[record size (4 bytes)]
[topic size(2bytes)][topic]
[partition (4 bytes)]
[timestamp (8 bytes)]
[key length (4 bytes)][key][value length (4 bytes)][value]
[header count (4 bytes)][first header key length][first header key][first header value length][first header value]...
``` 
**tail**
```
[record count (4 bytes)]
```
- [ ] 實作可將指定目錄下的檔案導入指定topics，包含
1. 可指定是否要依循 partition 分佈，當選擇依循partition分佈，但指定 topic 的分佈不符合時則拋出錯誤
1. 可指定執行緒數量

- [ ] 將import/export 製作成 main function
- [ ] 將import/export 放置GUI

**Comment by chia7712** [comment]
@Haser0305 @chaohengstudent 這是我上次會議提到一個獨立的新功能，希望你們能跟我一起完成。我建議你們一開始可以協助完成幾個基本設施，包含：

1. RecordWriter，指定某個檔案，可不斷寫入`Record<byte[], byte[]>`
2. RecordReader，指定某個檔案，可不斷讀取`Record<byte[], byte[]>`

**Comment by Haser0305** [comment]
好的
那我先做  RecordReader 的部份

**Comment by chia7712** [comment]
@Haser0305 感謝，我會先推一個初版上去，後續再麻煩你們接著處理

**Comment by chia7712** [comment]
@Haser0305 @chaohengstudent 如果可以的話，麻煩你們先發一隻PR來訂好 interface，這樣方便我先把後續動作銜接完成。現在已經有`RecordWriter`和`RecordReader`兩個介面，但並未填寫任何方法，等你們先發PR來把方法補齊，因此建議你們可以有幾個思考方向：

1. 你們期待使用者如何做"大量"資料的讀寫？例如，要如何避免頻繁讀寫硬碟拖累效能？要如何重複使用記憶體避免GC壓力？
2. 這個介面如何方便的切換“資料位置”？例如我今天本來是往檔案寫，接下來要改成往某個 ip/port 寫

如果有一個頭緒就可以先推PR把方法填上去，並且在該些方法上撰寫使用方式

謝謝

**Comment by Haser0305** [comment]
好的
#1097  那邊的有把record 資料填完了，可能會先發那邊的 PR ，然後會再發 PR 來定義 interface

順便想問一下，第2點方向的 ip/port 是只說這工具在其他機器執行，然後是寫成檔案到其他機器裡，還是說是寫入到其他 broker 裡?

謝謝

**Comment by chia7712** [comment]
> 第2點方向的 ip/port 是只說這工具在其他機器執行，然後是寫成檔案到其他機器裡，還是說是寫入到其他 broker 裡?

這一點是暗示說，資料的來源或輸入除了本地檔案以外，之後我們也要支援將資料 import/export到遠端，因此在設計 reader/writer 的介面上要思考一下讀寫資料的介面要用哪一個？

**Comment by chia7712** [comment]
補充一下，所謂的遠端，可以先以檔案系統來想像，就是寫到遠端的檔案系統。至於重複寫到另一個broker ，這個題目先不用考慮

**Comment by chia7712** [comment]
這隻議題剩下 GUI 的部分尚未完成，接下來要實作基於 connector 的版本 (https://github.com/skiptests/astraea/issues/1188)

等我完成GUI的部分後會關閉此議題

**Comment by chia7712** [comment]
> 等我完成GUI的部分後會關閉此議題

GUI 的單機版可以被 CLI 取代，之後會以整合 connector 版本為目標，因此關閉此議題
