### ISSUE TITLE
Implement `ClusterBean` query syntax with quantity requirement.

### ISSUE THREAD

**Issue by garyparrot** [skiptests/astraea#1112]
Context: https://github.com/skiptests/astraea/pull/1103#discussion_r1020194164

使 `ClusterBean` 本身的 metrics 索取語法具有對數量的要求，且當不滿足需求時應該丟出 `NoSufficientMetricsException`

**Comment by garyparrot** [comment]
我接下來會處理這個議題

**Comment by garyparrot** [comment]
@chia7712 我有一個小疑問。

我設計這個界面到一半，我理解是要提供類似下面的界面讓 CostFunction 能過濾資料和對資料做處理, but。

```java
  interface ClusterBeanQuery {
    ClusterBeanQuery requireSize(int quantity);

    ClusterBeanQuery requireTime(Duration sinceBefore);

    ClusterBeanQuery requireTarget(Set<Integer> id);

    ClusterBeanQuery orderByTime();

    <T> Map<Integer, Stream<T>> query(Class<T> metricType);
  }
```

有了 `Sensor` 之後， `CostFunction` 可以直接和 `Sensor` 要資料，不用再自己寫一些條件來過濾資料和對資料做處理。過濾資料&資料處理邏輯可以放到 `Sensor` 裡面做就好。所以這個功能好像會和 Sensor 做的事情衝突，是不是這個過濾的功能可以被 Sensor 取代

**Comment by garyparrot** [comment]
更具體的說法，比起寫

```
clusterCost(...) {
  var metrics =  custerBean.select().from().where().do();
  var calc = someCalculation();
  return aggregation(calc);
}
```

為何不

```
sensros() {
  return select_and_calculation();
}

clusterCost() {
  return aggregation(clusterBean.sensor())
}

**Comment by chia7712** [comment]
這個想法很不錯，有兩個題目要討論，一個是 sensor 適不適合暴露出去，另一個是 sensor 帶來的資料可以如何索引。這牽涉到兩個項目：

1）責任分工，Sensor 時負責協助統計資料的物件，因此要同時扮演被索引的角色就不適合，因為使用者會同時面對一個可變更的物件 （sensor），在多執行緒的環境下，安全穩健的設計是將 mutable / immutable 分開給不同使用者操作。因此我並不建議將 Sensor 重新暴露出去

2）要提供哪些索引？現在我們有兩種 metrics，第一種是 remote raw beans，這些物件可以用 class type, timestamp 等方式索引。第二種則是 Sensor 內部的統計值，#1171 裡面一開始用的是 metrics name（不過我覺得這個很危險，暗示著不同 cost function 之間使用的 sensor 都要具有唯一性），另一個方式是類似 Fetcher，每個 cost function 要回傳一個「動作」，該動作是接受一串 raw beans，然後回傳新的 HasObejctBean（透過 Sensor 內的統計值來產生新的 bean），這樣就能讓兩邊 ( remote raw beans 和 我們內部統計的值）走相同的流程，然後也套用相同的索引

總之，  Sensor 的資料如何整合還要看 @qoo332001  的實作，但我的想像中是要沿用我們設計好的 Bean 體系。不過不管怎樣， @garyparrot 可以先就一起存在的 remote raw beans (HasObjectBean) 來設計 query 的方式，如果 @qoo332001 能將 sensor 那段的資料結構與 remote raw bean 整合那是最好，否則就到時再設計一條路專門給 Sensor 吐出來的資料使用
