### ISSUE TITLE
Astraea tool : Import csv

### ISSUE THREAD

**Issue by wycccccc** [skiptests/astraea#1114]
#1092 後續議題

1. csv to kafka (這邊我們會需要一個 Map<String, String> serialization）
2. 除了支援刪除已經完成的檔案以外，也要像 spark 一樣支援封存)
3. `CleanCsv`要用更通用的名字，改成`ImportCsv`，並且要支援skip用來指定除了標頭以外，要跳過幾行的資料。這個模式適用於那些csv資料除了標頭以外，還會有一些橫列是作為該檔案的metadata。這樣除了這次實驗的wind資料以外，其他同類型的可也已支援
4. 輸入來源要改成 `schema://path`的寫法，要為接下來支援不同檔案系統做準備
5. 上述都完成後，要麻煩寫個文件和測試一下速度

**Comment by chia7712** [comment]
@wycccccc 感謝，這部分看有沒有機會包含在 0.1.0 裡面

**Comment by wycccccc** [comment]
我盡力，有幾個問題想先確認一下
> csv to kafka (這邊我們會需要一個 Map<String, String> serialization）

這邊的serialization有什麼特殊要求嗎？我預計使用專案已經在用的jackson來處理這個，它看起來蠻合適的。會將Map轉換為如下形式。我會再看一下另一名好夥伴有做這一段嘛，沒有的話我再考慮一下怎麼包一層。
```
{
  "key" : "value"
}
```

> 要支援skip用來指定除了標頭以外

已經有skip方法跳過行數。不過只能跳過目前讀到的行數的後幾行。這樣我想應該足夠。

> 輸入來源要改成 schema://path的寫法，要為接下來支援不同檔案系統做準備

所以不同來源讀到的資料格式也都是csv嘛。還是現在就先這麼考慮。
我會新開一個interface，叫DataSource怎麼樣。然後目前的就變為FolderSource。

**Comment by chia7712** [comment]
> 這邊的serialization有什麼特殊要求嗎？我預計使用專案已經在用的jackson來處理這個，它看起來蠻合適的。會將Map轉換為如下形式。我會再看一下另一名好夥伴有做這一段嘛，沒有的話我再考慮一下怎麼包一層。

json 也是一個選項，目前已經有`JsonConverter`可以使用，這邊可以不用再包一層 Serializer，直接轉成 String 扔進去

> 已經有skip方法跳過行數。不過只能跳過目前讀到的行數的後幾行。這樣我想應該足夠。

是的，這樣已經足夠

> 我會新開一個interface，叫DataSource怎麼樣。然後目前的就變為FolderSource。

建議結合 `FileSystem` (https://github.com/skiptests/astraea/blob/main/fs/src/main/java/org/astraea/fs/FileSystem.java)，也就是從輸入端取得`schema`後嘗試呼叫對應的 `FileSystem`，接著將後面的路徑拿來與`FileSystem`進行互動

至於各個檔案系統可能需要的特定參數（例如帳密），這部分要擴充`FileSystem`讓它能吃一個`Configuration`來進行初始化

**Comment by wycccccc** [comment]
> csv to kafka (這邊我們會需要一個 Map<String, String> serialization

我想確認一下這句話，意思是目前的import csv 需要新增一個功能，可以讓用戶選擇在clean csv後是否要將其send to kafka？

**Comment by wycccccc** [comment]
> 因此我是建議你完成第一個和第二個版本就好。

第一和第三？

> 至於 clean csv 的部分，希望是能通用化成可以"跳過header後幾行“來處理，也就是說上述三個方案都會支援”從某個檔案系統的目錄撈取多個csv檔案，並根據指定跳過的行數開始讀取，並且將資料轉換成 json (in key)

ok 我瞭解這個故事了

**Comment by chia7712** [comment]
> 第一和第三？

喔 你說的沒錯

**Comment by wycccccc** [comment]
處理10001個學長發給我的example所花費時間如下

單純處理不做任何額外操作 14秒
![螢幕快照 2022-11-30 17-18-23](https://user-images.githubusercontent.com/43372856/204756406-a3b12730-0e05-457e-b5dd-4c208cd89d5c.png)

處理完畢後封存 27秒
![螢幕快照 2022-11-30 17-23-06](https://user-images.githubusercontent.com/43372856/204757454-a1dbd937-bf6d-4caa-8cb3-2bac17e9df7d.png)

**Comment by chia7712** [comment]
> 處理10001個學長發給我的example

這個資料總量多少？我們要測試至少 10GB 的量

**Comment by wycccccc** [comment]
1.3GB，那我再造點資料測一下

**Comment by chia7712** [comment]
> 1.3GB，那我再造點資料測一下

我給你實際的資料，這樣比較有真實性

**Comment by wycccccc** [comment]
20180707有問題
單純處理不做任何額外操作 2分18秒
![image](https://user-images.githubusercontent.com/43372856/204793872-4c0b1cee-c53a-4d9a-a4b6-f71449de075d.png)
處理完畢後封存 4分32秒
![image](https://user-images.githubusercontent.com/43372856/204794988-fc386662-825e-4d10-9f9a-03d2d7c41c85.png)

**Comment by chia7712** [comment]
是不是那個檔案特別大？

**Comment by wycccccc** [comment]
> 是不是那個檔案特別大？

抱歉忘記說原因，是因爲其中有一行長度不一樣。我再去確認了一下，原因是最後一行是空白。這個邏輯我再去處理一下，最後一行是空白時忽略這行。

**Comment by chia7712** [comment]
> 最後一行是空白時忽略這行。

多一個換行符號嗎？

**Comment by wycccccc** [comment]
> 多一個換行符號嗎？

對沒錯

**Comment by chia7712** [comment]
> 對沒錯

這應該是可以作為選項，就是讓使用者選擇要不要跳過空白行
