### ISSUE TITLE
移除 LogMetricsTest 裡面註解掉的程式碼

### ISSUE THREAD

**Issue by chia7712** [skiptests/astraea#1124]
see https://github.com/skiptests/astraea/blob/main/common/src/test/java/org/astraea/common/metrics/broker/LogMetricsTest.java#L57

**Comment by saivirtue** [comment]
我也想對這個專案貢獻一點心力，請問這個issue可以由我來做嗎？

**Comment by chia7712** [comment]
@saivirtue 完全可以，感謝幫忙！
