### ISSUE TITLE
Potential bug in `ReplicaInfo` 

### ISSUE THREAD

**Issue by garyparrot** [skiptests/astraea#1167]
https://github.com/skiptests/astraea/blob/266479dd63b63af7ad3b140bafa3c8ecfdb60945/common/src/main/java/org/astraea/common/admin/ReplicaInfo.java#L167-L169

https://github.com/skiptests/astraea/blob/266479dd63b63af7ad3b140bafa3c8ecfdb60945/common/src/main/java/org/astraea/common/admin/ReplicaInfo.java#L176-L179

突然想到，如果 Replica 處於 Offline 的狀態，他還會有 `Follower` 的身份嗎，這個預設的 `ReplicaInfo#isFollower()` 實作可能會說某個 Offline Replica 是 Follower。

**Comment by chia7712** [comment]
> 突然想到，如果 Replica 處於 Offline 的狀態，他還會有 Follower 的身份嗎，這個預設的 ReplicaInfo#isFollower() 實作可能會說某個 Offline Replica 是 Follower。

應該說 kafka 只會說 replica 是不是 leader，所以這邊我們採取簡單的策略，不是 leader 就是 follower。此外，如果 replica 掉線，replica 就會變成 offline + 不是 leader。如果有觀察到某些行為跟我們自己定義的有衝突，可以提出來看看是否要調整

**Comment by garyparrot** [comment]
目前沒看到行為定義上的衝突，這可能暫時還不是個問題，先關閉
