### ISSUE TITLE
Proposing a way to evaluate the partition egress loading of brokers

### ISSUE THREAD

**Issue by garyparrot** [skiptests/astraea#1181]
這個 Issue 想要提出一個：衡量 Partition 負載分佈和 Broker 節點，在網路輸出上的負載量關係。
即假設有個 Broker b 他有 p0, p1, p2 這三個 Partition，則這三個 Partition 會給 b 帶來多少網路輸出上的開銷。
有了這個計算方法，我們就能實作出讓節點的輸出負載平衡的 Cost Function

這個問題需要特別討論的原因是：

1. Kafka 內提供的 metrics 很難去反映這個負載量和 Partition 的關係，這對 Balancer 產生計劃打分帶來一個問題。
2. 需要一個精準的方法來衡量這個負載量，如果衡量不準，那我們產生出來的負載優化計劃對叢集是否有幫助會是個問號。

以下會提出幾種我想到的衡量方法，每個版本有自己的特色，會再特別做討論

## Version 0 (這個版本實務上做不到)

![image](https://user-images.githubusercontent.com/39105714/204347552-f350ef54-a14d-4a4a-9309-7684fcce3726.png)

* 最理想的計算方法
* 想不到從 kafka metrics 取得 `tp 被撈取的速度` 的方法，所以這個**計算方法不可行**

## Version 1 (這個版本實務上做不到)

![image](https://user-images.githubusercontent.com/39105714/204347782-1585b934-d8aa-41a3-b061-25f204a2c2af.png)

* 這個方法引入 ConsumerGroup的角色，從 ConsumerGroup 去進一步揣測每個 Partition 的流量
  * 因為只顧慮到 ConsumerGroup，所以 **非 ConsumerGroup 的撈取是黑數**
* 想不到如何從 broker 取得 `group_fetch_speed` 的方法，所以這個**計算方法不可行**

## Version 2

![image](https://user-images.githubusercontent.com/39105714/204348222-a401e79d-3d4f-4014-86bd-174167182d55.png)

這個方法的直覺是，所有 ConsumerGroup 都在撈取最新的資料，所以資料的輸入理論上會等同**資料的輸出速度**(理想情況)

* `partition_ingress` 可以從 `log` 增長速度來取得
* 如果 ConsumerGroup 跳著撈資料，則這個方法不可行
  * ConsumerGroup 的一大目的就是要確保每個資料都被處理，所以我認為不常發生 ConsumerGroup 跳著撈資料的情況，由於觸發頻率不高，且這個 Cost 是要反映叢集長遠的效能表現，所以這個問題能被忽略。
* 如果 ConsumerGroup 以 below-ingress-speed 撈資料，則這個方法判斷的實際流量會失真
  * 我覺得這個情況會發生在下面幾個情況會發生
    1. ConsumerGroup 不足以應付負載量，這個其實不是 Balancer 的問題，應該請維護者擴充 Consumer 數量，讓 Balancer 處理這個問題的價值也不高，因為這個問題背後隱含的另外一個危險是資料來不及處理，這個問題比負載平衡還嚴重，應該先處理好他，如果沒處理好他，沒辦法談後續的負載平衡，如果這個問題處理好了，那 ConsumerGroup 將以 full-speed 撈資料，這個問題也就不存在了。
    4. 這個 Partition 有 Brust Load 的情況，也就是平常沒什麼資料，但資料一來就是大批的塞進來，通常這個情況，維護者也不在乎資料有沒有及時處理完，有處理完就好，且他有很大的信心一定會處理完，如果他沒信心的話應該添加 Consumer 的數量，因為這個 Brust Load 從進來到處理完都不是長遠的行為（我們在意的流量問題），所以不在這個 Cost 要處理的範疇內。
* 如果 ConsumerGroup 以 over-ingress-speed 撈資料，則這個方法判斷的實際流量會失真
  * 我覺得這個情況會在下面幾個情況會發生，多半和資料堆積有關：
    1. ConsumerGroup 因為某些原因暫停，過一下子繼續跑：這類的事件不常發生且影響小，Cost 要反映叢集長遠的效能表現，所以這個問題可以被忽略。
    2. ConsumerGroup 因為某些原因暫停，過了很久才繼續跑：這類的事件不常發生，如果發生了，只要叢集有資源就能慢慢追上，就 Cost 要反映長遠的效能表現這點，我覺得這個問題可以被忽略。
* 因為上面的討論都以長遠的表現來反駁那些問題，所以這個做法在**長期**看來，我們的負載計算方法是正確的。但如果從**短期**來看，我們一定會看到負載不平衡的現象，但那些應該都一段時間的事情，這些很隨機的事件很難從 Cost Function 的角度去處理，所以只能這樣...
* 非 ConsumerGroup 的撈取依然是黑數

## Version 3

![image](https://user-images.githubusercontent.com/39105714/204351105-2206b1a9-dc2c-421a-af76-bfddb6c5f5b1.png)

這個是 Ver2 的延伸，這個版本要嘗試解決非 ConsumerGroup 撈取是黑數的問題，但方法是臆測，基本上是從 `BrokerTopicMetrics#BytesOutPerSec(topic)` 這個 metrics 中萃取出非 ConsumerGroup 的那部分，然後從中以各個 Partition 的輸入資料量來刮分這個部分，因為真的不知道非 ConsumerGroup 對各個 partition 的撈取狀況，我們只能假設這個撈取的量和其輸入速度大小有關，**但這個直覺有可能會不正確**。

* `BrokerEgressVer2` 是上面 Ver2 的公式
* `BrokerBytesOutNonGroup(b, tp)` == `BrokerTopicMetrics#BytesOutPerSec(topic)` - `consumer group 的那部分撈取`，後面 consumer gorup 那部分的撈取是已知數，我們 Ver2 中有求出來。
* 最後那個分數是對應 partition 在輸入速度方面所佔據的比例

其實非 ConsumerGroup 的撈取有可能代表他不在乎有沒有 catch 上進度，做 random access/ old data sequential access 是一種可能，這邊的衡量方法是從目前的輸入速度下去猜， random access 的量和 log size 的關聯比較高，或許應該從整體的 log size 去做從揣測，而非從輸入速度去猜。

**Comment by chia7712** [comment]
@garyparrot 這個題目應該會很有趣，不過可否在描述中說一下這個是想解決什麼問題？

**Comment by garyparrot** [comment]
> 不過可否在描述中說一下這個是想解決什麼問題？

在第一段，我把他改寫比較清楚一點。

@chia7712 你覺得有辦法取得到 topic/partition 和資料輸出量之間的關係嗎，我覺得拿不太到具體的數字，所以只能透過上面的方法去設一大堆假設和預測，如果假設失真或是預測不準那他們的計算結果就會出現誤差。

**Comment by chia7712** [comment]
> 即假設有個 Broker b 他有 p0, p1, p2 這三個 Partition，則這三個 Partition 會給 b 帶來多少網路輸出上的開銷。
有了這個計算方法，我們就能實作出讓節點的輸出負載平衡的 Cost Function

這邊的輸出是指資料從節點中流出嗎？所以簡單來說，這個題目是想要以“提高讀取端的負載平衡“為目標嗎?

> 你覺得有辦法取得到 topic/partition 和資料輸出量之間的關係嗎，我覺得拿不太到具體的數字，所以只能透過上面的方法去設一大堆假設和預測，如果假設失真或是預測不準那他們的計算結果就會出現誤差。

這個題目會比較不容易，有兩個原因，第一個是 kafka 統計值只有到 topic-level，第二個 consumer 的行為遠比 producer 複雜，要用數字去推估不容易（除非我們要建立一個很長期的收集，透過一些數學分析來猜趨勢，但這個就是另一個大議題）

但如果我們將故事簡化，假設 partition 的資料增長狀況是常態，那我們可以拿 topic-level 的吞吐量根據 partition size 作比例分配，藉此估計 partition-level 的讀取速度，然後以此來做分配。例如 topic A 目前在節點 x, y, z 的流量分別是 100, 50, 30，則所謂的最佳狀況就是透過搬移 topic A partition 使得流量變成 60, 60, 60。

**Comment by garyparrot** [comment]
> 這邊的輸出是指資料從節點中流出嗎？所以簡單來說，這個題目是想要以“提高讀取端的負載平衡“為目標嗎?

是這樣沒錯。

> 這個題目會比較不容易，有兩個原因，第一個是 kafka 統計值只有到 topic-level，第二個 consumer 的行為遠比 producer 複雜，要用數字去推估不容易

網路 IO 開銷是很重要的題目，我覺得不做的話我們的東西會看起來怪怪的

>（除非我們要建立一個很長期的收集，透過一些數學分析來猜趨勢，但這個就是另一個大議題）

如果是要觀察過去資料的互動情況的話，Balancer 可以開一個 Consumer 去讀取 Partition 的資料，從 record timestamp/key/value size 去重建資料當時輸入的流量速度，這樣就不用過去那個時間真的要保留資料了。

> 但如果我們將故事簡化，假設 partition 的資料增長狀況是常態，那我們可以拿 topic-level 的吞吐量根據 partition size 作比例分配，藉此估計 partition-level 的讀取速度，然後以此來做分配。例如 topic A 目前在節點 x, y, z 的流量分別是 100, 50, 30，則所謂的最佳狀況就是透過搬移 topic A partition 使得流量變成 60, 60, 60。

如果有個 Topic 的 retention 設定會使他囤積比較多資料，在這個情境下他會看起來好像 consumer 比較忙，但實際情況可能未必會是這樣，其實後面堆積的都是沒在讀取的 cold data。如果要以這個手法下去做的話，可能要假設所有 Topic 的 retention 設定都一樣。

**Comment by chia7712** [comment]
> 網路 IO 開銷是很重要的題目，我覺得不做的話我們的東西會看起來怪怪的

這個題目值得做，但目標要下修一下，只做到 topic 在各個 broker 之間是平衡，而不是做到 partition 在各個 broker 之間是平衡

> 如果有個 Topic 的 retention 設定會使他囤積比較多資料，在這個情境下他會看起來好像 consumer 比較忙，但實際情況可能未必會是這樣，其實後面堆積的都是沒在讀取的 cold data。如果要以這個手法下去做的話，可能要假設所有 Topic 的 retention 設定都一樣。我個人覺得這個假設很惱人，可能沒辦法被使用者接受。

所以要搭配 topic-level metrics，假如有一個 topic 屯了很多資料，但 metrics 中的 `bytes out` 很低，那在這個情境中我們就要給很低的分數，因為這暗示這個 topic 都是冷資料，沒人要讀取

**Comment by chia7712** [comment]
@harryteng9527 麻煩看一下這個題目，看一下從伺服器端來看讀取的平衡和從 consumer 端來看有什麼不一樣

**Comment by garyparrot** [comment]
>> 如果有個 Topic 的 retention 設定會使他囤積比較多資料，在這個情境下他會看起來好像 consumer 比較忙，但實際情況可能未必會是這樣，其實後面堆積的都是沒在讀取的 cold data。如果要以這個手法下去做的話，可能要假設所有 Topic 的 retention 設定都一樣。我個人覺得這個假設很惱人，可能沒辦法被使用者接受。
>>
> 所以要搭配 topic-level metrics，假如有一個 topic 屯了很多資料，但 metrics 中的 bytes out 很低，那在這個情境中我們就要給很低的分數，因為這暗示這個 topic 都是冷資料，沒人要讀取

聽起來可能可行，可以試試看。

我覺得這個做法比較像是 Ver3 的公式，但是 ConsumerGroup 和非 ConsumerGroup 的所有流量都是用統計方法去粗略估計。這邊的粗略估計會隨著使用情境是否單純而影響方法可不可靠。我猜這個手法在比較不單純的叢集中，就算提出了一個 Cost 分數 0 的解，因為統計方法忽略的誤差，搬移後在硬體效能那邊反映出來的數字也不會是完全的平均，是否接近就要看叢集的使用有多不單純了。

**Comment by chia7712** [comment]
> 我覺得這個做法比較像是 Ver3 的公式，但是 ConsumerGroup 和非 ConsumerGroup 的所有流量都是用統計方法去粗略估計。這邊的粗略估計會隨著使用情境是否單純而影響方法可不可靠。我猜這個手法在比較不單純的叢集中，就算提出了一個 Cost 分數 0 的解，因為統計方法忽略的誤差，搬移後在硬體效能那邊反映出來的數字也不會是完全的平均，是否接近就要看叢集的使用有多不單純了。

實際上就是讀寫兩邊的客戶端也要考慮負載平衡，否則伺服器端忙個半天，客戶端就是想要亂搞，那整個流量就一定無法平衡。至於我們在解題目可以先從一個間單合理的題目開始切入，否則要考慮各種刁專的用法最後就會是無解。例如使用partition大小來估算吞吐量可能會遭遇兩種例外，第一種是寫入端的資料分配很不一致，會跳來跳去。另一種則是讀取端設定offset很不一致，有的從頭有的從中間，像這些例子就會讓要處理這個議題變得很複雜（或者無解）:(

**Comment by garyparrot** [comment]
我測試了一下這個統計的手法，如果 tp 資料都是等速度流入那效果還不錯。

有遇到一個陷阱是：我是用 fifteenMinuteRate 去衡量叢集 topic 的流量，在負載優化剛完成，叢集分佈劇烈變動後，我們 fifteenMinuteRate 裡面的數字會是 before cluster 和 after cluster 二種的合體，也就是這個 metric 裡面可能會有很大的雜訊或說時空背景不同的資訊在裡面。

也就是說，如果透過 fifteenMinuteRate 來衡量流入資料量，且我們在優化剛完成後立刻啟動另外一個優化計劃的生成，那有很高的機率我們第二次產生出來的計劃沒有參考價值。我這邊遇到的情況是我在第一個優化完成後立刻啟動另外一個優化計劃的生成，第二個計劃從 new cost 來看似乎效果不錯，但實際套用下去其實叢集沒有什麼大改變。

**Comment by chia7712** [comment]
> 也就是說，如果透過 fifteenMinuteRate 來衡量流入資料量，且我們在優化剛完成後立刻啟動另外一個優化計劃的生成，那有很高的機率我們第二次產生出來的計劃沒有參考價值。我這邊遇到的情況是我在第一個優化完成後立刻啟動另外一個優化計劃的生成，第二個計劃從 new cost 來看似乎效果不錯，但實際套用下去其實叢集沒有什麼大改變。

這種「特殊」狀況可以先不用考慮，就好比我們也會去考慮是不是同時有兩個 balancer 在互相影響評分。

不過有一點倒是可以討論，就是當數據有劇烈變化（或是俗稱不穩定）時是否要阻止負載平衡？這個問題就比較「通用」，不管是你提到的例子、或是使用情境正在大幅度調整，處於這個狀態時先前累積的數據很可能通通失真，導致 balancer 無法順利「猜」未來的狀況
