### ISSUE TITLE
(connector) Support to export/import topic data

### ISSUE THREAD

**Issue by chia7712** [skiptests/astraea#1188]
這個議題銜接 #1093

我們已經有了單機版本的 importer/exporter，接下來要實作基於 kafka connector 的版本，預計完成以下實作：

1. 基於 SinkConnector 實現可從 topics 中將資料撈取出來，並寫道指定檔案系統下
  - 初步測試以 FTP 為主
  - 在指定輸出的目錄下產生以下結構的檔案：/root/{topic}/{partition}/{start_offset}
1. 基於 SourceConnector 實現可從某些檔案系統讀取資料，並且將資料放到 topic 裡面
  - 初步測試以 FTP 為主
  - 指定目錄後，要能遞迴找尋所有可讀取的檔案
  - 讀取完的檔案要支援兩種模式，一種是刪除、一種是歸檔（也就是移到另一個指定存放的目錄）

**Comment by chia7712** [comment]
@Haser0305 @chaohengstudent 麻煩你們看一下，可以先思考一下如何實作。另外由於 connector client (https://github.com/skiptests/astraea/pull/1012) 尚未完成，因此可能無法方便撰寫整合測試，不過你們可以先透過專案內的 https://github.com/skiptests/astraea/blob/main/docs/run_kafka_worker.md 來真的建構 connector 服務並且手動測試 :)

**Comment by Haser0305** [comment]
好的，最近會試試看建構一個 connector 服務

**Comment by chia7712** [comment]
> 目前在 ftp write 那邊有點問題，因為 ftp 不能一次建立好幾個 storefilestream ，需要在建立新的時把前面的那個先關閉，那這樣做的話需要每寫一筆 record 就需要 close 再連一個新的，不知這邊我對於 ftp 的理解有沒有錯。

請問一下你是如何架設 ftp server?

**Comment by Haser0305** [comment]
之前是用 docker 架設 vsftpd，現在改為本機架設 apache ftpserver，剛剛透過 apache 的簡易測試

如果第一個連線不關閉直接開第二個 outputstream ，就會一直執行轉圈且不會再往下跑
第一個連線關閉但不執行 completePendingCommand 的話，第二個 outputstream 就會是 null
最後如果 close 與 completePendingCommand 都有跑的話就可以成功寫入兩個檔案

**Comment by chia7712** [comment]
> 如果第一個連線不關閉直接開第二個 outputstream ，就會一直執行轉圈且不會再往下跑
第一個連線關閉但不執行 completePendingCommand 的話，第二個 outputstream 就會是 null
最後如果 close 與 completePendingCommand 都有跑的話就可以成功寫入兩個檔案

請問有開多個 data port 嗎？ftp 協定中 data port 通常是獨佔的，因此可以簡單來說 data port 的數量決定了資料傳輸的平行度

以下是我用的指令可以參考看看：
```bash
docker run -d \
    -p 10000:21 \
    -p 10001-10003:10001-10003 \
    -v $HOME/data:/tmp/ftp \
    -e USERS="chia7712|chia7712|/tmp/ftp" \
    -e ADDRESS=chia7712.asuscomm.com \
    -e MIN_PORT=10001 \
    -e MAX_PORT=10003 \
    delfer/alpine-ftp-server
```

上述的 `MIN_PORT` and `MAX_PORT` 就是 data port 的範圍，越多的話平行傳輸的量就可以越高

**Comment by Haser0305** [comment]
之前 docker 跑得時候有開多個 port，然後有試試看上述的指令，在一個 ftp client 中試著開兩個 storefilestream 一樣會是之前測試的結果，以下是我在測試時的程式碼，這是可以跑正確的寫法，

```java
ftp.enterLocalPassiveMode();

var topicName = "topic0";
ftp.makeDirectory(topicName);
ftp.changeWorkingDirectory(topicName);

var output0 = ftp.storeFileStream("./test0.hex");
output0.write(1);
output0.close();
ftp.completePendingCommand();

var output1 = ftp.storeFileStream("./test1.hex");
output1.write(2);
output1.close();
ftp.completePendingCommand();
```

**Comment by chia7712** [comment]
@Haser0305 看起來應該是 FTPClient 不是多執行序安全，這部分我會修正，改謝你回報

**Comment by chia7712** [comment]
@Haser0305 see #1217

**Comment by Haser0305** [comment]
好的，看到了
非常感謝
我再以現在的 file system 來實做 sink connector

**Comment by chia7712** [comment]
關閉此議題因為已經完成基本功能
