### ISSUE TITLE
Information loss when using `Broker` in conjunction with `NodeInfo`

### ISSUE THREAD

**Issue by garyparrot** [skiptests/astraea#1189]
Context: https://github.com/skiptests/astraea/pull/1184#discussion_r1034931675

`NodeInfo` 本身有設計成能當資料結構的 key 使用，另外 `Broker` 是 `NodeInfo` 的子類別，因此 `Broker` 本身也可以當做 key 使用。當 `Broker` 和 `NodeInfo` 混在一起使用時，有機會 `NodeInfo` 會在資料結構中覆蓋過 `Broker`，使 `Broker` 的訊息消失。

嘗試修正這個問題，避免 `Broker` 和 `NodeInfo` 一起使用時造成的訊息丟失。

**Comment by chia7712** [comment]
一個簡單的做法是將 `NodeInfo` 的“比較”拿掉，避免鼓勵使用者如果要將`NodeInfo`放置於 key時，同時也要將Set<NodeInfo>的用法移除，改成List<NodeINfo>
