### ISSUE TITLE
[PERF][CONNECTOR] 使用 Kafka connector 實作 perf tool

### ISSUE THREAD

**Issue by chia7712** [skiptests/astraea#1219]
Astraea perf tool 是一個方便又強大的工具，但目前侷限在單機上，並不方便擴充使用（要反覆敲打多個指令），我們應該沿用已經加入的 connector 框架來重新實作該工具

1. key.distribution #1277 
2. value.distribution #1277
3. interdependent.size
4. specify.partitions #1315
5. ~specify.brokers~ 這個不實作因為要在 connector 內部取得 bootstrap.servers 實務上有困難
6. key.size #1222
7. value.size #1222

**Comment by chia7712** [comment]
@Haser0305 @chaohengstudent 麻煩看一下這個題目，概念上就是把現有的 perf 功能用 source connector 重新實作，並不一定要一次到位，可以從幾個基本的功能開始搬移

**Comment by chia7712** [comment]
@g1geordie 這個題目看你是否也有興趣？我們需要把 perf tool 的功能逐步移植到 connector 上面，幾個重要的功能如下：

1. key.distribution
2. value.distribution
3. interdependent.size
4. specify.partitions
5. specify.brokers
6. key.size
7. value.size

**Comment by g1geordie** [comment]
沒問題  我明天來看看這個tool

**Comment by chia7712** [comment]
大部分功能都已經完成，後續會開設個別議題追蹤

https://github.com/skiptests/astraea/issues/1385
