### ISSUE TITLE
使用自行實作的 csv reader/writer 取代 opencsv

### ISSUE THREAD

**Issue by chia7712** [skiptests/astraea#1239]
Opencsv 提供了豐富的功能來解析 csv 檔案，但我們實際上並不需要支援太複雜的 csv 格式（例如雙引號、跳脫字元等等），同時 opencsv 引入了不少相依的函式庫（如下），因此我們應該重新實作 csv reader/writer，不需要太多相依函式庫，同時以支援簡易的csv 格式就好

\--- com.opencsv:opencsv:5.6
     +--- org.apache.commons:commons-lang3:3.12.0
     +--- org.apache.commons:commons-text:1.9
     |    \--- org.apache.commons:commons-lang3:3.11 -> 3.12.0
     +--- commons-beanutils:commons-beanutils:1.9.4
     |    +--- commons-logging:commons-logging:1.2
     |    \--- commons-collections:commons-collections:3.2.2
     \--- org.apache.commons:commons-collections4:4.4

**Comment by chia7712** [comment]
@wycccccc FYi

**Comment by chia7712** [comment]
@MaxwellYHL please take a look

**Comment by chia7712** [comment]
@yijhenlin 是否有機會從這個議題開始？

**Comment by chia7712** [comment]
可以刪除，在正式版本之前我們可以清除用不到的code

**Comment by chia7712** [comment]
@brandboat https://github.com/skiptests/astraea/blob/main/etl/src/test/scala/org/astraea/etl/FileCreator.scala

這裡還有使用到 opencsv 我們可否替換成自己的版本？

**Comment by brandboat** [comment]
要看一下，當初是看到這是測試使用的就沒特別換

**Comment by brandboat** [comment]
> @brandboat https://github.com/skiptests/astraea/blob/main/etl/src/test/scala/org/astraea/etl/FileCreator.scala
> 這裡還有使用到 opencsv 我們可否替換成自己的版本？

@chia7712  有需要的話，我可以開個議題著手處理這件事

**Comment by chia7712** [comment]
> 有需要的話，我可以開個議題著手處理這件事

是的，有需要，我們要移除 opencsv

**Comment by brandboat** [comment]
> 是的，有需要，我們要移除 opencsv

我會著手處理，感謝 https://github.com/skiptests/astraea/issues/1825
