### ISSUE TITLE
Rewrite JvmMemory#toString

### ISSUE THREAD

**Issue by chia7712** [skiptests/astraea#1249]
https://github.com/skiptests/astraea/blob/main/common/src/main/java/org/astraea/common/metrics/platform/JvmMemory.java#L52

目前是用舊時代的寫法，現代的JVM已經可以很好處理字串的合併（例如偷偷使用`StringBuilder`)，因此我們不用特別呼叫`StringBuilder`

**Comment by yangminglintw** [comment]
Hi, 請問這議題是要將toString改寫成什麼樣子呢

**Comment by chia7712** [comment]
這個議題的重點是不要用 builder 了，這個是舊時代的寫法
