### ISSUE TITLE
Change Member#groupInstanceId from String to Optional<String>

### ISSUE THREAD

**Issue by chia7712** [skiptests/astraea#1252]
https://github.com/skiptests/astraea/blob/main/app/src/main/java/org/astraea/app/web/GroupHandler.java#L181

`Member#groupInstanceId` 應該改成用`Optional<String>`來明確表達其可以是null

**Comment by yangminglintw** [comment]
Hi, 請問這issue有人做嗎，沒有的話我可以試試看嗎謝謝。

另外想請問幾個問題：
1. 在自己本機要怎麼確認是否build成功，是看build.gradle沒問題就可以了嗎。
2. 本地端測試有哪些指令我需要先跑過的呢。
3. 分支命名規則，我看了其他PR都是描述實作的功能。

**Comment by chia7712** [comment]
> 在自己本機要怎麼確認是否build成功，是看build.gradle沒問題就可以了嗎。
本地端測試有哪些指令我需要先跑過的呢。

我們有建立QA，所以別怕XD

但如果想在本地測試的話，就請跑測試：

./gradlew clean test

> 分支命名規則，我看了其他PR都是描述實作的功能。

這個就你開心就好 :)
