### ISSUE TITLE
Jackson databind clashes

### ISSUE THREAD

**Issue by wycccccc** [skiptests/astraea#1261]
![螢幕快照 2022-12-11 15-58-01](https://user-images.githubusercontent.com/43372856/206900174-8d812475-9c1f-4c5a-9fcf-0e6d988b980b.png)

在整合完我們的jackson後運行時會遇到上述問題。這似乎是因爲astraea與spark使用了不同版本的jackson。
astraea: com.fasterxml.jackson.datatype:jackson-datatype-jdk8
spark: com.fasterxml.jackson.datatype:jackson-datatype-jsr310

我嘗試將astraea的jackson替換爲spark版本的，它變得可以正常執行。但這樣做會缺失一些功能，例如對於Optional的處理。（可能還有更多我還沒確認）
想問一下學長有什麼比較好的辦法解決package之間產生的衝突。

**Comment by chia7712** [comment]
我一直很盡力在專案中避免這種衝突，結果還是遇到了 QQ

> 想問一下學長有什麼比較好的辦法解決package之間產生的衝突。

可否確認一下 spark 3.3+ 用的 Jackson 有沒有跟我們的相容？如果有的話，那我們試著升級到 3.3版。如果沒有，那就要你手動做一個將 `Map<String, String>`轉成 json string 的方法，並且要遵守二進制相同的這個邏輯

**Comment by wycccccc** [comment]
https://github.com/skiptests/astraea/pkgs/container/astraea%2Fspark
不過專案的spark需要先更新，這部分我好像沒法處理，得先拜託學長

**Comment by chia7712** [comment]
> 不過專案的spark需要先更新，這部分我好像沒法處理，得先拜託學長

可否先發 PR 把 `start_spark.sh`更新到 3.3+，接著我再來更新 image

**Comment by chia7712** [comment]
@wycccccc 如果#1227還要一些時間的話，可否先發隻PR把 etl module 的版本升級到 3.3.1?
