### ISSUE TITLE
如何同時衡量 Ingress 和 Egress 效能指標

### ISSUE THREAD

**Issue by garyparrot** [skiptests/astraea#1285]
Context: https://github.com/skiptests/astraea/pull/1240#discussion_r1046196360

採用 coefficient of variation 或是 (max - min) / max 的衡量方法，他們在遇到同時優化多個指標時可能會遇到一些問題，如

今天三個 broker，採用 (max - min) / max 的方式衡量分數

* 他們的輸入流量分別是 [30 MB/s, 50 MB/s, 100 MB/s]，這個分數會是 0.7
* 他們的輸出流量分別是 [3 MB/s, 5 MB/s, 10 MB/s]，這個分數也會是 0.7

從分數上來看，我們認為兩個指標一樣不平衡，但如果細看內容的話會發現輸入相比於輸出有更不平衡的趨勢。這個在遇到優化算法沒辦法找到兩全其美的解時帶來一些取捨（new score ~= 0），有機會這些取捨會被套用在其實沒有那麼嚴重的效能指標上。

* 一種解決這個問題的方法是給輸入流量較高的權重，如此依賴他的分數會被比較重視，但這個做法需要人為介入去決定參數。
* 另外一種做法是 Ingress 和 Egress 不分開，兩個實作成同一個 Cost Function 來進行優化

**Comment by chia7712** [comment]
或者是要追縱可能的最大值，並且改成用 `(最大值 - 目前的值)` 來作為分數的衡量

**Comment by garyparrot** [comment]
你是指比如：

* 輸入流量分別是 [30 MB/s, 50 MB/s, 100 MB/s]
* 輸出流量分別是 [3 MB/s, 5 MB/s, 10 MB/s]

然後可能的最大值是輸入流量那邊的 (100 + 50 + 30) = 180 MB/s

* 輸入流量的分數是 (100 - 30)  / 180 = 0.3888
* 輸出流量的分數是 (10 - 3) / 180 = 0.03888

**Comment by chia7712** [comment]
> 我之前有類似的想法，但是打某個例子打到一半發現不對勁，然後就把打一半的留言刪掉了，我現在想不起來那個不對勁的點是什麼，不過這個想法看起來好像可行。

勾起我的好奇心了 :)

不過就先試試看這個調整比例的手法，搞不好寫到一半就想起來了

**Comment by garyparrot** [comment]
我想起來了，我之前是用 (100 - 30) 當共用的最大值，所以會出問題，但這邊的例子是使用 (100 + 50 + 30)，這樣應該不會有事。

**Comment by garyparrot** [comment]
也可能不是，我忘了我是用哪個值，看我有沒有機會想起來
