### ISSUE TITLE
給 Importer 撰寫完整的 definition 

### ISSUE THREAD

**Issue by chia7712** [skiptests/astraea#1297]
https://github.com/skiptests/astraea/blob/main/connector/src/main/java/org/astraea/connector/backup/Importer.java#L58

`Importer`現在針對 `FileSystem` 的參數定義是稀缺且不正確，我們應該要提供以下幾種定義：

1. "fs.schema"，用來定義要使用的檔案系統類型
2. `fs.ftp.hostname`
3. `fs.ftp.port`
4. `fs.ftp.user`
5. `fs.ftp.password`
6. `path`
7. `size`

**Comment by chia7712** [comment]
@Haser0305 可否麻煩你處理一下？

**Comment by Haser0305** [comment]
收到，沒問題
