### ISSUE TITLE
Importer#Task要提早取得參數值以提早觸發錯誤

### ISSUE THREAD

**Issue by chia7712** [skiptests/astraea#1299]
https://github.com/skiptests/astraea/blob/main/connector/src/main/java/org/astraea/connector/backup/Importer.java#L84

`path`, `size`, and `topicName` 應該在`init`時就要先取值，這樣才能提早噴出錯誤

**Comment by chia7712** [comment]
@Haser0305 請看一下

**Comment by Haser0305** [comment]
好的
想順便確認一下，ftp sink 算是 exporter 還是說是 importer，當初我是照著 `backup Exporter` 的方式寫的

**Comment by chia7712** [comment]
ftp sink 算是 exporter (將 topic 資料倒出來）
