### ISSUE TITLE
RateByTime 與 Avg.rateByTime 的差異

### ISSUE THREAD

**Issue by chia7712** [skiptests/astraea#1322]
@qoo332001 @chinghongfang 可否協助解釋一下？

**Comment by qoo332001** [comment]
RateByTime只會計算最新資料與前一次紀錄的差值，每次紀錄的間隔必須大於period
Avg.rateByTime會對所有紀錄的值加總，最後除以紀錄的次數

**Comment by chia7712** [comment]
> RateByTime只會計算最新資料與前一次紀錄的差值，每次紀錄的間隔必須大於period

這個的使用情境是什麼？

**Comment by chinghongfang** [comment]
> 這個的使用情境是什麼？

`RateByTime` 目前還沒有使用，原來是為了計算當前速率 (數值變動速率)。

**Comment by chia7712** [comment]
> RateByTime 目前還沒有使用，原來是為了計算當前速率 (數值變動速率)。

有預期要給那一個cost使用嗎

**Comment by chinghongfang** [comment]
`RateByTime` 原本是我寫的，原來的想法是想要之後串 Avg expWeight ，變成我們的目標統計值 `Avg rateExpWeight`。

**Comment by chia7712** [comment]
> RateByTime 原本是我寫的，原來的想法是想要之後串 Avg expWeight ，變成我們的目標統計值 Avg rateExpWeight。

可否提供一個明確的用法？例如可能搭配哪一個cost?

**Comment by chinghongfang** [comment]
目前沒有從現有的 cost-function 找到可能使用的地方。

比如說之前的某一個 cost-function `ReplicaDiskInCost` (#976 )，裡面想要計算 replica 的增長速率，但是我們可以觀測到的數值只有 “現在 replica 的大小”，所以當時把 "計算速率" 這件事放在 cost-function 內計算。如果用現在這個 `RateByTime` 的話，每次把 fetch 到的 replica size 丟給 sensor ，速率計算 就交給 sensor-stat 處理了。

**Comment by chia7712** [comment]
> 如果用現在這個 RateByTime 的話，每次把 fetch 到的 replica size 丟給 sensor ，速率計算 就交給 sensor-stat 處理了。

`RateByTime` 可能無法計算這個，因為`RateByTime`並不是基於"時間"去算平均，另外我們應該要預期使用者去算出“差異”，然後再把每次的差異餵食給某個基於時間的統計值，然後取得平均

簡單來說，取平均目前有兩種基底，一種是基於次數、一種是基於時間。後者應該是有很多種用途，但不知道為何我們幾個byTime都是基於次數

**Comment by chia7712** [comment]
@chinghongfang 如果一時三刻沒有想到用途，我建議把其中一個刪掉，名字太像了

**Comment by chinghongfang** [comment]
> 如果一時三刻沒有想到用途，我建議把其中一個刪掉，名字太像了

其實兩個都還沒有用到，或許兩個都刪掉， @qoo332001 那邊也打算在 sensor 外，自己計算 rate ，這樣我們也不需要計算 rate 這項 stat ，讓使用者自己處理？

**Comment by chia7712** [comment]
> 那邊也打算在 sensor 外，自己計算 rate ，這樣我們也不需要計算 rate 這項 stat ，讓使用者自己處理？

Rate 應該還是有用的的地方，例如 #1331 

我還不太確定 @qoo332001 要用的 rate 的邏輯，不過可以的話我們要盡量共用統計的方式

**Comment by chia7712** [comment]
> 其實兩個都還沒有用到，或許兩個都刪掉，

確定沒有用到就麻煩發PR刪掉

**Comment by chinghongfang** [comment]
> Rate 應該還是有用的的地方，例如 https://github.com/skiptests/astraea/pull/1331 

我們要用的 rate 和 #1331 講的 rate 不一樣，我們要用的 rate 是紀錄 "觀測值" 然後計算出該 "觀測值" 的增減速率。 #1331 則是每一次紀錄的總和除以時間。

**Comment by chia7712** [comment]
> 我們要用的 rate 是紀錄 "觀測值" 然後計算出該 "觀測值" 的增減速率

增減速率就是每次「這一次」和「上一次」的差值在次數/時間上的變化嗎？

**Comment by chinghongfang** [comment]
是的，每次是「這一次」和「上一次」的差值，且「這一次」和「上一次」之間是有 debounce 的，也就是「這一次」和 「上一次」的觀測值，一定會超過某段自訂的時間 (e.g. 1秒)。

以 `RateByTime` 來舉例，每次會回傳「這一次」和「上一次」的差值。
以 `Avg.rateByTime` 來舉例，每次會回傳 "所有差值" 的平均。

**Comment by chia7712** [comment]
> 以 Avg.rateByTime 來舉例，每次會回傳 "所有差值" 的平均。

了解，所以 @qoo332001 後來打算怎麼處理統計？可以在這邊先分享一下嗎

**Comment by qoo332001** [comment]
> 所以 @qoo332001 後來打算怎麼處理統計？可以在這邊先分享一下嗎

我的作法會是紀錄所有「這一次」和「上一次」的差值，最後拿這些資料來做加權平均，實作的部分就是在`CostFunction#sensors`裡面處理rate差值以及儲存，最後使用現有的統計方法`Avg.expWeightByTime`來做加權平均，這樣的算法會用在計算每個replica的寫入速度，我等實驗跑完之後就會開PR把新的CostFunction推上來

**Comment by chia7712** [comment]
> 我的作法會是紀錄所有「這一次」和「上一次」的差值，最後拿這些資料來做加權平均，實作的部分就是在CostFunction#sensors裡面處理�rate差值以及儲存，最後使用現有的統計方法Avg.expWeightByTime來做加權平均，這樣的算法會用在計算每個replica的寫入速度，我等實驗跑完之後就會開PR把新的CostFunction推上來

感謝告知，聽起來不錯。所以 rateByTime 和 RateByTime 似乎在你的案例中也用不到。 @chinghongfang 你覺得呢？是否要直接移除？

**Comment by chinghongfang** [comment]
是的，要在 "外面" 計算 rate 那這兩個 `Stat` 就都不需要了。我把兩個都刪除。

**Comment by chia7712** [comment]
resolved by #1334
