### ISSUE TITLE
補足 Grafana 的文件

### ISSUE THREAD

**Issue by chia7712** [skiptests/astraea#1339]
目前專案內介紹 Grafana 的文件有些稀疏，並無法真實反應我們在做效能量測時如何產生圖表，因此我們應該要補上以下幾點資訊：

1. 如何在圖形介面上匯入 Prometheus 。目前只有透過命令列的方式
2. 如何使用 query 來建立效能相關的圖表

**Comment by chia7712** [comment]
@harryteng9527 可否麻煩你協助這個議題？我相信你在做 consumer 實驗的時候應該已經對工具有一定掌握度了

**Comment by harryteng9527** [comment]
OK

**Comment by chia7712** [comment]
@harryteng9527 @qoo332001 @garyparrot @chinghongfang 如今天會議提到，astraea 專案需要有一個“官方”的dashboard，可否請你們四位各自把自己的dashboard 匯出貼上來？我會來統整一下，目標是讓之後專案的效能報告都能從這個“官方面板”上來觀察，方便大家有共同的畫面、使用者也可方便重現和觀察
