### ISSUE TITLE
需要更多benchmark情境

### ISSUE THREAD

**Issue by chinghongfang** [skiptests/astraea#135]
- [ ] transactional send, idempotent send #136 
- [ ] 資料大小分佈
- [ ] record key分佈 #152 

為使我們的工具可廣泛運用在各實際用途上，我們需要新增更多的可模擬情境。
目前列出兩項可新增的情境
提供設定producer 使用transaction mode, idempotent mode
提供參數決定會有多少比率的大資料，多少比率的小資料。
提供參數設定key的分佈，比如，有10%的record是相同key。

**Comment by chia7712** [comment]
麻煩針對各個項目把對應的PR標上去喔
