### ISSUE TITLE
關於RequireBrokerCluster的Host()問題

### ISSUE THREAD

**Issue by wycccccc** [skiptests/astraea#137]
我在撰寫refactor後的parititon的test中遇到了一個問題，我們的RequireBrokerCluster創建的node中的host抓到的是我計算機的名稱。而jmxserver的host則是127.0.0.1。（圖中上面為node地址，下面為jmx地址）我不太清楚前者沒有抓到127.0.0.1的原因。希望能得到一些建議。

![2021-12-03 23-39-52 的螢幕擷圖](https://user-images.githubusercontent.com/43372856/144630289-0f47f5a5-73f2-405d-af4c-d3eeaed12039.png)

**Comment by wycccccc** [comment]
另外還有一個設計上的問題也想請教一下，我用jmx的host與node的host進行匹配，進而使我們抓到的jmxmetrics可以與node匹配上。這個做法會存在漏洞嘛。

**Comment by chia7712** [comment]
@wycccccc 感謝回報，我會處理

**Comment by chia7712** [comment]
> 我用jmx的host與node的host進行匹配，進而使我們抓到的jmxmetrics可以與node匹配上。這個做法會存在漏洞嘛。

port最好也要比對

**Comment by wycccccc** [comment]
我有點不太理解port的比較，
我是通過kafka的jmx address應該與所服務的kafka在同一節點上來進行關聯的。
這兩者都有各自的port應該無法比較？
例如kafka node：192.168.103.41:9092 jmx server:192.168.103.41:9999。這樣就可以通過host相同把nodeID傳給metrics。
這種做法合理嘛，現實中應該每個host下只會放一個kafka與對應的jmx？

**Comment by chia7712** [comment]
> 這種做法合理嘛，現實中應該每個host下只會放一個kafka與對應的jmx？

理論上生產環境上的確是這樣，可是broker曝露出來的資訊可能會綁在同一個"host"上，例如有兩個brokers在不同實體機上，但曝露出來的位置卻都是10.2.2.2，但jmx和服務各自綁定不一樣的port

**Comment by chia7712** [comment]
另一個角度是說 這個問題先緩一緩 先把重構的部份處理好再回來

**Comment by wycccccc** [comment]
這個問題應該緩不了，因為我們的測試環境就是一個host上有三個node。算是上述提到的半個情景，我有嘗試解決，現在可以支持同一個host上有多個node的情況。
