### ISSUE TITLE
2023年採購的 威剛XPG SX8200Pro 1TB 測試

### ISSUE THREAD

**Issue by chia7712** [skiptests/astraea#1397]
此議題用來追蹤新採購的硬碟們效能表現如何

**Comment by harryteng9527** [comment]
## 測試方式

```=bash
fio --name=ssd-test --bs=1KiB --size=70GiB --rw=write --ioengine=io_uring --numjobs=10 --group_reporting
```
## 測試環境

### Assignor
| Node                   | CPU Chipset                 | OS version         | Kernel version    |
| ---------------------- | --------------------------- | ------------------ | ----------------- |
| 171 - 小台 Intel 12 代 | Intel® B660 Chipset         | Ubuntu 20.04.3 LTS | 5.4.0-135-generic |
| 172 - 小台 Intel 12 代 | Intel® B660 Chipset         | Ubuntu 20.04.3 LTS | 5.4.0-135-generic |
| 173 - 小台 Intel 12 代 | Intel® B660 Chipset         | Ubuntu 20.04.3 LTS       | 5.4.0-135-generic |
| 175 - Intel 11 代      | Intel® Z590 Express Chipset | Ubuntu 22.04 LTS   | 5.15.0-56-generic |
| 72 - Intel 11 代       | Intel® Z590 Express Chipset | Ubuntu 22.04 LTS   | 5.15.0-56-generic |
| 70 - Intel 13 代       | Intel® Z790 Chipset         | Ubuntu 22.04 LTS   | 5.15.0-56-generic |
| 71 - Intel 13 代       | Intel® Z790 Chipset         | Ubuntu 22.04 LTS   | 5.15.0-56-generic |
| 174 - 大台 Intel 12 代 | Intel® Z690 Chipset         | Ubuntu 20.04.3 LTS | 5.4.0-135-generic |
| 176 - 大台 Intel 12 代 | Intel® Z690 Chipset         | Ubuntu 20.04.4 LTS | 5.4.0-135-generic |

### Partitioner
| Node                   | CPU Chipset         | OS version   | Kernel version    |
| ---------------------- | ------------------- | ------------ | ----------------- |
| 185 - 大台 Intel 12 代 | Intel® Z690 Chipset | 20.04.5 LTS  | 5.4.0-135-generic |
| 186 - 大台 Intel 12 代 | Intel® Z690 Chipset | 20.04.5 LTS  | 5.4.0-135-generic |
| 187 - 大台 Intel 12 代 | Intel® Z690 Chipset | 20.04.5 LTS  | 5.4.0-135-generic |
| 188 - 大台 Intel 12 代 | Intel® Z690 Chipset | 20.04.5 LTS  | 5.4.0-135-generic |
| 189 - 大台 Intel 12 代 | Intel® Z690 Chipset | 20.04.5 LTS  | 5.4.0-135-generic |
| 190 - 大台 Intel 12 代 | Intel® Z690 Chipset | Ubuntu 22.10 | 5.19.0-26-generic |


## 測試結果

### Assignor
Assignor 叢集由下列電腦組成：
1. 小台的 12 代 Intel
2. 大台的 12 代 Intel
3. 11 代 Intel
4. 13 代 Intel

這邊列出各個電腦的 Disk 的寫入速率、溫度
而 12 代的電腦因為 ubuntu 版本沒有更新到 22.04 or 22.10 ，所以 Prometheus 撈不到 nvme 的溫度

#### 小台的 12 代 Intel

磁碟寫入速率：
![image](https://user-images.githubusercontent.com/90374678/210852379-ff2d03a7-d8e2-4e0a-a055-b154cce163cd.png)

Grafana Snapshot 連結：[SSD - 小台 12 代](https://snapshots.raintank.io/dashboard/snapshot/amV8bywEmJfvSNXhGAHUHT3mEs0bG4j7)

#### 大台的 12 代 Intel

此台規格與 Partitioner 的 12 代 Intel 相同

磁碟寫入速率：
![image](https://user-images.githubusercontent.com/90374678/210852885-b133d472-de1f-40ba-8e92-f5474eb487f3.png)

Grafana Snapshot 連結：[SSD - 大台 12 代](https://snapshots.raintank.io/dashboard/snapshot/Iuvfs3DPIpZbLEuqK0liWNP641kNjOUf)

#### 11 代 Intel

磁碟寫入速率與溫度：
![image](https://user-images.githubusercontent.com/90374678/210853314-fbcfba0c-1b66-4ffc-8ac8-72ea92ba6346.png)

Grafana Snapshot 連結：[SSD - 11 Intel](https://snapshots.raintank.io/dashboard/snapshot/NX3dendpxN6BOYeS6FID0eZPGT6j9eZA)

#### 13 代 Intel

磁碟寫入速率與溫度：
![image](https://user-images.githubusercontent.com/90374678/210853732-3d04ef10-598b-47e1-b824-21d8fa22bb5c.png)

13 代 Intel 的磁碟寫入速率偏低

Grafana Snapshot 連結：[SSD - 13 Intel](https://snapshots.raintank.io/dashboard/snapshot/LJvNc6XyltGKspeIh97Tb3xPbQWssBY0)

### Partitioner

磁碟寫入速率與溫度：
![image](https://user-images.githubusercontent.com/90374678/210854523-2b4ae3f5-519e-4b4e-96f8-6fb80dca07e2.png)

Grafana Snapshot 連結：[SSD - Partitioner](https://snapshots.raintank.io/dashboard/snapshot/jfNfu1qcrmBG1ZQgMaH21Hx25latBE6C)

**Comment by harryteng9527** [comment]
## 測試方式
也是一樣用 fio ，但是調整 bs 與 direct，指令如下
```=bash
fio --name=ssd-test --bs=4KB --size=70GiB --rw=write --direct=1 --ioengine=io_uring --numjobs=10 --group_reporting
```

此次測試只有測試 assignor 的叢集

## 測試環境

為了看小台 12 代 Intel 的溫度，有把其中一台重灌，規格如下
| Node                   | CPU Chipset                 | OS version         | Kernel version    |
| ---------------------- | --------------------------- | ------------------ | ----------------- |
| 171 - 小台 Intel 12 代 | Intel® B660 Chipset         | Ubuntu 20.04.3 LTS | 5.4.0-135-generic |
| 172 - 小台 Intel 12 代 | Intel® B660 Chipset         | Ubuntu 20.04.3 LTS | 5.4.0-135-generic |
| 173 - 小台 Intel 12 代 | Intel® B660 Chipset         | Ubuntu 22.10       | 5.19.0-21-generic |
| 175 - Intel 11 代      | Intel® Z590 Express Chipset | Ubuntu 22.04 LTS   | 5.15.0-56-generic |
| 72 - Intel 11 代       | Intel® Z590 Express Chipset | Ubuntu 22.04 LTS   | 5.15.0-56-generic |
| 70 - Intel 13 代       | Intel® Z790 Chipset         | Ubuntu 22.04 LTS   | 5.15.0-56-generic |
| 71 - Intel 13 代       | Intel® Z790 Chipset         | Ubuntu 22.04 LTS   | 5.15.0-56-generic |
| 174 - 大台 Intel 12 代 | Intel® Z690 Chipset         | Ubuntu 20.04.3 LTS | 5.4.0-135-generic |
| 176 - 大台 Intel 12 代 | Intel® Z690 Chipset         | Ubuntu 20.04.4 LTS | 5.4.0-135-generic |

## 測試結果
### 12 代 Intel - 小台電腦
![image](https://user-images.githubusercontent.com/90374678/210971611-1c822e07-9575-42ba-93f1-84fca906cfd4.png)

[Grafana Snapshot](https://snapshots.raintank.io/dashboard/snapshot/VzQXpU7L9EggBNqPnAxTUiKYck22ncjY)

### 12 代 Intel - 大台電腦

![image](https://user-images.githubusercontent.com/90374678/210972772-f5e5a1b7-d817-4b16-a4de-c63d4f57cdc3.png)

[Grafana Snapshot](https://snapshots.raintank.io/dashboard/snapshot/dMQyGcqscEszBLgzrDb3VEWOq7oFl9nJ)

### 11 代 Intel

![image](https://user-images.githubusercontent.com/90374678/210973019-b6c11c3b-8d36-4af1-bc9f-58bc16dfec89.png)

[Grafana Snapshot](https://snapshots.raintank.io/dashboard/snapshot/oGCK3CFhsA4FCaKvrSXcAFQDUiQykXbb)

### 13 代 Intel

![image](https://user-images.githubusercontent.com/90374678/210973208-3d28c8c5-c8f9-4826-8eda-3ec45ca84cb4.png)

[Grafana Snapshot](https://snapshots.raintank.io/dashboard/snapshot/AwZ564LSeh52fKLrfcKvsJY68xiTMj52)

**Comment by garyparrot** [comment]
## 測試方式

```
fio --name=ssd-test --bs=1MB --size=70GB --rw=write --numjobs=10 --group_reporting --direct=1
```

## 測試環境

| 設備編號 | CPU | Kernel Version | 
| --- | --- | --- |
| 177 | Intel i9-12900K | 5.15.0 |
| 178 | Intel i9-12900K | 5.15.0 |
| 179 | Intel i9-12900K | 5.15.0 |
| 180 | Intel i9-12900K | 5.15.0 |
| 181 | Intel i9-12900K | 5.15.0 |
| 182 | Intel i9-12900K | 5.15.0 |
| 183 | Intel i7-11700K | 5.15.0|
| 184 | Intel i7-13700K | 5.15.0 |
| 141 | Intel i7-11700K | 5.15.0 |
| 142 | Intel i7-13700K | 6.1.1 |
| 143 | Intel i7-13700K | 5.19.0 |
| 144 | Intel i7-13700K | 5.15.0 |
| 145 | Intel i7-13700K | 5.19.0 |
| 146 | Intel i7-13700K | 5.15.0 |
| 147 | Intel i7-13700K | 5.19.0 |

## Intel 11 代 (Linux)

![image](https://user-images.githubusercontent.com/39105714/211548608-e87c6711-e21c-4a28-8bb4-46e25ac20c0e.png)

## Intel 12 代 (Linux)

![image](https://user-images.githubusercontent.com/39105714/211550193-e1feeade-2406-4ad1-bd1b-c45cf1b974c0.png)

## Intel 13 代 (Linux)

![image](https://user-images.githubusercontent.com/39105714/211550765-8550986d-ee6a-46b8-8fd4-90852d5f2b9b.png)

## On Windows

* AMD Ryzen 5  3600 6-Core
* 使用 13 代購買的 SSD
* 結果
  * 前幾十秒可以是 3 GB/s
  * 後面降為 600 MB/s
  * 再經過一段時候後降為 300 MB/s 

![image](https://user-images.githubusercontent.com/39105714/211552032-d2cfbd72-56e3-4383-b90a-6855b6431693.png)

![image](https://user-images.githubusercontent.com/39105714/211552012-a59e08c5-9cdc-46ae-b998-e614ce83c839.png)

**Comment by chia7712** [comment]
@garyparrot @harryteng9527 感謝你們的測試和整理，我已經通知廠商處理散熱的問題，然後我們先以這批硬碟進行測試，年後我會找時間換成其他高階硬碟
