### ISSUE TITLE
支援將 `Duration` serializer for Json converter

### ISSUE THREAD

**Issue by chia7712** [skiptests/astraea#1430]
`Duration` 是我們常用的一個型別，因此在 json 轉換上支援該類別會相當有幫助。不過我們在 argument 轉換上使用的字串型別並不是標準的 Duration 字串，而是人類更容易閱讀的"value"+"unit"，因此在將Duration轉換回json字串時我們也應該使用該格式

**Comment by brandboat** [comment]
JsonConverter L89 提到 `TODO: how to support ns?`，Duration 轉成 json string，是不是可以判斷若 ns 部分仍有殘留，就以 ns 這個單位來處理呢，若無，則繼續沿用 ms 此單位？

**Comment by chia7712** [comment]
> 想了想就直接判斷Duration的值是否可整除"天"，可行就以天為單位輸出，依此類推到奈秒，這樣如何呢 ?

這是一個可以考慮的方案，另一個角度則是要看 輸出後如何再轉回來，並且要避免“失真”，你覺得呢？
