### ISSUE TITLE
Altos R380 F5 伺服器測試

### ISSUE THREAD

**Issue by Haser0305** [skiptests/astraea#1558]
# 測試方式

```
fio --name=ssd-test --bs=1MB --rw=write --direct=1 --ioengine=io_uring --numjobs=10 --group_reporting --size=70GiB
```

# 測試環境
硬碟有 sda 與 sdb 兩塊，這兩塊分別各切為 ssd1(792.7G)與 ssd2(1.6T)來測試速度
實體硬碟如以下表格所列
A

型號 | 大小 | 數量
-- | -- | --
intel DC S4510 | 960G | 1
Altos AS2500DC | 960G | 1

B

型號 | 大小 | 數量
-- | -- | --
intel DC S4500 | 480G | 2
intel DC S4510 | 480G | 3

Ubuntu 版本為 22.10

# 測試結果

這邊列出兩顆硬碟同時測試時的寫入狀況

依照結果可以得到sdb(ssd2) 的寫入大約相對穩定在550MiB 左右， sda(ssd1)再一開始可以在480 MiB，但是到後面就會掉到130MiB左右並維持在這速度

圖片：
<img width="1184" alt="截圖 2023-03-09 下午1 42 32" src="https://user-images.githubusercontent.com/100994342/223946538-c02f04aa-1069-487d-a51c-0f870dd3303f.png">

**Comment by chia7712** [comment]
sdb2 那塊能在塞久一點的資料嗎？五分鐘有些太短

**Comment by Haser0305** [comment]
現在指令大小改為 75G，其餘一致
結果不知道是溫度關係或是其他因素，速度只有280～300上下，並且不穩定
![Screenshot from 2023-03-10 16-23-15](https://user-images.githubusercontent.com/100994342/224262714-aa27d594-c31d-451d-9d1c-cb4091080782.png)

**Comment by Haser0305** [comment]
> sdb2 那塊能在塞久一點的資料嗎？五分鐘有些太短

上面那張圖片 sdb 是大約跑了20分鐘，然後今天又在跑了一次，sdb的寫入大小改為 90GB，其餘參數沒變
但sdb的硬碟速度大約只有200多，結果為下圖

![Screenshot from 2023-03-10 19-09-37](https://user-images.githubusercontent.com/100994342/224301580-4fb8af2d-08cc-4e64-b727-978ad8123d6d.png)

**Comment by chia7712** [comment]
@Haser0305 ok 感謝測試，我了解了，這部分就先這樣。可以把機器收起來，我叫廠商拿回去

**Comment by Haser0305** [comment]
好的
那我把這個issue關閉了
