### ISSUE TITLE
[Metric] BeanObject serialization/deserialization

### ISSUE THREAD

**Issue by chinghongfang** [skiptests/astraea#1570]
在 #1281 中，我們新的 `MetricCollector` 使用 Kafka 來收集、儲存 jmx mbean ，但是我們現在對 `BeanObject` >的處理方式是直接 **轉成字串** ，一個 `BeanObject` 即是一個 record。`MetricCollector` 把字串拉下來以後，再 parse 成 `BeanObject`。

而現在的作法 `BeanObject#attribute` 的型別並沒有正確轉出 (應該是 `Map<String, Object>` 但都是`Map<String, String>`)，所以我們需要自己實做 BeanObject 的 Serializer/Deserializer。

我目前的想法是：
把 `BeanObject` 三個 field 分開序列化，再放入同一個 byte array
1. (1 byte) domain name 長度 + ("長度" bytes) domain name
2. (4 byte) Map\<String, String\> 長度 + ("長度" bytes) Map.toString().getBytes()
3. (1 byte) key 長度 + ("長度" bytes) key + (1 byte) 型別 + (0 or 1 byte) 字串長度 + ("型別長度" bytes) value

其中 3. 會出現多次。
想請問大家這樣會不會太複雜，還請大家多多指教。

**Comment by chia7712** [comment]
@chinghongfang 這是一個很好的機會來探索一下“序列化”的技術，可否請你趁這次機會試著分析一下“轉成字串“的缺點（例如記憶體消耗、空間膨脹等等），同時研究一下 JVM 平台上較熱門的序列化技術，分析一下優缺點並且試著挑選出適合“此次情境”的解決方案

**Comment by chinghongfang** [comment]
### `BeanObject` 特性

`BeanObject` 裡面有三個 fields：

1. domain name (String)
2. properties (Map\<String, String\>)
3. attributes (Map\<String, Object\>)

`BeanObject` 轉成字串的格式是：

```
[<domain name>:<key>=<value>,<key>=<value>,...]
{<key>=<value>,<key>=<value>,...}
```

比如說，`BeanObject`
domain name: org.astraea
properties : {"type"="publisher", "name"="BeanFetch"}
attributes : {"rate"="30.9999"}

會轉成以下字串

```
[org.astraea:type=publisher,name=BeanFetch]
{rate=30.9999}
```

把 `BeanObject` 轉成字串傳輸的缺點有：

1. 型別消失
2. 空間膨脹 (整數 102400 需要 6 bytes，但 int 只需要 4 bytes 就可以表示)
3. 反序列步驟較多 (bytes -> String -> parsing -> type casting)
4. 內容受限 (domain name, key, value 不可包含 `[`, `]`, `=`, `{`, `}`, `:`)

---

### Serilize 方法

1. Java Object serialization
2. Json
3. Protocol Buffer
4. Apache Avro

第一種方式不可行，`Map`, `Object` 不是 `Serializable`。
第二種 Json
    優：
        更新結構方便
    缺：
        需較大空間
        解析較花時間
第三種 Protocol Buffer 不可行，不支援 "不同 type"
    優：
        空間使用有效率
    缺：
        更新結構時，兩邊都要更新
第四種 Apache Avro 不可行，不支援 "不同 type"
    優：
        不用生成程式碼，可直接讀取 Json 設定檔
        支援多種型別

因為 `BeanObject` 需求比較特殊，Map value 是 `Object` ，且可能是不同型別(int, float, ...)，所以 `BeanObject` serialization 應該還是會自己刻。

---

### 提出

```bash
+ 1 // [domain name length]
+ n // [n bytes of domain name]
+ 1 // [nums of key value pair]

  ┌ 1 + [key]   // [key length + n bytes of key]
  │ 1 + [value] // [value length + n bytes of value]
  +        ⋮
  │ 1 + [key]
  └ 1 + [value]

+ 1 // [nums of key value pair]

  ┌ 1 + [key]       // [key length + n bytes of key]
  │ 1 [+ 1] + [value] // [value type + value length + n bytes of value]
  +        ⋮   
  │ 1 + [key]
  └ 1 [+ 1] + [value]
```

其中 value type 會決定 value 的型別是 primitive type 中的哪一個，如果是 String ，就會多一個 byte 來紀錄該字串的長度。

**Comment by chia7712** [comment]
這個議題跟 #1581 有關聯

隨著專案發展我們越來越多“東西”需要被序列化，與其一個一個完成，我們可否有一個“基礎設施”專門用來序列化各種東西？常見的第三方套件就是 protobuf ，或是有其他熱門好用的第三方也可以研究一下

**Comment by chia7712** [comment]
> 拿 protobuf 和 Apache Avro 相比，我會選擇 Apache Avro。他提供比較多的型別(如：Map, array 等)，而且在定義 schema 時是讀取 JSON 檔，相比 protobuf 建立 .java 檔，在理解 schema 上會比較方便一點。

如你第二段所描述，效能可能是我們第一考量，易讀性則可能是第二點 ( 不過這點還有待商榷)

> BeanObject 使用這些套件的話，也是可以，但可能會需要多一次型別的轉換 (byte -> string -> type v.s. byte -> type)。所以為了省一個型別轉換，才會想另外客製 BeanObject 的序列化。

假如我們真的引用了某個序列化工具，那之後`BeanObject`這個物件就會是直接用序列化工具產生的“code"，所以真的轉換路徑會變成 `java bean` -> `BeanObject` -> `bytes` -> `BeanObject`，其實跟現在的路徑一樣，差別在於“轉換成bytes"的動作是由序列化工具完成

**Comment by chinghongfang** [comment]
> 假如我們真的引用了某個序列化工具，那之後BeanObject這個物件就會是直接用序列化工具產生的“code"，所以真的轉換路徑會變成 `java bean` -> `BeanObject` -> `bytes` -> `BeanObject`

可是最麻煩的地方還在 -- `BeanObject` 序列化工具沒辦法直接定義。

`BeanObject#attributes` 裡面的型別是 `Object` 而且還不一定每個都是同型別，比如說
{count=10,mean=3.2}
兩者的型別是 `Object` 但其實他們是 `Integer` 和 `Double`。而我看到的序列化工具都要先固定好型別，沒辦法對 `Object` 序列化。

**Comment by chia7712** [comment]
> BeanObject#attributes 裡面的型別是 Object 而且還不一定每個都是同型別，比如說
{count=10,mean=3.2}
兩者的型別是 Object 但其實他們是 Integer 和 Double。而我看到的序列化工具都要先固定好型別，沒辦法對 Object 序列化。

我們是以 kafka 效能指標為目標的話，物件應該都是 primitve type，因此我們可以將該“限制”作為基礎來看這件事情

**Comment by chinghongfang** [comment]
> 我們是以 kafka 效能指標為目標的話，物件應該都是 primitve type，因此我們可以將該“限制”作為基礎來看這件事情

想請問 "限制" 是指把 `long`, `short`, `float` 這些型別都轉型成比較通用的 `double` 嘛？
之後的 `HasCount`, `HasRate` 再自行用 attribute name 來判斷型別。

**Comment by chia7712** [comment]
> 想請問 "限制" 是指把 long, short, float 這些型別都轉型成比較通用的 double 嘛？

應該說是在序列化的時候我們要根據“物件原本的型別”去做轉換，但我們只針對 primiitve type，其他型別一率拋出錯誤

**Comment by chinghongfang** [comment]
> 應該說是在序列化的時候我們要根據“物件原本的型別”去做轉換

我看到的工具，要事先定義好物件是由哪些 primitive type 組成的，所以不會檢查型別再拋錯。

還是指定義各種 schema 以不同的物件傳送嘛？

比如說，有一個 `BeanObject` 其對應的 `HasBeanObject` 實做了 `HasCount` 和 `HasStatistics`，所以這個 `BeanObject` 的 `attribute` 內有
{"Count"=10,
"Max"=100.0,
"Min"=20.0,
"Mean"=60.0,
"StdDev"=30.0}

那我就定義一個新的型別 (比如 `CountStatistics`)，裡面要有 1 個 `long`, 4 個 `double`，使用這個新的型別來序列化這樣嘛？

**Comment by chia7712** [comment]
> 我看到的工具，要事先定義好物件是由哪些 primitive type 組成的，所以不會檢查型別再拋錯。
還是指定義各種 schema 以不同的物件傳送嘛？

應該是說我們要用一個通用的方式來保存`BeanObject`

```java
  private final String domainName;
  private final Map<String, String> properties;
  private final Map<String, Object> attributes;
  private final long createdTimestamp;
```

以上方為例，`attributes`應該是唯一要討論的，由於我們限定只支援 primitive type，我們就可以將物件都轉成字串，最後再用`parse`將各自的內容從字串轉回來

類似這樣的手法

**Comment by chinghongfang** [comment]
> 由於我們限定只支援 primitive type，我們就可以將物件都轉成字串，最後再用parse將各自的內容從字串轉回來

原來如此，這樣就可以用工具來幫忙做序列化了。
不過這樣有一個缺點，多了 "最後再用parse將各自的內容從字串轉回來" 的型別轉換吧？

**Comment by chia7712** [comment]
> 多了 "最後再用parse將各自的內容從字串轉回來" 的型別轉換吧？

是的，這會是一個副作用

**Comment by chinghongfang** [comment]
好的，那我再來實際使用 Aapche Avro 和 protocol buffer 看看，然後再到 #1581 分享。

**Comment by chia7712** [comment]
> 好的，那我再來實際使用 Aapche Avro 和 protocol buffer 看看，然後再到 https://github.com/skiptests/astraea/issues/1581 分享。

讚讚，盡量試著用 #1581 提到的那幾個使用案例作為參考，看能否適用於目前專案內的各種用法

**Comment by chinghongfang** [comment]
#1640
