### ISSUE TITLE
a new infra for metrics system

### ISSUE THREAD

**Issue by chia7712** [skiptests/astraea#1594]
`LocalMetricCollector` 實作在本地拉取 metrics 的手法，當同一個 JVM 身上有許多元件需要 metrics 的時候，會導致同時建立多的 metrics collector，這個在效能上的開銷非常的大

雖然我們已經有設計另一個 `InternalTopicCollector` 實作，透過獨立且額外的程式來拉取 metrics，即時如此，`LocalMetricCollector`依然是一個用來個體使用和測試的好工作

**Comment by chia7712** [comment]
另一個作法則是我們要讓`InternalTopicCollector`可以像是 embedded 般服務，如此我們可以將各個元件和測試時使用的metrics collector 都換成`InternalTopicCollector`版本

@chinghongfang 你覺得呢

**Comment by chia7712** [comment]
> 所以 Service 在建立 cluster 時，也可以設定 publisher 的參數並一起建立，讓我們測試的時候可以用 InternalTopicCollector 測試

綁在 service 也是一個手法，不過這一步要走的話必須要重新撰寫目前的 metrics publisher，寫成一個 main class 不容易做成一個 service

**Comment by chia7712** [comment]
現在"internal topic" and "local" 兩者最大的差異其實來自於“metrics"到底放在哪裡？所以我們可以根據這個概念重新實作”基礎的metrics"：

1. metrics publisher：都是透過 mBean client 撈取遠端全部(註1)的metrics，並且放到目標端（topic or local）

2. Metrics collector 則是從目標端(local or topic）拉取資料，並經過`metrics sensor`的處理（得知哪些要留下來），然後通通保存到local cache(註2）


註1:應該要有一個方法來收斂要抓的metrics範圍
註2:local cache 會將保存的metrics封裝成 ClusterBean

依照上述的架構，我們可以讓local and topic 大部分的程式碼都共用

@chinghongfang 你覺得呢？

**Comment by chinghongfang** [comment]
原來如此，請問是像下面這張圖的架構嗎？

<img width="586" alt="截圖 2023-03-23 下午8 06 56" src="https://user-images.githubusercontent.com/26920893/227199130-e2012e7b-7ad8-44a6-9e44-df00e12261d9.png">

Metric collector 共用同一個邏輯，但是 "介面" 底下有不同的實作。
Metric publisher 則是共用 "拉取 mbean" 的邏輯，只是放到不同的儲存地點。然後 Metric publisher 則是會跟著 "介面" 的實作，來決定是否生成 (使用 local 則**需要** publisher，使用 topic 則**不需要** 因為放在其他地方了)。

**Comment by chia7712** [comment]
> Metric collector 共用同一個邏輯，但是 "介面" 底下有不同的實作。

應該是說我們把有不同實作的“動作”抽成介面，然後其他邏輯就可以共用。例如使用metrics這段，我們把拿資料這段抽象成 `Receiver`，對於 topic 版本而言就是用 consumer去實作來從 topic拉資料、local版本就是在本地的queue直接拿資料就好

> Metric publisher 則是共用 "拉取 mbean" 的邏輯，只是放到不同的儲存地點。\

類似你說的，再加上上面我補充的部分，所以這裡抽象化的動作是`publish`，topic版本是會丟到topic，local版本則是把資料推到local cache

**Comment by chinghongfang** [comment]
那我再來重構 Metric Collector 和 Metric publisher。

**Comment by chia7712** [comment]
@chinghongfang 麻煩試試看新的架構能不能重寫原本的 metrics publisher? 另外我也會逐一替換現有的 local metrics collector

**Comment by chia7712** [comment]
大部分的工作都已經完成，所以關閉此議題。後續的效能和改善會開新的議題
