### ISSUE TITLE
`TopicAdmin#groups` API semantic question 

### ISSUE THREAD

**Issue by garyparrot** [skiptests/astraea#163]
我使用 `TopicAdmin#groups` 時發現，他好像抓不到沒被分配到 partition 的 consumer

```java
        public static void main(String[] args) {

            // create a single partition topic
            TopicAdmin.of("localhost:16612")
                    .creator()
                    .topic("my-topic")
                    .numberOfPartitions(1)
                    .create();

            // add four consumers into the same group, even though only one of them will work
            launchUselsesConsumer(Set.of("my-topic"), "salary-thieves", "alex", false);
            launchUselsesConsumer(Set.of("my-topic"), "salary-thieves", "bob", false);
            launchUselsesConsumer(Set.of("my-topic"), "salary-thieves", "gary", false);
            launchUselsesConsumer(Set.of("my-topic"), "salary-thieves", "dallas", false);

            var groups = TopicAdmin.of("localhost:16612")
                    .groups(Set.of("my-topic"));
            groups.forEach((x, y) -> System.out.printf("%s %s%n", x, y));

        }
```
```
my-topic-0 [Group{groupId='salary-thieves', offset=0, members=[Member{memberId='alex-815964ef-030d-43cf-897b-a96c55825a28', groupInstanceId=Optional[alex], clientId='alex', host='/192.168.0.2'}]}]
```

* 上面的程式碼建立 `my-topic` 這個只有一個 1 個 partition 的 topic
* 然後建立 consumer group `salary-thieves`, 加入 4 個 consumer
  * 可以預期 4 個 consumer 只有一個會工作
* `TopicAdmin#groups` 的回傳結果中只看得到在工作的那 1 個 consumer, 抓不到其他 3 位薪水小偷

API 語義本身看起來是回傳每個 `TopicPartition` 對應到的 `List<Group>` 訊息，因為薪水小偷沒有被分配到 `Partition` 所以這邊沒抓到似乎有點正常。

我在處理 TopicOffset 的 issue 時想要抓到所有的 consumer member, 我是不是應該加個新 API，或有其他處理方式

**Comment by chia7712** [comment]
> API 語義本身看起來是回傳每個 TopicPartition 對應到的 List<Group> 訊息，因為薪水小偷沒有被分配到 Partition 所以這邊沒抓到似乎有點正常。

這邊可以考慮翻轉一下語意，原本設計用`partition`作為key顯然有疏失，會導致薪水小偷的`member`被忽略，因此可以考慮倒過來

簡單來說，我覺得修改API是個比較好的方向，看你是否有空思考一下新的設計，我覺得你能提出更好的方式

**Comment by garyparrot** [comment]
我稍早在電腦前沉思了幾個小時後的想法：

* 其實舊有 API 看起來目標是要索取每個 `TopicPartition` 被 consumer group 消費的狀況，他只關係消費的狀況，不關注誰沒在工作或 member 真的有幾位。這隻 API 尷尬的點應該是在命名的部分 `groups` 容易讓人誤導這件事情。改成 `consumerGroupOffset` 可能比較貼切些。
* 如果真的建立一個 API 把蒐集 offset 和 member 全部都抓起來做，我感覺怪怪的，那個 API 的回傳結果好像包含了很多彼此獨立的事情，這個奇怪的感覺大概是源自於 Consumer group 和 topic 之間的關係是多對對，在多對多的情況下建立一個包含所有情境的結果讓我覺得不太對勁(要收集 topic/partition 的資料又要收集 consumer 的資料, 感覺好像這個 API 在做兩個分離的事情)

我現在的想法是

* `groups` 改名 `consumerGroupOffset`
* 新增 API, `consumerGroupMember`, 用來索取 consumer group 當前的 member 有哪些

這兩個 API 配合使用能做到顯示沒有工作的 consumer 的效果

**Comment by chia7712** [comment]
> 要收集 topic/partition 的資料又要收集 consumer 的資料, 感覺好像這個 API 在做兩個分離的事情)

我們要提供自己的介面封裝kafka admin有一個很大的原因是 - 在各個元件中很容易需要存取這些資料之間的合集，而這也是kafka admin沒有提供的功能，當然kafka admin會這樣做有效能和設計上的考量，畢竟提供“單一”功能然後讓使用者自行組合是比較安全且簡單的做法

> 新增 API, consumerGroupMember, 用來索取 consumer group 當前的 member 有哪些

這個方法也可以，如果你覺得要調整現有`groups`很奇怪的話，新增一隻API針對memeber做存取也可以，不過如果做的過程發現很多東西跟`groups`重複，那就要重新思考是否要調整舊有APIs就好
