### ISSUE TITLE
[SCRIPT] 針對 start_hadoop.sh 新增 data folder 參數

### ISSUE THREAD

**Issue by Haser0305** [skiptests/astraea#1636]
當下使用專案中 `start_hadoop.sh` 建立 data node 時，無法像建立 broker 一樣設定 `DATA_FOLDERS` 來指定資料存放位置
因此建議可以像 `start_broker.sh` 一樣設定 `DATA_FOLDERS`，使的腳本建立 datanode 時可以透過這參數指定 datanode 預設存放路徑 `/tmp/hadoop-astraea` mount 到本機的位置。

**Comment by chia7712** [comment]
好建議，這個應該是很需要做的功能，因為會直接影響 io

我把它放到 0.3.0裡面
