### ISSUE TITLE
[perf] connector 應該要支援使用 RecordGenerator

### ISSUE THREAD

**Issue by chia7712** [skiptests/astraea#1639]
#1638 將 `RecordGenerator`從單機版抽取出來，其豐富的資料產生功能應該要套用到 perf connector 身上，讓我們可以在分散式版本的 perf connector 進行多元的資料組合測試

**Comment by chia7712** [comment]
@Haser0305 @chaohengstudent 可否看一下這個題目

**Comment by chia7712** [comment]
@Haser0305 @chaohengstudent #1644已經完成基本的移植，但許多參數還沒真的套用，麻煩你們後續接著改

如果沒有時間的話，也麻煩說一聲

**Comment by chia7712** [comment]
@Haser0305 麻煩確認一下是否所有參數都已經移植過去？

**Comment by Haser0305** [comment]
> @Haser0305 麻煩確認一下是否所有參數都已經移植過去？

有確認了 RecordGenerator Builder 中可以變更內部參數的10個 method 都有被使用並在 PerSource 中添加說明

**Comment by chia7712** [comment]
@Haser0305 感謝，確認後麻煩關閉次議題 謝謝
