### ISSUE TITLE
移除中文的log訊息

### ISSUE THREAD

**Issue by chia7712** [skiptests/astraea#164]
現在的`Tracker`中有不少的中文輸出資訊，在不支援中文的環境中會變成亂碼，為了世界和平我們應該要統一用英文的輸出格式

**Comment by chia7712** [comment]
@chinghongfang 可否麻煩看一下，這是我今天在廠商那邊遇到的狀況，雖然我也很喜歡中文，但變成亂碼就是會怪怪的

**Comment by chinghongfang** [comment]
好的，我把輸出的中文都改成英文。
