### ISSUE TITLE
[PARTITIONER] 應該考慮 partition 的選擇

### ISSUE THREAD

**Issue by chinghongfang** [skiptests/astraea#1650]
現在的 partitioner 選擇 partition 的邏輯是：針對 broker 進行打分 -> 選擇 broker -> broker 內隨機挑選 partition

然而，同一個 broker 內的 partition 之間也有負載平衡問題，比如說，同一台 broker 內 partitions 分在不同顆硬碟上，然後不同顆硬碟的剩餘使用空間不同。

討論後，我們可以改成：
1. 先挑選 broker，若 broker 內有多個 partitions ，從其中挑選
2. 直接從所有 partition 挑選

我們傾向使用 1. ，先用 smooth round-robin 選擇 broker ，然後再從中挑選 cost 最低的 partition。
因我們認為 broker 有比較大的影響，且 round-robin 會儲存每一個項目的權重，若我們拿所有的 partition 做 smooth round-robin ，同樣 broker 的權重仍應該會相似，增加不必要的判斷。

**Comment by chia7712** [comment]
> 我們傾向使用 1. ，先用 smooth round-robin 選擇 broker ，然後再從中挑選 cost 最低的 partition。
因我們認為 broker 有比較大的影響，且 round-robin 會儲存每一個項目的權重，若我們拿所有的 partition 做 smooth round-robin ，同樣 broker 的權重仍應該會相似，增加不必要的判斷。

+1
