### ISSUE TITLE
[WEB] Enable non-string JSON type in `/balancer` request payload

### ISSUE THREAD

**Issue by garyparrot** [skiptests/astraea#1717]
Context: https://github.com/skiptests/astraea/pull/1711#discussion_r1188742959

![image](https://github.com/skiptests/astraea/assets/39105714/9cb852c8-abf0-400f-ac8b-4a806117683a)

讓 `balancerConfig` 接受非 String 的輸入形態

**Comment by garyparrot** [comment]
剛剛注意到 `CostConfig` 的地方是有寫數字的情況，測試一下後發現現在的程式碼 (`balancerConfig` & `costConfig`) 好像已經可以支持非 String 的輸入，底下的序列化框架會把數字轉換成字串。所以文件內的字串括弧應該是可以刪除。

![image](https://github.com/skiptests/astraea/assets/39105714/5f6a212e-2b4c-4609-a2a9-4b5672f213d8)

另外一方面如果輸入 Object 或 Array 的話底下的框架會報錯

![image](https://github.com/skiptests/astraea/assets/39105714/6b70b910-b667-4b32-a666-51f0861dcb41)

![image](https://github.com/skiptests/astraea/assets/39105714/6f5112a2-0f58-4323-80e5-62d5c1c13105)

如果把底下接 PostRequest 的物件格式從 String 改成 Object 的話，可以序列化成 Array & Object

![image](https://github.com/skiptests/astraea/assets/39105714/484f5750-22d5-4404-b119-7301a263c129)

![image](https://github.com/skiptests/astraea/assets/39105714/b2dcf1f5-8722-4719-8938-5a4a0bc2f112)

**Comment by chia7712** [comment]
看來我們應該先討論`Configuration`要否支援完整的`json` type? 現在的 configuration 有自己的格式來處理 (string) array，也就是透過逗號，原本這個方便是為了符合 Kafka configs的風格，畢竟我們大部分的參數傳遞還是透過 kafka 的機制...

如果保持現在的格式的話，其實也能達到數字的處理，我個人是覺得應該有滿足應用了，這樣的話就只要改文件就好

@garyparrot 你覺得呢？

**Comment by garyparrot** [comment]
> 如果保持現在的格式的話，其實也能達到數字的處理，我個人是覺得應該有滿足應用了，這樣的話就只要改文件就好

我也覺得可以暫時保持這樣，如果未來有很顯著的需求的 Array/Object 需求的話可以再研究，後面會開一個 PR 修正文件

**Comment by chia7712** [comment]
@garyparrot 感謝確認，文件再麻煩協助更新
