### ISSUE TITLE
[METRICS] topic collector 需要收集 local jmx metric

### ISSUE THREAD

**Issue by chinghongfang** [skiptests/astraea#1718]
現在的 topic collector 只有從 topic 收集 `BeanObject` ，而這些存在 topic 的 `BeanObject` 是從另一個獨立元件 `MetricPublisher` 來的。現在我們若想要使用 topic collector 同時又收集 local jmx metric ，有兩種方法：
1. 將 local jmx metric 同樣使用 `MetricPublisher` 放到 topic 上
2. 再開一個 local metric collector 專門收集 local jmx metric

但是這兩種方法都不好，1.) local jmx metric 直接取用的成本低於放到 topic 上，沒必要多此一舉。2.) 外部使用將需要管理兩個 `MetricCollector`，回傳的 cluster bean 也會變成兩個，不方便使用。

提出作法：
修改 `MetricStoreImpl` 的實做，將 `MetricStore::Builder#reciever()` 改成 `MetricStore::Builder#addReceiver()` ，為 `MetricStore` 新增多種來源。

其他作法：
在 topic receiver 中新增 "抓取 local jmx" 的邏輯。
這樣一個 receiver 內會接收兩個不同的來源端，reciever timeout 的時間將要分給兩種來源端，邏輯奇怪，且不合原本介面的設計。

**Comment by chinghongfang** [comment]
@chia7712 我這裡先寫了一版上面提出的作法 (#1720 )，這裡只是先提供程式馬上來給大家看看，可以再討論看看要不要這樣修改 (把 reciever 改成 addReceiver)。

**Comment by chia7712** [comment]
> 現在我們若想要使用 topic collector 同時又收集 local jmx metric

不好意思，這件事情現在的程式碼中沒有做嗎？ 

https://github.com/skiptests/astraea/blob/main/common/src/main/java/org/astraea/common/partitioner/StrictCostPartitioner.java#L153

就我目前的認知是`localReceiver`會建構一個 embedded MetricFetcher，然後`StrictCostPartitioner`會加入 local `JndiClient`，如此應該會抓到 local metrics才對，還是我有什麼誤會？

**Comment by chinghongfang** [comment]
Closed by #1720
