### ISSUE TITLE
Performance tool 輸出CSV檔

### ISSUE THREAD

**Issue by chinghongfang** [skiptests/astraea#172]
目前專案內的Performance tool會把數據直接打印出來，為了數據獲取的方便性，應該要額外把數據格式化輸出，例如：.csv 檔。可直接使用試算表工具開啟，後續要繪製圖表、製作報告較為方便。

**Comment by chia7712** [comment]
@chinghongfang 考量之後我們要交換文件，可能用google docs（或其他線上文件）會比較方便，因此要麻煩確認一下該些線上工具是否支援`csv`

**Comment by chinghongfang** [comment]
好的。
已確認google sheet, Microsoft office 365 excel 可以讀取`csv`檔。

**Comment by chinghongfang** [comment]
待處理
1. 數字保持小數點後兩位就好，太長後面也沒有意義影響閱讀。producer rate和consumer rate要加進去。
2. tracker的東西可以選擇輸出到console。
3. tracker的東西可以選擇要否輸出到file。

**Comment by chia7712** [comment]
@chinghongfang csv的輸出路徑是否為固定無法選擇的？如果是固定的話，請發一隻PR來讓其可以彈性設定，謝謝
