### ISSUE TITLE
[BALANCER] Balancer 要能夠看到 internal topic 的資訊

### ISSUE THREAD

**Issue by garyparrot** [skiptests/astraea#1747]
Context: https://github.com/skiptests/astraea/pull/1737#issuecomment-1547785303

目前 Balancer 沒有辦法對 internal topic 進行處理，這個情況間接造成清除節點負載的功能沒辦法把 internal topic 移走，對此我們可能需要新增一個設定讓 balancer 能夠看到 internal topic 的資訊。

**Comment by garyparrot** [comment]
這個 Issue 我覺得有兩種處理方式

* 給 [POST /balancer](https://github.com/skiptests/astraea/blob/main/docs/web_server/web_api_balancer_chinese.md#%E6%8E%92%E7%A8%8B%E6%90%9C%E5%B0%8B%E6%96%B0%E7%9A%84%E8%B2%A0%E8%BC%89%E5%84%AA%E5%8C%96%E8%A8%88%E5%8A%83) 添加一個新的參數 `withInternalTopic`，當 WebAPI 看到這個 Flag 就要給他包含 internal topic 的 `ClusterInfo`。
  * 好處: 不需要增加 Balancer 實作的複雜度，這個功能可以在 Web API 內完成
  * 壞處: `ClusterInfo` 序列化檔案內如果沒有包含 internal topic 的資訊，則我們沒辦法事後說想模擬 internal topic 的負載平衡實驗(喪失了 Balancer 這層的門把去決定要不要做 internal toic 的處理)
  * 壞處: 如果使用者要使用 `demoted` 功能，那幾乎一定要開啟這個 flag，且有機會導致其他非 `demoted` 的節點上的 internal topic 被更動
  * 壞處：選擇忽略 internal topic，需要注意"忽略"和"不作為"有很大的差異，有他的缺點在，詳細見下面討論
* 實作成 `AlgorithmConfig` 的一個新設定，設定表示要不要進行 internal topic 的負載平衡，同時 WebAPI 總是要提供有 internal topic 版本的 `ClusterInfo`
  * 好處: 我們可以在 Balancer 這層多一個門把來 決定要不要做 internal topic 的處理。
  * 壞處: Balancer 的實作複雜度增加，現在他在處理的時候可能要刻意地去迴避 internal topic

我目前是偏好後者方案。

* 後者方案的缺點其實還好，因為只是多幾個過濾要考慮這樣，Balancer 實作本身已經夠複雜了，這個新增的複雜度其實算小。
* 雖然使用者可能會在 `AlgorithmConfig` 內指名避免進行 internal topic 的移動，但具體實作可以讓 `demoted` 可以跨過這個限制，同時不會有前者方案的第二個壞處（讓其他非 `demoted` 節點的 internal topic 被移動）
* 前者方案把 internal topic 從 Balancer 眼裡隱藏，隱藏的下場是 Balancer 可能會漏算他們的負載，造成負載上的不平衡風險。後者方案要求輸入 ClusterInfo 一定要包含 internal topic 資訊，能夠看到更全局的叢集負載狀況，且雖然看到也不一定要對他們做負載平衡，這個是一種 "不作為"，不作為和隱藏的差距就是不作為可以被他們的負載也一起算進來，來做更精密的負載衡量。

**Comment by garyparrot** [comment]
> +1 你覺得參數該如何設計比較好？

我原本是想說放到 `AlgorithmConfig`，但後來覺得和你說的一樣，跟 `allowedTopics` 做在一起會比較好，因為這個參數有一些複雜的互動存在（見下面），可能會需要比較細緻的實作，用成 Config 然後要求 Balancer 實作明確指出我可以支援比較好。

> 我直覺是在allowedTopics這個函式做調整就好？應該其他部分不會有太大變動？

這個是一種做法，但他會和 `demoted` 有點衝突，當 `demoted` 被使用且 internal topic 又不是 allowed 的情況。也就是這個 Issue 的問題源頭

![](https://user-images.githubusercontent.com/39105714/238279812-8709b9e9-db12-4a48-8ea6-e80923a32d25.png)

如果遇到這種情況的時候 `demoted` 會有清不乾淨的情況，我目前是在想這個部分要怎麽處理，我目前想法是有三種

* 如果 `demoted` 被指定的話，位於 `demoted` broker 的 internal topic 會被強制 allow。
* 如果 `demoted` 被指定的話，如果設定 `balancer.force.demote.internal.topic`，位於 `demoted` broker 的 internal topic 會被強制 allow。
* 讓 `balancer.allowed.topics.regex` 參考 `balancer.broker.balancing.mode` 的做法，用三種 case 表達這個情況(`balancing`, `demote_only`, `excluded`)。
* 把 `balancer.allowed.topics.regex` 的指定粒度從 `topic` 變成 `topic` & `topic-partition` & `topic-partition-replica`，然後使用者要自己去調整這個參數以至於 `demoted` 節點身上的負載變成 `allowed` 以至於他們可以被負載平衡。

第三種做法，我猜最後大家幾乎不會去使用 `excluded` 這個選項，因為絕大多數我們想要 `demoted` 的時候，我們應該也會期待 internal topic 也一起被移走。剩下第一種和第二種做法的差異只是在，把這個行為弄成可以參數調整，或是直接固定採取一個做法。

第四種做法可能會很複雜，使用者可能需要撰寫非常精密的設定才能夠跑 Balancing，但這個做法的自由度最高。

我目前是偏好第四種做法

**Comment by chia7712** [comment]
> 如果遇到這種情況的時候 demoted 會有清不乾淨的情況，我目前是在想這個部分要怎麽處理，我目前想法是有三種

@garyparrot 感謝分析，這幾個作法涵蓋了各種情境。不過為了讓使用者用起來不會寫出”很恐怖“的參數，我們採取第一種做法可能比較適合，迎合常見的情境同時參數設定也簡單

**Comment by garyparrot** [comment]
> 我們採取第一種做法可能比較適合，迎合常見的情境同時參數設定也簡單

+1, 這個議題會在 #1737 合併後開始進行，有一些比較核心的處理等他合併後再開始會比較順
