### ISSUE TITLE
[CONNECTOR] Importer 讀取效能問題

### ISSUE THREAD

**Issue by chaohengstudent** [skiptests/astraea#1842]
## 實驗環境簡述：
3 台 borker、 3 台 worker、1 台 namenode、3 台 datanode

## 實驗資料：
原始資料：performance tool 以預設參數打入 500 GiB 資料 (1 個 Topic、100 partition、replica = 1)，使用 Exporter 寫入 hdfs

hdfs 中呈現方式：
```
<Root>
│
├── <Topic>
│   ├── <Partition 0>
│   │   ├── <Offset 0>
│   │   ├── <Offset 1115714>
│   │   └── ...
│   ├── <Partition 1>
│   │   ├── <Offset 0>
│   │   ├── <Offset 1111444>
│   │   └── ...
│   └── ...
└── ...
```
* 一個 `partition` 資料夾中約有 46 個 file
* 一個 file 大小 （`Offset k`）約為 95 MB
* dfs replication = 3

### 1. hdfs 指令讀取
三台 worker 分別讀取部份資料
```shell
./hadoop-3.3.5/bin/hdfs dfs -copyToLocal hdfs://<HOST>/tmp/Exporter1/NewTopic/{0..33} /ssd1/Exporter/NewTopic/
./hadoop-3.3.5/bin/hdfs dfs -copyToLocal hdfs://<HOST>/tmp/Exporter1/NewTopic/{34..66} /ssd1/Exporter/NewTopic/
./hadoop-3.3.5/bin/hdfs dfs -copyToLocal hdfs://<HOST>/tmp/Exporter1/NewTopic/{67..99} /ssd1/Exporter/NewTopic/
```
#### 圖片一 
> avg：600 ~ 700
![image](https://github.com/skiptests/astraea/assets/106939297/8081e993-cf5a-4a29-8c28-b5a06b243bde)

#### 圖片二
> avg：≈ 60
![image](https://github.com/skiptests/astraea/assets/106939297/705a959f-730c-43e0-a71a-a1cd9cb80a83)

#### 圖片三
> avg：≈ 500
![image](https://github.com/skiptests/astraea/assets/106939297/38fe94df-67dd-48c8-a0a6-ce41916daada)

#### 圖片四
> tasks 數量依序：3、15、30、45、60
對應 avg：70、170、240、300、300
![image](https://github.com/skiptests/astraea/assets/106939297/bbf3d48a-763b-4be7-a4b3-79d5df9010ab)

## 目前觀察：

目前邏輯 `Importer.take()` 中會讀取一個檔案並將資料組成 `List<SourceRecord>` 回傳 ，
以此實驗情境即是讀取一個約 `95 MB` 的檔案，其中約包含 `180000` 筆 records ，
`take()`操作約耗費 `220 milliseconds`
再到下一個 `take()` 操作約間隔 `1200 milliseconds`（AbstractWorkerSourceTask 中的 [poll-convert-send loop](https://github.com/apache/kafka/blob/4590d565ef08e48411123aa1ecbb46bd8130a3de/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/AbstractWorkerSourceTask.java#L336-L386)）
因此平均讀取速率約落於 95/1.42 =  `66.9 MiB/s`。

也有嘗試過減少一次 take() 回傳的 SourceRecord 數量，但總體而言平均速率差異不大，在想是否是 poll-convert-send loop 需要的時間導致，只有在不回傳 SourceRecord 時（圖片三），才能達到因為沒有資料而不斷執行 poll 提昇讀取（但沒有意義）。

目前只能透過增加 task 數量（圖片四）提昇速率。

**Comment by chia7712** [comment]
> 也有嘗試過減少一次 take() 回傳的 SourceRecord 數量，但總體而言平均速率差異不大，在想是否是 poll-convert-send loop 需要的時間導致，只有在不回傳 SourceRecord 時（圖片三），才能達到因為沒有資料而不斷執行 poll 提昇讀取（但沒有意義）。

看起來像是組成 record 的成本很高？有試過先產生假的record 然後每次都回傳同樣的records嗎？也就是避免掉產生record 的成本

**Comment by chaohengstudent** [comment]
測試在 init 時就建好 source records 然後在 poll 時直接回傳建好的 source records 不做其他操作，
下一次 poll 時間間隔和回傳數量呈現正比關係，
讀取速率會被這個間隔限制住。

![image](https://github.com/skiptests/astraea/assets/106939297/c2a07342-7dd2-4080-993e-729da80a90a2)

**Comment by chaohengstudent** [comment]
以目前的實做而言讀取效能受到處理 records 的時間所限制，如須提昇可能需要調整實做方式如非同步讀取來設法改善。
