### ISSUE TITLE
Dependency client optimize

### ISSUE THREAD

**Issue by wycccccc** [skiptests/astraea#190]
Dependency client應該在多producer調用的情況下保證thread-safe
Dependency client應該再沒有啟動dependency功能的時候擁有防呆

**Comment by wycccccc** [comment]
@chia7712 想問一下學長，如果我在`producer.send(ProducerRecord<>(topic, partition, timestamp, key, value, Header.of(headers)))`外再包一層可以嗎，
例如`dependency.send(topic, partition, timestamp, key, value, Header.of(headers))`.
或者`dependency.send(ProducerRecord<>(topic, partition, timestamp, key, value, Header.of(headers)))`

然後設計改成不通過partitioner直接計算要丟到哪個partition，直接發送。

**Comment by chia7712** [comment]
可否提供一段範例講一下客戶會怎麼使用這個新的API?

**Comment by wycccccc** [comment]
```
KafkaProducer producer = new KafkaProducer(props);
DpendencyClient  dependencyClient = new DpendencyClient(producer);
dependencyClient.send(ProducerRecord<>());
dependencyClient.send(ProducerRecord<>());
dependencyClient.send(ProducerRecord<>());
```

應該這樣就可以了。

**Comment by chia7712** [comment]
我想先問一下為何要改成這種用法？是技術問題嗎？

**Comment by wycccccc** [comment]
讓producer可以同時兼顧dependency和普通的傳輸，就代表了我們不能為partitioner維護一個狀態控制資料的發送。
換言之，控制dependency的手段，就變成了只能以每筆資料為單元進行控制。
而從每筆資料的角度出發，我能想到的目前只有兩種。
第一種是通過包裝`send() `自動format record的key讓partitioner有能夠識別dependency資料的手段。
但我猜這對於使用者來說應該有些嚴格。
第二種就是直接呼叫计算load的method，算出一个broker然后从其中挑选一个partition。用producer的`send()`中的partition参数直接指定目标partition。
第二種我感覺更加合理，因為一個dependency的partition決定了之後也就不會再變了。只要一開始能知道目標也就不需要partitioner再決定partition的去處了。另外partitioner篩選dependency的資料也會是一個問題。
