### ISSUE TITLE
BeanCollect中的tryUpdate()在多producer調用的情況下存在一些問題

### ISSUE THREAD

**Issue by wycccccc** [skiptests/astraea#197]

**Comment by chia7712** [comment]
please describe the "bug" - for example, how to reproduce the bug?

**Comment by wycccccc** [comment]
當調用astraea partitioner時，使用多個producer時會有這個問題。但使用一個producer就不會
![image](https://user-images.githubusercontent.com/43372856/150670911-fe187d31-d24b-4bad-92f3-e33f9d4a3ae4.png)

**Comment by chia7712** [comment]
目前沒在觀察到此問題，故關閉
