### ISSUE TITLE
Our cluster is a little weird.

### ISSUE THREAD

**Issue by wycccccc** [skiptests/astraea#199]
目前的測試中會有一個很神奇的現象。當Performance運行一段時間後（大約在1~2min）效能會突然陡然下降，在Default Partitioner的時候尤其明顯，會變為0。然後再次升高到1000。上述情況會呈現出週期性的波動。

我首先嘗試了只開一個Performance對Default Partitioner進行測試（我們的實驗會在兩台機器上分別開一個performance）。結果與上述一致。

然後我們使用了openMessage的kafka測試工具對我們的集群進行測試。
結果一樣是會呈現出throughPut週期性變化。由此排除是我們的Performance出現了問題。
![1642926619171](https://user-images.githubusercontent.com/43372856/150826368-ebcb32fd-3d59-4e6a-902e-976d99fd2bee.png)

接著我們下載了Kafka，直接建立集群進行測試
結果一樣如上圖數據，throughPut呈現出週期性變化。由此排除docker kafka影響。

接著我們將外網網路切斷，繼續進行測試。結果依舊如上。排除外網干擾因素。

重啟機器及交換器，情況依舊如上。

使用Prometheus查看集群硬體狀況，大項的硬體指標均沒有滿載情況（CPU usage，cache usage，IO usage）。細項的指標的話還不太能理解。

我不太能夠想到還有其他可能會造成改狀況的原因。因為似乎上次測試的時候數據的顯示還比較正常。

在無數的測試過後，我總結出了一些規律。
docker啟動後的第一次測試數據是相對最正常的。第二次開始上述的問題就會變得越發嚴重。
docker重啟後第一次狀況依然保持最好。
如果我讓集群休息很長時間。例如我跑完一次測試然後去吃了個飯。回來之後他又變成了類似於第一次狀況比較好的情況。
我們的partitioner對於這種狀況的應變能力總是優於Default Partitioner。

得出的第二次上傳的數據結論，經過多次測試且每一次都保證為docker重新啟動後的第一次測試。

對比第一次測試時集群的狀況它目前應該是不正常的，我想詢問下學長，可能導致變成這樣的原因。

**Comment by wycccccc** [comment]
集群系統的時間不是台灣時區的時間可能會造成影響嘛，之前有針對這個點進行修改測試，改成正常時間後，似乎也沒有用。但是今天重啟集群機器，時間又變回+0時區了，記憶紊亂不太確定是重啟後測試還是測試後重啟，再問一下學長這個點。

**Comment by chia7712** [comment]
@wycccccc 可否把叢集的參數和performance的參數也貼上來？

**Comment by wycccccc** [comment]
測試時間13：55～14：15，共20min

![Screenshot from 2022-01-25 14-22-11](https://user-images.githubusercontent.com/43372856/150928077-a150fa82-18d5-44a5-bee2-b80e5d5996e3.png)

以下爲performance 測試數據
https://drive.google.com/drive/folders/1UsQgKfB1CO8qDzi-gg03qsiBdpeI7PRE?usp=sharing

另performance存在一個bug，經常不會自己結束，所以記錄下來的數據末尾會有很多0。該bug我之前有和方竫泓討論過，目前還在解決中。然後之前測試記錄下來的數據我都會截取20min再做圖標。

**Comment by chia7712** [comment]
這已經確定是硬碟問題 (https://github.com/skiptests/astraea/issues/228)
