### ISSUE TITLE
[研究] 測試yunikorn的整合

### ISSUE THREAD

**Issue by chia7712** [skiptests/astraea#201]
測試一：透過yunikorn去排程spark application on k8s
- 請自行build yunikorn

測試二：測試最新版 (source code) yunikorn scheduler可以跑在哪些k8s版本
- 1.20.14
- 1.21.8
- 1.22.5
- 1.23.1

測試三：k8s原生scheduler  v.s yunikorn scheduler
- 資源不夠時會發生什麼事情？
- spark driver and executor如何排程？會不會有餓死的狀況

**Comment by chungen0126** [comment]
- 1/28 完成測試版本
- 1/28 完成測試k8s default scheduler & yunikorn scheduler

# yunikorn & k8s的版本相容
yunikorn可以跑在k8s的版本如下：

* [x] 1.20.14
* [x] 1.21.8
* [x] 1.22.5
* [x] 1.23.1



# k8s default scheduler & yunikorn scheduler
## starvaion
4個spark client連續發送10個application ，每個application 的 executor instances是10，造成了starvation，如下圖：只有driver pod在執行。
使用yunikorn 並設定application sort policy 為 fifo、fair這兩種同樣也會遇到starvation的情況。

![](https://i.imgur.com/wsiwMGS.png)
## 解決方法一(stateaware)
設定appication sort policy為 stateaware，則在start狀態的application只有一個，確保k8s是在知道application需要的總資源才去開啟下一個application。![](https://i.imgur.com/MKyFVq1.png)
![](https://i.imgur.com/yAF59rZ.png)
## 解決方法二(gang schedule)
### Hard模式
gang schedule只能在fifo、stateaware下使用，這邊我在fifo情況下使用。
設定最小member為5模式是Hard的情況下，可以看到使用gang schedule會先產生place holder再將這些pods的資源轉移給真正要跑的pods。
![](https://i.imgur.com/J4cwMMt.jpg)
若持有的這些place holder仍無法達到最低的資源要求則會終止執行。
![](https://i.imgur.com/54as0Kk.jpg)

### Soft模式
若gang schedule的模式為soft的情況下，若持有的place holder無法達到最低資源仍會執行。

![](https://i.imgur.com/uXV6Ljg.jpg)

### gang scheduler遇到的問題

兩種模式下，gang schedule執行到一定的程度之後都會觀察到一種情形：
    yunikorn似乎讀不到k8s可用的memory，只有一兩個running pod在使用資源，但是pods都是在pending的階段，但是執行spark使用k8s原生schedule卻可以執行。

**Comment by chia7712** [comment]
> yunikorn似乎讀不到k8s可用的memory，只有一兩個running pod在使用資源，但是pods都是在pending的階段，但是執行spark使用k8s原生schedule卻可以執行。

這個現象在stateaware也會發生嗎？

**Comment by chia7712** [comment]
另外可否比較一下stateaware and gang scheduler的差異？例如功能、分發任務的速度等等，謝謝

**Comment by chungen0126** [comment]
> > yunikorn似乎讀不到k8s可用的memory，只有一兩個running pod在使用資源，但是pods都是在pending的階段，但是執行spark使用k8s原生schedule卻可以執行。
> 
> 這個現象在stateaware也會發生嗎？

這個是我的錯誤，目前已修正這個問題。

**Comment by chia7712** [comment]
> 這個是我的錯誤，目前已修正這個問題

不好意思，可以多說一些細節嗎？例如這個問題的發生是參數沒設定對嗎？

**Comment by chia7712** [comment]
另外，如果項目都已經確認完成，可否將測試過程用的指令和參數檔都貼上來，然後此議題就可以結束，我們在另一個議題討論https://github.com/skiptests/astraea/issues/201#issuecomment-1024195398

**Comment by chungen0126** [comment]
> > 這個是我的錯誤，目前已修正這個問題
> 
> 不好意思，可以多說一些細節嗎？例如這個問題的發生是參數沒設定對嗎？

學長，我又試了幾次在stateaware queue下使用gang scheduler，這個問題好像依然存在，跑到queue滿的時候其餘的pods卡在pending。
然而我試了在不使用gang scheduler的情況下使用stateaware，執行完一個job是會將queue清空的，但是gang scheduler似乎是不會清空的。
另外，fifo情況下的gang scheduler也發生的同樣情況。

**Comment by chungen0126** [comment]
> 不好意思，可以多說一些細節嗎？例如這個問題的發生是參數沒設定對嗎？

我又嘗試了幾次，這個問題依然存在，當我使用gang scheduler來排程，到達一定的數量時，pods都會卡在pending階段。

可能的原因：
我觀察到最後卡在pending的時候queue都會是滿的，所以我嘗試gang scheduler排程10個任務後，發現queue的空間是沒有被釋放的，因此我確認了在沒有gang scheduler的情況下，queue的空間是否會被釋放，然而應該是會被釋放掉的。

**Comment by chia7712** [comment]
> 發現queue的空間是沒有被釋放的，因此我確認了在沒有gang scheduler的情況下，queue的空間是否會被釋放，然而應該是會被釋放掉的。

gang scheduler是比較新的功能，有一些狀況可以想像。接下來有幾個後續：

1）試著去追查此現象的原因，並且嘗試提出修正的方式

2）使用較穩定的stateaware把排程剩下的功能測試完

項目一比較難，可以另外開議題先紀錄等之後功力提升再追。

**Comment by chia7712** [comment]
@chungen0126 可否提供你測試的方式（腳本or指令)? 我這邊也會抽空看一下

**Comment by chungen0126** [comment]
> @chungen0126 可否提供你測試的方式（腳本or指令)? 我這邊也會抽空看一下


首先是yunikorn scheduler的設定
yunikorn configmap

```yaml=
partitions:
  - name: default
    nodesortpolicy:
        type: fair
    queues:
    - name: root
      submitacl: '*'
      queues:
        - name: stateaware
          submitacl: '*'
          properties:
            application.sort.policy: stateaware
        - name: fifo
          submitacl: '*'
          properties:
            application.sort.policy: fifo

```

根據官方網站建立namespace, service account, cluster role bindings等設定 

```bash=
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Namespace
metadata:
  name: spark-test
EOF
```
```bash=
cat <<EOF | kubectl apply -n spark-test -f -
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark
  namespace: spark-test
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spark-cluster-role
  namespace: spark-test
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list", "create", "delete"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spark-cluster-role-binding
  namespace: spark-test
subjects:
- kind: ServiceAccount
  name: spark
  namespace: spark-test
roleRef:
  kind: ClusterRole
  name: spark-cluster-role
  apiGroup: rbac.authorization.k8s.io
EOF
```

gang scheduler測試腳本
-n 設定數量
-s 設定為stateaware的queue（ 默認為fifo )
-h 設定為hard mode( 默認為Soft mode )
```bash=
QUEUE="fifo"
MODE="Soft"


while getopts "n:sh" opt; do
  case $opt in
    n)
    submitnumber=${OPTARG}
    ;;
    s)
    QUEUE="stateaware"
    ;;
    h)
    MODE="Hard"
    ;;
  esac
done
for ((i=1;i<= $submitnumber ;i++))
do
        var=$[$RANDOM  % 10000]
cat > driver$i$var.yaml << EOF
apiVersion: v1
kind: Pod
metadata:
  labels:
    queue: root.$QUEUE
  annotations:
    yunikorn.apache.org/schedulingPolicyParameters: "placeholderTimeoutInSeconds=30 "
    yunikorn.apache.org/task-group-name: spark-driver$i$var
    yunikorn.apache.org/task-groups: |-
      [{
          "name": "spark-driver$i$var",
          "minMember": 1,
          "minResource": {
            "cpu": "1",
            "memory": "1Gi"
          },
          "nodeSelector": {},
          "tolerations": []
      },
       {
           "name": "spark-executor$i$var",
           "minMember": 5,
           "minResource": {
             "cpu": "1",
             "memory": "1Gi"
           }
       }
      ]
spec:
  schedulerName: yunikorn
EOF
cat > executor$i$var.yaml <<EOF
apiVersion: v1
kind: Pod
metadata:
  labels:
    queue: root.$QUEUE
  annotations:
    yunikorn.apache.org/task-group-name: spark-executor$i$var
spec:
  schedulerName: yunikorn
EOF

bin/spark-submit   --master k8s://http://localhost:8001 --deploy-mode cluster --name spark-pi  \
 --class org.apache.spark.examples.SparkPi  \
 --conf spark.executor.instances=5  \
 --conf spark.kubernetes.container.image=wfps1210/spark:latest  \
 --conf spark.kubernetes.authenticate.driver.serviceAccountName=spark  \
 --conf spark.kubernetes.driver.podTemplateFile=driver$i$var.yaml  \
 --conf spark.kubernetes.executor.podTemplateFile=executor$i$var.yaml  \
 --conf spark.kubernetes.submission.waitAppCompletion=false \
 --conf spark.kubernetes.namespace=spark-test \
 local:///opt/spark/examples/jars/spark-examples_2.12-3.2.0.jar


rm driver$i$var.yaml
rm executor$i$var.yaml
done

```

without gang scheduler
如果不是gang scheduler我就沒有生成driver & executor pod template file，而是直截讀取我本地的檔案。
根據想使用的排程方式填入metedata.labels.queue內的名稱。

driver.yaml

```yaml=
apiVersion: v1
kind: Pod
metadata:
  labels:
    queue: root.stateaware
spec:
  schedulerName: yunikorn
```

executor.yaml

```yaml=
apiVersion: v1
kind: Pod
metadata:
  labels:
    queue: root.stateaware
spec:
  schedulerName: yunikorn
```

測試腳本

```bash=
for((i=1;i<=1;i++))
do
bin/spark-submit   --master k8s://http://localhost:8001 --deploy-mode cluster --name spark-pi   --class org.apache.spark.examples.SparkPi \
--conf spark.executor.instances=5   \
--conf spark.kubernetes.container.image=wfps1210/spark:latest   \
--conf spark.kubernetes.authenticate.driver.serviceAccountName=spark   \
--conf spark.kubernetes.driver.podTemplateFile=../driver.yaml   \
--conf spark.kubernetes.executor.podTemplateFile=../executor.yaml   \
--conf spark.kubernetes.submission.waitAppCompletion=false \
--conf spark.kubernetes.namespace=spark-test  \
local:///opt/spark/examples/jars/spark-examples_2.12-3.2.0.jar
done
```

**Comment by chungen0126** [comment]
# Node policy

此次測試，有三台工作節點為yunikorn02、yunikorn03、yunikorn04，三台cpu都是8，三台memory依序是8g、16g、32g。
提交spark任務，driver pod memory 為1，executor pod memory 為 2， executor instances 分別測試4 and 8

## binpacking

根據觀察，此種節點排程政策會從yunikorn-scheduler所在的node排程開始，將所有pod排程至此node，直到無法排程，再依據hostname排序，將剩下的pod牌去到下一個node上。

executor instances 為4的情況下
![](https://i.imgur.com/d72Bxt3.png)

executor instances 為8的情況下
![](https://i.imgur.com/6rzvRzB.png)

## fair

根據觀察，此種節點排程政策，會根據資源可提供的比例來排序，將pod放到最多資源的節點上，因此yunikorn04應該會分配到較多的pod。

executor instances 為4的情況下
![](https://i.imgur.com/0bfvgzp.png)

executor instances 為8的情況下
![](https://i.imgur.com/RXhzWVH.png)

## Resource weighting

在fair的政策下，默認情況下，可用的資源如memory, vcpu計算的權重為1:1，可以透過resource weighting調整memory 和vcpu重視的程度。

調整memory, cpu 的權重為1:9的情況下，由於cpu的資源都是相同的，在看中cpu的情況下，pod會平均分配到各個節點。

executor instances 為4的情況下
![](https://i.imgur.com/gHTldWn.png)

executor instances 為8的情況下
![](https://i.imgur.com/8eh6mMU.png)

調整memory, cpu 的權重為9:1的情況下，由於memory資源不平行的情話下，pod會較多會被分配到yunikorn04。

executor instances 為4的情況下
![](https://i.imgur.com/KwuYxM7.png)

executor instances 為8的情況下
![](https://i.imgur.com/dfakgQB.png)

**Comment by chia7712** [comment]
我參考你貼的gang相關參數去執行，有driver一直處於pending，然後去看log有以下關鍵字

```
request is waiting for cluster resources become available
```

這個你有遇到過嗎？

**Comment by chia7712** [comment]
> 目前我就是遇到這個問題，還在研究中。

你也是拉最新的程式碼嗎？我看了一下原始碼應該是yunikorn bug，你有空的話也可以查看一下

**Comment by chungen0126** [comment]
> 你也是拉最新的程式碼嗎？我看了一下原始碼應該是yunikorn bug，你有空的話也可以查看一下
是的，好那我去看看原始碼。

**Comment by chia7712** [comment]
我這邊看的結果應該是yunikorn後來增加了檢查placeholder與實際請求的資源檢查 https://github.com/apache/incubator-yunikorn-core/commit/9539c18fa4ad46b3ef6b829be58ac18917a1de62

而你的腳本裡面並沒有計算memory overhead，這導致placeholder先佔的資源總是比實際要拿的還要少，因此一直無法順利配置

一個快速的解法是增添下列參數將overhead都設定成0
```
    --conf spark.kubernetes.memoryOverheadFactor=0 \
    --conf spark.driver.memoryOverhead=0 \
    --conf spark.executor.memoryOverhead=0 \
```

**Comment by chia7712** [comment]
@chungen0126 麻煩你也驗證一下上面https://github.com/skiptests/astraea/issues/201#issuecomment-1034054503的解法，如果確認可行的話，麻煩更新一下你的腳本

**Comment by chungen0126** [comment]
> @chungen0126 麻煩你也驗證一下上面https://github.com/skiptests/astraea/issues/201#issuecomment-1034054503 的解法，如果確認可行的話，麻煩更新一下你的腳本
gang scheduler功能應該沒有問題，已更正我的腳本。

**Comment by chungen0126** [comment]
> 請問一下crash的原因為何？
目前觀察下來，是由於starvation的情況發生導致。
使用fifo來排成時，都會造成crash。

**Comment by chia7712** [comment]
> 使用fifo來排成時，都會造成crash。

yunikorn scheduler本身crash? 可否把錯誤資訊貼上來？另外你用的是哪一版本？

**Comment by chungen0126** [comment]
> yunikorn scheduler本身crash? 可否把錯誤資訊貼上來？另外你用的是哪一版本？


目前是github clone下來的包成image，會造成yunikorn scheduler這個容器死掉。
scheduler的logs:
`standard_init_linux.go:228: exec user process caused: exec format error`

**Comment by chia7712** [comment]
> 目前是github clone下來的包成image，當因為starvation，導致yunikorn 被Evicted後，重啟yunikorn scheduler時，這個容器死掉。
scheduler的logs:
standard_init_linux.go:228: exec user process caused: exec format error

能否開一個議題追蹤一下這個題目？

**Comment by chungen0126** [comment]
#235
