### ISSUE TITLE
研究confluent balance tool

### ISSUE THREAD

**Issue by chia7712** [skiptests/astraea#205]
# 進度

1. [x] 實作方便建立 Confluent Kafka docker container 的腳本
2. [ ] 設計模擬情境
3. [ ] 執行模擬情境
4. [ ] 分析結果

## 設計情境

對 Confluent Kafka 和啟動 Balancer(Auto Data Balancing, Self-Balancing)。執行下列情境的實驗，觀察 Balancer 的舉動

1. 不平衡的 Produce Request, 特定 Broker 受到比較顯著的 Produce Request
2. 不平衡的 Consume Request, 特定 Broker 受到比較顯著的 Consume Request
3. 時有時無的 Burst Loading (Produce Request or Consume Request)
4. 特定 Broker 底層儲存空間即將用完的情境
5. 特定 Broker 在 Network IO 上處於劣勢，Balancer 能否察覺該 Broker 不適生產而做出修正?
6. 特定 Broker 在 Disk IO 上處於劣勢，Balancer 能否察覺該 Broker 不適生產而做出修正?

### 追蹤confluent balancer 對 JBOD的支援性 (@garyparrot)

* For Self-Balancing https://github.com/skiptests/astraea/issues/205#issuecomment-1077514065
* For Cruise-Control https://github.com/skiptests/astraea/issues/205#issuecomment-1079748994

**Comment by chia7712** [comment]
@garyparrot @qoo332001 麻煩準備一下balancer tool功能簡介和簡報，再給個報告日期，謝謝

**Comment by chia7712** [comment]
@garyparrot @qoo332001 再麻煩將投影片貼上來

**Comment by chia7712** [comment]
@garyparrot 再麻煩回報JBOD的部分

**Comment by garyparrot** [comment]
> 再麻煩將投影片貼上來

[Self Balancing Cluster.pdf](https://github.com/skiptests/astraea/files/8333434/Self.Balancing.Cluster.pdf)

**Comment by qoo332001** [comment]
> 再麻煩將投影片貼上來

[Auto Data Balancing.pdf](https://github.com/skiptests/astraea/files/8333448/Auto.Data.Balancing.pdf)

**Comment by garyparrot** [comment]
> @garyparrot 再麻煩回報JBOD的部分

```shell
# 建立 Zookeeper
$ ./docker/start_zookeeper.sh
699c33c00c2f73bace4e413cb8fc10b16072b7420b4245744642059fdc9a883e
=================================================
run /home/garyparrot/IdeaProjects/astraea/docker/start_broker.sh zookeeper.connect=192.168.103.49:18137 to join kafka broker
run env CONFLUENT_BROKER=true /home/garyparrot/IdeaProjects/astraea/docker/start_broker.sh zookeeper.connect=192.168.103.49:18137 to join confluent kafka broker
=================================================

# 建立 Confluent Broker, 設定兩個 data folders
$ env DATA_FOLDERS=/tmp/aaa,/tmp/bbb CONFLUENT_BROKER=true /home/garyparrot/IdeaProjects/astraea/docker/start_broker.sh zookeeper.connect=192.168.103.49:18137
0c16b93a580dae7d4da01f1964315bca50dd688c890751c228eb942efab70711
=================================================
mount /tmp/aaa,/tmp/bbb to container: broker-13955
broker id: 1001
broker address: 192.168.103.49:13955
exporter address: 192.168.103.49:19312
=================================================
```

我之前說錯了，到這部分的時候 Kafka Broker 還是能夠正常運作，不會跳出錯誤來。不過如果用 Confluent Kafka 內建的 `kafka-rebalance-cluster` 腳本來取得 Balancer 的狀態，他會跳出這個錯誤

```
$ ./kafka-rebalance-cluster --bootstrap-server 192.168.103.49:13955 --status
Balancer status: ERROR
  org.apache.kafka.common.errors.BalancerJbodEnabledMisconfigurationException: SBC configured with multiple log directories
```


Curise Control 是否有 JBOD 限制我要再研究一下，可能需要一些時間。

**Comment by garyparrot** [comment]
@chia7712 其實他強調的是只能設定一個 log directory。如果把多個 disk 做成一個 RAID 或是 LVM 會不會就能夠繞過這個問題，想問有人會再 production 上用 RAID 當作 Kafka 的 log folder 嗎?

**Comment by chia7712** [comment]
> 問有人會再 production 上用 RAID 當作 Kafka 的 log folder 嗎?

不常見，因為這樣等於軟硬體都做副本，這樣成本會很高

**Comment by garyparrot** [comment]
> > Cost Function 可能要支援非 JMX 的 metric? 如果我們要走這部分?
>
> yep，如果有需要的話

收集數據的部分，Cruise Control 那邊的手法是塞入一個自己寫一個 [metric reporter](https://github.com/apache/kafka/blob/99b9b3e84f4e98c3f07714e1de6a139a004cbc5b/clients/src/main/java/org/apache/kafka/common/metrics/MetricsReporter.java)，然後在 Apache Kafka 內的 [metric.reporters](https://kafka.apache.org/documentation/#brokerconfigs_metric.reporters) 設定設成自己的 repoter class。
如果可以插入我們自己的程式碼的話，應該有機會讓我們自己管理屬於我們自用的 JMX metric(我沒驗證過，但我覺得好像可行)。這樣會違反到之前開會提到的，**不能在 broker 旁擺一個屬於我們自己的背景程式**的規則嗎，雖然這個手法只是由跑額外的程式變成插入額外程式碼而已。

## Cruise Control JBOD 研究

很快速地對他們的 repo 進行關於 JBOD 的搜尋：https://github.com/linkedin/cruise-control/search?p=1&q=JBOD

其中看到一些有趣的東西，在 `README.md` 的部分有提到一個 capacity file

> Modify `config/cruisecontrol.properties` of Cruise Control:
>
> - (Required) fill in `bootstrap.servers` and `zookeeper.connect` to the Kafka cluster to be monitored.
> - (Required) update `capacity.config.file` to the path of your capacity file.
>   - Capacity file is a JSON file that provides the capacity of the brokers
>   - You can start Cruise Control server with the default file (`config/capacityJBOD.json`), but it may not reflect the actual capacity of the brokers
>   - See [BrokerCapacityConfigurationFileResolver configurations](https://github.com/linkedin/cruise-control/wiki/Configurations#brokercapacityconfigurationfileresolver-configurations) for more information and examples

這邊有一個 [capacity file](https://github.com/linkedin/cruise-control/blob/4e5927b48bf2581ab76acbbecbf42b355b871b65/config/capacityJBOD.json) 範例檔案，看起來他們將 broker 各項 resource 的 capability 寫死在這個檔案，其中包含 cpu, size of each log folded

[這邊](https://github.com/linkedin/cruise-control/blob/4e5927b48bf2581ab76acbbecbf42b355b871b65/cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/BrokerCapacityConfigFileResolver.java#L24-L148)有指出 capacity file 的一些細節格式，看起來 Curise Control 是有針對 JBOD 下去設計的。

不過我還是很好奇他們知道哪個 replica 放置在哪個 log folder，因為這應該不是 JMX 可以拿到的訊息。在他的程式碼游泳給個小時後，[我找到他們判斷 replica 的方法了](https://github.com/linkedin/cruise-control/blob/4e5927b48bf2581ab76acbbecbf42b355b871b65/cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/MonitorUtils.java#L374)，他們是直接在 Balancer 透過 `AdminClient` 讀取這些 replica 的資訊。

他們的 metric report 應該只有產生出 [log size 這些資訊](https://github.com/linkedin/cruise-control/blob/4e5927b48bf2581ab76acbbecbf42b355b871b65/cruise-control-metrics-reporter/src/main/java/com/linkedin/kafka/cruisecontrol/metricsreporter/metric/MetricsUtils.java#L68)，所以看起來他們假設

1. 整個 `capacity file` 內提到的空間，就是設定者保證 Kafka 在這個 log folder 所屬的 disk 可以使用的空間
2. 這些空間被利用了多少，是由 log size 扣出來的

我一開始以為他們會去讀取 filesystem 資訊，以得知還有多少空間能用，他們的手法也可以，而且只用到 JMX，但是這個假設建立在設定者真的能保證這麼多空間被留給 Kafka 用，只要設定的人注意一下的話應該沒問題..

如果從程式碼上來看的話他們有試著去支援 JBOD，但是為什麼 Self-Balancing 要設定不支援 JBOD 這件事情就便得很匪夷所思了

**Comment by chia7712** [comment]
> 這樣會違反到之前開會提到的，不能在 broker 旁擺一個屬於我們自己的背景程式的規則嗎

應該說我們要避免我們的balancer會需要「重新啟動」叢集，換言之，在伺服器端塞程式碼這個舉動就不太可行

> 他們是直接在 Balancer 透過 AdminClient 讀取這些 replica 的資訊。

我們的balancer也可以用AdminClient

**Comment by chia7712** [comment]
目前已經在忙其他項目，這個先關閉
