### ISSUE TITLE
Call `close()` in `execute()` will cause deadlock 

### ISSUE THREAD

**Issue by chinghongfang** [skiptests/astraea#21]
https://github.com/skiptests/astraea/blob/70fc307805ee9097f249ce2a5d502991ea11edaa/app/src/main/java/org/astraea/performance/latency/CloseableThread.java#L27

#### 敘述
在`CloseableThread.execute()`內呼叫`close()`會導致deadlock。因為`close()`會等`execute()`結束。

#### 問題
如果想要`execute()`只執行一次，便要直接改動`AtomicBoolean closed`，想請問如此行為有符合原本設計嗎？或者`CloseableThread`不該拿來只執行一次？

**Comment by chia7712** [comment]
> 在CloseableThread.execute()內呼叫close()會導致deadlock。因為close()會等execute()結束。

這點應該要拋出錯誤處理，就是當呼叫`close`的執行緒跟執行`execute`的一樣時，應該拋出錯誤

> 如果想要execute()只執行一次，便要直接改動AtomicBoolean closed，想請問如此行為有符合原本設計嗎？或者CloseableThread不該拿來只執行一次？

原本的設計並沒有支援執行一次，但我們可以新增該模式

上述兩個議題可以各開一隻PR去處理，看你要不要接手弄弄看，或者我晚點會發PR

**Comment by chinghongfang** [comment]
好的，我來修改。

**Comment by chia7712** [comment]
@chinghongfang 麻煩將相關PR連結到此議題喔 (右邊欄位的Linked pull requests)
