### ISSUE TITLE
Move all `/tmp` folder usage to project scope `build` folder

### ISSUE THREAD

**Issue by garyparrot** [skiptests/astraea#218]
Context: https://github.com/skiptests/astraea/issues/200#issuecomment-1032861458

先前的討論中發現將腳本產生的檔案放到 `/tmp` 資料夾會衍生出一些問題。

仰賴 `/tmp` 資料夾來儲存檔案可能不是一個好的手法，我們或許應該將這類檔案的存放改到專案內的 `build` 資料夾。

**Comment by garyparrot** [comment]
突然想到如果有人把整個 project 放在 `/tmp` 內的話也無法避免這個問題，比如 `build` 資料夾在 `/tmp/path/to/somewhere/astraea/build` (實際上我測試環境就正在這樣做)。可能別把要緊的東西放這裏比較好...

**Comment by chia7712** [comment]
> /tmp/path/to/somewhere/astraea/build (實際上我測試環境就正在這樣做)。可能別把要緊的東西放這裏比較好...

有其他建議的方式嗎？或者我們加一個檢查來拋出錯誤就好？

**Comment by garyparrot** [comment]
> 或者我們加一個檢查來拋出錯誤就好？

不知道做到這種程度是否值得... 畢竟這感覺起來是 snap only 的問題

**Comment by chia7712** [comment]
> 不知道做到這種程度是否值得... 畢竟這感覺起來是 snap only 的問題

感覺你們都是用snap安裝？就看你們了 :)

**Comment by chia7712** [comment]
#356會將參數檔移回`/tmp`底下，換言之我們不再支持使用snap，所以關閉此議題
