### ISSUE TITLE
測試yunikorn在計算可用資源時會否將不可部署的節點納入

### ISSUE THREAD

**Issue by chia7712** [skiptests/astraea#222]
k8s中的control plane預設是無法部署pod，然而yunikorn依然會將該些節點納入資源計算（從restful APIs可看到)，因此我們必須去測試在算可用資源時該些節點會否也被納入計算，如果會的話，就可能以為現在有可用資源但實際上該些節點無法部署的狀況

**Comment by chia7712** [comment]
@chungen0126 可否麻煩你看一下這個問題，並且協助測試，如果問題描述不夠明確還請提出

**Comment by chungen0126** [comment]
學長，我不太清楚我要測試什麼情況，這種情況發生時，就算yunikorn知道有資源可以用，但也會被像是filter那樣把一些節點擋掉，導致不能部署節點，而這個pod會卡在pending等資源。

> 就可能以為現在有可用資源但實際上該些節點無法部署的狀況

我嘗試了一下你說的情況，然後pod基本上就是卡在pending，然後pod的排程描述如下。
<img width="1279" alt="截圖 2022-02-09 下午6 44 15" src="https://user-images.githubusercontent.com/65023303/153182311-12a8313f-41c7-4785-8b27-5f26373b5a86.png">

我曾經在單純k8s的排程上也有遇過這種情形，以k8s原生的排程，得到的結果跟回覆基本上是一樣的。

**Comment by chia7712** [comment]
> 學長，我不太清楚我要測試什麼情況，這種情況發生時，就算yunikorn知道有資源可以用，但也會被像是filter那樣把一些節點擋掉，導致不能部署節點，而這個pod會卡在pending等資源。

我舉個例子，叢集有兩個節點，master有兩個cores、worker有四個cores，其中master不可以部署pod，在這個狀況下，假如我提交了一個spark job會剛好用完6 cores的話，yunikorn會否讓這個任務進入排程？

**Comment by chungen0126** [comment]
> 我舉個例子，叢集有兩個節點，master有兩個cores、worker有四個cores，其中master不可以部署pod，在這個狀況下，假如我提交了一個spark job會剛好用完6 cores的話，yunikorn會否讓這個任務進入排程？

我先確認一下，所以是spark job的driver 跟executor pod個別都要使用6 cores嗎？

如果是的話，以這個例子來講，worker節點沒有足夠的資源分配給這個任務，因此pod卡在pending。
然而若是將control plan也納入考量，排成也會因為兩個節點各別都沒辦發分配資源給這個任務，倒置pod卡在pending，因此想請問跟是否將control plan資源納入考量的關係？

> k8s中的control plane預設是無法部署pod，然而yunikorn依然會將該些節點納入資源計算（從restful APIs可看到)，因此我們必須去測試在算可用資源時該些節點會否也被納入計算，如果會的話，就可能以為現在有可用資源但實際上該些節點無法部署的狀況

另外，這個情形是否是在講我上一個回覆提到的截圖，這個測試情形是我將能部署的node都unscheduler，然後submit一個control plan資源足夠的job。
如果是的話，yunikorn在control plan上的部署情況，就和k8s原生的scheduler一樣，會得到相同的結果，除非條整k8s原本的設定。

**Comment by chia7712** [comment]
> 我先確認一下，所以是spark job的driver 跟executor pod個別都要使用6 cores嗎？

不是，我指的是加總需要六個cores，例如driver要兩個、executor要六個

**Comment by chungen0126** [comment]
> 承上，因此假如master node可以部署pod的話，此任務應該是可以執行的（總共需要六個cores，而叢集剛好可以提供六個cores)

我大概瞭解了，那首先我講一下我的測試，我有1個  control plan是yunikorn01，3個worker node分別是yunikorn01, yunikorn02, yunikorn03，他們的都有8個cores，那我執行一個spark job，driver 需要6 cores，executor 需要6 cores，然後executor instances有4個，然後我測試是否會將pod部署到control plan。

以上是我的測試內容，下面會是測試的結果。

首先觀察所有pod的狀態，有三個pod正常在運作然後有兩個pod因資源不足在pending。
<img width="1279" alt="截圖 2022-02-10 上午1 48 12" src="https://user-images.githubusercontent.com/65023303/153259674-f1bbff4a-828f-4391-958e-6abff23b88cc.png">
然後觀察這些pod所在的node位置，所有pod部署的位置都不在control plan上。
<img width="1279" alt="截圖 2022-02-10 上午1 51 07" src="https://user-images.githubusercontent.com/65023303/153260183-4dae9b2d-37b7-4013-bb41-a024c4e2c94c.png">

最後，我用describe 觀察pod部署的情形，pod會因為toleration的關係不會部署到control plan上。

`
Name:           spark-pi-93247c7edf922887-exec-3
Namespace:      spark-test
Priority:       0
Node:           <none>
Labels:         queue=root.stateaware
                spark-app-selector=spark-80d7b6eee94946f3ae02564d6841c5d9
                spark-exec-id=3
                spark-exec-resourceprofile-id=0
                spark-role=executor
Annotations:    <none>
Status:         Pending
IP:             
IPs:            <none>
Controlled By:  Pod/spark-pi-b934167edf9209a0-driver
Containers:
  spark-kubernetes-executor:
    Image:      wfps1210/spark:latest
    Port:       7079/TCP
    Host Port:  0/TCP
    Args:
      executor
    Limits:
      memory:  1408Mi
    Requests:
      cpu:     7
      memory:  1408Mi
    Environment:
      SPARK_USER:                 lee
      SPARK_DRIVER_URL:           spark://CoarseGrainedScheduler@spark-pi-b934167edf9209a0-driver-svc.spark-test.svc:7078
      SPARK_EXECUTOR_CORES:       7
      SPARK_EXECUTOR_MEMORY:      1024m
      SPARK_APPLICATION_ID:       spark-80d7b6eee94946f3ae02564d6841c5d9
      SPARK_CONF_DIR:             /opt/spark/conf
      SPARK_EXECUTOR_ID:          3
      SPARK_RESOURCE_PROFILE_ID:  0
      SPARK_EXECUTOR_POD_IP:       (v1:status.podIP)
      SPARK_JAVA_OPT_0:           -Dspark.driver.blockManager.port=7079
      SPARK_JAVA_OPT_1:           -Dspark.driver.port=7078
      SPARK_LOCAL_DIRS:           /var/data/spark-55cb2c2a-8885-434c-aab9-7597afb573b8
    Mounts:
      /opt/spark/conf from spark-conf-volume-exec (rw)
      /var/data/spark-55cb2c2a-8885-434c-aab9-7597afb573b8 from spark-local-dir-1 (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from spark-token-gmd2j (ro)
Conditions:
  Type           Status
  PodScheduled   False 
Volumes:
  spark-conf-volume-exec:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      spark-exec-499ba37edf922dd8-conf-map
    Optional:  false
  spark-local-dir-1:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  spark-token-gmd2j:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  spark-token-gmd2j
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason            Age   From      Message
  ----     ------            ----  ----      -------
  Normal   Scheduling        24s   yunikorn  spark-test/spark-pi-93247c7edf922887-exec-3 is queued and waiting for allocation
  Warning  FailedScheduling  24s   yunikorn  predicate is not satisfied, error: node(s) had taint {node-role.kubernetes.io/master: }, that the pod didn't tolerate
  Normal   PodUnschedulable  24s   yunikorn  Task spark-test/spark-pi-93247c7edf922887-exec-3 is pending for the requested resources become available
  Warning  FailedScheduling  24s   yunikorn  predicate is not satisfied, error: node(s) had taint {node-role.kubernetes.io/master: }, that the pod didn't tolerate
`

**Comment by chia7712** [comment]
@chungen0126 感謝提供這麼精準的測試，以下是後續的討論

> 首先觀察所有pod的狀態，有三個pod正常在運作然後有兩個pod因資源不足在pending。

這是用gang scheduler嗎？如果是的話，照理說叢集的資源應該是不夠的（應該要扣掉不能部署的資源），不應該讓此任務開始跑才對。反之，如果不是用gang scheduler的話，可否用gang再測試一次？謝謝

**Comment by chungen0126** [comment]
> 這是用gang scheduler嗎？如果是的話，照理說叢集的資源應該是不夠的（應該要扣掉不能部署的資源），不應該讓此任務開始跑才對。反之，如果不是用gang scheduler的話，可否用gang再測試一次？謝謝

這邊沒有使用gang scheduler，是提交在fifo 的queue下執行。

**Comment by chia7712** [comment]
> 這邊沒有使用gang scheduler，是提交在fifo 的queue下執行。

了解，那就麻煩試試看gang scheduler，看看是否有使用“正確”的資源量來排程任務

**Comment by chungen0126** [comment]
以 https://github.com/skiptests/astraea/issues/222#issuecomment-1034039624 同樣情況下，執行gang scheduler，這邊以`gangSchedulingStyle`的參數分成Hard & Soft兩種模式來討論。
首先討論以Soft模式下，會產生一個driver pod 在pending 狀態等待place holder持有足夠資源，以及會產生一個driver 的place holder以及4個executor 的 place holder，有兩個executor place holder是處於pending的情況，且都running的pod都不是在control plan。
觀察到的情況如下圖：
<img width="1279" alt="截圖 2022-02-12 下午5 11 54" src="https://user-images.githubusercontent.com/65023303/153705177-7907eb62-c52e-4230-8e09-754bc8598512.png">
此情況會卡著直到30s，這段時間是由`placeholderTimeoutInSeconds`此參數定義的。
到這裡Soft &Hard會開始分歧，這裡是以Soft模式下，超過30s，gang scheduler會終止現在所有的place holder pod，並且以現在持有的資源直接執行，而執行情況會和未使用gang scheduler情況下一樣，有兩個executor pod在pending 狀態，其餘的都在running，且不會在control plan下執行。
觀察到的終止placeholder ：
<img width="1279" alt="截圖 2022-02-12 下午5 19 01" src="https://user-images.githubusercontent.com/65023303/153705437-feeae9ba-0e7a-4977-b62e-8b8695faaa1c.png">
執行情況：
<img width="1279" alt="截圖 2022-02-12 下午5 20 40" src="https://user-images.githubusercontent.com/65023303/153705460-39f3239d-856e-4707-ab70-b08453c26e53.png">

接下來討論Hard模式下，前面的情形和Soft 模式一樣，會產生一個driver pod 在pending 狀態等待place holder持有足夠資源，以及會產生一個driver 的place holder以及4個executor 的 place holder，placeholder pod兩個在pending狀態，其餘在running狀態下且都不在control plane 。
觀察到如下圖：
<img width="1279" alt="截圖 2022-02-12 下午5 28 13" src="https://user-images.githubusercontent.com/65023303/153705699-8a16b60f-48fc-469d-86bb-536ede5386e6.png">
同樣這個情況下卡著30s，此時間以`placeholderTimeoutInSeconds`參數設定。
在Hard的模式下，超過30s，gang scheduler會終止所有的place holder pod，並且不執行此任務，而spark job的狀態會變成`ResourceReservationTimeout`。
觀察到的情形如下：
<img width="1279" alt="截圖 2022-02-12 下午5 35 15" src="https://user-images.githubusercontent.com/65023303/153705929-0482a039-3c9c-41c8-8f5d-be9311f24425.png">

**Comment by chia7712** [comment]
所以能否給個結論，yunikorn是否會將不能部署pod的節點的資源計入，導致gang scheduler會誤以為有足夠的資源？

**Comment by chungen0126** [comment]
> 所以能否給個結論，yunikorn是否會將不能部署pod的節點的資源計入，導致gang scheduler會誤以為有足夠的資源？

結論:
yunikorn 的所有排成都會將不能佈署的節點過濾掉，因此yunikorn的排成不會將不能佈署的節點都計入。

**Comment by chia7712** [comment]
> yunikorn 的所有排成都會將不能佈署的節點過濾掉，因此yunikorn的排成不會將不能佈署的節點都計入。

不好意思，我想在釐清一下兩種狀況：

1. 叢集裡面所有節點都可以部署，但所有節點的剩餘資源就是不夠跑任務
2. 叢集裡面部分節點不可部署，但加上不可部署的節點後的剩餘資源是可以剛好跑任務

請問上述兩者在gang scheduler下的執行結果會一樣嗎？例如第二種狀況測試`soft`+`gang scheduler`的話，會出現只有部分executor跑得起來，那麼在第一種狀況下也是嗎？

**Comment by chungen0126** [comment]
> 叢集裡面所有節點都可以部署，但所有節點的剩餘資源就是不夠跑任務
> 叢集裡面部分節點不可部署，但加上不可部署的節點後的剩餘資源是可以剛好跑任務

以上兩種情況，加上一個條件，只要gang scheduler的driver pod的place holder pod 有足夠資源啟動，所有有啟動的place holder pod就會交換成要執行的pod，也就是學長說的部分的pod跑起來。
若沒有我的條件，driver會卡在pending。

另外，這邊還有一個現象我覺得可以跟學長講一下，gang scheduler 的 place holder pod資源設定是和spark資源設定是分開的，因此這邊會發生一個例外情形：

1. driver pod的place holder pod足以執行。
2. executor pod的spark資源設定足夠執行，但是place holder pod資源不足以執行。
以上兩種條件達成後會發生，executor place holder pod會一直pending直到設定的時間到之後會被terminal，並且place holder pod 會轉換成driver直行並且會自行啟動executor而不需要place holder pod。

**Comment by chia7712** [comment]
> 以上兩種情況，加上一個條件，只要gang scheduler的driver pod的place holder pod 有足夠資源啟動，所有有啟動的place holder pod就會交換成要執行的pod，也就是學長說的部分的pod跑起來。
若沒有我的條件，driver會卡在pending。

所以不會出現上面soft測試中，只有部分executor被啟動嗎？

> gang scheduler 的 place holder pod資源設定是和spark資源設定是分開的

這是yunikorn文件提到的嗎？還是你實際測試觀察到的現象？理論上寫gang scheduler的參數時應該要去計算佔用資源要跟實際存取的一致，否則會有資源量不匹配的問題（如前面提到的overhead問題）

**Comment by chungen0126** [comment]
> 所以不會出現上面soft測試中，只有部分executor被啟動嗎？

我說的情況就是部分的executor被啟動，這些部分的executor pod是基於，部分place holder已經持有資源run 起來的pod會替換成部分的executor。

> 這是yunikorn文件提到的嗎？還是你實際測試觀察到的現象？理論上寫gang scheduler的參數時應該要去計算佔用資源要跟實際存取的一致，否則會有資源量不匹配的問題（如前面提到的overhead問題）

這邊是我自己觀察到的結果，理論上資源要一致，但是現在yunikorn gang scheduler似乎不會因為資源不一致終止application，而會讓driver自己抓資源，看起來像是soft mode沒有寫好。

**Comment by chia7712** [comment]
> 我說的情況就是部分的executor被啟動，這些部分的executor pod是基於，部分place holder已經持有資源run 起來的pod會替換成部分的executor。

這個現象是在超過`placeholderTimeoutInSeconds`才會發生吧？

> 這邊是我自己觀察到的結果，�理論上資源要一致，但是現在yunikorn gang scheduler似乎不會因為資源不一致終止application，而會讓driver自己抓資源，看起來像是soft mode沒有寫好。

從官方文件來看

```
Spark driver and executor pod has memory overhead, that needs to be considered in the taskGroup resources.
```

應該是要求使用者要負責讓`placeholder`的資源和`spark pod`兩者的資源匹配

https://github.com/apache/incubator-yunikorn-core/commit/9539c18fa4ad46b3ef6b829be58ac18917a1de62

可否麻煩閱讀一下上面commit，然後試著回答下列兩個問題：
1. 當placeholder寫的資源大於spark pod的資源時會怎樣？
2. 反之，當placeholder的資源寫的比spark pod的資源還小的時候會怎樣？（從#201的實驗來看，應該是會一直處理pending的狀態)

**Comment by chungen0126** [comment]
> 這個現象是在超過placeholderTimeoutInSeconds才會發生吧？

是的。
