### ISSUE TITLE
替換目前五台機器中的所有硬碟

### ISSUE THREAD

**Issue by chia7712** [skiptests/astraea#228]
see https://github.com/skiptests/astraea/issues/130#issuecomment-1036219235

目前使用的硬碟`硬碟*2: 美光Mincron Crucial P2 1TB/M.2 PCIe 2280/讀:2400M/寫1800M/3D QLC顆粒`在大量資料存取下會有效能低落的問題 (相關報導 https://www.pcworld.com/article/399100/crucial-p2-nmve-ssd-review.html/amp)

我們需要更換新的硬碟以便支撐大量的資料測試

**Comment by chia7712** [comment]
我現在的想法如下：

1. 先使用壓縮演算法和避免自己灌自己資料，先完成一個階段的效能驗證 (@wycccccc @chinghongfang )
2. 同時，我需要有一個人來幫忙調查一下市面上的nvme ssd有哪一顆比較適合 
3. 承上，調查完後我們先買一顆來安裝並測試，以免又遇到一樣的狀況
4. 測試完後我們在大量採購替換所有硬碟

這邊要麻煩有人接手上述的2和3

**Comment by chia7712** [comment]
另外，我們也討論一下替換後的硬碟可以拿來做啥？

**Comment by wycccccc** [comment]
我翻了一下那個人的文章同時結合原價屋的價格進行了下比較。
發現在pcie3.0規格下似乎變慢是一種常態，幾乎同一價位的都會存在長時間的讀寫導致速率變慢的問題。

在綜合比較了後，xpg-sx8200從他的數據上來看似乎還比較符合實際。（長時間運行降到1G狀況還算是比較好的）
https://www.pcworld.com/article/402963/adata-xpg-sx8200-pro-nvme-ssd-review.html

一些其他參考對比的硬碟：
http://reviewcentralme.com/review-kingston-1tb-kc2500-nvme-ssd-drive/
https://www.pcworld.com/article/398516/wd-blue-sn550-nvme-ssd-review.html
https://www.pcworld.com/article/394173/samsung-980-nvme-ssd-review.html
https://www.pcworld.com/article/608860/wd-black-sn770-nvme-ssd-review-an-affordable-pcie-4-performer.html

**Comment by chia7712** [comment]
> 發現在pcie3.0規格下似乎變慢是一種常態，幾乎同一價位的都會存在長時間的讀寫導致速率變慢的問題。

變慢這可以接受，不過幾乎歸0就有點不太好 哈哈哈

> 在綜合比較了後，xpg-sx8200從他的數據上來看似乎還比較符合實際。（長時間運行降到1G狀況還算是比較好的）

看數字還可以接受，不過再找一顆來比較一下，至少二選一

**Comment by wycccccc** [comment]
WD BLACK SN750SE 看上去也還不錯
使用了pcie4.0規格，從圖中表現來看略優於sx8200。不過價格也同樣略優於它。

![image](https://user-images.githubusercontent.com/43372856/153707174-758bb4f7-b6c9-4101-8e3a-7fb9fb29a9f9.png)
> The 2TB model features a static 36GB write cache (22GB more than the 1TB model)

圖中測試爲2TB規格，1TB的速率可能會差一點（圖中xs8200 2TB 大概在1200MB/s,之前那個人寫的文章xs8200 1TB大概在0.98GB/s），不過如果還是按照之前的來買兩張的話這個點應該可以忽略。
網上找不到750SE的測試結果，基本上都是750。750SE相對於750似乎只有一點點小的提升。所以我認爲可以參照750的測試數據結果。

參考文章：
https://www.tomshardware.com/reviews/wd-black-sn750-ssd,5957-2.html

**Comment by wycccccc** [comment]
那似乎目前我看到的只有xs8200了。
pcie3.0的其他的速率掉的都有點誇張。

**Comment by chia7712** [comment]
> 那似乎目前我看到的只有xs8200了，它符合要求且cp值不錯。
pcie3.0的其他的速率掉的都有點誇張。

我們先以原價屋的清單來看，可否確認都沒其他選擇了？

<img width="697" alt="截圖 2022-02-13 上午12 12 23" src="https://user-images.githubusercontent.com/6234750/153718977-6faa9c1b-ddd0-463a-a8ec-d6c8e60ee5da.png">

**Comment by chia7712** [comment]
> 威剛 WD 金士頓 intel 美光 三星

不好意思，就針對這幾個總結一下可以嘛？就根據網路上查到的資料，謝謝

**Comment by wycccccc** [comment]
三星Samsung980 1TB 
>Below you can see the actual drop-off point during the 450GB write on the 980 (empty drive), plus an odd slow start that we rarely see. TurboWrite 2.0. Hmm.

980 依赖于系统DRAM作为它的主要缓存，在長時間寫入中一旦DRAM用完就會速度開始下降。測試中的475MB/s，很難說一定能滿足實際測試需求。
![image](https://user-images.githubusercontent.com/43372856/153741660-a5471c24-81c3-4e15-9aa2-edc6921de52f.png)
https://www.pcworld.com/article/394173/samsung-980-nvme-ssd-review.html

金士頓KC2500 
![image](https://user-images.githubusercontent.com/43372856/153741761-39cd1ee5-3e03-4b83-b270-feb8c5b516a9.png)
>Write speed when DRAM runs out

與980一樣的問題，長時間的讀寫一旦耗盡了DRAM，速率就開始下落，590MB/s也談不上多美麗的數據。
http://reviewcentralme.com/review-kingston-1tb-kc2500-nvme-ssd-drive/

WD SN570
![image](https://user-images.githubusercontent.com/43372856/153741885-7b2b37b8-b74d-49c2-a286-7812f6e14f67.png)
>它只能短暫達到約 1,840MB/s 速度，作用容量區間僅 25GB 左右，而後滑落至 840MB/s 上下跳動。

840MB/s比上兩款好一些但是只有在一開始25GB短暫達到1840MB/s。掉的有點太早了。
https://benchlife.info/western-digital-wd-blue-sn570-nvme-ssd-review/

intel660P
![image](https://user-images.githubusercontent.com/43372856/153742324-afbe1b66-c912-4067-bddb-cc9f657b1c0b.png)
> In HDTune we were able to write over 130GB of data before the drive’s write speed tanked. At that point, it averaged just 100MB/s of throughput.

只剩下100MB/s了，太慘了實在。
https://www.thessdreview.com/featured/intel-ssd-660p-m-2-nvme-ssd-review-1tb/6/

xpg-sx8200

>Though the SX8200 slows down at about the 30% mark of a 500GB transfer, the slower 1GBps transfer rate will still get copies done in a hurry. 
![image](https://user-images.githubusercontent.com/43372856/153742484-932e80f3-d697-4a7f-ac08-54e4d0982f4e.png)
相較之下，在面對大資料的情況下。它的效能依然能保持在1GBps左右。對比其他同價位的產品來看，數據上確實十分優秀。
![image](https://user-images.githubusercontent.com/43372856/153742494-2d198029-8d44-49e6-8d14-696d8acd36f0.png)
在其他人的測試中也有類似的實驗結果。（杜絕寫軟文的情況）

https://www.pcworld.com/article/402963/adata-xpg-sx8200-pro-nvme-ssd-review.html

**Comment by chia7712** [comment]
@wycccccc 感謝如此詳細的分享。

> xpg-sx8200

我去弄一顆1TB的來給你們試試看

**Comment by wycccccc** [comment]
fio測試中的sx8200的情況
![Screenshot from 2022-02-14 17-54-53](https://user-images.githubusercontent.com/43372856/153841393-98296519-98e9-4598-8600-33bb9cf432db.png)

可以看到速率在4350MB/s,且各項指標看上去沒太大問題。

Kafka單硬碟資料傳輸情況對比（record.size 10KiB,time 10 min）：
美光只剩下400MB/s了，且還在持續下降
![Screenshot from 2022-02-14 17-37-42](https://user-images.githubusercontent.com/43372856/153841846-02bc15a2-05cd-472f-bc35-11d4d3dd3ff7.png)

sx8200還有700MB/s，且速率趨於穩定。
![Screenshot from 2022-02-14 17-53-50](https://user-images.githubusercontent.com/43372856/153841832-0fd6fc24-5405-4b02-8d6e-234bdede4eb2.png)

**Comment by chia7712** [comment]
> 美光只剩下400MB/s了，且還在持續下降

![torvaldsnvidia-640x424](https://user-images.githubusercontent.com/6234750/153848242-a4a3e64e-bb9a-48c4-9fe5-96b2ab2853e4.jpg)

**Comment by chia7712** [comment]
@wycccccc 這個議題就留給你了，麻煩換完硬碟並且測試完後關閉它

**Comment by wycccccc** [comment]
測試數據：
record.size 100KiB
producer 5
comsumer 10

一台機器使用Default partitioner向整個集群發送資料。分別測試了3次15min，和1次30min。測試的結果throughput都能保證在1GB/s以上。更換硬碟的結果目前看來還是很不錯的。

![微信图片_20220216010605](https://user-images.githubusercontent.com/43372856/154112252-34d9227b-e33e-49ab-92d4-b39c7f1b31a5.png)
