### ISSUE TITLE
測試CPU與JVM的狀態對Kafka集群的影響

### ISSUE THREAD

**Issue by wycccccc** [skiptests/astraea#229]
在目前的設計中，針對cpu和jvm的相關metrics處理方式為設置一個閾值。但超過某個界限，例如usage達到70%。那麼我就主動減少該broker可能被partitioner選到的概率。
我將其作為一種預警，來提前防範高負荷的cpu或是內存帶來的糟糕影響。
可是cpu與內存真的負載很重的時候，對kafka through put的影響會有多大呢。

為了讓我們使用這些metrics作為預測更加有佐證。需要對其進行實驗。

**Comment by wycccccc** [comment]
有個問題想要先請教一下學長。
如果jvm與cpu真的會影響kafka through put。那麼我們是否只需要根據觀察through put 相關的metrics就能得出結論。（老闆觀點）
更進一步說，觀察jvm和cpu是否還有意義？
我將觀察它們作為一種預警來預防可能發生的導致throughput變差的情況。我感覺這樣做應該是有意義的。（可老闆似乎不是很認同）
這裡想悄悄問一下，我將jvm和cpu的metrics作為一種預警參數是否具有一定的合理性。

**Comment by chia7712** [comment]
吞吐量也是一個很好的觀測指標，可以在未來納入指標

但是只觀察吞吐量的話可能會有一個盲點，我們不容易得知目前的吞吐量是否為該機器的上限，舉個例子：

a機器目前的吞吐量是100MB/S，同時b機器的吞吐量是70MB/S，所以純粹比較吞吐量的話，應該是b比較不忙錄？但實際上有可能a是幾千萬元的設備，吞吐量的上限可以達到幾百GB，但b是個用了美光硬碟的爛機器，70MB已經是極限了

上述的例子就是我之前提過所謂的異質的叢集，這可能發生在定時擴增的叢集，購入的硬體不一定會一摸一樣

最後，回到我前面講的第一句話，演算法的設計會建議保持一個彈性，讓之後可以隨時插入更多「參考指標」，例如：
‘’’Java

interface Score {
  long value(ClusterStatus)；
}

static List<Score> loadScores(props);

‘’’

這樣讓使用者可能根據自身叢集的體質去微調演算法的參考依據，會讓你的partitioner有更高的彈性和適合情境

**Comment by chia7712** [comment]
另外針對cpu在kafka的效能影響，可以回想一下我課堂上講過的執行緒模型，簡單來說當cpu 忙不過來處理堆積在queue的請求時，那些請求就會逐一的timeout

**Comment by wycccccc** [comment]
>吞吐量也是一個很好的觀測指標，可以在未來納入指標

學長放心，吞吐量一直都是我們partitioner使用的重要指標之一。目前是這樣的彈性設計，不過應該要加個interface，讓他更加規範。這個我再開個pr處理。

>a機器目前的吞吐量是100MB/S，同時b機器的吞吐量是70MB/S，所以純粹比較吞吐量的話，應該是b比較不忙錄？但實際上有可能a是幾千萬元的設備，吞吐量的上限可以達到幾百GB，但b是個用了美光硬碟的爛機器，70MB已經是極限了

學長舉得這個例子與我用來説服老闆的例子很像。雖然老闆不是特別認同，但是學長也這麽說我就放心了。

>另外針對cpu在kafka的效能影響，可以回想一下我課堂上講過的執行緒模型，簡單來說當cpu 忙不過來處理堆積在queue的請求時，那些請求就會逐一的timeout

有概念，但是爲了説服老闆也讓設置的數字更有作證我還是會測試一下，實驗一下cpu的使用情況到什麽地步會產生什麽不同的影響。最後給出一個合理的閾值用來設定。有結果了我再貼上來。

**Comment by chia7712** [comment]
在順序上，要先有一個partitioner 可以跑（你現在在這個階段）、可以彈性調整不同算分演算法（下一個階段）、最後再來調整參數配置得到一個最「通用」的配置、或是最「快速」的配置

理想上，你搭好的框架（或是俗稱積木）就是給後面接手的人方便去排列組合出更多成果，如上面提到，「最通用」可以是一個題目、「吞吐量最高」可以是個題目

換言之，要看CPU or 吞吐量就屬於「點」的題目，可以先討論有個想法，但在順序上就是比較後面就是了
