### ISSUE TITLE
算分模組化

### ISSUE THREAD

**Issue by chinghongfang** [skiptests/astraea#230]
需要設計一個介面讓我們抽換 "算分模型" 。

不論是 "producer partitioner"、"partition 搬移" 或 "consumer group policy" 都可能需要先對broker (or something else??) 進行算分，然後才判斷之後的行動。於是，我們可能想出不同的算分方法 (e.g. 可能根據不同的數據、權重、演算法、目的)，這些算分方式可以抽換，就如同積木般 排列組合，進行不同組合的嘗試。

為此，我們要規範出**算分模組介面**，以便我們之後抽換，也方便後人使用。
如 https://github.com/skiptests/astraea/issues/229#issuecomment-1036985897 所述

目前的介面想法
```java
interface Score{
  long get(BrokerStat);
}
```
其中，`BrokerStat`包含各種"可選填"的**broker數據**(某些算法可能僅需部份數據)。
請問大家對此介面有否建議？

**Comment by chia7712** [comment]
這個介面看起來ok

@chinghongfang @garyparrot 你們可以協調一下看能否先做一個版本？

**Comment by garyparrot** [comment]
> 這些算分方式可以抽換，就如同積木般 排列組合，進行不同組合的嘗試。

想問 `Score#get` 的單位是什麼? 我很擔心看到 `10kg + 100cm` 之類的程式碼

**Comment by chia7712** [comment]
> 想問 Score#get 的單位是什麼? 我很擔心看到 10kg + 100cm 之類的程式碼

理想上要把各種資源數字正規化成一個「分數」，而如何正規化要套哪些因素就是個彈性

例如一個簡單且常見的方式，把閒置資源百分比後的數字當成分數，也就是佔用比越高分數越低

**Comment by chia7712** [comment]
另外補充一下，這個模組之後也應該被balancer重複使用（評分）

至於算分的部分，可以參考https://hbase.apache.org/2.0/devapidocs/org/apache/hadoop/hbase/master/balancer/StochasticLoadBalancer.html

這是hbase裡面在做資料平衡時的算分方式

**Comment by chia7712** [comment]
#256已經完成一部分，後續項目在#282追蹤
