### ISSUE TITLE
Performance test for astraea partitioner 

### ISSUE THREAD

**Issue by wycccccc** [skiptests/astraea#234]
| 測試方式 |版本|數據|改善|
|----------|-----|-----|----|
|一台發送資料到broker-0製造不平均的叢集、一台分別測試kafka/astraea partitioner<br>測試數據<br>producer:5<br>consumer:10<br>record.size:100KiB<br>runTime:30min|#234|kafka: <br>producer 1457MB/s <br>consumer 1398MB/s astraea: <br>producer 1714MB/s <br>consumer 1714MB/s|producer 117% <br>consumer 122%|
|一台發送資料到broker-0製造不平均的叢集、一台分別測試kafka/astraea partitioner<br>測試數據<br>producer:5<br>consumer:10<br>record.size:10KiB<br>runTime:30min|#241|kafka: <br>producer 1508MB/s <br>consumer 1445MB/s <br>astraea:<br>producer 1734MB/s <br>consumer 1734MB/s|producer 114% <br>consumer 119%|
|一台發送資料到broker-0製造不平均的叢集、一台分別測試kafka/astraea partitioner<br>測試數據<br>producer:5<br>consumer:10<br>record.size:10KiB<br>runTime:30min|#241 v2|kafka: <br>producer 1508MB/s <br>consumer 1445MB/s <br>astraea:<br>producer 1821MB/s <br>consumer 1800MB/s|producer 120% <br>consumer 124%|
|一台發送資料到broker-0製造不平均的叢集、一台分別測試kafka/astraea partitioner<br>測試數據<br>producer:5<br>consumer:10<br>record.size:10KiB<br>runTime:30min|#251|kafka: <br>producer 1508MB/s <br>consumer 1445MB/s <br>astraea:<br>producer 1836MB/s <br>consumer 1839MB/s|producer 121% <br>consumer 127%|
|一台發送資料到broker-0製造不平均的叢集、一台分別測試kafka/astraea partitioner<br>測試數據<br>producer:5<br>consumer:10<br>record.size:10KiB<br>runTime:25min|#257|kafka: <br>producer 1508MB/s <br>consumer 1445MB/s <br>astraea:<br>producer 1858MB/s <br>consumer 1752MB/s|producer 123% <br>consumer 121%|
|兩台發送資料到整個業集、分別測試kafka/astraea partitioner<br>測試數據<br>producer:3<br>consumer:5<br>record.size:10KiB<br>runTime:25min|#257|kafka: <br>producer 857MB/s <br>consumer 856.5MB/s <br>astraea:<br>producer 820.5MB/s <br>consumer 821MB/s|producer 95% <br>consumer 95%|

新集群的測試：
測試資料
producer 5
consumer 10
record.size 100KiB
run time 30 min

測試集群機器：1~4號機
測試發送資料機器：5號機，3090

左邊數據為只打集群中的一台機器，右邊數據為向整個集群發送資料

Default partitioner:
![1007363371](https://user-images.githubusercontent.com/43372856/154276180-f8cab392-f4a1-41d4-b4e5-c14c9c54a58b.jpg)
整個集群的吞吐量為兩邊producer throughput相加總和：1460MB/s

Astraea partitioner:

左邊數據為只打集群中的一台機器，右邊數據為向整個集群發送資料

![1149077190](https://user-images.githubusercontent.com/43372856/154276185-3a189587-ab0b-44e8-b597-5b407b9fe02f.jpg)
整個集群的吞吐量為兩邊producer throughput相加總和：1715MB/s

從狀況上可以看出,目前的測試環境使用Astraea partitioner可以使繁忙的機器有更多的資源，進而提高整體的through put。

**Comment by chia7712** [comment]
我們能捕捉client的資源用量嗎？cpu and memory，這可以用來說明astraea partitioner造成的成本

**Comment by wycccccc** [comment]
可以，我有用htop在比較，astraea partitioner cpu usage會比較高，且有些核心基本處於100%滿負荷運轉。明天我會貼一些測試過後的相關數據上來。

**Comment by chia7712** [comment]
@wycccccc 那個吞吐量的部分可否把producer/consumer的數據都顯示出來？

**Comment by wycccccc** [comment]
是把表格更新成這樣對嘛

**Comment by chia7712** [comment]
> 是把表格更新成這樣對嘛

沒錯

另外可能要想一下為何consumer的速度也會提升？是因為資料分布夠均勻嗎？如果是的話，那我們也需要一個數據來表示現在的”資料均勻程度“

**Comment by wycccccc** [comment]
測試資料
producer 5
consumer 10
record.size 10KiB
run time 30 min

測試集群機器：1~4號機
測試發送資料機器：5號機，3090

左邊數據為只打集群中的一台機器，右邊數據為向整個集群發送資料

astraea partitioner：
![Screenshot from 2022-02-20 23-06-35](https://user-images.githubusercontent.com/43372856/154849669-10421d0a-8d30-4c4e-8ec9-522fcaba55d8.png).

整個集群的吞吐量為兩邊producer throughput相加總和：1821MB/s

在我們現有的環境下，astraea partitoner在對比kafka已幾乎沒有提升空間。我認爲可以進入下一階段的測試。

下一階段我準備測試的情景
負載重的機器不斷變動，前10min打0號機，第二個10min打1號機，以此類推。
測試的同時我會完成 #244 的第一部分。

**Comment by chia7712** [comment]
> 在我們現有的環境下，astraea partitoner在對比kafka已幾乎沒有提升空間

請問這個結論的來源為何？

**Comment by chia7712** [comment]
@wycccccc 不好意思，也麻煩你將測試用的指令貼到`description`，謝謝

**Comment by wycccccc** [comment]
> 請問這個結論的來源為何？

因爲兩臺發送得到的數據和，單臺分別單獨進行測試，得到的數據結果十分接近。
如果在兩臺發送資料互相影響的情況下，astraea partitioner能做到Kafka partitioner（單臺向整個集羣發送資料）的throughput，那麼我認爲已經接近環境上線，幾乎沒有提升空間。（外加kafka partitoner的速率爲1000MB/S與網路上線溫和）

測試資料
producer 2
consumer 5
record.size 10KiB
run time 30 min

測試集群機器：1~4號機
測試發送資料機器：5號機，3090

左邊數據為只打集群中的一台機器 指令：
java -jar app-0.0.1-SNAPSHOT-all.jar performance --bootstrap.servers 192.168.103.173:13843 --record.size 10KiB --run.until 30m --partitions 50 --producers 2 --consumers 5 --jmx.servers 192.168.103.171:10141,192.168.103.172:19221,192.168.103.173:10634,192.168.103.174:11392 --partitioner org.astraea.partitioner.LoadPartitioner

右邊數據為向整個集群發送資料 指令：
./gradlew run --args="performance --bootstrap.servers 192.168.103.173:13843 --record.size 10KiB --run.until 30m --producers 5 --consumers 10 --createCSV --specify.broker 1004 --partitions 50" 

![Screenshot from 2022-02-23 23-31-43](https://user-images.githubusercontent.com/43372856/155355730-39cc17f2-61f9-442b-8db6-f64cc735449d.png)

整個集群的吞吐量為兩邊producer throughput相加總和：1836MB/s

新的partitioner面對最爲單純的測試環境表現不錯。且只用更少的producer就達到了機器throughput的上線。（old partitioner 5個producer，new partiioner 2個）接來下我會進行上面提到的稍復雜環境測試。

**Comment by chia7712** [comment]
> 因爲兩臺發送得到的數據和，單臺分別單獨進行測試，得到的數據結果十分接近。

因此你是說在「現有環境」以及「這個測試情境下」已經達到硬體（單台網路頻寬）的上限，同時吞吐量是勝過default partitioner？

如果是的話，那很好因為代表我們「至少」確定有一個合適的情境，接下來應該要測試更多情境，麻煩你設想一下

**Comment by wycccccc** [comment]
#257 
![Screenshot from 2022-02-28 14-37-54](https://user-images.githubusercontent.com/43372856/155940427-3ca9e7f0-7ede-424c-9e2e-85954c1df06f.png)

**Comment by wycccccc** [comment]
有關測試的情景，我準備先預設這幾個，沒問題的話我會更新到最上方
一臺發送資料到broker-0製造不平均的叢集、一台分別測試kafka/astraea partitioner
兩臺發送資料到整個業集、分別測試kafka/astraea partitioner
一臺發送資料到broker-0，過10min發送資料到broker-1…… 製造動態變化的不平均的叢集、一台分別測試kafka/astraea partitioner
一臺發送到broker-0,broker-1、一台分別測試kafka/astraea partitioner（測試負載沒有超過單一機器上線，但是業績負載不平均的情況）

**Comment by chia7712** [comment]
> 一臺發送資料到broker-0製造不平均的叢集、一台分別測試kafka/astraea partitioner
兩臺發送資料到整個業集、分別測試kafka/astraea partitioner
一臺發送資料到broker-0，過10min發送資料到broker-1…… 製造動態變化的不平均的叢集、一台分別測試kafka/astraea partitioner
一臺發送到broker-0,broker-1、一台分別測試kafka/astraea partitioner（測試負載沒有超過單一機器上線，但是業績負載不平均的情況）

這些情境看起來不錯。

動態的部分可否多做一個是中途加入新的broker (當然目標topic的partition也要移動/新增一個過去)

**Comment by chia7712** [comment]
後續請看 https://github.com/skiptests/astraea/issues/556
