### ISSUE TITLE
KTOP

### ISSUE THREAD

**Issue by chia7712** [skiptests/astraea#240]
現在已經有可以計算partition分數的功能，不過就整個叢集來說，partition的評估畢竟只是“限制”在某個範圍裡，理想上，我們還要能提供整體overview的總攬，一個很好的參考對象就是linux `top`

因此我們應該提升score的範疇，除了"細看"partition以外，也要能提供整個叢集的狀態，例如：

1. 叢集/個別broker/個別topic/個別partition 的cpu/memory/io的使用狀況
2. 週期刷新狀態（如同`top`)

**Comment by chia7712** [comment]
@garyparrot @qoo332001 你們覺得呢？

**Comment by garyparrot** [comment]
`io` 還行，不過你要如何得到 partition 消耗的 cpu/memory, 而且這個 cpu/memory 的定義也很曖昧

然後比起 `top` 我比較喜歡 prometheus 和 exporter 那套，他能夠畫圖表，和翻歷史資料，而且能夠方便看到叢集內多臺設備的狀態。如果用 `top` 的話我的螢幕可能要買 8 臺。

**Comment by chia7712** [comment]
> 然後比起 top 我比較喜歡 prometheus 和 exporter 那套，他能夠畫圖表，和翻歷史資料

prometheus 和 exporter當然很棒，不過那是比較複雜的用法，可以提供一個輕量又清楚的畫面是這個議題的重點

> 而且能夠方便看到叢集內多臺設備的狀態。如果用 top 的話我的螢幕可能要買 8 臺。

哈哈 應該是不要8台，理想上是可以在一個畫面內去顯示整個叢集的即時狀態XDDD

**Comment by chia7712** [comment]
> 不過你要如何得到 partition 消耗的 cpu/memory, 而且這個 cpu/memory 的定義也很曖昧

簡單一點來想的話，就是先抓jvm metrics，至於如何細緻到topic/partition，這可以之後再研究

**Comment by garyparrot** [comment]
> 可以提供一個輕量又清楚的畫面是這個議題的重點

也是, `ktop` 可以作爲一個比較 ad hoc 的觀測工具

> 簡單一點來想的話，就是先抓jvm metrics，至於如何細緻到topic/partition，這可以之後再研究

+1

**Comment by chia7712** [comment]
目前輸出和互動工具會以web為主，故關閉此議題
