### ISSUE TITLE
修改部分演算法

### ISSUE THREAD

**Issue by wycccccc** [skiptests/astraea#244]
有兩部分需要修改
平滑加權輪尋（Smooth weight round robin）需要大量計算，每有一個producer都需要單獨計算每一個broker的權重，會增加不少cpu和內存的消耗。並且得到的結果資料的分布也不夠均勻。面對下一階段的測試，也沒辦法快速應變沒。（因爲運行的越久權重越大，沒法靈活變換）是時候換掉它了。
![Screenshot from 2022-02-20 23-36-07](https://user-images.githubusercontent.com/43372856/154850639-5cac60af-3624-4c17-a397-900e3a380780.png)

直接丟球可能不錯，根據負載情況生成籃子進行丟球可能是一種比較直接且能實現預期效果的方法，且實做也不難。

異格機器的算法之前是基於平滑加權輪尋實做，且有點陽春。也需要設計個經的住實驗的算法。

- [ ] replace smooth weight round robin
- [ ] Algorithms adapted to computers of different specifications

**Comment by chia7712** [comment]
目前已經在忙其他項目，先關閉
