### ISSUE TITLE
效能測試程式改良

### ISSUE THREAD

**Issue by chinghongfang** [skiptests/astraea#26]
以[Performance testing tool](https://github.com/skiptests/astraea/pull/11)（完成）取代[latency](https://github.com/skiptests/astraea/tree/main/app/src/main/java/org/astraea/performance/latency)。並完成更多的情境。

TODO: 
- [x] 全力傳送訊息 (#77)
- [x] 使用隨機內容 (#106)
- [x] 設定測試的時間長短 (#106)
- [x] 確定consumer取得assignment (#91)
- [x] transactional send, idempotent send (#136)
- [x] 資料大小分佈 (#213)
- [x] record key分佈 (#152)

**Comment by chia7712** [comment]
@chinghongfang 那些完成的議題麻煩標注一下對應的PR

另外，現在的key值並沒有設計分佈可以調整，例如，我們需要測試一個狀況是有30% key都是類似（或是一樣）70%獨立。需要這樣測試的原因是大部分的partitioner都是依照key作為分散，我們需要知道在一些特殊狀況（例如hot key）的時候，我們的partitioner表現的如何

**Comment by chinghongfang** [comment]
好的，我再來寫key值分佈。
為了指定"測試時間"，有更動一些架構，我可能要等#106 做完再來新增。

**Comment by chia7712** [comment]
工作都已經完成
