### ISSUE TITLE
改善JMX server參數的使用方式

### ISSUE THREAD

**Issue by chia7712** [skiptests/astraea#262]
@wycccccc 麻煩看一下這邊的參數用法，我簡單說明一下

我最近在試smooth partitioner，注意到參數的使用方式在實際運用上蠻麻煩的，因為`JMX`的資訊寫起來太長，同時當有新的節點加入時又無法反應

不過在實際生產環境上，通常各個brokers所使用的JMX port其實蠻常是一樣的（為了方便後面串接的監控服務），因此這邊使用了新的參數方法，例如：

1. 可以只定義`jmx.port`，這樣代表所有brokers都是使用同樣的port來開放jmx服務
2. 可以定義`broker.{id}.jmx.port`來針對特定的broker使用不同的imx port。利如我們自己的腳本就可以用這個方式

這個方法看能否應用到smooth partitioner裡面，提早統一參數用法可以方便我們日後轉換

_Originally posted by @chia7712 in https://github.com/skiptests/astraea/pull/256#discussion_r816741093_

**Comment by wycccccc** [comment]
好 ，我會新開一個pr處理。
