### ISSUE TITLE
Performance#execute回傳了Future，但該方法並不是非同步執行

### ISSUE THREAD

**Issue by chia7712** [skiptests/astraea#265]
通常定義回傳型別為`Future`代表預期該方法為非同步運行，但根據原始碼 (https://github.com/skiptests/astraea/blob/main/app/src/main/java/org/astraea/performance/Performance.java#L134) 可以知道我們總是會等所有執行緒都完成後才回傳`Future`，如此一來，使用`Future`就沒有特別意義

**Comment by chia7712** [comment]
@wycccccc 請問當時這樣做的目的為何？

**Comment by wycccccc** [comment]
當時是爲了自動化測試，讓我們可以知道這次測試何時結束（執行緒都完成）。

**Comment by wycccccc** [comment]
當時的討論好像是，我因為每次結束都需要這次測試的topic name把topic刪掉來釋放硬碟空間。直接回傳個String，你說這樣不夠程序員的寫法。然後就包了個Future。故事大概是這樣。

**Comment by chia7712** [comment]
> 你說這樣不夠程序員的寫法。然後就包了個Future

後面這兩句當時不知道是怎麼連起來的@@

所以你們需要知道何時結束嗎？因為現在該方法都是等到結束後才會回傳，有無回傳值很重要嗎？

使用Future通常是該方法為非同步，如果只是單純想知道該方法結束與否，那連回傳值都不用了，直接呼叫該方法等他結束就好了

**Comment by wycccccc** [comment]
我記得當時測試的結果，我直接呼叫該方法不會等到線程池中的所有線程結束程式就會接著運行（無法知道該方法是否結束），所以就用了future

**Comment by chia7712** [comment]
> 程式不會等到thread pool中的所有線程結束程式就會接著運行

這聽起來像個bug? 從現在的程式碼來看，裡面有呼叫waitAll應該會等到結束才對

**Comment by chia7712** [comment]
https://github.com/skiptests/astraea/pull/173#discussion_r780776038

從上面討論來看，我當時應該是以為這個方法是非同步的QQ

我來發個PR修正一下
