### ISSUE TITLE
錄製技術分享短片

### ISSUE THREAD

**Issue by chia7712** [skiptests/astraea#279]
這個短片可以用來跟來賓快速說明此專案的兩個重點：partitioner and balancer

短片要有下列幾個需求：
1. 長度5～10分鐘
2. 說明動機目的和預期成果
3. 畫質至少1080p
4. 要露臉

這兩隻短片應該在4/10之前完成

預計登場時間：

1. 4/7 @chungen0126 
2. 4/21 @wycccccc @chinghongfang 
3. 5/5 @garyparrot @qoo332001

**Comment by chia7712** [comment]
我把你們的影片使用日期寫在上面了，麻煩大家看一下

@qoo332001 @garyparrot 我把你們的部分壓在最後面，如果到了四月中狀況不如預期的話，那就再看看能否調整

**Comment by chungen0126** [comment]
# YuniKorn 講稿
## 介紹
YuniKorn是用於容器系統的一個輕量型的資源排程器，YuniKorn提供更好的混合工作服務，包含批次任務工作以及常駐服務類型的工作，同時希望支援各個平台，目前以kubernetes以及YARN為主。

## 背景
現今，大部分公司將工作跑在多個不同的平台，不同的平台擁有不同的資源排程器，如YARN以及kubernetes，他們需要將各類型的工作安排到適合的平台上讓他們有效的運作。不同的資源排程方式通常適用於不同種的工作，像是：
* YARN適用於批次任務工作
* kubernetes默認排程適用於常駐服務類型的工作。

因此，YuniKorn想發展成一個獨立的資源排程器，統整這些排程器的優點，並且可以支援各個不同的平台，在各個不同的平台上滿足各類型工作的需求。

## 目前的發展
目前，YuniKorn針對kubernetes平台外加新功能，讓kubernetes更友善於批次任務，幫助在kubernetes上實現其他不同資源排程器的優點，如下：
* 同時支援批次工作以及常駐類型工作。
* 擁有巢狀結構的隊列，同時可以限制資源配額。
* 資源平均分配在各隊列、使用者、應用程式。
* 多元化的應用程式放置規則。
* 自動化的根據規則放置容器到正確的隊列。

同時，YuniKorn可以支援kubernetes上的特別功能：
* 支持kubernetes上的pod affinity/anti-affinity, node selectors等功能。
* 支持kubernetes上的PV以及PVC。

## 未來發展
YuniKorn仍然正在克服在單一個平台上跑各類型得工作，針對更多不同的大數據工作，如：spark, flink, Tensorflow等。主要想在kubernetes上支援更多的大數據工作。

**Comment by chia7712** [comment]
@chungen0126 這份講稿不錯，不過能否補充一下目前的使用者們以及開發者的背景。另外開頭的時候需要自我介紹一下，姓名、以及現在在yunikorn研究什麼（例如可以說在研究資源破碎化）

**Comment by chia7712** [comment]
> 不好意思，使用者部分，我這邊蒐集到的資訊比較少。其餘部分我有補充上去。

因為是口頭提到，可以簡單說主要有apple, cloudera之類的就好


另外可以開始錄製看看了

**Comment by wycccccc** [comment]
# Kafka Partitioner 講稿
## 自我介紹
大家好我是xxx，目前是一名成大資訊工程所研究生。參與開發Astraea project。今天借這個機會和大家分享Kafka Partitioner在Kafka中扮演了什麼角色。及我所負責的Astraea Partitioner這個部分想要解決什麼問題。

## Kafka Default Partitioner
Partitioner決定了producer送出的資料會發往哪個partition。Kafka允許使用者在任何情況下使用任意的partitioner。在沒有被指定使用某個partitoner的情況下會默認使用kafka自帶的Default Partitioner。
Default Partitioner的運行採取以下策略：
當資料設置key的時候，資料會根據key做hash得到的值來選擇partition。當資料沒有設置key的時候，會根據round-robin來均勻的為每一個partition分配盡可能相同數目的資料。
![](https://i.imgur.com/qdZ2udV.png)

## kafka Default Partitioner所不能處理情景
![](https://i.imgur.com/Y4Z6kRJ.png)

我們設計了以下情景。業集中有三台機器，其中Topic1分佈在Broker1與Broker2上，Topic2分佈在Broker2與Broker3上。Topic3分佈在Broker1，2，3上。每個Topic在每台機器上分佈著同樣數量的partition。這時有三台機器分別控制三個Producer以Producer1向Topic1這種一一對應的方式發送資料。
假設每一台機器的throughput ability都為1000MB/s，這時我們使用Default Partitoner就會導致Broker2預期將會吃到1333MB/s（1000/2+1000/2+1000/3）。而它的上限決定了它只能吃到1000MB/s的資料。
這時發生的情況不僅僅是broker2少吃了333MB/s的資料。因為Default Partitioner均勻分配資料的特性，每個Broker會吃到一個producer發來的被等量平分的消息。所有在Broker2中擁有partition的Topic都會因為Broker2少吃了333MB/s,而導致向這些topic發送資料的producer在向其他Broker1與Broker3發送資料的同時也會少掉333MB/s。這樣對於三個Producers將合集損失1000MB/s的thoughput量。

在實際的環境下，這一問題會因為消息的堵塞堆積而被放大變得更加不可忽視。以下是在我們實驗環境得出的結果。
![](https://i.imgur.com/pnE1Nt5.jpg)
（之後會換張漂亮的圖片）
可以看到按照上述情景實際的情況為550MB/s,750MB/S,560MB/s。消息的堵塞促使Broker2分配給了向它發送資料的三個Producer250MB/s的throughput。這也進一步促成了producer1與producer2只有550MB/s的局面


## Astraea Partitioner介紹
在Kafka cluster實際運行過程中，每一個broker的負載狀況是不可能做到一致的。Astraea partitioner為了提高整個集群對於資源的利用率，將減少選擇那些位於負載嚴重的broker中的partition作為資料發佈的目標的頻率。同時避免短時間內大量選擇同一個node造成hotspot導致他的負載變得不平衡。盡可能的做到整個cluster中每一個broker的負載情況保持在一個相對平均的狀況。

## 預期成果
我們將通過獲得Jmx metrics記錄整個葉集的資訊，通過分析諸如Broker，topic及producer自身 throughput狀態，broker memory與cpu usage等資訊。來動態的對資料的分配模式進行調整。做到整個葉集的load balace，提高葉集硬體資源的利用率。預期將會相比Kafka Default Partitioner提高整體producers端30%的效能。




 之後會大致按照上述內容製作slide，並進行錄音。Astraea Partitioner的細節部分我沒有大量描述，一方面我感覺要講的話得再多幾頁slide時間上來不及，另一方面最近可能還要對其中的部分演算法再做一下修改。

**Comment by chia7712** [comment]
@wycccccc 感謝提供文字。幾個建議：

1. 這份講稿已經走到有點細節去了，比較不適合在五分鐘的場合裡面。因為聽眾要消化細節需要時間，但這個場子沒有時間
2. 承上，因此需要講一些文字用很平鋪的方式來呈現。例如第一段在「描述」問題的時候，一種講法是，Kafka producer預設用key的hash值來選擇節點，但hash不在意哪一個節點比較忙，因此hash到狀況不好的節點時吞吐量就會掉下來，導致你幾百萬的機器可能只用到幾十萬的效能。如此說明用來取代上述很多數字細節的部分
3. astraea partitioner的解法也不用講太細，講概念就可以，然後強調幾個重點：實驗測試在負載不均的狀況可以提昇多少吞吐量、成本低（延遲沒有明顯增加）、彈性高等等

**Comment by chungen0126** [comment]
我有錄製了幾次，挑一個比較完整的影片上傳，但是影片檔案太大無法上傳到這裡，所以我上傳到youtube上。
下面是連結，請學長看完後給一些建議。
https://youtu.be/1yL6VSukJDg

**Comment by chia7712** [comment]
> 下面是連結，請學長看完後給一些建議。
https://youtu.be/1yL6VSukJDg

還不錯，這個版本就可以了。不過幾個小建議之後可以參考一下：
1）儘量不要出現「唸」投影片上的字，這個工作交給google小姐就好
2）投影片上的字放重點就好，例如平台比較的時候應該用表格而不是長長的文字

@chinghongfang @wycccccc @garyparrot @qoo332001 也麻煩你們參考一下

@chungen0126 麻煩把影片檔案原始檔寄給我，謝謝

**Comment by chia7712** [comment]
技術影片都已經完成，關閉議題
