### ISSUE TITLE
評估partition在節點/目錄間搬移的成本

### ISSUE THREAD

**Issue by chia7712** [skiptests/astraea#28]
Kafka支援將partition重新部署，分成兩個部分：

1. 變更partition的儲存路徑 (https://kafka.apache.org/26/javadoc/org/apache/kafka/clients/admin/KafkaAdminClient.html#alterReplicaLogDirs-java.util.Map-org.apache.kafka.clients.admin.AlterReplicaLogDirsOptions-)

這個操作允許使用者在同一個節點上變更某個partition的資料存放路徑（local filesystem)

2. 變更partition的服務節點 (https://kafka.apache.org/26/javadoc/org/apache/kafka/clients/admin/KafkaAdminClient.html#alterPartitionReassignments-java.util.Map-org.apache.kafka.clients.admin.AlterPartitionReassignmentsOptions-)

這個操作允許使用者將partition從一個節點移至另一個節點

---

上述功能對於大型叢集是非常方便的功能，原因有三：

1. 一個活躍的大型叢集常常會有資源上的水平擴充，此時為了快速提高資源使用率或負載平衡，我們會人工介入迫使一些partitions移動到指定的新資源 (節點 or disk) 上
2. 該些partition變更不需要下線叢集
3. 該些partition變更不會阻擋producer/consumer，也就是在搬移過程中依然可以操作原本的partitions

然而，該些變更都可能造成相當大的成本，因為kafka會背景開啟執行緒來複製資料，當資料量相當大的時候，該些變更可能持續好一陣子，甚至額外的負擔也可能拖累日常應用。因此如果能在正式執行搬移之前能先知道可能的“成本”，這會對叢集管理上帶來很好的幫助。

成本可能包含下列項目：
1. 要搬移的資料量
2. 預期執行時間
3. 可能要佔用的頻寬（MB/s）

---
第一步的實現
### 方案一
在假設業務邏輯的資料生產端為相對穩定且持續的，且每台broker的性能也一致的情況下。
可以找到partition的thoughput的關係由以下式子表示
load = Size of a partition on disk/retention.ms
進而提出初步的打分模式
 先判斷brokerload是否大於brokerload平均值,若是 :
* 設想的簡易公式 (((brokerload-brokerload平均值)/brokerload標準差)*(((partitionload-partitionload平均值)/partitionload標
準差))*60 = 分數

若brokerload小於brokerload平均值，則表示broker不需要搬移,將該broker的所有partition打0分
最終得到的分數越高的partition就越值的搬移。

**Comment by chia7712** [comment]
@wycccccc 這個是做offline balance的第一步，需要先有個方式來評估成本，如此才有後續可以考慮是否值得搬移。因為你正在忙partitioner，因此這個工作先交給學弟。但也會很需要你的意見~

**Comment by wycccccc** [comment]
好的，我會在做完partitioner test之後，去開始著手這一塊的內容。因為很不幸這禮拜正好我報告，預計星期四開始做這一塊的內容。

**Comment by wycccccc** [comment]
# 評估partition在節點/目錄間搬移的成本

1. 要搬移的資料量
    
3. 預期執行時間
4. 可能要佔用的頻寬（MB/s）
### 目的：打分的目的應該是讓我們根據“成本”進行評判現在哪個partition應該被搬移（找到現在應該搬移的理由）。


  系統的應用場景各不相同，想要建立一個普適的打分標準，也就需要儘可能多的收集變量之間的關係，才有可能使預測準確。
  
我認為成本這一概念其實無法用某個metrics的狀況進行區分。他因是基於複數條去評判的。

舉幾個例子：
  partition的資料量較小雖然搬移的成本顯得很低，但是卻無法確認搬移這一動作是否有價值。
該node存在partition的數量過多則代表他更有可能被輸入資料，日常占用的頻寬就會較高，頻寬對於其就顯得更加重要。

  因此將上述兩點進行結合，該node存在partition的數量過多同時該partition的資料量較小，他就顯得比較適合搬移，因為要搬移的資料量較小，成本就很低。最重要的是如果不對較小的partition現在進行搬移，隨着時間的積累，資料量變大顯然是不劃算的。

  partition分為leader和follower兩種狀態我認為這是需要分開進行討論的。（這裡先討論不開啟follower replica的情況）
毫無疑問leader的負載會更重，而且重新選舉leader也會帶來一定的成本。這一leader partition如果恰巧又經常被多個consumer group消費那很顯然他比較適合被單獨存放，與他在同一個node的其他partition就相應的更適合被搬移。然後連帶着也會影響到他的follower所處在的node的其他partition。

  而leader partition當下如果正在高負荷接受消費資料，顯然follower就應該去被優先進行上述情況處理。

消息的回收時間與儲存資料之間的關係，倘若要搬移的partition中的大部分資料都將要被回收，那搬移就顯得毫無意義。

有價值的metrics（峰值）應該不止有這些，儘可能先確定指標之間的關係可能是首先需要去做的。
上述的某些metrics可以最終整合為與預期執行時間，可能要佔用的頻寬此類經過計算得出的metrics。做到簡化上述問題的描述。

就我目前的判斷：
資料量的大小是其中最重要的指標。因資料相依性的關係，資料量大往往代表了應用端喜歡丟資料進入這個partiton。而單純就大小而言也是很直觀的成本。比較它與其他metrics之間的狀況，總結一些關係可能是我首先會去做的。

**Comment by wycccccc** [comment]
# 評估partition在節點/目錄間搬移的成本

### 目的：打分的目的應該是讓我們根據“成本”進行評判現在哪個partition應該被搬移（找到現在應該搬移的理由）。


  系統的應用場景各不相同，想要建立一個普適的打分標準，也就需要儘可能多的收集變量之間的關係，才有可能使預測準確。
  
我認為成本這一概念其實無法用某個metrics的狀況進行區分。他因是基於複數條去評判的。

舉幾個例子：
1.   partition的資料量較小雖然搬移的成本顯得很低，但是卻無法確認搬移這一動作是否有價值。該node存在partition的數量過多則代表他更有可能被輸入資料，日常占用的頻寬就會較高，頻寬對於其就顯得更加重要。
因此將上述兩點進行結合，該node存在partition的數量過多同時該partition的資料量較小，他就顯得比較適合搬移，因為要搬移的資料量較小，成本就很低。最重要的是如果不對較小的partition現在進行搬移，隨着時間的積累，資料量變大顯然是不劃算的。

2. partition分為leader和follower兩種狀態我認為這是需要分開進行討論的。（這裡先討論不開啟follower replica的情況）
毫無疑問leader的負載會更重，而且重新選舉leader也會帶來一定的成本。這一leader partition如果恰巧又經常被多個consumer group消費那很顯然他比較適合被單獨存放，與他在同一個node的其他partition就相應的更適合被搬移。然後連帶着也會影響到他的follower所處在的node的其他partition。
而leader partition當下如果正在高負荷接受消費資料，顯然follower就應該去被優先進行上述情況處理。

3. 消息的回收時間與儲存資料之間的關係，倘若要搬移的partition中的大部分資料都將要被回收，那搬移就顯得毫無意義。

有價值的metrics（峰值）應該不止有這些，儘可能先確定指標之間的關係可能是首先需要去做的。
上述的某些metrics可以最終整合為與預期執行時間，可能要佔用的頻寬此類經過計算得出的metrics。做到簡化上述問題的描述。

目前的判斷：
資料量的大小是其中最重要的指標。因資料相依性的關係，資料量大往往代表了應用端喜歡丟資料進入這個partiton。而單純就大小而言也是很直觀的成本。比較它與其他metrics之間的狀況，總結一些關係可能是我首先會去做的。

**Comment by wycccccc** [comment]
如果明天學的的jvm還沒有好的話，我會先繼續整理上述思路。先請學長幫忙看看大致思考的方向有無問題。
@qoo332001 可以看看[這篇文章](https://www.jianshu.com/p/587e88bdbf7a)先了解一下他是怎麼搬的。

**Comment by chia7712** [comment]
以下純技術討論:

> partition的資料量較小雖然搬移的成本顯得很低，但是卻無法確認搬移這一動作是否有價值。該node存在partition的數量過多則代表他更有可能被輸入資料，日常占用的頻寬就會較高，頻寬對於其就顯得更加重要。

這個就是kafka partition設計上造成的副作用，**partition並沒有明確限制資料分段**，這導致任何一筆資料(key)都可以出現在任何一個partition，換言之我們很難去預測說哪些partition之後會很常被使用。尤其partition又跟data order綁在一起，也就是資料往哪裡跑很容易跟應用程式的業務邏輯有關，這些資訊除非使用者告訴我們，不然都是很容易預測錯誤。

> 該node存在partition的數量過多同時該partition的資料量較小，他就顯得比較適合搬移

承接上面敘述，因此這句話的就存在很多不確定性。

> 最重要的是如果不對較小的partition現在進行搬移，隨着時間的積累，資料量變大顯然是不劃算的。

一樣。除非我們要假定一個情境是每個partition在一定時間內都一定會有大量資料進出。

> 這一leader partition如果恰巧又經常被多個consumer group消費那很顯然他比較適合被單獨存放

不太確定單獨存放是什麼意思？是指某個節點只服務該partition嗎？這樣好像不太實際

> 消息的回收時間與儲存資料之間的關係，倘若要搬移的partition中的大部分資料都將要被回收

有道理，這應該也要是評分的一大重點

**Comment by chia7712** [comment]
@wycccccc @qoo332001 

我提醒一下，第一步先做“評分”而不用做“搬移”。換言之，要先了解有哪些“指標”是具有參考價值（這部分會類似partitioner面對的課題）。@garyparrot已經做了一個非常棒的工具來抓取broker metrics，那麼這裡我們就可以討論一下，如果是以”評估哪些partitions"值得被考慮搬移，那麼我們還需要看哪些指標？或許跟partitioner要看的數值一樣？也或許不一樣？

另外，@wycccccc講的原始碼也值得一看，不過在看原始碼之前建議先用kafka工具玩一下partition的搬移，先有個操作上的認知會比較順。

**Comment by wycccccc** [comment]
我的設想是先可以把框架做出來，然後打分的機制可以再不斷迭代。因此在這裡我的目標是提出一個泛用且簡單的打分機制。

經過一番讀書，我感覺到大多metrics都是針對broker而非per partition，想要獲取實際每個partition的狀況用原版的kafka似乎比較難做到。
而我搜索了一下大多需要搬移的情況都是因為網絡或是硬碟的瓶頸造成的。意思就是partition的是否要搬移也就與它所處在的broker性能使用情況有關。

這裡我假設業務邏輯的資料生產端為相對穩定且持續的。（每台broker的性能也一致）
很顯然partition的thoughput可以由以下式子表示
load = Size of a partition on disk/retention.ms

找到合適搬移的partition步驟如下：
1.檢查一個broker 所有partiton 的 load再將這些load相加得出這個broker的load
2.計算所有broker的load進行比較找到出眾的
3.再從出眾的broker中進行比較找到適合搬移的partition

進而推出打分標準：（brokerload*權數）*（partitionload*權數）

設想的簡易公式 （brokerload標準差/brokerload平均值）*（partitionload標準差/partitionload平均值）* 60 = 分數

Size of a partition on disk 可以通過 `kafka.log:type=Log,name=Size,topic=([-.\w]+),partition=([0-9]+)`	該metrics抓到。但每個partition的retention.ms獲取方式可能還需要尋找一下。理論上應該根據partiton所屬的topic獲取？

這樣我就做到了其中一個維度的評判標準。
我感覺可以已這個概念先產出一個東西，這樣會比較實際，對項目推進也比較有幫助（前提是我這個概念沒有問題）。

理想上該打分系統應該有多個維度構成，最終得出一個綜合評分。
但我認為制定多維度的打分標準的前提是一個難點，找到普遍適用的假設可能還需要再與學長不斷討論常用的實際生產環境才可以確定。

以下是我感覺比較有價值的metrics，在此做一個記錄，學弟也可以參考補充：
kafka.controller:type=KafkaController,name=GlobalPartitionCount 
 
kafka.server:type=ReplicaManager,name=UnderReplicatedPartitions 
 
kafka.server:type=DelayedOperationPurgatory,delayedOperation=Produce,name=PurgatorySize 

kafka.network:type=RequestMetrics,name=RequestsPerSec,request=[Produce|FetchConsumer|FetchFollower]

kafka.network:type=RequestMetrics,name=ResponseSendTimeMs,request=[Produce|FetchConsumer|FetchFollower]

kafka.network:type=RequestMetrics,name=TotalTimeMs,request=[Produce|FetchConsumer|FetchFollower]

kafka.log:type=Log,name=Size,topic=([-.\w]+),partition=([0-9]+)

**Comment by wycccccc** [comment]
下一步我會計劃總結一下間斷性的生產資料，導致出現資源使用峰值的情況。
但使用 資源消耗情況來進行打分會出現一個問題，就是打分的過程可能要跑很久。因為需要記錄峰值等情況。
而想上面我提到的方法就只需要讀取數據計算就行，可能很快就能得出結果。
我們這個打分系統有運行時間的限制嘛。
另外像是這種間斷性的生產資料的情況（5min幹活5min休息），在業內情況多嘛，與持續穩定的生產資料相比哪情況更多一些。
像是業內一個broker上是會放很多不同topic的partition對嘛，這樣其實一個broker就會有不同運行邏輯的生產與消費者產生。還是說一般差不多業務邏輯的會被擺在一個broker上？

還有補充一個一定正確的打分標準，如果硬碟要滿了那也必須搬。我認為這個可以放在所有維度之前，作為絕對打分項，滿足這個直接滿分  ：）。

**Comment by chia7712** [comment]
> 我們這個打分系統有運行時間的限制嘛。

目前可能會使用的情境應該是使用者會週期的執行，然後查看是否有紅色警戒（超過一個閥值）

> 另外像是這種間斷性的生產資料的情況（5min幹活5min休息）

很少，通常都是不斷寫和讀。頂多是資料量多少可能會有一些震盪

> 像是業內一個broker上是會放很多不同topic的partition對嘛，這樣其實一個broker就會有不同運行邏輯的生產與消費者產生。還是說一般差不多業務邏輯的會被擺在一個broker上？

一定是混在一起，會事先配置好partitions一定是很懂kafka...而由於kafka預設用隨機的方式，通常一個叢集運作久了，partitions的分佈都會亂亂的

**Comment by chia7712** [comment]
這個題目已經交由 @qoo332001 ，所以關閉此議題
