### ISSUE TITLE
異質環境下的負載平衡

### ISSUE THREAD

**Issue by wycccccc** [skiptests/astraea#284]
現在cluster一共有五臺機器，我們加入了一臺只有100MB/s throughput 處理能力。
不管是Default partitoner 還是astraea都出現了一樣的狀況。最後的throughput只在500MB/s。
![Screenshot from 2022-03-11 18-06-27](https://user-images.githubusercontent.com/43372856/158370258-396aa428-03f1-477a-9dcc-9c6be7cf50f6.png)
所有機器的throughput都被限制到了100MB/s左右，就像水桶中最低的木板一樣。
我想將讓astraea partitioner解決亂源問題，作爲一個階段性的結尾。

kafka最後傳輸request的時候我記得資料結構會變爲<Node,Request>的形式，如果我能知道處理每個node的request會有多少delay，結合node的throughput就可以有推測出throughput動態上限的能力。
我想花一個禮拜的時間來做實驗實做並調查這件事，我想我應該還有一點時間來做這件事。

下面可能是一些有用的metrics：
kafka.server:type=KafkaRequestHandlerPool,name=RequestHandlerAvgIdlePercent
Average fraction of time the request handler threads are idle. Values are between 0 (all resources are used) and 1 (all resources are available).
kafka.server:type=Produce,name=DelayQueueSize
Number of producer clients currently being throttled. The value can be any number greater than or equal to 0.

**Comment by chia7712** [comment]
1. 這個題目應該正經一點叫做「異質環境下的負載平衡」
2. 哪些指標可以反應異質的現象？假設我們不能要求使用者告知
3. 兩個partitioner掉到500mb 的時間是一樣的嗎

**Comment by wycccccc** [comment]
> 兩個partitioner掉到500mb 的時間是一樣的嗎
一開始就是500MB/s 不需要掉。

我有找到一個metrics requestQueueTimeMs request=producer。這個metrics中的count參數似乎是把所有每一筆request產生的latency進行相加匯總。那麼我只要將現在的count和一秒前的count相減就能得到這一秒內request的latency。再結合當前throughput應該就有可能動態預測調整每臺機器的throughtput上限。

在上述實驗中已發現，100MB/s的機器與1000MB/s之間的latency存在顯著差異。
前者爲後者的三倍大概。
我會繼續做一些實驗，論證上述想法，並儘可能從數據中推算出throughput能力與latency之間的公式，方便轉換成演算法。

**Comment by chia7712** [comment]
> 我有找到一個metrics requestQueueTimeMs request=producer。這個metrics中的count參數似乎是把所有每一筆request產生的latency進行相加匯總。那麼我只要將現在的count和一秒前的count相減就能得到這一秒內request的latency。再結合當前throughput應該就有可能動態預測調整每臺機器的throughtput上限。

這樣其實比較像是在算「當下」這個節點能給出的處理produce request能力。

@garyparrot 我記得你也有提出類似的想法？你覺得呢？

**Comment by garyparrot** [comment]
很棒讚讚

**Comment by chia7712** [comment]
> 不過有一些因素可能會讓這個手法變不太可靠，Queue 裏面可能有奧客排隊，他的 request 要服務比較久 (壓縮?)

說得沒錯，要從這個數字直接推斷現有的處理能力會比較模糊一點。可能要考慮結合一下其他數字，例如也要看一下queue裡面是不是有其他吃資源的操作

另外這邊也提到具有歷史紀錄的metrics。這部分要修改cost function架構去支援該功能

@garyparrot 針對修改cost function有想法嗎？

**Comment by garyparrot** [comment]
> @garyparrot 針對修改cost function有想法嗎？

我和我自己的腦袋激烈討論過了，絕大多數的問題已經被我自己解決了

1. 有重要物理意義的 metric 我還在找，最近在複習 Brendan Gregg 的 System Performance，剛剛翻發現我的腦待內的知識已經和他當初寫得東西脫節了。JMX 內的東西看起來勉強能應付 90 % 的狀況，剩下 10% 的狀況應付了可能會有副作用...
2. 讓 partitioner 直接去撈 JMX metric 不知道會不會有效能上的問題，不過這部分我沒有證據所以我打算等他燒起來再說。

> 另外這邊也提到具有歷史紀錄的metrics。這部分要修改cost function架構去支援該功能

這邊我的想法是 Cost Function 可能需要收類似 time series 的資料，每個 metric 要有附帶的時間。
然後 cost function 新增一個 unavailable 的狀態，意指他知道的資訊不夠多不能進行判定。

然後使用 cost function 的上游 class 可以這樣做

1. 從某處撈到過去的歷史資料，然後用歷史資料當下的時間點組合成一個 (time, metric) 餵給 cost function。這邊的 time 可能是一個過去很久的時間，所以 cost function 必須要知道收到過去的資料時該如何處理 (ignore it or something idk)。
3. 不餵過去的歷史資料，慢慢等新資料進來 cost function，讓 cost function 自己慢慢溫機。

手法 1 可能可以讓他比較早脫離 unavailable 的狀態，而後者需要時間溫機。

**Comment by garyparrot** [comment]
> 然後 cost function 新增一個 unavailable 的狀態，意指他知道的資訊不夠多不能進行判定。

這部分 Confluent 的 Self-Balancing 似乎有類似的設計 https://docs.confluent.io/platform/current/kafka/sbc/index.html#broker-removal-attempt-fails-during-sbc-initialization

> Self-Balancing requires 30 minutes to initialize and collect metrics from brokers in the cluster. If you attempt to remove broker before metrics collection completes, the broker removal will fail almost immediately due to insufficient metrics for Self-Balancing. This is the most common use case for “remove broker” failing. The following error message will show on the command line or on Control Center, depending on which method you used for the remove operation:

**Comment by chia7712** [comment]
> 讓 partitioner 直接去撈 JMX metric 不知道會不會有效能上的問題，不過這部分我沒有證據所以我打算等他燒起來再說。

狂打的話一定會有，這就是之前@wycccccc 跟我一直在討論single metrics collector的部分，同一個JVM只能有一個metrics collector。不過這算是另一個議題了

> 就把要不要餵歷史資料這個責任丟給上游這樣，我也不知道要怎麼辦

這個我們回到#282 討論吧

@chinghongfang 麻煩你看一下 @garyparrot 的想法，我們在#282 繼續

**Comment by wycccccc** [comment]
我繼續了上述實驗，我發現它的count只是代表了request的數量，還好他給我留了其他資訊，讓我能夠算出每一筆Request所花費的時間。
我選取了該metrics ，如下是confulent的解釋，看起來是一筆Request從request到response的總時間。
>kafka.network:type=RequestMetrics,name=TotalTimeMs,request={Produce}
Total time in ms to serve the specified request.

以下爲計算每筆得出的數據：
1000MB/S機器:7.818875492408401E-4
100MB/S機器:0.023718892756939034

可以看出後者確實與前者有顯著差距。

現有的結論已經可以支持我嘗試在現有的實驗環境下完成異質機器的平衡。可是會有一個問題，該latency真的能夠表達異質機器這一問題嗎。該實驗的假設是建立在，latency是由Request的堆積產生的。那會不會存在有一個機器網線特別長，然後他的latency就會變得很高，但他的網路頻寬又特別強？
忽略這根特別長的網線似乎就萬事大吉了。想問一下學長對這根網線的看法。

**Comment by garyparrot** [comment]
> JMX 內的東西看起來勉強能應付 90 % 的狀況

我剛剛恢復了我失去的記憶，JMX 看不到 replica leader/follower 的分佈

**Comment by garyparrot** [comment]
> 我繼續了上述實驗，我發現它的count只是代表了request的數量，還好他給我留了其他資訊，讓我能夠算出平均每筆Request所花費的時間。
> 我選取了該metrics ，如下是confulent的解釋，看起來是一筆Request從request到response的總時間。
>> kafka.network:type=RequestMetrics,name=TotalTimeMs,request={Produce}
Total time in ms to serve the specified request.

你之前找到的不是 `kafka.network:type=RequestMetrics,request=Produce,name=RequestQueueTimeMs` 嗎，怎麽變成 `kafka.network:type=RequestMetrics,name=TotalTimeMs,request={Produce}` 了，你是不是和我一樣失去記憶了 @@

> latency是由Request的堆積產生的。那會不會存在有一個機器網線特別長，然後他的latency就會變得很高，但他的網路頻寬又特別強？

網路訊號應該接近光速，如果有 latency 那應該是 network congestion 造成的

**Comment by chia7712** [comment]
> latency是由Request的堆積產生的。那會不會存在有一個機器網線特別長，然後他的latency就會變得很高，但他的網路頻寬又特別強？

@garyparrot 講的是對的。另外距離和網路的延遲的量化通常會以隔了多少個hub，如果在同一個hub下網路線再長通常延遲也不會差很多。

**Comment by wycccccc** [comment]
>你之前找到的不是 kafka.network:type=RequestMetrics,request=Produce,name=RequestQueueTimeMs 嗎，怎麽變成 kafka.network:type=RequestMetrics,name=TotalTimeMs,request={Produce} 了，你是不是和我一樣失去記憶了 @@ 還是其實他們一樣

他們是不一樣的意思，我後面又去翻了一下資料。後者代表的意思爲Request到server所花費的時間。前者是指Request在RequestQueue裏面等待的時間。而Request在發送前都會在RequestQueue裏面待著。
我重新選擇了一個表達的意義上更加直白的metrics。

**Comment by chia7712** [comment]
目前專案不考慮異質環境，先行關閉
