### ISSUE TITLE
Yunikorn資源破碎化實驗

### ISSUE THREAD

**Issue by chia7712** [skiptests/astraea#285]
如稍早會議提到，我們需要先把實驗和觀察工具準備好，此議題用來追蹤測試工具和觀察工具的狀況，包含

1. - [ ] 參數化調整workload的內容
1. - [ ] spark job提交後可以觀察過程中的資源使用率
1. - [ ] spark job提交後可以計算每個任務的完成時間
1. - [ ] 所有任務執行完後可以顯示總執行時間以及各個任務最大/最小的執行時間

**Comment by chia7712** [comment]
@chungen0126 如會議提到，工具的部分看能否先準備好，方便我們進行實驗，同時這個實驗也能做一些圖表出來讓我們好說明資源破碎化的存在會如何干擾效能

**Comment by chungen0126** [comment]
會議提到的我還有些東西不清楚，想確認一下，隨機提交spark job是指，我要寫一個scala的程式，其中可能可以提交一些參數來調整spark job的大小，或是同時透過spark submit調整任務所需的資源大小？

**Comment by chia7712** [comment]
> 隨機提交spark job是指，我要寫一個scala的程式，其中可能可以提交一些參數來調整spark job的大小，或是同時透過spark submit調整任務所需的資源大小？

更仔細的說，我們需要有一個工具可以模擬提交大量spark jobs給yunikorn，而且模擬提交的spark job要可以參數化控制數量、資源量等等方便我們測試不同的情境

例如我們可以下參數說 總共100個任務 任務為睡30秒 每個任務所需的cpu 資源最多為10 最少為3 分配比例為常態分配 記憶體資源最多為10GB 最少為2Gb 分配比例為zips分佈

然後我們會拿上述的參數去測yunikorn然後再測yunikorn +客製化的節點排序 來看兩者的差異（這也需要能觀察，例如算出平均任務執行量、最大最小延遲）

**Comment by chungen0126** [comment]
目前做的實驗，不過實驗結果不是很明顯:
在4個worker node帶有8vcore以及16memory的集群。
appication的vcore隨機分布在1~4，memory分布在1~8，instances分布在1~4。
[實驗結果](https://hackmd.io/@IVUP6rGJQAmUMyQytt73_g/S1S4dlNE5
)

不過還是有一些觀察，比較明顯的是:
在大概6:17，memory使用率很低，同時正在運作的applications也很少。
在6:25，memory以及vcore使用率都很低，同時正在運作的applications也很少。
在6:27，applications正在運作的也少，但是使用率並沒有相對的比較低，可能是在跑一個大任務。
由於任務通常都是一開始就提交完，因此application的最長延遲時間和最短延遲時間差距很大。

總結:
我嘗試過將application的vcore分布在1~7，memory分布在1~14，但是這樣的實驗很不理想，正在運行的application通常只有一個，這樣使用率基本上就是看提交的application的使用資源量大小。因此，我覺得應該要思考一下，application的資源使用量的最大最小值，在整個集群資源量的占比，至少不能過大或過小。

**Comment by chia7712** [comment]
> 並執行sleep 20s。

可否讓執行時間也是一個範圍內的隨機？

> [實驗結果](https://hackmd.io/@IVUP6rGJQAmUMyQytt73_g/S1S4dlNE5)

能否也提供原始數據？

**Comment by chungen0126** [comment]
> 可否讓執行時間也是一個範圍內的隨機？
我改成執行一個sparkPi的程式，讓他執行10^8~10^9次計算。
[實驗結果二
](https://hackmd.io/@IVUP6rGJQAmUMyQytt73_g/S1S4dlNE5#%E5%AF%A6%E9%A9%97%E4%BA%8C)

> 能否也提供原始數據？
這次實驗的數據
[20220417.csv](https://github.com/skiptests/astraea/files/8502293/20220417.csv)

主要能看到當只有2個application正在運行的時候，資源的使用率也會相對的比較低。

**Comment by chia7712** [comment]
文件裡說的「最長延遲時間:」是什麼意思？

**Comment by chungen0126** [comment]
> 文件裡說的「最長延遲時間:」是什麼意思？

指的是submission time到finished time 這段時間。

**Comment by chia7712** [comment]
> [20220417.csv](https://github.com/skiptests/astraea/files/8502293/20220417.csv)

圖表看起來很棒，不過能否把max/avg/min CPU/Memory使用率也計算出來？之後就可以跑跑看你的工具，看看幾個數據的表現

**Comment by chungen0126** [comment]
> 圖表看起來很棒，不過能否把max/avg/min CPU/Memory使用率也計算出來？之後就可以跑跑看你的工具，看看幾個數據的表現

我更新了一些實驗數據，如下。
[實驗二(default yunikorn scheduler)](https://hackmd.io/@IVUP6rGJQAmUMyQytt73_g/S1S4dlNE5#%E5%AF%A6%E9%A9%97%E4%BA%8C)
[實驗三(with my yunikorn-tool)](https://hackmd.io/@IVUP6rGJQAmUMyQytt73_g/S1S4dlNE5#%E5%AF%A6%E9%A9%97%E4%BA%8C)
結論: 
我的yunikorn-tool並沒有幫助到資源使用率，目前想到可能的原因:
- 原本Applications會在starting階段，將所需要的所有資源暴露在restAPIs，但後來改版後只會暴露正在使用的資源量，導致我原本要及時的更新resource，現在無法達到這種效果。
- 實驗本身還不夠全面，application應該跑更實際的應用。
- 最差的可能，我想的演算法本身太過簡單，無法起到任何效果。

**Comment by chia7712** [comment]
> 我的yunikorn-tool並沒有幫助到資源使用率，目前想到可能的原因:

我想確認一下你先後兩次灌的資料集會是一樣的嗎？如果是全程隨機的話，那時間和applications要再拉大一點才能把隨機造成的差異性攤平

另外實驗的部分觀察工具可能還不夠完整，我們先回PR把一些基礎項目往前推，然後再回頭審視實驗的部分
