### ISSUE TITLE
為Cost Function定義對分數利用模式的method

### ISSUE THREAD

**Issue by wycccccc** [skiptests/astraea#295]
為Cost Function 框架新定義一個對分數利用模式的method，將Smooth weight rewrite 為該method。

**Comment by chia7712** [comment]
@chinghongfang 這部分可能要儘早開始，如果可以順利收斂成cost function，那就代表這個演算法也能用在load balancer，也就是 @wycccccc 所研究的項目可以被重複使用

**Comment by chinghongfang** [comment]
要收進cost function沒問題。

我認為問題在於要**把cost function定下來，讓load balancer也使用**。這需要多考慮(是否好用)和了解(load balancer)。

我現在先找找cost function的優缺點，然後去了解load balancer那邊要cost function需要什麼功能，再來改進現在的架構。不知道這個方向對不對？

**Comment by chia7712** [comment]
> 我認為問題在於要把cost function定下來，讓load balancer也使用。這需要多考慮(是否好用)和了解(load balancer)。

load balancer可能可以選用這個cost，也可以不用。端看到時候 @garyparrot  @qoo332001  他們想拿來做題目的情境是否需要

> 我現在先找找cost function的優缺點，然後去了解load balancer那邊要cost function需要什麼功能，再來改進現在的架構。不知道這個方向對不對？

沒錯，就是用smooth當例子試著把它塞到cost裡面，可能只有部分能塞進去、也可能部分要用來調整架構。最終理想上是系統裡面保持一個dispatcher的實作，以及增加多個cost function。然後藉由參數調整的方式來達到smooth一樣的效果

**Comment by garyparrot** [comment]
> load balancer可能可以選用這個cost，也可以不用。端看到時候 @garyparrot @qoo332001 他們想拿來做題目的情境是否需要

@chia7712，我想確定一下

我們的 Balancer 是可以

1. 使用者透過調整參數可以解 n 種情境
2. 使用者透過調整參數和自己寫程式來解 n 種情境
3. 只能解一種情境，想解別的要再寫一個新的 balancer

>  他們想拿來做題目的情境是否需要

我們現在是以第一個的方向下去準備，可是上面這個說法看起來好像是三？

**Comment by chia7712** [comment]
> 使用者透過調整參數可以解 n 種情境
使用者透過調整參數和自己寫程式來解 n 種情境
只能解一種情境，想解別的要再寫一個新的 balancer

全部都是。我們提供了n種cost function，使用者可以透過參數決定要選哪些cost作為balance參考依據，例如使用者只在意leader平衡，那就只選leader cost。如果想合併考慮吞吐量，那就再加上throughput cost。如果目前cost沒有使用者喜歡的，那他也可以自己寫一個cost function。

換言之，使用者可以參數選擇n種cost再加上自己寫的m種cost。

這些cost的互動方式，目前就一種，也就是透過加權後排序。這個方法可能不夠彈性，因為使用者只能參數化權重，不過這個題目可以放在後期再來討論

> 我們現在是以第一個的方向下去準備，可是上面這個說法看起來好像是三？

承接上面的回答，第一個「小」目標是你們先選一個目標，然後試著去解，去做出你們第一隻balancer，有點類似 @wycccccc 的流程，你們先解一個題目做一個版本。之後再討論框架後重新實作。這個方法可能有點迂迴，但這是為了縮減你們的時辰，以免你們同時要解第一個情境、又同時要設計框架

當然，如果你們覺得沒問題，能在解第一個情境時就把框架也做好（結合cost function）那會是最好。不過這就回到我會議上問的，你們有機會在五月給第一個版本嗎？

**Comment by garyparrot** [comment]
> 全部都是。我們提供了n種cost function，使用者可以透過參數決定要選哪些cost作為balance參考依據，例如使用者只在意leader平衡，那就只選leader cost。如果想合併考慮吞吐量，那就再加上throughput cost。如果目前cost沒有使用者喜歡的，那他也可以自己寫一個cost function。

瞭解，我這個禮拜是往這個方向在思考，然後發現了一些產生搬移計劃上的難題，應該和這個 Cost Function 的議題有關，我貼在 https://github.com/skiptests/astraea/issues/289#issuecomment-1087666894。

> 承接上面的回答，第一個「小」目標是你們先選一個目標，然後試著去解，去做出你們第一隻balancer，有點類似 @wycccccc 的流程，你們先解一個題目做一個版本。之後再討論框架後重新實作。這個方法可能有點迂迴，但這是為了縮減你們的時辰，以免你們同時要解第一個情境、又同時要設計框架
> 
> 當然，如果你們覺得沒問題，能在解第一個情境時就把框架也做好（結合cost function）那會是最好。不過這就回到我會議上問的，你們有機會在五月給第一個版本嗎？

最完整的框架不太可能 5 月完成，上面的 issue 有點出產生負載平衡計劃的難處。但比較小目標的 Balancer 比較有機會能完成，不過內部可能有不少東西會是比較寫死的狀況，擴充性或許沒辦法那麼好。

**Comment by chia7712** [comment]
> 不過內部可能有不少東西會是比較寫死的狀況，擴充性或許沒辦法那麼好。

第一版要這樣完全沒問題，重點是你們腦袋裡知道“這是因為時間壓力而先寫死”，如果是覺得寫死好棒棒那我才會真的很擔心

**Comment by chia7712** [comment]
cost function 的各個介面已經都到位，所以關閉此議題
