### ISSUE TITLE
欠缺可靠的手法來衡量 TopicPartitionReplica Allocation 的優異

### ISSUE THREAD

**Issue by garyparrot** [skiptests/astraea#305]
延續 https://github.com/skiptests/astraea/issues/289#user-content-fn-1-43f718e1648667894d00c1cf4b51d960, https://github.com/skiptests/astraea/issues/289#issuecomment-1100871269, https://github.com/skiptests/astraea/issues/289#issuecomment-1100876894 的討論。

目前 Balancer 衡量一個提出的搬移計劃是否較好，是以『提出的分佈』和『過去的 metrics』來決定分數。

這部分會衍生出一些物理意義上的問題，過去的 metrics 是源自『當前的分佈』，將未來提出的分佈和與他無關的過去 metrics 黏起來打一個分數好像不太對勁，畢竟這些過去的 metrics 不是在我們提出的分佈下量到的。

這邊打開這個 issue 追蹤這個問題

**Comment by chia7712** [comment]
這個議題統稱來說是要面對不一致的 cluster info 和 metrics，目前的解決手法是仰賴各個 cost 自行去處理兩者的不一致，通用的手法是 cost 需要自己去提供適當的統計方式，藉由統計來消除差異，並且比對兩者 (cluster and metrics) 的差異來選擇要繼續評估成本或是拋出例外 `NoSufficientMetricsException` 來中斷此次評估

綜合上述，現在關閉此議題
