### ISSUE TITLE
Current throughput of consumer gets zero

### ISSUE THREAD

**Issue by chia7712** [skiptests/astraea#323]
```
consumer completion rate: 99.60%
  average throughput: 33.442 MB/second
  current throughput: 0.000 Byte/second
  end-to-end max latency: 11204 ms
  end-to-end mim latency: 75 ms
  consumer[0] average throughput: 22.529 MB
  consumer[0] average ene-to-end latency: 5721.148 ms
  consumer[1] average throughput: 10.913 MB
  consumer[1] average ene-to-end latency: 5147.574 ms

```

重現方式就是開兩個consumers拉資料，過程中的`current throughput`的數據常常為0，直到最後一刻才會出現非整數

**Comment by chinghongfang** [comment]
起因是 #318 ，我們的consumer 會在 "取得一定數量" 或 "時間到" 才會回傳資料。

[這裡](https://github.com/skiptests/astraea/pull/318/files#diff-a2548b027cd37fab3f90d7d0af614d8df8676b535e73b5c5268e0289bbbbf3f5R11-R21) 我們預設是盡量累積record，所以外層才會等到10秒到了，才做紀錄。而實際上，consumer已經拿到資料，只是囤積著還沒給出來。

有2個解決方法
1. 在外層把timeout 調低
2. 在外層指定`recordCount`為1

我傾向2. 在外層指定`recordCount`為1，和過去的執行方式會比較像。

**Comment by chia7712** [comment]
> 我傾向2. 在外層指定recordCount為1，和過去的執行方式會比較像。

既然原因是發生在`poll(Duration timeout)`這個方法的“怪異行為”，那麼只修正performance tool的話，那其他元件用到該方法的一樣會踩到該怪異現象，因此一個比較治根的做法應該是去修正`poll(Duration timeout)`才對，也就是它的邏輯應該是要在以下條件任何一個完成時返回：
1. duration終止
2. 拿到任何資料一筆資料

**Comment by chinghongfang** [comment]
問題在 #357 已解決。
