### ISSUE TITLE
撰寫 Web API 中文文件

### ISSUE THREAD

**Issue by brandboat** [skiptests/astraea#358]
文件將會是全中文，格式為 markdown

## Web API list
- /topics
- /groups
- /brokers
- /producers
- /quotas

**Comment by brandboat** [comment]
ping @chia7712 , I will take over this issue, many thanks~

**Comment by chia7712** [comment]
@brandboat 感謝幫忙，可否在根目錄下開一個資料夾docs然後把這些文件進去，然後把超連結在放到根目錄的readme?

**Comment by brandboat** [comment]
> @brandboat 感謝幫忙，可否在根目錄下開一個資料夾docs然後把這些文件進去，然後把超連結在放到根目錄的readme?

收到

**Comment by brandboat** [comment]
想確認一下有關所有 api 都需要補上 kafka 原生的 config 嗎？(如果是的話，我需要對齊哪個 kafka 版本呢？) 
還是只需列出我們有重新封裝過的 config name ？

以 POST /topics 為例，裡頭我們有重新封裝的 config， `name`, `partitions`, `replicas` 。但 user 也可以指定 `max.message.bytes` 這類的 kafka config，我有需要也將這類 config 一並列出嗎？

**Comment by chia7712** [comment]
> 想確認一下有關所有 api 都需要補上 kafka 原生的 config 嗎？(如果是的話，我需要對齊哪個 kafka 版本呢？)

主要是介紹restful apis怎麼用，所以重點不是列出所有configs，以建立topic來說，文件只要介紹說用restful apis可以用來建立topic，然後用幾個常用的參數來當例子這樣就行了
