### ISSUE TITLE
Topic 資料讀取 Web APIs

### ISSUE THREAD

**Issue by brandboat** [skiptests/astraea#360]
實作 `org.astraea.consumer.Consumer` Web API. 並撰寫中文文件

- API 名稱 -> 未定
- HTTP Method
  - GET
    - query arguments (待定，列舉目前在 Consumer 看到的 config)
      - topics (required)
      - timeOut (required)
      - distanceFromLatest (optional)
      - groupId (optional)
      - autoOffsetReset (optional, could be `earliest` or `latest`)
    - success Operation (待定)
      
  - POST (N/A)

**Comment by brandboat** [comment]
ping @chia7712 , 還有一些項目需要再確認，再請您撥冗協助，感恩

**Comment by chia7712** [comment]
> API 名稱 -> 未定

URL大概如下：
```
GET http://{hostname}:{port}/data/{topic}
```

Query的話要麻煩能支援幾種模式：

(下方說的offset是kafka資料的定位，每一個topic裡面的每一筆資料都會有一個唯一的offset，該值的大小代表資料在topic內的新舊也等於排序，offset越大代表資料越新）

1. 只撈最新的幾筆（這個會用到`distanceFromLatest`），例如總共有100筆，使用者可以只撈最新的3筆，注意，使用者不會知道總共有100筆
2. 從指定位置開始撈n筆（會用到`seek`，但這個還沒被封裝），例如使用者可以從offset=90開始撈3筆，也就是回傳90, 91, 92這三筆資料
3. 從最早的資料開始撈n筆（會用到`seek`），例如使用者可以從最早的資料撈5筆。注意，使用者不會知道最早的資料的offset
4. 上述三種模式都要支援指定partition (partition代表topic的某一段資料）

其他參數跟上述用途無關的都應該伺服器端自己產生，例如`groupId`代表要參與哪一個consumer group，但因為restful APIs是每次請求處理完就結束，不會有session的概念，因此伺服器端可以自己產生一個隨機值就好

**Comment by brandboat** [comment]
close this since https://github.com/skiptests/astraea/pull/405 merged
