### ISSUE TITLE
`ReplicaMigrator#moveTo(int leader, Set<Integer> follower)` 在處理有點規模的 topic 時會出錯

### ISSUE THREAD

**Issue by garyparrot** [skiptests/astraea#386]
`ReplicaMigrator#moveTo(int leader, Set<Integer> follower)` 這個函數的目標在進行特定 topic/partition 的 replica list 變更。目前函數的實作是

1. 進行 `AdminClient#alterPartitionReassignment` 開始搬移。
2. 等待上面的 RPC request 被接受
3. 進行 `AdminClient#electLeader` 開始更換 leader
4. 等待上面的 RPC request 被接受

上面的執行流程存在一個盲點，如果湊齊下面的條件

1. 第一步指定的 preferred leader 原本不在 replica list 內，需要複製資料過去新 preferred leader 的 broker
3. 資料複製需要執行一段時間，大概比第 1 到 3 步的 function call 還要久 （幾秒）

這時  `AdminClient#electLeader` 會觸發下面的錯誤

```
org.apache.kafka.common.errors.PreferredLeaderNotAvailableException: 
Failed to elect leader for partition whatever-0 under strategy PreferredReplicaPartitionLeaderElectionStrategy
```

這個錯誤的觸發原因是：preferred leader 因為還在進行資料複製還不在 in sync replica 集合內，目前 `electLeader` 不允許這種情況發生。

## 重現的步驟

1. 建立一個 1GB 大小的 topic/partition, replica 有兩個 replica 分別在 1001, 1002
2. 執行 
```java 
  @Test
  void testReplica() throws InterruptedException {
    try (Admin admin = Admin.of("192.168.0.4:12514")) {
      admin.migrator()
              .partition("whatever", 0)
              .moveTo(1003, Set.of(1002));
    }
  }

```

## 建議的修正

* 刪除 `moveTo(int, Set<Integer>)`
* 實作 `Admin#electLeader(Set<TopicPartition>)` ，讓上游應用自己決定何時觸發 leader election

**Comment by chia7712** [comment]
@garyparrot 感謝幫忙修復bug，你的見解是對的，我們不應該把兩個動作包在一起

>刪除 moveTo(int, Set<Integer>)
實作 Admin#electLeader(Set<TopicPartition>) ，讓上游應用自己決定何時觸發 leader election

這個概念很棒，期待PR
