### ISSUE TITLE
使用normalization介面修正cost function

### ISSUE THREAD

**Issue by wycccccc** [skiptests/astraea#387]
#382 有關cost function新需求的討論，需要引入不同的normalization方式來得到不同的BrokerCost Score。

有兩種改動的方式
1.在new一個物件的時候傳入對應的Normalization。
2.添加HasBrokerCost class中的brokerCost function參數，新增Normalization。

我認爲第二種更加靈活，傾向於改成這種模式。

**Comment by chia7712** [comment]
> 添加HasBrokerCost class中的brokerCost function參數，新增Normalization。

同意這個應該比較彈性，可否提供一下可能的用法？

**Comment by wycccccc** [comment]
#389 已完成該issue
