### ISSUE TITLE
比較kafka最新的partitioner速度

### ISSUE THREAD

**Issue by chia7712** [skiptests/astraea#390]
剛好趕上kafka新版的partitioner架構，我們應該比較一下在負載不平衡的狀況下是否依然有突出的表現

細節請看: https://cwiki.apache.org/confluence/display/KAFKA/KIP-794%3A+Strictly+Uniform+Sticky+Partitioner

**Comment by wycccccc** [comment]
我大致讀了一下文章，我認爲它確實會有所改善。

他想解決的問題在於，原先的sticky會在某些情況下，出現發往delay節點的partition的batct size過大的情況。因爲batch一直發不出去，sticky又一直往上粘導致這個batch變得很大（其他partition因爲linger.me=0所以發出去都是小小的）。本來該節點狀況就不好又一直給他塞的滿滿的batch，導致其負擔更大，最終變得惡性循環。
就像他舉的例子的數據結果，發往每個partition的batch數目都差不多，但是其中一個partition的每個batch的大小都很大，導致其實際收到的資料量是別人的好幾倍。

它的改進方式有兩個大方向
partitioner.adaptive.partitioning.enable=false在於每一個batch都發送相同的資料
partitioner.adaptive.partitioning.enable=ture（defalut）向delay較高的機器發送更少的資料

我認爲他的adaptive做法會相當直觀有效，如果在機器全部同質的前提下，producer delay與broker input保持反比，那麼應該會有不錯的效果，不過具體結果還是要等3.3.0測試之後。

**Comment by chia7712** [comment]
@wycccccc 感謝分享，可否試著條列一下優點、以及可能的缺點（用想像的也沒關係）

**Comment by wycccccc** [comment]
> 1. It's uniform, which is simple to implement and easy to understand.  Intuitively, this is what users expect.
> 2. It creates better batches, without adding linger latency on low production rate but switching to better batching on high production rate.
> 3. It adapts to higher latency brokers, using larger batches to push data, keeping throughput and data distribution uniform.
> 4. It's efficient (logic for selecting partitions doesn't require complex calculations).

這是他KIP自己寫的優點。
缺點的話下面是我的奇思妙香：
它是通過batch的延遲來判定關閉那些超過延遲且還未發送的batch，達到將資料丟給閒置的節點來提升效能。
因此會有兩個問題：
並不能確認丟給的閒置節點，是否適合再處理更多的資料。
延遲並不能真實的反映節點接收到的資料量，這可能導致資料的長期傾斜，在壓縮的情況下這一問題更加不可預測。

具體可能要看一下它的code是怎麼實現的，不過要稍微過段時間，最近還有一些畢業相關的問題要處理。。。

**Comment by chia7712** [comment]
> 具體可能要看一下它的code是怎麼實現的，不過要稍微過段時間，最近還有一些畢業相關的問題要處理。。。

ok，下一個議題是要量測一下它的效能，不過可能要給 @chinghongfang 接手

**Comment by chinghongfang** [comment]
目前Apache Kafka社群內的partitioner有3種，分別是
1. DefaultPartitioner (按照key值選)
2. UniformStickyPartitioner (在觸發`onNewBatch`前，都選同一個)
3. 新的partitioner (同2. 但新的batch **較容易** 開在 **較順暢** 的partition)

## Apache Kafka 新的partitioner 比較

依序按照以下順序實驗測試。

1. 按照KIP-794所描述的情境。比較 DefaultPartitioner 和 新partitioner。
2. 我們的情境 (topic 分佈不均)。觀察 新的partitioner 可否解決。

#### KIP-794 情境

他的情境是：
1. batch linger.ms 小
2. 叢集中有台機器延遲高

預期：
* UniformStickyPartitioner 會較容易把資料送到延遲高的那台。造成延遲提高。
* 新partitioner 會避開延遲高的那台。

實驗情境：
1. batch linger.ms=0
2. 3 brokers，其中一臺跑一隻無窮迴圈的程式，搶cpu資源。
3. 45 partitions, 1 replicas, record size 100000 bytes
這裡使用KIP 實驗的工具，kafka 自帶的 `bin/kafka-producer-perf-test.sh`來測試。

實驗結果：

UniformStickyPartitioner
average throughput: 110.27 MB/sec
average publish latency: **2.42 ms**

新partitioner
average throughput: 111.29 MB/sec
average publish latency: **1.31 ms**

(p.s. 在沒有搶cpu資源的情況下，兩者的 publish latency 大約都在 0.2ms)

新partitioner 確實有效降低 publish latency。

---

#### topic 分佈不均

實驗情境：
1. 3 brokers
2. 3 topics, 分別 60 partitions, 1 replicas
    (1). "test12": 30 partitions 分在 broker1，30 partitions 分在broker2
    (2). "test23": 30 partitions 分在 broker2，30 partitions 分在broker3
    (3). "test123": 20 partitions 分在 broker1，20 partitions 分在broker2，20 partitions 分在broker3
3. 3 台機器做produce/consume，分別是
    (1). 向 "test12" produce/consume
    (2). 向 "test23" produce/consume
    (3). 向 "test123" produce/consume
4. 3台 produce/consume 都是 record size 10KiB, 5 producer threads, 8 consumer threads

實驗結果：

![New_Default](https://user-images.githubusercontent.com/26920893/175538937-be41f029-d8c7-463f-8e28-f492b2b9dea6.png)

![Uniform](https://user-images.githubusercontent.com/26920893/175539009-0d573cc5-ce13-4fe1-b408-f7566a3491e8.png)

新Partitioner 和過去的其他Partitioner 一樣會有流量集中在broker2的情況。

**Comment by chinghongfang** [comment]
”流量於節點間分布不均“
把情境也描述進去的話，”partition 分布不均導致流量於節點間分布不均“
請問是要這樣的 一句話來解釋 嗎？

**Comment by chia7712** [comment]
> 請問是要這樣的 一句話來解釋 嗎？

我想知道說 為何這個新的partitioner一樣「無法應付」分佈不均勻的叢集？能不能用一句話來說明

**Comment by chinghongfang** [comment]
在找尋原因的時候發現先前的實驗並**沒有使用**到新的partitioner，所以上面的實驗將重新跑過。

要使用新的partitioner，有2個條件
1. producer config中，不可設定partitioner.class
2. record中不設定key 或 設定keys.ignore

[前面留言](https://github.com/skiptests/astraea/issues/390#issuecomment-1165549632)的實驗都要作廢

**Comment by chinghongfang** [comment]
#### topic 分佈不均

實驗情境：
1. 3 brokers
2. 3 topics, 分別 60 partitions, 1 replicas
    (1). "test12": 30 partitions 分在 broker1，30 partitions 分在broker2
    (2). "test23": 30 partitions 分在 broker2，30 partitions 分在broker3
    (3). "test123": 20 partitions 分在 broker1，20 partitions 分在broker2，20 partitions 分在broker3
3. 3 台機器做produce/consume，分別是
    (1). 向 "test12" produce/consume
    (2). 向 "test23" produce/consume
    (3). 向 "test123" produce/consume
4. 3台 produce/consume 都是 record size 10KiB, 5 producer threads, 8 consumer threads
5. producer全力發送資料25分鐘

實驗結果:

左邊的高峰是新的Partitioner，右邊的高峰是SmoothWeightRoundRobinDispatcher
![Log_size](https://user-images.githubusercontent.com/26920893/177041866-56a70f14-f77b-4a4d-b76a-2fceaaa0e51d.png)

上折線圖代表每秒log的增加量；下折線圖代表log現在有多大。

#### 觀察
* 新的 partitioner 可以解 topic 分佈不均的問題，儘管 broker 之間的輸入量還是有差距，但彼此間的距離還是拉進了許多。
* 我們的 partitioner 所有 broker 之間的輸入量差距較小，不過也沒有特別高的輸入量。
* 從下折線圖知道 log 的大小，也就是總輸入量，我們的總 throughput 略低一點。

一句話：新的 partitioner 會根據 queue 長度隨機選擇 partition，而 broker 堵塞會造成 queue 長度增加。

**Comment by chia7712** [comment]
> 從下折線圖知道 log 的大小，也就是總輸入量，我們的總 throughput 略低一點。

這個我看不太出來，下圖(all log size)要怎麼看出兩個partitioners的測試？

**Comment by chia7712** [comment]
另外延遲的部分有差異嗎？

**Comment by chinghongfang** [comment]
> 下圖(all log size)要怎麼看出兩個partitioners的測試？

其實下圖就是所有log的大小加總，所以斜線就是在打的過程(或 刪topic的過程)，平的就是打完了 沒有在打資料。
我看兩者的測試是看 平的那段 的高度，同樣25分鐘，新的 partitioner 產生的資料量比較多，現就會在比較高的位置。

**Comment by chia7712** [comment]
> 我們的 partitioner 所有 broker 之間的輸入量差距較小，不過也沒有特別高的輸入量。

這件事蠻有趣的，為何新的kafka partitioner產生的吞吐量差異比較大？

> 從下折線圖知道 log 的大小，也就是總輸入量，我們的總 throughput 略低一點。

why? 如果大家嘗試要避開“比較忙”的節點，為何smooth躲的技巧比較差？

**Comment by chinghongfang** [comment]
## 七月16日 實驗

調整producer/consumer thread的數量，因為發現原來5 producer threads, 10 consumer threads 時，consumer 消費來不及，end-to-end latency 會持續上升，無法看出穩定的曲線。因此調整成使用4 producer threads, 10 consumer threads。

實驗環境：
1. 3 brokers {172, 173, 174}, zookeeper {172}
    172's kafka server version: 2.8.0 (Commit:ebb1d6e21cc92130)
    173's kafka server version: 2.8.0 (Commit:ebb1d6e21cc92130)
    174's kafka server version: 2.8.0 (Commit:ebb1d6e21cc92130)
2. 3 topics, 分別 60 partitions, 1 replicas
    (1). "test12": 30 partitions 分在 broker1，30 partitions 分在broker2
    (2). "test23": 30 partitions 分在 broker2，30 partitions 分在broker3
    (3). "test123": 20 partitions 分在 broker1，20 partitions 分在broker2，20 partitions 分在broker3
3. 3 台機器做produce/consume，分別是
    (1). 向 "test12" produce/consume
    (2). 向 "test23" produce/consume
    (3). 向 "test123" produce/consume
4. 3台 produce/consume 都是 record size 10KiB, **4 producer threads, 10 consumer threads**
5. producer全力發送資料25分鐘

**Astraea version: merge request443 and request479**
(因為SWRR需要 PR-443 才完整，所以先合併來做實驗)

實驗結果：

![2022-07-18_15-43](https://user-images.githubusercontent.com/26920893/179473483-80527b57-f438-46d0-b49c-7e71ca480e48.png)

左圖是server端 log 大小的增長速率，右圖也是，但右圖是疊加圖，方便拿來看加總值。
可以看出左邊SWRR的 Log size 增加速率較右側 Default Partitioner 平衡。
從疊加圖可以看出 SWRR 的總增長速率大部分時間大於 Default Partitioner。

---

SWRR Latency
![SWRR Latency](https://user-images.githubusercontent.com/26920893/179474831-d77d0a6a-f2e6-43ca-a6e7-5fa3695d93d5.png)

publish 延遲都在200毫秒以內。
端到端延遲都在100~150毫秒以內。

---

Default Partitioner Latency
![Default Partitioner Latency](https://user-images.githubusercontent.com/26920893/179474965-2735e4ad-c211-4fa5-ae3e-0e4436250268.png)

一個producer 的 publish 延遲在200\~300毫秒之間，其餘都在200毫秒以內。
端到端延遲從 30毫秒\~1000+毫秒。

**Comment by chinghongfang** [comment]
> 請問這個實驗的目的

是定期的實驗。另外，回覆上面 [留言](https://github.com/skiptests/astraea/issues/390#issuecomment-1173101299) 對延遲的問題。

> 3. 端到端延遲從 30毫秒~1000+毫秒。

現在只有想到一個原因：其中一個broker過於忙碌，因此回應速度慢。
但無法肯定就是這個原因。或許可以看看各個 consumer 被分配到的 partition，看是否 "被分配到較多 broker2 partition 的 consumer，會有較高的延遲"。

> 請問總平均增加幾%？

總平均增加 10.7%

> 跟之前實驗相比有改變嗎？

之前是跟 Built In Partitioner 比較

> 另外我看上次的提問還沒被答覆，要麻煩試著回答（解釋數據）。
"為何新的kafka partitioner產生的吞吐量差異比較大？"
"why? 如果大家嘗試要避開“比較忙”的節點，為何smooth躲的技巧比較差？"

確實需要解釋，我會再想想(/找找)原因。

**Comment by chia7712** [comment]
> 但無法肯定就是這個原因。或許可以看看各個 consumer 被分配到的 partition，看是否 "被分配到較多 broker2 partition 的 consumer，會有較高的延遲"。

這需要另外捕捉consumer的訂閱分佈，和資料拉取的狀況，如果現在沒時間弄，可否先討論只看producer的時候，資料寫入的延遲狀況？

> 之前是跟 Built In Partitioner 比較

定期的部分建議要納入這個這，另外strict dispatcher也需要測試

也麻煩在描述中整理測試結果

**Comment by chinghongfang** [comment]
# 八月16日 實驗

### 實驗環境：
1. 1 zookeeper {185}, 3 brokers {185, 187, 174}
  172's kafka server version: 3.2.1
  173's kafka server version: 3.2.1
  174's kafka server version: 3.2.1
3. 1 topic: 60 partitions
4. 1 台機器做 produce/consume
5. 網路拓樸如下（發送端 "較靠近" 其中一台broker）
6. producer 輸出流量限制在 500MiB/sec
7. 4 producers, 10 consumers, 10KiB record, throttle throughput 500MiB
(3 brokers, 1 client(C1), 2 brokers(B1, B2) in the same rack, 1 broker(B3) in different rack)
```
           (5G)
      ┌─────────────┐
 switch(10G)   switch(10G)
   ┌──┴───┐      ┌──┴───┐
   B1     B2     B3     C1
```
**Astraea version: request587**

---

### 實驗結果

![Screenshot from 2022-08-18 10-06-17](https://user-images.githubusercontent.com/26920893/185281626-b0aee359-8472-4f39-95b0-0d7b3d241f09.png)

4個 producer 的平均 latency 的平均分別是 118.008ms 和 124.228，平均的平均雖然不夠準確(因為每個producer的produce 數量不一定一樣)，但目前沒有紀錄整體的平均延遲，所以先如此粗略的計算，Strict Cost Partitioner 略輸一點。Strict Cost Partitioner 確實有將資料都發送到離自己較近的那台機器上，但都只會發送到同一個 partition 上，所以會導致 consumer 來不及消費，也不確定是不是這個原因讓我們的延遲沒有明顯的比預設 partitioner 好，將再實驗試試。

**Comment by chia7712** [comment]
> 但都只會發送到同一個 partition 上

應該不會都放到同一個partition吧？應該是分佈在不同節點，只是有多有少的問題。如果都集中在同一個節點上，那就是bug

**Comment by chinghongfang** [comment]
> 應該不會都放到同一個partition吧？應該是分佈在不同節點，只是有多有少的問題。如果都集中在同一個節點上，那就是bug

確實不應該都放到同一個 partition 上，不過從consumer 的消費來看 確實只有一個consumer在消費，我再看看哪裡出bug了。

**Comment by chinghongfang** [comment]
# 八月19日實驗

### 實驗環境：
1. 1 zookeeper {185}, 3 brokers {185, 186, 187, 188, 189, 176}
  kafka server version: 3.2.1
3. 1 topic: 30 partitions
4. 1 台機器做 produce
7. 4 producers, 0 consumers, 10KiB record
(6 brokers, 1 client(C1)
```
                    switch
            (1G)       │       (1G)
      ┌────────────────┴─────────────────┐
 switch(10G)                        switch(10G)
   ┌──┴──┬─────┬─────┬─────┬─────┐       │
   B1    B2    B3    B4    B5    C1      B6
```
**Astraea version: request599**

### 實驗結果

StrictCostPartitioner
![Screenshot from 2022-08-19 14-32-35](https://user-images.githubusercontent.com/26920893/185563937-037d7b9f-8ee5-4a06-9dc9-693e4b6eb87e.png)

Kafka default partitioner
![Screenshot from 2022-08-19 15-05-08](https://user-images.githubusercontent.com/26920893/185563978-a422f876-4a7e-444b-a423-53e52bf5421a.png)

1. Max Latency 是有進步的，但是平均延遲卻比較高，從client 端的 jmx 來看 producer-node-metrics request-avg-latency ，較遠的那台(B6)延遲沒有比較高。
2. 雖然 C1 到 B6 只有 1Gbps ，但資料似乎沒有堆積，延遲**沒有**線性增長，仍需進行測試。

**Comment by chia7712** [comment]
> 雖然 C1 到 B6 只有 1Gbps ，但資料似乎沒有堆積，延遲沒有線性增長，仍需進行測試。

從吞吐量來看，應該是沒有用盡頻寬。可以拿掉兩個好的broker試試看

**Comment by chinghongfang** [comment]
# 八月19日實驗

### 實驗環境：
1. 1 zookeeper {185}, 3 brokers {185, 186, 187, 188, 189, 176}
  kafka server version: 3.2.1
3. 1 topic: 30 partitions
4. 1 台機器做 produce
7. 4 producers, 0 consumers, 10KiB record
(4 brokers(B1~B3, B6), 1 client(C1))
```
               switch
            (1G)  │   
      ┌───────────┴────────┐
 switch(10G)          switch(10G)
   ┌──┴──┬─────┬─────┐     │   
   B1    B2    B3    C1    B6
```
**Astraea version: request599**

### 實驗結果

StrictCostPartitioner
<img width="559" alt="截圖 2022-08-20 上午12 01 55" src="https://user-images.githubusercontent.com/26920893/185661681-3ffd0632-4768-470e-bb36-12014c00904b.png">

Kafka default partitioner
<img width="559" alt="截圖 2022-08-20 上午12 15 01" src="https://user-images.githubusercontent.com/26920893/185662262-9d36787a-f47b-4845-9bbf-cc348e6b84ac.png">


**Strict Cost Partitioner 平均延遲 174 ms
Kafka Default Partitioner 平均延遲 249 ms**
延遲降低30%左右

延遲有變好很多，且確定default partitioner 的吞吐量有受到限制，被較遠的機器的網路頻寬所限制。但Kafka default partitioner 並沒有如我所預期的 "延遲呈線性成長"( 原本認為堵塞的訊息會越來越多，所以延遲會"快速"變高)。

**Comment by chia7712** [comment]
> "延遲呈線性成長"( 原本認為堵塞的訊息會越來越多，所以延遲會"快速"變高)。

延遲的計算是從“request"建立後到"response"回來，所以有可能是一直堆積導致記憶體無法清掉，因此連request都無法產生，所以延遲也不會無限延伸

**Comment by chia7712** [comment]
@chinghongfang 可否用這個環境再測試久一點，另外也依照這份數據先試著寫一個報告並發出PR

**Comment by chia7712** [comment]
後續由 #1265 繼續
