### ISSUE TITLE
支援建立不同參數的 embedded cluster 

### ISSUE THREAD

**Issue by garyparrot** [skiptests/astraea#391]
Context: https://github.com/skiptests/astraea/pull/388#discussion_r889496058

要提供一個機制來讓那些特殊的測試可以使用不同的參數來建置embedded cluster
直接給 `Services#brokerCluster` 添加參數，累積下去難保有一天不會彼此打架

**Comment by chia7712** [comment]
我來接手這個題目，分成兩個階段：

1. 新增一個`Service`用來提供所有內嵌的服物，並暴露常用的方法出來
2. 逐一不同模組替換掉目前使用的`RequireXX`，統一所有測試的呼叫方式
