### ISSUE TITLE
Topic 資料寫入 Web APIs

### ISSUE THREAD

**Issue by brandboat** [skiptests/astraea#397]
實作 astraea Producer Web API. 並撰寫中文文件

**Comment by brandboat** [comment]
ping @chia7712 , 有關實作細節需要再補充，再請您撥冗協助，感恩

**Comment by chia7712** [comment]
資料性別的部分：
考量我們是用json 格式，或許可以先支援json認可的type就好，例如字串和數字，另外也應該要可以支援json這個格式，不過我們目前還沒實作json serializer/deserializer，因此可以留到後面再來處理

request body的格式：
可以把Kafka record會用到的欄位放上去，包含：
Key
Value
Timestamp
Topic
Partition
上述除了topic以外都是選填，但key and value不能都為空

**Comment by brandboat** [comment]
有關 restful api url，請問用以下 url 實作嗎？

```
POST http://{hostname}:{port}/data/{topic}
```

**Comment by chia7712** [comment]
> POST http://{hostname}:{port}/data/{topic}

可否將`data`這個字換成`record`?
