### ISSUE TITLE
Web API 資料讀取 / 寫入格式

### ISSUE THREAD

**Issue by brandboat** [skiptests/astraea#398]
由於 kafka producer / consumer 都是用 byte array 作為讀取 / 寫入的型別。需要討論一下我們在 web api 要如何支援以及回傳上面要做怎樣的處理。

related to https://github.com/skiptests/astraea/issues/397
related to https://github.com/skiptests/astraea/issues/360

**Comment by brandboat** [comment]
ping @chia7712 , 有關 topic 讀取 api，我有一個粗淺的想法，直覺的把byte array 用 base64 encode to string 顯示給客戶端，不知道有沒有其他的意見呢？

**Comment by chia7712** [comment]
> 直覺的把byte array 用 base64 encode to string 顯示給客戶端

這可以當作預設行為，也就是在資料查詢的時候讓使用者可以輸入要用什麼「deserializer」來解析資料，如果使用者沒選擇，就照你說的把bytes印出來

至於一開始要能支援的格式就選我們現在有支援的Deserializer就行

你覺得如何？

**Comment by brandboat** [comment]
收到，topic 讀取 api 的部分要能支援不同的 deserializer 
那我就以以下 api 作為範本進行實作可以嗎？

GET /data/{topic}?keyDesearializer=[byteArray|string|integer|long|float|double]&valueDeserializer=[byteArray|string|integer|long|float|double]

user 可以分別指定 key / value deserializer，deserializer 目前支援 byteArray, string, integer, long, float, double 這幾種模式

不填寫預設就通通是 byteArray

**Comment by chia7712** [comment]
> 那我就以以下 api 作為範本進行實作可以嗎？

是的，就先以這些型別作為目標，感謝

**Comment by brandboat** [comment]
close this since #397 and #360 merged
