### ISSUE TITLE
移除 `ClusterLogAllocation` 內的 TODOs

### ISSUE THREAD

**Issue by garyparrot** [skiptests/astraea#433]
先前 https://github.com/skiptests/astraea/pull/415#discussion_r905268396 提到要用 `TopicPartitionReplica` 來取代指定 `TopicPartition topicPartition` 和 `int atBroker` 的 API 用法，為此添加了兩個 TODO:  `TODO: Revise the log argument by TopicPartitionReplica, once #411 is merged `

https://github.com/skiptests/astraea/blob/7093ba91513165a850d066dd3e10e2b3a75d480a/app/src/main/java/org/astraea/app/balancer/log/ClusterLogAllocation.java#L30-L54

我改到一半的時候發現這樣用起來會有點彆扭，我感覺原因如下：

## `TopicPartitionReplica` 物件不容易在 `ClusterLogAllocation` 物件附近出現

目標函數 `ClusterLogAllocation#migrateReplica` 多半是在 `RebalancePlanGenerator` 內被使用，而 RebalancePlanGenerator 想要知道有哪些 log 能夠做動作，多半是從 [`ClusterLogAllocation#topicPartitionStream`](https://github.com/skiptests/astraea/blob/7093ba91513165a850d066dd3e10e2b3a75d480a/app/src/main/java/org/astraea/app/balancer/log/ClusterLogAllocation.java#L63) 中得知，而其回傳形態是 `TopicPartition` 而非 `TopicPartitoinReplica`，如果該 API `ClusterLogAllocation#migrateReplica(TopicPartiiton, int, int)` 被改為 `ClusterLogAllocation#migrateReplica(TopicPartiitonReplica, int)` ，那麼每次在使用上都必須要手動包一個新的 `TopicPartitionReplica` 物件，因為手邊沒有這種物件`。

## `ClusterLogAllocation` 也不適合使用 `TopicPartitionReplica`

上面第一點中，這個多一個步驟的感覺主要來自 `ClusterLogAllocation` 本身沒有在用 `TopicPartitionReplica` 的關係。而 `ClusterLogAllocation` 不適合用 `TopicPartitionReplica` 的原因是因為我們要追蹤每個 Log 放在哪個 Data Directory，還有誰是 Preferred leader，這兩個因素沒有考量在 `TopicPartitionReplica` 內，對此我們記錄時是用 `Map<TopicPartition, List<LogPlacement>` 來表示，這個標示方法以足以應付需求，如果套用 `TopicPartitionReplica` 的話可能會看起來很奇怪。

## 如果使用者真的從某處取得 `TopicPartitionReplica`

如果今天 `ClusterLogAllocation`  的使用者真的從某個地方拿到了 `TopicPartitoinReplica`，以現有的做法可能用起來不雅觀：

```java
TopicPartitoinReplica log = getLog();
clusterLogAllocation.migrateReplica(new TopicPartition(log.topic(), log.partition()), log.brokerId(), toBroker);
```

但只要我們實作  `TopicPartitionReplica#topicPartition()` 的話，看起來會比較正常

```java
public class TopicPartitionReplica {
  // ...
  TopicPartition topicPartition() {
    return new TopicPartition(topic(), partition());
  }
  // ...
}
```

```java
TopicPartitoinReplica log = getLog();
clusterLogAllocation.migrateReplica(log.topicPartition(), log.brokerId(), toBroker);
```

但反觀有 `TopicPartition` 的使用者，想要用 `TopicPartitionReplica` 版本的 API 會比較麻煩：

```java
TopicPartition tp = getTopicPartition();
clusterLogAllocation.migrateReplica(new TopicPartitoinReplica(tp.topic(), tp.partition(), atBroker), toBroker);
```

可能有人會說我們也能讓 `TopicPartition` 新增一個函數變成 `TopicPartitionReplica`，但是這樣有點奇怪，因為訊息變豐富了，反而要檢討為何不是一開始就得到 `TopicPartitionReplica`。

## 總結

1. `TopicPartitionReplica` 物件不容易在 `ClusterLogAllocation` 物件附近出現
2. `ClusterLogAllocation` 也不適合使用 `TopicPartitionReplica`
3.  如果使用者真的從某處取得 `TopicPartitionReplica`，我們有優雅的解決方案

所以我覺得應該

1. [移除那兩個 TODO](https://github.com/skiptests/astraea/blob/7093ba91513165a850d066dd3e10e2b3a75d480a/app/src/main/java/org/astraea/app/balancer/log/ClusterLogAllocation.java#L30-L54), 沿用 `migrateReplica(TopicPartition, int, int)` 這個簽名
2. 新增 `TopicPartitionReplica#topicPartition()`

**Comment by garyparrot** [comment]
@chia7712 能否撥空看看這個想法如何，如果沒問題的話我在開 PR 修改，謝謝

**Comment by garyparrot** [comment]
> ClusterLogAllocation#topicPartitionStream 這個方法回傳的顆粒度是 partition 而不是 replica，請問這是為什麼？我直覺在balancer的世界中，應該看事情的角度是 replica，因為那個才是真的要做“處理”的對象

1. 當初會這樣寫是因為當時不存在 `TopicPartitionReplica`，然後底下的儲存 map 是以 TopicPartition 對應 Replicas（考量 Replicas 數量通常不大，弄成 list 在做線性搜尋時通常大家也都能接受，一方面避免 map key 大小爆炸，同時 replica list 第一位能反映誰是 preferred leader，還有到時對接 AdminClient API 比較順，所以用 map 存），如果這邊要弄成 `topicPartitionReplicaStream` 或是 `logStream` 也行，但是誰會這樣用(見下點2)。
2. 通常碰 replica list 之前，使用者會在意整個 replica list 的狀況，比如要把某個 replica 從 A broker 換到 B broker，你會需要擔心 B 會不會已經在 replica list 內，對此會需要整個 replica list 的狀況，只單純撈一個 TopicPartiitonReplica 的情境反而沒有

> 同上，ClusterLogAllocation#logPlacements這個方法使用的顆粒度也是partition，所以會回傳陣列表達“所有的replicas"，但直覺應該是先有一個 replica 對應 一個 LogPlacement，然後再用該方法來實作 一個partition 對應 多個 LogPlacement

如點 2 在做搬移時我們應該在意整個 replica list 而非單獨的 replica，我們應該把 replica list 當做整體來操作。

**Comment by garyparrot** [comment]
> 如點 2 在做搬移時我們應該在意整個 replica list 而非單獨的 replica，我們應該把 replica list 當做整體來操作。

不過這部分有點尷尬，看上面的說法，改變 placement 應該設計成 `alterReplicaList(TopicPartition, List<LogPlacement>)。不過現在改變的 API 是 `migrateReplica(TopicPartition, int, int)` 比較有單獨一個 replica 改變的味道

**Comment by garyparrot** [comment]
這邊還可以再寫一些東西，當初會出現 `ClusterLogAllocation` 的一些原因

1. `ReplicaInfo` 表達過多資訊，超出搬移的範圍，不能直接使用
2. `Map<TopicPartition, List<LogPlacement>` 太過原生，可能會發生使用者不小心改變 replica factor 的問題。
3. `ClusterLogAllocation`，內建一些檢查避免使用者誤操作，改變 replica factor 或是其他問題。

後來為了讓使用者用起來比較順手，跑出來 `migrateReplica` 和 `changeLeader` 這類的 method

**Comment by chia7712** [comment]
> 通常碰 replica list 之前，使用者會在意整個 replica list 的狀況，比如要把某個 replica 從 A broker 換到 B broker，你會需要擔心 B 會不會已經在 replica list 內，對此會需要整個 replica list 的狀況，只單純撈一個 TopicPartiitonReplica 的情境反而沒有

這個理由我覺得不錯，可是目前`ClusterLogAllocation#migrateReplica`這個方法似乎剛好就有你擔憂的事情？

> 不過這部分有點尷尬，看上面的說法，改變 placement 應該設計成 alterReplicaList(TopicPartition, List<LogPlacement>)。不過現在改變的 API 是 migrateReplica(TopicPartition, int, int)` 比較有單獨一個 replica 改變的味道

同意（也同上）


> Map<TopicPartition, List<LogPlacement> 太過原生，可能會發生使用者不小心改變 replica factor 的問題

這個改變對kafka是合法的，但對balancer是不合法的嗎？是暗示目前搬移策略中“並不考慮新增或刪除replicas"嗎？

> ClusterLogAllocation，內建一些檢查避免使用者誤操作，改變 replica factor 或是其他問題。

同上

---

我現在“直覺"`ClusterLogAllocation#migrateReplica` 這個介面的設計立意良善，不過在使用上會有一些矛盾的行為，例如能不能支援“移除”、to和from一樣的話會怎樣。另一方面，`ClusterLogAllocation `的視角究竟要以replica來看，還是partition來看似乎有些不一致，尤其在我們現在有`TopicPartitionReplica`後，有些方法似乎可以再簡化參數，例如`ClusterLogAllocation#letReplicaBecomeLeader`

**Comment by garyparrot** [comment]
抱歉，我忘了這個 Issue 的存在

>>> ClusterLogAllocation#topicPartitionStream 這個方法回傳的顆粒度是 partition 而不是 replica，請問這是為什麼？我直覺在balancer的世界中，應該看事情的角度是 replica，因為那個才是真的要做“處理”的對象
>>>
>> 通常碰 replica list 之前，使用者會在意整個 replica list 的狀況，比如要把某個 replica 從 A broker 換到 B broker，你會需要擔心 B 會不會已經在 replica list 內，對此會需要整個 replica list 的狀況，只單純撈一個 TopicPartiitonReplica 的情境反而沒有
>>
> 這個理由我覺得不錯，可是目前ClusterLogAllocation#migrateReplica這個方法似乎剛好就有你擔憂的事情？
>
>>不過這部分有點尷尬，看上面的說法，改變 placement 應該設計成 alterReplicaList(TopicPartition, List)。不過現在改變的 API 是 migrateReplica(TopicPartition, int, int)` 比較有單獨一個 replica 改變的味道
> 同意（也同上）

`ClusterLogAllocation#topicPartitionStream` 已經被移除，看起來是被 `Set<TopicPartition> topicPartitions()` 取代。

改成 `alterReplicaList(TopicPartition, List)` 會多一個副作用，現在 `Generator` 的實作者需要自己製造那個 `List`，給他們帶來一些額外的程式碼要處理。然後這樣做對確保使用者丟進來的 replica list 有沒有問題沒有幫助，這個 Generator 產生的 list 還是有可能有問題。我覺得傳入的資訊不正確這件事情有點難從程式碼這邊防禦，因爲 replica list 需要 `list 內容有 order` 和 `list 內容不重複`，這個特性有點 Set 非 Set 又 List 非 List，我想不到 API 怎麽設計可以看起來避免問題 & 自然不複雜。

現在粒度比較低的做法 `migrateReplica(TopicPartition, int, int)` 至少不會需要使用者製造 replica list，某種程度上使用起來比較簡單。

> 這個改變對kafka是合法的，但對balancer是不合法的嗎？是暗示目前搬移策略中“並不考慮新增或刪除replicas"嗎？

要讓 balancer 支援新增/刪除 replicas 也行，但是我現階段沒打算讓問題變得複雜，所以暫時不支援這些操作，等到要支援的時候可以再給 `ClusterLogAllocation` 添加對應的函數，支援變更 replica factor。

> ClusterLogAllocation 的視角究竟要以replica來看，還是partition來看似乎有些不一致，

如同先前說的，我感覺選擇後者會讓使用者的程式碼變複雜。

> 尤其在我們現在有TopicPartitionReplica後，有些方法似乎可以再簡化參數，例如ClusterLogAllocation#letReplicaBecomeLeader

但在簡化之前可能要先解決 `ClusterLogAllocation` 內不容易拿到 `TopicPartitionReplica` 的問題，不然 API 修改過去之後，用起來會很尷尬。這個 Issue 就是在說因爲有這個問題所以別用 `TopicPartitionReplica`。
我有想到一個折衷的方法，讓 `LogPlacement` 可以回傳自己所屬於的 `TopicPartitionReplica`，或是直接用 `LogPlacement` 來當作修改的對象，這樣可以用起來比較自然又不尷尬。

```java
// move MyTopic-1-? to broker 2
var thePartition = TopicPartition.of("MyTopic", 1);
var theDestinationBroker = 2;
allocation.migrateReplica(allocation.logPlacements(thePartition)
    .stream()
    .filter(someCondition)
    .findFirst()
    .orElseThrow(), theDestinationBroker);
```

**Comment by chia7712** [comment]
> 但在簡化之前可能要先解決 ClusterLogAllocation 內不容易拿到 TopicPartitionReplica 的問題

這句的原因我有點忘了，現在`ClusterLogAllocation`裡面的資料結構是 `TopicPartition -> List<LogPlacement>`，因此要產生`TopicPartitionReplica`應該不是問題才對?

**Comment by garyparrot** [comment]
> 這句的原因我有點忘了，現在ClusterLogAllocation裡面的資料結構是 TopicPartition -> List<LogPlacement>，因此要產生TopicPartitionReplica應該不是問題才對?

產生不是問題，但我覺得外面用起來拿不太到 `TopicPartitionReplica`。
不過可能是我多心了，我會開一個 PR 把它改過去，如果你覺得不會用起來很尷尬的話就用 `TopicPartitionReplica`。或是說看有沒有其他改法。

**Comment by chia7712** [comment]
> 產生不是問題，但我覺得外面用起來拿不太到 TopicPartitionReplica。

或許這是一個好機會來重新審視這個東西 @qoo332001 你有想法嗎 我們在 https://github.com/skiptests/astraea/pull/434 好像有討論過？

如果不用`TopicPartitionReplica`的話，那作為輸入參數就會改成`TopicPartition + Broker id`?

**Comment by garyparrot** [comment]
> 如果不用TopicPartitionReplica的話，那作為輸入參數就會改成TopicPartition + Broker id?

後者的做法要傳兩個參數，那樣也不太雅觀，我覺得主要的問題是 `Map<TopicPartition, List<LogPlacement>>` 的資料結構導致設計變的不太對勁。

0. shuffle plan generator 想要對 `myTopicPartition` 的 replica list 做修改
1. shuffle plan generator 呼叫 `ClusterLogAllocation#logPlacement(myTopicPartition)`, 取得 `List<LogPlacement>`
2. shuffle plan generator 想要修改 leader，發現手上只有 `TopicPartition myTopicPartition` 和 `List<LogPlacement>`，沒有 `TopicPartitionReplica`，所以自己手動透過現有的兩個變數組合出 `TopicPartitionReplica`，這個是我覺得尷尬的地方。

我覺得可以

* 現在: `LogPlacement` 是 `Broker Id`, `Optional<Data Dir>`
* 改成: `LogPlacement` 是 `Topic`, `Partition`, `Broker Id`, `Optional<Data Dir>`

把 `LogPlacement` 改成有所有資訊的物件，這樣 shuffle plan generator 在上面那個例子直接給 log placement 就能把它換成 leader

**Comment by chia7712** [comment]
我會比較傾向盡量重複使用資料結構，否則不斷進行的結構轉換會是之後很難改的負擔，例如，ClusterLogAllocation 能否以`Replica`作為資料結構呢？

**Comment by garyparrot** [comment]
> 現在data folder應該是篤定有值了吧?

我的記憶還停留在 https://github.com/skiptests/astraea/pull/415 ，這邊有一個用法是讓 data folder 能設 null，來表示要使用 kafka 的 implementation detail 來決定要放在哪個 data directory。實際上現在[程式碼還有一段真的會給他設 null](https://github.com/skiptests/astraea/blob/868d702eb252a53047c5ad59e531787ef9003b96/app/src/main/java/org/astraea/app/balancer/log/ClusterLogAllocation.java#L67-L78)，只是都沒有 Generator 用這個函數就是了。然後剛剛看了一下 executor 的實作，沒有針對這個部分做防禦，所以沒意外 executor 遇到這個 null 的時候應該是會噴錯的，算是一個從來沒有觸發的 bug。

> 例如，ClusterLogAllocation 能否以Replica作為資料結構呢？

Replica 的資訊太豐富了，如果要把 replica 換到別的 broker，insync, isFuture, offline 欄位可能會變成要填入沒有意義的值

**Comment by chia7712** [comment]
> Replica 的資訊太豐富了，如果要把 replica 換到別的 broker，insync, isFuture, offline 欄位可能會變成要填入沒有意義的值

我覺得這個是一定要處理的議題，因為無論是`ClusterCost` 或是 `MoveCost`都預期用 `Replica`來計算成本，就算在這個階段不用`Replica`改用簡單的資料結構，最後無論是輸出做呈現、或是計算成本都一樣要透過某個手法將某個簡單的資料結構轉回`Replica` (也就是`BalancerUtils#update`) 在做的事情

從現有的元件來看，`Shuffler`是有這個責任負責產生新的叢集分佈，所以我才會說是否要直接使用`Replica`，insync, isFuture, offline 這些欄位應該可以直接複製來源處 (如同`BalancerUtils#update`)

**Comment by garyparrot** [comment]
> 所以我才會說是否要直接使用Replica，insync, isFuture, offline 這些欄位應該可以直接複製來源處 (如同BalancerUtils#update)

我會開一個 PR，使用 `List<Replica>` 來取代 `List<LogPlacement>` 的用法

**Comment by chia7712** [comment]
> 我會開一個 PR，使用 List<Replica> 來取代 List<LogPlacement> 的用法

這邊可以先套套看，然後思考一下是否有更好的資料結構的用法，大方向有幾個：
1. 盡可能共用資料結構，否則隨著元件增加，資料結構之間的轉換會累積成技術債
2. 如果共用資料結構很有難度或是邏輯上很不合理，那我們再來討論是否要新增/結合中間某幾層的資料結構
3. 盡量避免出現`BalancerUtils#update`, `BalancerUtils#merge`這種在production端 mock/fake 資料的用法

**Comment by chia7712** [comment]
> 後者的做法要傳兩個參數，那樣也不太雅觀

提一個觀點，TopicPartitionReplica 這種物件的設計最初是作為回傳值給使用者方便辨識和使用（類似 Java optional)，如果要把它用在輸入參數的話，通常是為了該路徑上已經是可以直接取得 TopicPartitionReplica、又或者TopicPartitionReplica的建構過程需要先做參數檢查。反之，使用者必須先建構 TopicPartitionReplica 再傳入的話，這樣就顯得迂迴

**Comment by qoo332001** [comment]
> 我是可以接受把 TopicPartitionReplica移除，這樣也有空間來放可能需要的 新LogPlacement

@chia7712 請問把 TopicPartitionReplica移除的意思是從專案移除嗎，還是指ClusterLogAllocation這邊不要用，現在專案目前有很多地方都有用到`TopicPartitionReplica`，移除之後是要用什麼取代呢

**Comment by chia7712** [comment]
> 請問把 TopicPartitionReplica移除的意思是從專案移除嗎，還是指ClusterLogAllocation這邊不要用，現在專案目前有很多地方都有用到TopicPartitionReplica，移除之後是要用什麼取代呢

https://github.com/skiptests/astraea/issues/433#issuecomment-1255181296 先看我這邊描述的部分，重點是避免專案裡面出現一堆 POJO，然後在資料交換過程中還需要不斷的轉換，這也是之前在討論 ClusterCost and MoveCost 要選哪個資料結構一樣的出發點

所以我說移除的意思是 如果 @garyparrot 覺得有一種 POJO 可以取代 TopicPartitionReplica，那我覺得可以直接刪掉 TopicPartitionReplica 並用新的來取代

**Comment by qoo332001** [comment]
> 所以我說移除的意思是 如果 @garyparrot 覺得有一種 POJO 可以取代 TopicPartitionReplica，那我覺得可以直接刪掉 TopicPartitionReplica 並用新的來取代

好的了解了，那我現在先修 #434 ，到時後轉過去新的資料結構應該會比較容易，這樣可以嗎

**Comment by chia7712** [comment]
> 好的了解了，那我現在先修 https://github.com/skiptests/astraea/pull/434 ，到時後轉過去新的資料結構應該會比較容易，這樣可以嗎

現在還不確定是否要訂新的結構還是沿用舊的。如果要先進行 #434 的話，要先從原本討論的 `Admin#replicas`來看，是否有存在很尷尬的用法，也就是使用者其實是要直接使用"replica"而非看`partition"，然後導致使用者要另外重組資料結構，幾個例子：

1. https://github.com/skiptests/astraea/blob/main/app/src/main/java/org/astraea/app/performance/Performance.java#L310 這邊就重新組合了 replicas
2. https://github.com/skiptests/astraea/blob/main/app/src/main/java/org/astraea/app/balancer/executor/RebalanceAdminImpl.java#L149
3. https://github.com/skiptests/astraea/blob/main/common/src/main/java/org/astraea/common/admin/Builder.java#L337

如果類似上面的例子很多，那我們就值得將`Admin#replicas` 這個方法的回傳值改成`Map<TopicPartitionReplica, Replica>`，並且新增一個方法允許使用者用`TopicPartition`來事先過濾搜尋結果

**Comment by qoo332001** [comment]
> 如果類似上面的例子很多，那我們就值得將Admin#replicas 這個方法的回傳值改成Map<TopicPartitionReplica, Replica>，並且新增一個方法允許使用者用TopicPartition來事先過濾搜尋結果

我看了一輪，除了上面三個以外還找到這幾個直接拿到`Map<TopicPartitionReplica, Replica>`會比較好處理，適合拿到`TopicPartition`跟`TopicPartitionReplica`的大約各佔一半，或許可以兩種都保留?
1. https://github.com/skiptests/astraea/blob/main/common/src/main/java/org/astraea/common/admin/Builder.java#L538
2. https://github.com/skiptests/astraea/blob/main/common/src/main/java/org/astraea/common/admin/Builder.java#L645
3. https://github.com/skiptests/astraea/blob/main/common/src/main/java/org/astraea/common/admin/Builder.java#L664

**Comment by chia7712** [comment]
> 或許可以同時保留回傳Map<TopicPartitionReplica, Replica>跟 Map<TopicPartition, List<Replica>>的方法?

這個主意可以，可以用輸入的參數還決定是回傳哪種結構，例如：
```java

Map<TopicPartition, List<Replica>> replicas(Set<String> topics);
Map< TopicPartitionReplica, Replica > replicas(Set<TopicPartition> partitions);
```

**Comment by qoo332001** [comment]
@chia7712 我實做完成`Map< TopicPartitionReplica, Replica > replicas(Set<TopicPartition> partitions);`之後，發現當replica在做datafolder之間的搬移時，`admin.describeLogDirs()`撈回來的結果會在同一個broker中找到兩個相同的replica在不同的datafolder，導致在這過程中若呼叫`replicas(Set<TopicPartition> partitions)` 會發生Duplicate key的問題，想請問回傳的型態要是否要改變成`Map< TopicPartitionReplica, List<Replica>>` ?，或是有更好表示方法呢

**Comment by qoo332001** [comment]
>可以看一下我們專案裡是否很常用到 Map 的索引

剛剛看了一下，確實非常少用到Map的索引，拿到Map之後都會重新組合，那是要改成這樣嗎
`List<Replica> replicas(Set<String> topics);` 

如果是的話，我開支PR改界面之後把有用到的地方做一下整理

**Comment by chia7712** [comment]
> 如果是的話，我開支PR改界面之後把有用到的地方做一下整理

ok，如果改到太多東西的話，可以拆成兩段，先新增新版本的 APIs，然後下一隻再做取代
