### ISSUE TITLE
`ReplicaSyncingMonitor` doesn't support showing data directory migration progress

### ISSUE THREAD

**Issue by garyparrot** [skiptests/astraea#436]
As title

**Comment by chia7712** [comment]
我們正在往Web APIs前進的路上，我會建議把這個功能整合到Web Server會比較好

**Comment by garyparrot** [comment]
> 我們正在往Web APIs前進的路上，我會建議把這個功能整合到Web Server會比較好

所以有需要把這些獲得進度的部分弄成適合其他介面的形式嗎，可能 Web 或 Terminal

**Comment by garyparrot** [comment]
> 弄成Web APIs會比較好，這樣使用者才方便串接做更多下游應用
 
不然我弄成 Admin 可以多一個 API 回傳搬移的進度，渲染進度成可視文字的部分我會抽成一個模組，看有人要串 raw data 或是這個渲染成文字的結果，或是把這些東西用 Web API 暴露出去都可以，不過我只做 Terminal 的部分。

然後搬移進度的部分我要提醒一下，我感覺 data directory 之間的搬移看不到 size 的進度，似乎只能看到 offset 的進度，後面這種搬移的進度可能數字單位會不太一樣

**Comment by chia7712** [comment]
> 不然我弄成 Admin 可以多一個 API 回傳搬移的進度

這個也可以，不過要看會不會跟`admin#replicas`這隻的實作太過雷同

> 不過我只做 Terminal 的部分。

就專案的角度來看，我會希望我們跟客戶一起用相同的工具，這樣才能及時反應和修正、同時也不用維護太多功能重複的工具或程式碼。terminal很棒，我也喜歡，但要替那些需要串些上下游應用、以及看terminal會恐慌症發作的人著想

> 然後搬移進度的部分我要提醒一下，我感覺 data directory 之間的搬移看不到 size 的進度，似乎只能看到 offset 的進度

這倒是一個有趣的問題，或許我們可以統一用“offset"來算比例？

**Comment by chia7712** [comment]
close as it is traced by #595
