### ISSUE TITLE
Remove limit when polling records in RecordHandler#get

### ISSUE THREAD

**Issue by brandboat** [skiptests/astraea#441]
https://github.com/skiptests/astraea/pull/405#discussion_r909148039

RecordHandler#get 中會從 consumer.poll 撈取完資料後再將多餘的資料筆數給刪除，造成額外的效能負擔。

**Comment by brandboat** [comment]
這個議題主要是 Consumer#poll(recordCount, timeout)，在給定 recordCount 時有時會發生回傳資料筆數 > recordCount 的狀況，導致 RecordHandler 需要做進一步的資料刪除。目前看起來這個行為是正常的嗎？(因為 poll javadoc @param recordCount 意指 max number of returned records)，如果是的話，那麼這個議題有什麼建議的方向來處理嗎？

**Comment by chia7712** [comment]
> 這個議題主要是 Consumer#poll(recordCount, timeout)，在給定 recordCount 時有時會發生回傳資料筆數 > recordCount 的狀況，導致 RecordHandler 需要做進一步的資料刪除。目前看起來這個行為是預期的嗎？(因為 poll javadoc @param recordCount 意指 max number of returned records)，如果是的話，那麼這個議題有什麼建議的方向來處理嗎？

這裡的議題主要是當支持使用自訂group的時候，多撈到的資料該如何處理？複雜一點就是把auto commit移除，手動提交commit避免有資料遺失。或是簡單一點更動web apis 上的max行為，將其改成「建議值」的概念就好，就不去做強制只能幾筆

**Comment by brandboat** [comment]
經過私下討論，我會將 web api 中 limit 的行為改成建議值的概念，而非直接刪除多餘的資料。以避免後續支援 group id 時發生user指定相同 group id 時埋下重複拉取資料的隱憂。
