### ISSUE TITLE
為Performance tool新增kill consumer功能

### ISSUE THREAD

**Issue by harryteng9527** [skiptests/astraea#449]
https://github.com/skiptests/astraea/pull/445#discussion_r912035273

此處討論performance tool要在什麼時間點殺死consumer

因為performance tool的行為是開啟`producer`與`consumer`對指定的topic送、拉資料並印出throughput，在使用者設定的時間到達或是已傳送使用者設定的records數就結束performance tool的運行。

主要考量以下兩點
* 要殺幾個
* 哪個時間點要殺死consumer

我目前想到下列kill consumer的時機點
1. 以執行時間與consumer數量相除，以該時間為kill的頻率
e.g., --run.until 10m --conosumers 5 => 每兩分鐘kill一個
2. 使用者設置要殺死幾個consumer，performance tool執行期間隨機kill
e.g., --run.until 10m => 在10分鐘內隨機kill consumer，所以可能performance tool啟動沒多久consumer就被刪光光

**Comment by chia7712** [comment]
科普一下，這種行為有一個術語叫做chaos monkey

在我們performance的過程中能夠支援chaos monkey會是一個不錯的事情，因為可以測試在chaos發生時系統的吞吐量的表現，因此我想把這個議題拉高一個層次叫做 - 設計屬於performance tool的 chaos monkey

上面這個設計完成後，你就可以用你設計的框架來完成第一隻chaos monkey，也就是會隨機刪除/重啟 consumers

**Comment by chia7712** [comment]
@harryteng9527 有任何想法嗎？

**Comment by harryteng9527** [comment]
預計會實作
* 實作monkey thread作刪除/重啟consumer的任務，目前還在想重啟consumer要怎麼實作
* 為了紀錄rebalance time，要修改listener的界面，新增一個`onPartitionsRevoked` method

**Comment by chia7712** [comment]
請問後來實作的部分有推上來嗎？

**Comment by harryteng9527** [comment]
還沒，目前想先把 JCConf 搞定，再來趕緊把這功能補上

**Comment by chia7712** [comment]
@harryteng9527 這個議題是否可以關閉了？
