### ISSUE TITLE
Throttle issue in `Performance` tool.

### ISSUE THREAD

**Issue by garyparrot** [skiptests/astraea#458]
Performance Tool 內建的 `--throttle` 功能能夠限制傳輸資料量。不過從 Grafana 上的圖表中可看出 throttle 沒法輸出期望的資料量

![image](https://user-images.githubusercontent.com/39105714/177516053-70c94a76-6938-4dc6-8a85-a284799d8ed1.png)

上圖為 ``performance --producers 2 --consumers 4 --record.size 10KiB --partitions 13 --replicas 3 --run.until 256h --throughput 200MB`` 的結果，可以看到在 `$__interval` 長度的 average window 下，網路的輸出約在 114 MiB 到 134 MiB

![image](https://user-images.githubusercontent.com/39105714/177515696-90b8edd7-fcef-4685-afdb-69d86baade1e.png)

上圖的 average window 為 `2s` 可以看到單位時間最多能輸出到 `200MiB` 附近，但絕大多數時間沒辦法妥善維持在相同的輸出量。間接導致 average 過的輸出沒辦法維持在 throttle 的設定

雖然 throttle 的億思是不超過設定的限制，但是實際上會希望如果硬體能達成就儘量達到。

**Comment by chia7712** [comment]
@harryteng9527 可否協助確認現在的版本還會否有這個問題？

**Comment by harryteng9527** [comment]
> 可否協助確認現在的版本還會否有這個問題？

看起來是沒有這問題，我把實驗結果與方式放在下面：
### 指令
> performance --producers 2 --consumers 4 --record.size 10KiB --partitions 13 --replicas 3 --run.until 256h --throughput 200MB

因為 performance tool 的參數改變滿多的且現在 throttle 的方式有兩種，故根據上面提出的 performance tool 的參數，修改成下列兩種指令來測試
1. 利用 throughput 來限制流量
```=bash
./start_app.sh performance --bootstrap.servers 192.168.103.171:9092,192.168.103.172:9092 --topics a1,a2,a10 --producers 2 --consumers 4 --read.idle 15s --run.until 15m --value.size 10KiB --throughput 200MB/s
```
2. 利用 throttle 來限制流量
```=bash
./start_app.sh performance --bootstrap.servers 192.168.103.171:9092,192.168.103.172:9092 --topics a1,a2,a10 --producers 2 --consumers 4 --read.idle 15s --run.until 15m --value.size 10KiB --throttle a1-0:20MB/s,a2-0:20MB/s,a2-1:20MB/s,a10-0:20MB/s,a10-1:20MB/s,a10-2:20MB/s,a10-3:20MB/s,a10-4:20MB/s,a10-5:20MB/s,a10-6:20MB/s,a10-7:20MB/s,a10-8:20MB/s,a10-9:20MB/s
```
### Topic 與對應的 Partition 數量
| Topic | Partition 數量 | Replica 數 |
| ----- | -------------- | ---------- |
| a1    | 1              | 1          |
| a2    | 2              | 1          |
| a10   | 10             | 1          |

### Network transmit & Bytes in per Topic 
1. 利用 throughput 限制流量

使用 throughput 來限制流量的 network transmit 與 bytes in per topic ，網路的輸出大概在 200 MB/s 上下，如下圖

![image](https://user-images.githubusercontent.com/90374678/210220331-e2de2a11-5b12-4498-9d25-bd30cb1848a0.png)
送到 3 個 topic 的資料量也有限制在 200 MB/s 內
![image](https://user-images.githubusercontent.com/90374678/210219551-47b179bb-5242-4248-a103-74c4ab72a213.png)

2. 利用 throttle 限制流量

因為 throttle 的指令是 throttle 每個 partition 在 20 MB/s ，所以網路的輸出大概在 260 MB/s 上下，如下圖

![image](https://user-images.githubusercontent.com/90374678/210220205-17a7b119-648e-4fca-802a-8cd74bbdf609.png)

送到 topics 的資料量也有被限制住
![image](https://user-images.githubusercontent.com/90374678/210220246-5ff66ee8-b36f-4b15-a83f-67fe9c7d3dbc.png)

**Comment by chia7712** [comment]
@harryteng9527 感謝驗證，那關閉此議題
