### ISSUE TITLE
Find a way to cache transactional producer in RecordsHandler

### ISSUE THREAD

**Issue by brandboat** [skiptests/astraea#473]
https://github.com/skiptests/astraea/pull/464#discussion_r917259008

目前 RecordsHandler 若使用 transactionId，每次請求都會建立一新 producer，重複建立的成本很高，我們應該想一個方式快取 transactional producer

**Comment by brandboat** [comment]
ping @chia7712 , 我會開始著手處理這項議題，感謝

**Comment by chia7712** [comment]
@brandboat thanks for taking over this ticket. Could you share the solution with me?

**Comment by brandboat** [comment]
我想一個最簡單的方式是直接引入 guava cache，裡頭提供的 API 我想是我們需要的功能。不過引入後許多既有的 API 會跟 java 原生 API 有類似或者相同的功用，諸如 ImmutableList, ImmutableMap，以及 ListenableFuture 等，可能會造成開發者在使用上碰到選擇障礙，而且我想專案在一開始就沒有引入 guava 應該也有其他考量。

一個初步的想法是參考 guava cache https://github.com/google/guava/wiki/CachesExplained API 實作一個簡易的版本
透過以下語法建立 Cache
```
CacheBuilder.newBuilder()
  .maximumSize(long)
  .expireAfterAccess(Duration)
  .removalListener(RemovalListener)
  .build(
    new CacheLoader<Key, Value>() {
             @Override
             public Value load(Key key) throws AnyException {
               return createExpensiveValue(key);
             }
     })
```

透過 maximumSize 來控制 Transaction Producer cache 數量，並透過 expireAfterAccess 來確保 producer 再經過一段閒置時間被移除，並在移除時觸發 RemovalListener 來將 producer 正確關閉 (i.e. producer.close())。

**Comment by chia7712** [comment]
> 而且我想專案在一開始就沒有引入 guava 應該也有其他考量。

主要是guava實在太常見了，作為一個要發布出去二次開發的函式庫如果自帶特定版本的`guava`很容易遭遇到相容性的議題（例如客戶使用a版的guava、但我們使用b版的guava），因此一開始就不會引入。至於`GSON`因為很小所以碰撞的問題不大、`JCommander`目前沒聽過相容性的議題

> 一個初步的想法是參考 guava cache https://github.com/google/guava/wiki/CachesExplained API 實作一個簡易的版本
透過以下語法建立 Cache

這個方式聽起來不錯

**Comment by brandboat** [comment]
> 主要是guava實在太常見了，作為一個要發布出去二次開發的函式庫如果自帶特定版本的guava很容易遭遇到相容性的議題（例如客戶使用a版的guava、但我們使用b版的guava），因此一開始就不會引入。至於GSON因為很小所以碰撞的問題不大、JCommander目前沒聽過相容性的議題

感謝回覆，的確 guava 太常見了，開發 trino 的時候他們本身就引入 guava，再加上其他的 connectors 本身也很多都有 guava dependency 處理起來挺費功夫。

> 這個方式聽起來不錯

那我就按照這思路下去處理，感謝
