### ISSUE TITLE
Web APIs for `ReplicationThrottler`

### ISSUE THREAD

**Issue by garyparrot** [skiptests/astraea#480]
Context: https://github.com/skiptests/astraea/pull/478#pullrequestreview-1037721613

這個議題是關於 `RepliationThrottler` 的 Web API 實作

**Comment by chia7712** [comment]
@brandboat FYI

**Comment by garyparrot** [comment]
@chia7712 我接下來會處理這個議題，謝謝

**Comment by garyparrot** [comment]
## `ReplicationThrottler` HTTP API

目標提供

1. 套用 replication throttle
2. 取得當前 replication throttle

這兩種 API

## New API for `Admin`

目前 `Admin` 內只有套用 replication throttle 的 API，並沒有索取 `replication throttle` 當前設定的函數，對此應該先開另外一個 PR 新增下面這四種函數

```java
public interface ReplicationThrottler {
  public Map<Integer, DataRate> brokerIngress();
  public Map<Integer, DataRate> brokerEgress();
  public Set<TopicPartitionReplica> throttledLeaderLogs();
  public Set<TopicPartitionReplica> throttledFollowerLogs();
}
```

如果直接放在 `Admin` 裡面，函數名稱可能會便得很長(`Admin#replicationThrottleBrokerIngress`)，如果省去 `Replication` 或是 `Throttle` 可能會讓函數名稱看起來意義不明，對此我想把這四個函數放在 `ReplicationThrottler` 裡面。

## API endpoints

預計所有功能會實作在 `/throttles/replication` 這個 Path 底下，之所以要強調這個是 `replication` 專用的，是因為有其他 data directory 之間的 throttle，另外還有一個 KIP 是針對 [reassignment 的 throttle](https://cwiki.apache.org/confluence/display/KAFKA/KIP-542%3A+Partition+Reassignment+Throttling)（不過還沒被實作[，看起來似乎也沒有要實作的樣子？），考慮到有多種可能的 throttle 對象所以做成兩階段的 endpoint。

* `/throttles/replication/brokers`
  * `GET`, 取得 broker 被套用的限流量
    ```json
    {
      "1000": { "ingress": 1000000000, "egress": 1000000000 },
      "1001": { "ingress": 1000000000, "egress": 1000000000 },
      "1002": { "ingress": 1000000000, "egress": 1000000000 }
    }
    ```
  * `POST`, 套用節點的限流量 （這裡可能比較適合用 `PUT`?）
    ```json
    {
      "1000": { "ingress": 1000, "egress": 1000 }
    }
    ```
  * `DELETE`, 清除節點的限流量
    ```json
    [ "1000", "1001", "1002" ]
    ```
* `/throttles/replication/throttled-logs`
  * `GET` 取得目前所有 Topic 的 throttled log
    ```json
    {
        "MyTopicA": { 
            "leader": [ "1:3" ],
            "follower": [ "1:3" ]
        },
        "MyTopicB": { ... },
        "MyTopicC": { ... },
    }
    ```
  * `POST`, 因為 `ReplicationThrottler` 是用 `OpType.APPEND` 來新增要限流的對象，這裡的 method 可能用 `PATCH` 會比 `POST` 適合，不過看起來 `Handler` interface 只有實作 `GET`, `POST` 和 `DELETE` 三種方法，如果有需要可能要另外添加
    ```json
    {
        "MyTopicA": { 
            "leader": [ "1:3" ],
            "follower": [ "1:3" ]
        }
    }
    ```
  * `DELETE`，移除特定 topic/partition/replica 的資料，下面三個欄位都是 Optional，有提供才進行對應的操作
    ```json
    {
        "topic": [ "MyTopicA", "MyTopicB" ],
        "partitions": [ "MyTopicA-1", "MyTopicB-1" ],
        "replicas": [ "MyTopicA-1-1" ]
    }
    ```

@chia7712  你看看上面的設計如何，謝謝

**Comment by chia7712** [comment]
> New API for Admin

我們已經可以調閱topic/broker config，或許不用再放重複的APIs上去

>   public Map<Integer, DataRate> brokerIngress();
  public Map<Integer, DataRate> brokerEgress();
  public Set<TopicPartitionReplica> throttledLeaderLogs();
  public Set<TopicPartitionReplica> throttledFollowerLogs();

如果真的要放的話，我倒是覺得這幾個名稱已經很有識別性了，可以開一隻PR先來處理，或是直接把這幾個解析configs的動作放在Web APIs那邊就好

>  預計所有功能會實作在 /throttles/replication 這個 Path 底下

盡量維持扁平的設計（也是這個專案的精神 - 精美），我們可以從post的格式來選擇要處理怎樣的throttle

**Comment by garyparrot** [comment]
> 如果真的要放的話，我倒是覺得這幾個名稱已經很有識別性了，可以開一隻PR先來處理，或是直接把這幾個解析configs的動作放在Web APIs那邊就好

那我把解析的動作留給 Web API 處理就好

> 盡量維持扁平的設計（也是這個專案的精神 - 精美），我們可以從post的格式來選擇要處理怎樣的throttle

你是指 `/throttles&type=replication` 或是 JSON Payload 格式弄成 `{ "type: "replication", "config": { ... } }`

**Comment by chia7712** [comment]
> 你是指 /throttles&type=replication 或是 JSON Payload 格式弄成 { "type: "replication", "config": { ... } }

這兩個方法都不錯，我原本是想`POST`的格式差很多的話，就可以直接從post body來區分行為就好

**Comment by chia7712** [comment]
> 這兩個方法都不錯，我原本是想POST的格式差很多的話，就可以直接從post body來區分行為就好

誒更正，這兩個方法都有一些小問題，前面的話"type"會變成選項值，後面的話要多一個type有點多餘，可以的話從body內的東西來區分就好

**Comment by garyparrot** [comment]
那就弄成單一個 endpoint `/throttles`，然後 `POST` body 的格式可以是

#### 針對 replication throttle

```json
{
    "replication-throttle": {
        "brokers": {
            "1001": {"ingress": 1000, "egress": 1000},
            "1002": {"ingress": 1000, "egress": 1000},
            "1003": {"ingress": 1000, "egress": 1000}
        },
        "logs": {
            "MyTopicA": {
                "leader": [ "1:2", "2:3", "4:5" ],
                "follower": [ "1:2", "2:3", "4:5" ]
            },
            "MyTopicB": { ... },
            "MyTopicC": { ... }
        }
    }
}
```

#### 針對未來的 data directory migration throttle

```json
{
    "data-log-migration-throttle": {
        "brokers": {
            "1001": 1000,
            "1002": 1000,
            "1003": 1000,
        }
    }
}
```

### 更平的版本

或是要採用這種更平的版本，把第一階的 `data-log-migration-throttle` 或是 `replication-throttle` 給省了

```json
{
    "replication-throttle-broker-bandwidth": {
            "1001": {"ingress": 1000, "egress": 1000},
            "1002": {"ingress": 1000, "egress": 1000},
            "1003": {"ingress": 1000, "egress": 1000}
    },
    "replication-throttle-logs": {
        "MyTopicA": {
            "leader": [ "1:2", "2:3", "4:5" ],
            "follower": [ "1:2", "2:3", "4:5" ]
        }
    },
    "data-log-migration-throttle-bandwidth": {
        "1001": 1000,
        "1002": 1000,
        "1003": 1000,
    }
}
```

**Comment by chia7712** [comment]
我覺得更平的版本還不錯，該些項目應該都可以是選項值，有寫就設定，不過名稱可以再簡化一點，例如第一個key可以叫做broker就好，以及log 的項目可以合併進去，分別叫做ingress egress internal 之類的

**Comment by chia7712** [comment]
另外也要設計如何「取消」

**Comment by garyparrot** [comment]
## 設定

```json
{
    "brokers": {
        "1001": { "ingress": 1000, "egress": 1000, "internal": 1000 },
        "1002": { "ingress": 1000, "egress": 1000, "internal": 1000 },
        "1003": { "ingress": 1000, "egress": 1000, "internal": 1000 }
    },
    "logs": {
        "MyTopicA": {
            "leader": [ "1:2", "2:3", "4:5" ],
            "follower": [ "1:2", "2:3", "4:5" ]
        },
        "MyTopicB": { ... },
        "MyTopicC": { ... },
    }
}
```

我覺得這個緊湊的設計有些潛在的問題

* Leader/Follower Log 設定的部分，他背後的行爲是 `Append`，但是 broker 流量的部分是 `Set`，這樣混雜在一起最後 HTTP Method 也是用 `POST` 嗎

## 取消

下面這個 JSON和上面的設定非常類似，主要目標是讓我們能夠透過同一份 JSON 套用和刪除設定
 
* 取消掉 1001 broker 的 ingress/egress/internal 設定, 其 key 對應的值 don't care
* 取消掉 1002 broker 的 ingress/egress 設定, 其 key 對應的值 don't care
* 取消掉 1003 broker 的 ingress 設定, 其 key 對應的值 don't care
* 透過 `OpType.SUBTRACT` 刪除 `MyTopicA` 的 leader/follower 對應設定

```json
{
    "brokers": {
        "1001": { "ingress": 0, "egress": 0, "internal": 0 },
        "1002": { "ingress": 0, "egress": 0 },
        "1003": { "ingress": 0 }
    },
    "logs": {
        "MyTopicA": {
            "leader": [ "1:2", "2:3", "4:5" ],
            "follower": [ "1:2", "2:3", "4:5" ]
        }
    }
}
```

## 新增針對整個 topic/partition/replica 的 throttle?

目前上面的範例都是針對比較細的對象進行套用，看有沒有需要添加這種針對 topic/partition/replica 的新增或是刪除

```json
{
    "brokers": { ... },
    "logs": {
       "@topic": [ "MyTopicA", "MyTopicB" ],
       "@partition": [ "MyTopicA-1", "MyTopicB-1" ],
       "@replica": [ "MyTopicA-1-1", "MyTopicB-1-2" ],
    }
}
```

因爲 `@` 不是 Kafka topic 能夠使用的 character，他們能夠和普通的 topic name 一起放在同一層

**Comment by chia7712** [comment]
> "logs"

可否直接叫做`topic`，這樣對應`broker`

> 取消

打算用哪個URL?

> "leader"

這邊可否一樣做成平坦的
```json
"topics": [
  {
    "name": "xxx",
    "broker": 10,
    "partition": 11,
    "type": "leader"
  }
]
```

broker那邊一樣，request要盡量做得平坦，這樣的好處是人眼容易閱讀也容易輸入

> 新增針對整個 topic/partition/replica 的 throttle?

承接上述，做成平坦後，我們就可以把預設值視為全部，例如
```json
"topics": [
  {
    "name": "xxx",
    "broker": 10
  }
]
```
上面這個代表只要是broker:10上面屬於topic:xxx的leader/follower都要限制

**Comment by garyparrot** [comment]
>> 取消
>
> 打算用哪個URL? 

應該也是 `/throttles`

## `/throttles` GET

回傳所有 throttle 設定， `leader.replication.throttled.replicas` 這個 config 是儲存很多鬆散的 `Partition:Broker` pairs，不過 API 那邊會儘量把結果聚合成最簡的樣子，如下，而非一大堆 `{ "name": "MyTopic", "partition": ..., "broker": ..., "type": ... }`

```json
{
    "brokers": {
        "1001": { "ingress": 1000, "egress": 1000, "internal": 1000 },
        "1002": { "ingress": 1000, "egress": 1000 },
        "1003": { "ingress": 1000 }
    },
    "topics": [
      { "name": "MyTopicA" },
      { "name": "MyTopicB", "partition": 10 },
      { "name": "MyTopicC", "partition": 11, "broker": 11 },
      { "name": "MyTopicD", "partition": 12, "broker": 12, "type": "leader" }
    ]
}
```

## `/throttles` POST

* `brokers`, 套用對應的限流流量
* `topics`, 針對影響的對象套用限流

```json
{
    "brokers": {
        "1001": { "ingress": 1000, "egress": 1000, "internal": 1000 },
        "1002": { "ingress": 1000, "egress": 1000 },
        "1003": { "ingress": 1000 }
    },
    "topics": [
      { "name": "MyTopicA" },
      { "name": "MyTopicB", "partition": 10 },
      { "name": "MyTopicC", "partition": 11, "broker": 11 },
      { "name": "MyTopicD", "partition": 12, "broker": 12, "type": "leader" }
    ]
}
```

## `/throttles` DELETE

* `brokers` 底下，所有的條目對應的 key 設定進行刪除，value 的部分沒有功能
* `topics` 底下，所有的條目對應的對象進行刪除

```json
{
    "brokers": {
        "1001": { "ingress": 0, "egress": 0, "internal": 0 },
        "1002": { "ingress": 0, "egress": 0 },
        "1003": { "ingress": 0 }
    },
    "topics": [
      { "name": "MyTopicA" },
      { "name": "MyTopicB", "partition": 10 },
      { "name": "MyTopicC", "partition": 11, "broker": 11 },
      { "name": "MyTopicD", "partition": 12, "broker": 12, "type": "leader" }
    ]
}
```

**Comment by chia7712** [comment]
> /throttles DELETE

`DELETE`盡可能不要用body，可否改用query？例如`topic=aaa&partition=10`代表要移除topic + partition的設定。`topic=aaa&partition=10&type=leader`代表只要移除leader的設定

**Comment by garyparrot** [comment]
> DELETE盡可能不要用body，可否改用query？例如topic=aaa&partition=10代表要移除topic + partition的設定。topic=aaa&partition=10&type=leader代表只要移除leader的設定

## `/throttles` DELETE

要移除的參數透過 query 設定

* `/throttles?topic=MyTopicA` 移除 Topic 的 throttle
* `/throttles?topic=MyTopicA&partition=3` 移除 Topic/Partition 的 throttle
* `/throttles?topic=MyTopicA&partition=3&broker=4` 移除 Topic/Partition/Replica 的 throttle
* `/throttles?topic=MyTopicA&partition=3&broker=4&type=leader` 移除 Topic/Partition/Replica/Type 的 throttle
* `/throttles?broker=1001&ingress=` 移除 broker 的 ingress 設定
* `/throttles?broker=1001&ingress=&egress=` 移除 broker 的 ingress/egress 設定
* `/throttles?broker=1001&ingress=&egress=&internal=` 移除 broker 的 ingress/egress/internal 設定

我最近會開始弄 PR，應該會先完成文件的部分，然後再慢慢把實作和測試推上來

**Comment by chia7712** [comment]
> 我最近會開始弄 PR，應該會先完成文件的部分，然後再慢慢把實作和測試推上來

ok，PR也可以分成多隻實作不同的API
