### ISSUE TITLE
Add delete record api

### ISSUE THREAD

**Issue by g1geordie** [skiptests/astraea#483]
- [x] Wrap kafka admin deleteRecord method 
- [x] Impl delete method to RecordHandler
```
   DELETE /records/mytopic?partition=0&offset=5   
```
 partition ~~Required~~  (default: all partition)
   offset Required
- [x] Add document of record delete

**Comment by chia7712** [comment]
> partition Required

如果沒有指定就是預設所有partitions如何？

**Comment by g1geordie** [comment]
其實我有點不確定
預設所有partition 的話 
會不會在record 分布不均的時候 讓資料壞掉押

**Comment by chia7712** [comment]
> 預設所有partition 的話
會不會在record 分布不均的時候 讓資料壞掉押

Kafka的刪除是將指定的offset前的資料都刪除，跟資料壞掉不壞掉應該無關，還是你有注意到什麼限制嗎？

**Comment by g1geordie** [comment]
如果以資料的時間來表示
partition1:    10  , 12  , 14  , 16 , 18 ..
partition2:    9  ,  20  ,   ...
partition3:    11,  13 ,   15  , 17 , 19 ..

在分布不均的情況下  會怕很近期的資料都會被先刪掉而已

**Comment by g1geordie** [comment]
如果可以接受這情況 我相信 default 是所有是OK的!!

**Comment by chia7712** [comment]
> partition1: 10 , 12 , 14 , 16 , 18 ..
partition2: 9 , 20 , ...
partition3: 11, 13 , 15 , 17 , 19 ..

這個例子好像怪怪的，不同partitions之間的offset是獨立計算的

> 在分布不均的情況下 會怕很近期的資料都會被先刪掉而已

這句話是有道理，不過使用者應該要有這個心理準備

**Comment by g1geordie** [comment]
了解  那我備註在document 裡面就好了!!

**Comment by chia7712** [comment]
@g1geordie 回傳值有想法嗎？

**Comment by g1geordie** [comment]
回傳值 預期會跟原本api 相去不遠
```
{
   result :[{
    partition: 0 ,
    lowWatermark:  27
  } ,...
]}
```

**Comment by chia7712** [comment]
> 回傳值 預期會跟原本api 相去不遠

ok
