### ISSUE TITLE
辨別 Cost Function 使用 local metric 或 remote metric

### ISSUE THREAD

**Issue by chinghongfang** [skiptests/astraea#486]
我們現在的 MBeanClient 有分 local 或 remote。同時，Cost Function 也有可能需要 local 或 remote metric，但不知道 Fetcher 要 local 或 remote metric，我們無法給予正確的 MBeanClient 。(也因此 StrictCostDispatcher 目前無法運作)

我們要選一個方法：
1. 可以從 fetcher 得知 local or remote。
2. 限制 Cost Function 只能使用 local or remote metric，然後從 Cost Function 得知它是 local or remote。

(1.)的作法會比較有彈性，Cost Function 可以同時取 local metric 和 remote metric，但 Fetcher 的實做會變複雜，可能變成不是`FunctionalInterface`。(2.)優劣和(1.)是相對的。個人傾向(1.)的作法。

想請問 @chia7712 有什麼想法嘛？

**Comment by chia7712** [comment]
>也因此 StrictCostDispatcher 目前無法運作)

請問現在有遇到什麼問題嗎？

**Comment by chinghongfang** [comment]
[這裏](https://github.com/skiptests/astraea/blob/71df382be12450710a7d514de3d58e5fe3761bfe/app/src/main/java/org/astraea/app/partitioner/StrictCostDispatcher.java#L214-L215) 會把所有Cost Function的 Fetcher 加到 local collector 裡面，儘管某些 Fetcher 要抓 remote metric。

**Comment by chia7712** [comment]
> [這裏](https://github.com/skiptests/astraea/blob/71df382be12450710a7d514de3d58e5fe3761bfe/app/src/main/java/org/astraea/app/partitioner/StrictCostDispatcher.java#L214-L215) 會把所有Cost Function的 Fetcher 加到 local collector 裡面，儘管某些 Fetcher 要抓 remote metric。

沒錯，不過我好奇你說的“無法運作”是指什麼？是指strict dispatcher一跑就會死掉？還是某些cost掛上去會出問題？或者是參數設定都沒錯，但一跑就會掛掉？

**Comment by chinghongfang** [comment]
喔喔，是指使用 remote metric cost function 時，會跳錯誤。
比如說參數設定使用 BrokerInputCost 時，MBeanClient (local) 一去 fetch 資料，也就是call `reciever.current()`，就會丟出 fetch 不到的 exception。

**Comment by chia7712** [comment]
@chinghongfang 另外請問一下，預設使用的cost function不合預期嗎？還是你只是單純想試試套用不同的cost function?

**Comment by chinghongfang** [comment]
> 預設使用的cost function不合預期嗎？還是你只是單純想試試套用不同的cost function?

還沒有測試過預設的，只是單純想試試套用不同的cost function。

**Comment by chia7712** [comment]
> 還沒有測試過預設的，只是單純想試試套用不同的cost function。

了解。這個議題你要處理嗎？還是我來也可以

**Comment by chinghongfang** [comment]
還麻煩學長處理了。

**Comment by chia7712** [comment]
closed by #492
