### ISSUE TITLE
Add delete group api

### ISSUE THREAD

**Issue by g1geordie** [skiptests/astraea#497]
- [ ] Wrap kafka admin deleteGroup method 
- [ ] Impl delete method to GroupHandler

~Request  DELETE /groups/{groupId}?deleteGroup=true~
~deleteGroup optional   , default false~
`Request  DELETE /groups/{groupId}?group=true`
group optional   , default false

`Response void `
- [ ] Add document of group delete

**Comment by chia7712** [comment]
這個項目應該已經完成了

https://github.com/skiptests/astraea/blob/main/app/src/main/java/org/astraea/app/web/GroupHandler.java

不過你可以檢查一下看有沒有漏掉的

**Comment by g1geordie** [comment]
目前想法比較單純
希望加上一個parameter deleteGroup=true
表示連group都要刪除 而不是只有member

或是@chia7712 有沒有其他想法

**Comment by chia7712** [comment]
> 希望加上一個parameter deleteGroup=true

這個聽起來可以，不過deleteGroup這個拼法有點長，或許group就可以？

**Comment by g1geordie** [comment]
沒問題  使用group
