### ISSUE TITLE
Migrate PartitionScore into Web APIs or just remove it?

### ISSUE THREAD

**Issue by chia7712** [skiptests/astraea#523]
如標題所寫，balancer 正在努力開發中，舊有的工具 `PartitionScore` 是時候功成身退，有兩種方式：

1. 直接移除
2. 將功能合併到 Web APIs

**Comment by chia7712** [comment]
@qoo332001 你覺得呢？

**Comment by qoo332001** [comment]
這個可以直接移除，成本估計最後應該會用CostFunction不會用到這個
