### ISSUE TITLE
Add Kafka controller metrics

### ISSUE THREAD

**Issue by g1geordie** [skiptests/astraea#543]

**Comment by chia7712** [comment]
@g1geordie 麻煩列舉一下你預期實作的metrics

**Comment by g1geordie** [comment]
了解  目前要實作的是 kafkaController 中 的metrics
```
ActiveControllerCount
OfflinePartitionsCount
PreferredReplicaImbalanceCount
ControllerState
GlobalTopicCount
GlobalPartitionCount
TopicsToDeleteCount
ReplicasToDeleteCount
TopicsIneligibleToDeleteCount
ReplicasIneligibleToDeleteCount
ActiveBrokerCount
FencedBrokerCount
```

**Comment by chia7712** [comment]
> ActiveControllerCount
OfflinePartitionsCount
PreferredReplicaImbalanceCount
ControllerState
GlobalTopicCount
GlobalPartitionCount
TopicsToDeleteCount
ReplicasToDeleteCount
TopicsIneligibleToDeleteCount
ReplicasIneligibleToDeleteCount
ActiveBrokerCount
FencedBrokerCount

麻煩注意一下這些指標包含的資訊是否可以用同一個物件來包裝，可以參考 `ProducerMetrics`
