### ISSUE TITLE
Astraea 重點元件的文宣

### ISSUE THREAD

**Issue by chia7712** [skiptests/astraea#557]
這個議題用來討論以下項目的文宣：
1. 整體 @chia7712 
2. partitioner @chinghongfang 
3. balancer @qoo332001 @garyparrot 
4. consumer @harryteng9527

**Comment by chia7712** [comment]
各組完成初稿後就可以貼上來討論一下

**Comment by chia7712** [comment]
![Astraea poster A4](https://user-images.githubusercontent.com/6234750/183294978-b790b9f7-f21a-46d7-8373-33d1cdaaaaf4.png)

上面是"整體"的文宣初版，大家可以看一下
另外 @chinghongfang @garyparrot @qoo332001 partitioner and balancer 的效能再麻煩你們提供最新的數據

**Comment by chia7712** [comment]
@chinghongfang 如果要用strict dispatcher作為主角的話，數字的呈現就改成以latency為主，這樣才不會跟balancer的數字重疊性太高

@garyparrot @qoo332001 balancer 如果不想用吞吐量來呈現的話也行，但要盡快提出你們打算用什麼數字

**Comment by chia7712** [comment]
![Astraea poster A4](https://user-images.githubusercontent.com/6234750/183485150-895d09df-b563-458b-b6bf-9ef918c20e9d.png)

為了避免 partitioner 與 balancer 量測的項目過於重複，這次文宣將 partitioner 的測試改為比較延遲

**Comment by harryteng9527** [comment]
Consumer 海報連結 : https://docs.google.com/presentation/d/1NXJuZJTnO3T-VOAyRUFguXFVNH9ZVzYm6qYc3BPQZos/edit?usp=sharing

有把一些「建議」加到海報中了

**Comment by chia7712** [comment]
@harryteng9527 這個海報的字太多，可否用一些圖表替代？例如所謂的dowetime可否有明確的實驗數字？

**Comment by garyparrot** [comment]
Balancer 海報1: https://docs.google.com/presentation/d/1K_BMNdvYAQRE2AAPP2eGY6Q0ihe4QHgBpBKQ-LqmhM8/edit?usp=sharing

**Comment by chia7712** [comment]
@garyparrot 我們專案的圖片和kafka的圖片要一樣顯眼

**Comment by chinghongfang** [comment]
Partitioner 海報連結：
https://docs.google.com/presentation/d/1v6J7skr8EoB-qf0UNUIct3336Y1-QoE7OPck6-ot254/edit?usp=sharing

**Comment by chia7712** [comment]
@chinghongfang 標題的梗還不錯，不過要盡量能貼切到 client端的負載平衡 這個概念，否則看起來很像把格局說小了，變成只能做”延遲的優化”，但延遲的優化應該只是其中一項而已

**Comment by qoo332001** [comment]
Balancer 海報2 : 
https://docs.google.com/presentation/d/1Xr7oQoygQFV2pdnx1u4ve_Rl1-4O2BujIbAvkGaESuA/edit?usp=sharing

**Comment by chia7712** [comment]
@qoo332001 "有無成本估計的差異" 這邊麻煩把數字差異高調出來

**Comment by chia7712** [comment]
![Astraea poster A4](https://user-images.githubusercontent.com/6234750/185676962-7d1cb62c-b388-4534-9c59-818c2e810aad.jpg)


這應該是定版了，麻煩大家看一下

另外也請大家更新一下手上的文宣，依照上面的建議，之後我一起拿去輸出

**Comment by harryteng9527** [comment]
海報連結 : https://docs.google.com/presentation/d/1NXJuZJTnO3T-VOAyRUFguXFVNH9ZVzYm6qYc3BPQZos/edit?usp=sharing
Consumer 文宣更新， 有儘量將字減少

**Comment by chia7712** [comment]
@harryteng9527 感謝更新，在講四個assignora的部分麻煩把 assignor名稱放置於開頭，並且對齊，這樣才不會看起來亂亂

**Comment by harryteng9527** [comment]
> 在講四個assignora的部分麻煩把 assignor名稱放置於開頭，並且對齊

ok，已經修改完畢

**Comment by chia7712** [comment]
@harryteng9527 ok，讚讚

**Comment by chia7712** [comment]
[Astraea poster A4.pdf](https://github.com/skiptests/astraea/files/9392996/Astraea.poster.A4.pdf)

這是晚點要輸出的文件，其他人的我也會一並處理
