### ISSUE TITLE
Utils.swallowException behave the same as Utils.packException

### ISSUE THREAD

**Issue by brandboat** [skiptests/astraea#565]
如題，如果我沒看錯的話，Utils.swallowException 以及 Utils.packException 行為是一模一樣的。
按照 swallowException javadoc desc 字面敘述來看 `Swallow any exception caused by runner.` 這個 method 用意應該是要將所有的 exception 給吞掉，不再把 error 往外丟。

如果我有誤會的話，歡迎關掉這張 issue。如果需要處理，我很樂意接手

**Comment by brandboat** [comment]
gentle ping @chia7712

**Comment by chia7712** [comment]
這是一個好發現，還請幫忙修正swallowException的行為。另外可否貼一下是哪一隻PR造成此bug

**Comment by brandboat** [comment]
> 另外可否貼一下是哪一隻PR造成此bug

https://github.com/skiptests/astraea/pull/380 引入 `Utils.swallowException(Runner)` 用以取代 `Utils.close(AutoClosable)`，不過在實作上沒有在 swallowException 中將例外隱藏
