### ISSUE TITLE
a better way to trace "current throughput"

### ISSUE THREAD

**Issue by chia7712** [skiptests/astraea#577]
目前`performance`的目前速度的算法是每秒看一次總共統計多少，但這樣的算法並不是平滑的統計，這會導致有時候會出現突然驟降的數字，很容易誤導使用者以為出了嚴重的事情

我們可以考慮改用類似 oneMinRate (`Exponentially-weighted moving average`)的算法

**Comment by chinghongfang** [comment]
> 這會導致有時候會出現突然驟降的數字，很容易誤導使用者以為出了嚴重的事情

因為想要追蹤詳細的數字，想要可以明顯看出什麼時候流量下降？持續多久？如果用平均數的話，時間過得越久，數字的變動會越小。
假如：我們跑了30分鐘的實驗後，"流量掉至0 持續1分鐘"，那我們看到的數字改變量也只有 1/30 (3.33 %)。
如果時間過得更久，那這個數字越沒辦法反應即時的數據。

如果不想要看到 "突然驟降的數字"，或許
1. 可以拉長觀測的區間，
2. 或者使用 windowed average。

**Comment by chia7712** [comment]
> 因為想要追蹤詳細的數字，想要可以明顯看出什麼時候流量下降？持續多久？如果用平均數的話，時間過得越久，數字的變動會越小。

你說的沒錯，平均和`current`是看不同的面相。只是現在`current`的算法是不適合的

> 或者使用 windowed average。

這個會比較好，要平滑的移動時間區間來算`current`，這樣才不會突然出現失真的數字

**Comment by chia7712** [comment]
@chinghongfang 如果你有興趣的話，這邊可以切一個題目用來實作平滑版本的current throughput，看是要基於windowed average or Exponentially-weighted moving average都可以

**Comment by chinghongfang** [comment]
好的，我再想想看windowed average 或 Exponentially-weighted moving average 要怎麼做。
我再開個議題來追蹤。

**Comment by chia7712** [comment]
> 我再開個議題來追蹤。

在這個議題討論應該就夠了 :)

**Comment by chia7712** [comment]
目前新增 kafka 統計的數字來呈現，另外專屬於 astraea 的統計內容則移動到 #623 討論
