### ISSUE TITLE
> 另外我感覺mapByPartition的設計似乎缺少明確的意義，它似乎只是一個劣化版的mapByReplica，不如把它修改成回傳leader partition 或者直接移除。

### ISSUE THREAD

**Issue by chia7712** [skiptests/astraea#582]
> 另外我感覺mapByPartition的設計似乎缺少明確的意義，它似乎只是一個劣化版的mapByReplica，不如把它修改成回傳leader partition 或者直接移除。

同意，`mapByPartition`似乎可以被`mapByReplica`所取代

@qoo332001 你覺得呢？

_Originally posted by @chia7712 in https://github.com/skiptests/astraea/pull/569#discussion_r943592409_

**Comment by qoo332001** [comment]
好的，我開一隻PR處理，把回傳的replica改回只回傳leader

**Comment by chia7712** [comment]
> 我開一隻PR處理，把回傳的replica改回只回傳leader

我倒是覺得移除比較好，畢竟`mapByReplica`應該在做cost使用時更適合，因為它帶有節點的資訊。還是說`mapByPartition`有特定的用途嗎？

**Comment by qoo332001** [comment]
> 還是說mapByPartition有特定的用途嗎？

目前確實是沒有用到`mapByPartition`的地方，那我先拿掉好了
