### ISSUE TITLE
Kafka connector 整合

### ISSUE THREAD

**Issue by brandboat** [skiptests/astraea#586]

**Comment by brandboat** [comment]
ping @chia7712，細項再麻煩您補充了，感恩

**Comment by chia7712** [comment]
一開始的方向要完成可以讓大家使用和測試 kafka connector 的環境，包含：
1. 完成腳本讓我們可以快速建構一個 kafak connector cluster
2. 擴建 embedded service 讓我們可以撰寫 connector 的整合測試
3. 封裝 kafka connector admin，將其 restful APIs 的格式封裝成 java code

**Comment by chia7712** [comment]
@brandboat 這個議題有想法了嗎？因為後續還有 perf tool 要改成用分散式 (kafka connector) 來完成，所以需要加速一下這個項目，我打算請 @g1geordie 一起協助完成這個議題，因此想先知道你這邊的狀況，謝謝

**Comment by g1geordie** [comment]
嗨 @brandboat  初次見面您好 我是Geordie

**Comment by brandboat** [comment]
> @brandboat 這個議題有想法了嗎？因為後續還有 perf tool 要改成用分散式 (kafka connector) 來完成，所以需要加速一下這個項目，我打算請 @g1geordie 一起協助完成這個議題，因此想先知道你這邊的狀況，謝謝

這部分我目前還沒開始動工，拍謝

> 嗨 @brandboat 初次見面您好 我是Geordie

你好~ 😃

**Comment by g1geordie** [comment]
了解  @brandboat    
那我先拿走 第二項
`2. 擴建 embedded service 讓我們可以撰寫 connector 的整合測試`

**Comment by chia7712** [comment]
connector 腳本、封裝和後續 connector implementation 都已經在路上，所以關閉此議題
