### ISSUE TITLE
硬碟調查

### ISSUE THREAD

**Issue by harryteng9527** [skiptests/astraea#590]
## 選手
* Micorn Crucial P5 Plus 2TB
* Intel solid 670P 2TB
* Intel 760P 2TB

### Goal
看硬碟們的評價跟速度

## Micron Crucial P5 Plus 2TB

[Crucial P5 Plus 2TB Review](https://www.tweaktown.com/reviews/9992/crucial-p5-plus-2tb-ssd-elite-performance/index.html)
### 速度

* Sequential Read : 6600MB/s
* Sequential Write : 5000MB/s

### 災情

[PS5 寫入效能減半](https://www.reddit.com/r/buildapc/comments/w8y0j2/m2_crucial_p5_plus_2tb_running_at_half_speed/): 但這個是用在PS5，而且沒有什麼討論，所以不知道為什麼會寫入效能減半 ((但就算寫入速率砍半好像也跟Intel的差不多？

### 評價

看網路上大部份都沒什麼鹹蛋超人的災情（可能都拿來當遊戲碟），缺點好像就貴了點

## Intel Solid 670P 2TB

[Intel Solid 670P Review](https://www.reddit.com/r/NewMaxx/comments/lve90a/intel_670p_reviews/)

[評測](https://www.tomshardware.com/reviews/intel-ssd-670p-m-2-nvme-ssd-review)
### 速度

* Sequential Read : 3500 MBps
* Sequential Write : 2700 MBps

### 評價

看起來也沒有太大的災情，不過滿多人因為670P是用`QLC`顆粒，所以不推薦的

### 速度

* Sequential Read : 3230 MBps
* Sequential Write : 1625 MBps

### 災情

[凍結](https://www.ptt.cc/bbs/Storage_Zone/M.1542294305.A.B05.html) : 看起來是會有一段時間(數十秒)無法做任何操作

### 評價

除了凍結以外，表現中規中矩

**Comment by chia7712** [comment]
@harryteng9527 感謝整理！做得很棒

**Comment by chia7712** [comment]
預計明年會做新的硬體更新，這個議題先關閉等候接下來的討論
