### ISSUE TITLE
Reassignment Web APIs 支援顯示搬移進度

### ISSUE THREAD

**Issue by chia7712** [skiptests/astraea#595]
搬移通常是一個需要時間的動作，我們應該在`Reassignments`上顯示相關進度

**Comment by chia7712** [comment]
@brandboat FYI

**Comment by brandboat** [comment]
> @brandboat FYI

感謝，我有意願處理這議題

**Comment by chia7712** [comment]
@brandboat 感謝願意接手，再麻煩提一下可能的做法

**Comment by brandboat** [comment]
> @brandboat 感謝願意接手，再麻煩提一下可能的做法

抱歉這麼晚才回覆，上次線下的討論有提到此功能僅需要提供 “搬移進度” 即可。

有關進度的算法我的想法是根據 reassignments 中計算 `to` 中的資料加總 / `from` 中的資料加總，得出的結果用百分比顯示。  
```json
{
  "reassignments": [
    {
      "topicName": "chia",
      "partition": 0,
      "from": [
        {
          "broker": 1002,
          "path": "/tmp/log-folder-0"
        }
      ],
      "to": [
        {
          "broker": 1001,
          "path": "/tmp/log-folder-1"
        }
      ],
     "progress": [SUM(from) / SUM(to)] %
    }
  ]
}
```

不過要做到這件事我們需要取得 from 以及 to 中的各個 path 資料大小，目前 astraea 似乎沒有地方提供這種資訊(如果有錯煩請糾正)，我的想法是在 `Admin#reassignments(Set<String> topics)` 所回傳的 Reassignment 中的 Location 也一併回傳資料大小。
這部分需要修改前述提及的 `Admin#reassignments(Set<String> topics)`，我想取得資料大小的 api 會是使用 kafka 原生 api `admin.describeLogDirs(brokerIds()).allDescriptions()`。您覺得如何呢？

**Comment by chia7712** [comment]
> 我的想法是在 Admin#reassignments(Set<String> topics) 所回傳的 Reassignment 中的 Location 也一併回傳資料大小。

目前這個需求只有 web apis 這段需要使用，可否改成在web apis 內部自己呼叫`Admin#replicas`來比對結果

**Comment by brandboat** [comment]
> 目前這個需求只有 web apis 這段需要使用，可否改成在web apis 內部自己呼叫Admin#replicas來比對結果

我有觀察過在同節點下搬移 replica 至不同茲料夾，Admin#replicas 僅會顯示 to (目的端) 的資料，而不會兩個都顯示。而在不同節點 replica 的搬移 from & to 都會顯示

**Comment by chia7712** [comment]
@brandboat see #709
