### ISSUE TITLE
使用Embedded cluster來撰寫更多測試

### ISSUE THREAD

**Issue by chia7712** [skiptests/astraea#60]
我們現在已經有embedded cluster可以使用，因此一些與kafka互動的程式碼應該要補上相關測試

1. TopicExploer
2. ReplicaCollie
3. performance
4. metrics

**Comment by garyparrot** [comment]
Ok, 我會試著把它替換過去

**Comment by garyparrot** [comment]
我目前這邊測試主要是要測我這邊 object 的形態和 metric 的形態有對到，然後 attribute 確實存在。這個問題對 `metrics` 部分的測試沒有影響，所以其實可以放著不管www

**Comment by chia7712** [comment]
> 可以注意到在建立好 topic 後立刻對 topic 做操作會出事。但等待一秒鐘做之後不會。

喔 這是kafka各個節點同步的議題，的確有可能造成測試失敗，我會發PR修復
