### ISSUE TITLE
新增用來統計metrics數值的物件

### ISSUE THREAD

**Issue by chia7712** [skiptests/astraea#623]
現在無論是 dispatcher 還是 balancer 都會經過時間的累積來統計 metrics 的結果，但目前我們缺乏各種方便的統計元件，應該要先完成幾隻常用的版本讓大家的生活都可以簡單一點

**Comment by chia7712** [comment]
@chinghongfang @qoo332001 麻煩你們兩位看一下

**Comment by chia7712** [comment]
updated: https://github.com/skiptests/astraea/pull/650#issuecomment-1288908513

**Comment by chinghongfang** [comment]
> 接下來的重點是如何將 kafka metrics 中沒有被統計的值 (例如HasGauge) 轉換成統計值，換言之，這邊會遇到跟 https://github.com/skiptests/astraea/pull/955 類似的議題，BeanCollector 需要具備取樣的能力，並且將HasGauge等物件轉換成類似HasRate的統計結果，這樣方便後續 cost function 可以直接取用。

想先釐清一下觀念，目前我對 `Gauge` 想法是，它是一種觀測量，這種觀測量隨時間變化，因此對每一次的 "觀測" 做統計沒有意義。比如說 "topic size" 是一種觀測量，同一時間的重複觀測，只會得到相近的值，反而要得到不同時間點的觀測值，才可算出如 "每秒變化率" 這類有用的數值。

我預計新增 `Stat` ，來專門統計 `Gauge` 這類的數據。
紀錄時傳入時間，讓 `Stat` 內可以根據時間來判斷要如何處理新的觀測值。以目前的重點 Rate 為例，可能會新增 `RateByTime` 的 `Stat` ，只有 `record()` 的時間點超過指定週期時，數據才會被紀錄、統計。

**Comment by chia7712** [comment]
> 我預計新增 Stat ，來專門統計 Gauge 這類的數據。
紀錄時傳入時間，讓 Stat 內可以根據時間來判斷要如何處理新的觀測值。以目前的重點 Rate 為例，可能會新增 RateByTime 的 Stat ，只有 record() 的時間點超過指定週期時，數據才會被紀錄、統計。

這個概念ok，只是要能與 @garyparrot 後來設計的 auto-update BeanCollector 搭配，也就是說，使用者能否啟動 auto-update 後，直接從BeanCollector 取出“已經被統計”好的值？而不是自己拉出來後重新排序計算得到結果
