### ISSUE TITLE
快速建立測試環境叢集的方法

### ISSUE THREAD

**Issue by garyparrot** [skiptests/astraea#629]
需要一套方法，能夠快速建立整個測試環境，這對他人快速測試我們的工具很有幫助。

這包含建立其整個 Kafka Cluster/Zookeepers/Prometheus/Grafana & Dashboard/Producers/Consumers

**Comment by chia7712** [comment]
我們可否先拆成幾個部分，例如：
1. 先完成監控這部分，例如提供事先撰寫好的參數讓使用者可以快速啟動適合的監控
2. Performance tool現在可否建構流量不均的狀況？如果不行的話，我們應該先完成該功能
3. 是否要提供跨節點的控制腳本？我個人是傾向目前不需要，只要有提供單機建構方便的腳本，使用者可以用其他工具來組合，例如多個terminal輸入等工具來建構大型叢集

**Comment by garyparrot** [comment]
> 先完成監控這部分，例如提供事先撰寫好的參數讓使用者可以快速啟動適合的監控

監控是指什麼，如果是 prometheus 腳本，我們已經有了

> 是否要提供跨節點的控制腳本？我個人是傾向目前不需要，只要有提供單機建構方便的腳本，使用者可以用其他工具來組合，例如多個terminal輸入等工具來建構大型叢集

ok, 那到時候測試報告內是有一段詳細的步驟，一步一步告訴大家要打什麼指令嗎，連線到哪裡嗎

**Comment by chia7712** [comment]
> 監控是指什麼，如果是 prometheus 腳本，我們已經有了

現在的監控圖表能直接看到 balancer 實驗需要看的數據嗎?

> ok, 那到時候測試報告內是有一段詳細的步驟，一步一步告訴大家要打什麼指令，連線到哪裡嗎

1. zookeeper 的話測試過程應該只需要一台
2. broker 的話可以用同一個指令同時輸入到多台就好，所以這部分在實驗上可以用數量呈現就好，例如說我們是在哪些節點上m用哪個指令 (一樣的 start_broker.sh xxx) 建構了叢集
3. 流量不均的部分，也是一樣說明在哪幾個節點用了哪個指令 (start_app.sh) 帶了哪些參數 (設定不同流量)

現階段的實驗數量應該不會到上百台，指定也不會太多種，應該是不會太難重現

**Comment by garyparrot** [comment]
> 現在的監控圖表能直接看到 balancer 實驗需要看的數據嗎?

他們用一樣的 jmx exporter 設定，輸入一樣的 query 就能看到數據

> zookeeper 的話測試過程應該只需要一台
> broker 的話可以用同一個指令同時輸入到多台就好，所以這部分在實驗上可以用數量呈現就好，例如說我們是在哪些節點上m用哪個指令 (一樣的 start_broker.sh xxx) 建構了叢集
> 流量不均的部分，也是一樣說明在哪幾個節點用了哪個指令 (start_app.sh) 帶了哪些參數 (設定不同流量)

ok

我先關閉這個 issue，我們應該暫時不需要這個東西，performance tool 能不能做到那個功能我會再去確認
