### ISSUE TITLE
Balancer Web APIs 需要顯示搬移的成本

### ISSUE THREAD

**Issue by chia7712** [skiptests/astraea#631]
預期新增的項目如下：
```json
{
  "migration": [
    {
      "function": "size",
      "cost": 1000,
      "unit": "bytes"
    }
  ]
}

```

`migration` 代表要完成叢集搬移的成本，`function`是評估成本的方式、`cost`則是純數代表成本、`unit`則是單位。由於搬移過程不需要涉及前後比較，只需要顯示“此次”的成本即可，因此不需要像`ClusterCost` 或是 `BrokerCost`一樣需要去正規化數字才能比較，也就是說搬移成本可以用真實的數字呈現即可。

第一階段希望能觀察到的搬移成本如下：
1. 有多少資料量需要移動
2. 有多少replicas需要移動
3. 有多少replicas leader需要移動

依據要完成的工作如下：
1. - [x] 完成`MoveCost`的介面，並添加第一個實作 (有多少資料量) #641
2. - [x] 將第一個實作套用到 balancer Web APIs，並完成上述的欄位 #666
3. - [x] 實作剩下兩個`MoveCost` (#675)

**Comment by chia7712** [comment]
@qoo332001 麻煩你看一下這個議題，並把它視為最高優先需要處理的項目，目前已經開的PR麻煩依照我這邊提到的工作項目去拆分。

**Comment by chia7712** [comment]
@qoo332001 例如第一個任務，`MoveCost`的介面，請試著去想該如何設計才能滿足Web APis的呈現內容

**Comment by qoo332001** [comment]
@chia7712 我想問一下，有多少資料量要移動是要計算總量就好嗎?，不需要知道移動來源跟目的

**Comment by chia7712** [comment]
> 有多少資料量要移動是要計算總量就好嗎?，不需要知道移動來源跟目的

這個想法還不錯，總量說一定要放的，其他你覺得可以做到什麼程度呢？來源目的和資料量三個資訊都呈現嗎？可以試著提提看你想像中的格式

**Comment by chia7712** [comment]
> 其他你覺得可以做到什麼程度呢？來源目的和資料量三個資訊都呈現嗎？可以試著提提看你想像中的格式

補充一下，這個設計必須能泛用到其他“資源”，例如在描述中提到的三個元件："名稱“、"數值"、"單位"就是可以通用到其他資源格式（例如資料量、頻寬、記憶體使用率等等)

**Comment by qoo332001** [comment]
> 其他你覺得可以做到什麼程度呢?

我覺得還是先把上面三個目標處理完再來討論這個好了，因為還沒實作另外兩個moveCost，還不確定另外兩個的格式，我目前處理完上面的 1. 跟 2. 會分成兩支PR發

**Comment by chia7712** [comment]
@qoo332001 感謝協助完成大部分的工作，下一個階段我們要來考慮如何讓使用者可以設定`migration cost`的上限，例如希望整體搬移的資料量不要大於多少，又或者希望不要超過多少leaders變化等等

**Comment by chia7712** [comment]
@qoo332001 如果這個題木處裡完畢，可否請你協助完成 #725 ?

**Comment by qoo332001** [comment]
> 如果這個題木處裡完畢，可否請你協助完成 https://github.com/skiptests/astraea/issues/725 ?

不好意思，沒有看到通知，這個現在是交給 @Haser0305 處理對嗎?

**Comment by qoo332001** [comment]
更新一下，這三個`MoveCost` 預計會長這樣
```json
   "migrationCosts":[
      {
         "function":"leader",
         "totalCost":9,
         "cost":[
            {
               "brokerId":1001,
               "cost":-7
            },
            {
               "brokerId":1002,
               "cost":2
            },
            {
               "brokerId":1003,
               "cost":5
            }
         ],
         "unit":"partition leaders"
      },
      {
         "function":"Replica Number",
         "totalCost":9,
         "cost":[
            {
               "brokerId":1001,
               "cost":-7
            },
            {
               "brokerId":1002,
               "cost":2
            },
            {
               "brokerId":1003,
               "cost":5
            }
         ],
         "unit":"replica"
      },
      {
         "function":"size",
         "totalCost":197029615367,
         "cost":[
            {
               "brokerId":1001,
               "cost":-149011629651
            },
            {
               "brokerId":1002,
               "cost":24610751754
            },
            {
               "brokerId":1003,
               "cost":124400877897
            }
         ],
         "unit":"byte"
      }
   ]
```

**Comment by chia7712** [comment]
> 不好意思，沒有看到通知，這個現在是交給 @Haser0305 處理對嗎?

是的

**Comment by chia7712** [comment]
close as all sub tasks are completed
