### ISSUE TITLE
Performance Tool 添加 ``--specify.partitions`` 功能

### ISSUE THREAD

**Issue by garyparrot** [skiptests/astraea#658]
Context: https://github.com/skiptests/astraea/issues/644#issuecomment-1231329911

為了建立 Skewed Load 的情境，我們需要比 Topic 更細粒度的資料施打機制，對此添加 ``--specify.partitions`` 來決定 Performance Tool 可以傳資料的對象。

**Comment by chia7712** [comment]
@garyparrot 你要接手這個議題嗎?

**Comment by garyparrot** [comment]
我可以接手

**Comment by garyparrot** [comment]
這個項目會碰到的程式碼會和 #657 非常有關, 我可能要等 #657 合併後才能開工
