### ISSUE TITLE
Implement IgnoreCase Enum 

### ISSUE THREAD

**Issue by g1geordie** [skiptests/astraea#660]
很開心你願意處理這個議題，這個方法不錯，不過有幾個可以更好的地方：

1. 最後輸出的錯誤資訊不夠完整，使用者無法得知有哪些可以用的名字
2. `metricNameMapper` 這個過於明確，無法套用到所有enum type
3. 使用者在操作enum的時候依然可能使用錯誤的名字

為了一次解決上述的問題，希望你能獨立發一隻PR來處理，該PR需要包含：
1. 專案裡每一個Enum都需要有"alias"這個方法，用來代表可以對應的名字
2. 為了達到上述目的，需要建立一個介面(例如`EnumInfo`)，提供`alias`方法，並且預設實作為回傳`name()`
3. `ofIgnoreCaseEnum`就可以簡化，因為可以明確使用`alias().equalsIgnoreCase`
4. 確保每一個Enum都有實作`EnumInfo`這個介面
5. 確保每一個Enum都有提供`ofAlias(String)`這個介面
6. 為了達到上述4. 和 5.，需要在`EnumInfoTest`裡面新增一個測試，動態走訪專案裡所有的enum class，並且檢查是否有實作 4. 和 5.

_Originally posted by @chia7712 in https://github.com/skiptests/astraea/pull/648#discussion_r956773122_

**Comment by chia7712** [comment]
@g1geordie 你有意願處理嗎？

**Comment by g1geordie** [comment]
當然  請assign 給我吧
