### ISSUE TITLE
Performance tool - tracker 導致 performance tool 無法結束 

### ISSUE THREAD

**Issue by harryteng9527** [skiptests/astraea#680]
當 Producers 執行完而 Consumers 還沒消費完資料時，會發生 `consumerDone` 無法更新導致 performance tool 結束不了。

如下圖， performance tool 設定執行時間為 30 seconds，但是跑了一分多鐘都還沒結束， `tracker` 也沒有紀錄資料

![tracker bug 2](https://user-images.githubusercontent.com/90374678/188822346-7cd2fd41-0070-4fc4-95c0-93e9a6b47076.png)

利用 Debug mode 後發現

如下圖，得知 main 正在等待 tracker 完成工作

![tracker bug 3](https://user-images.githubusercontent.com/90374678/188822465-1be3d55a-7345-4fe9-a66d-43f14c4b68d5.png)

進入 tracker thread 後，發現 consumerDone 為 false

![tracker bug 1](https://user-images.githubusercontent.com/90374678/188822529-98f10a83-aadf-4870-8cfe-b7dfc9de5b9f.png)

綜合以上發現，應該要新增判斷 : producerDone == true 且 consumerDone == false 時 繼續更新 consumerDone

學長我要開個 PR 來修改嗎??

**Comment by chia7712** [comment]
好的，再麻煩幫忙修正 謝謝
