### ISSUE TITLE
補上`ListField`的測試

### ISSUE THREAD

**Issue by chia7712** [skiptests/astraea#686]
目前`ListField`的測試基於`Performance`，這是不正確的，它應該在測試scope中建構臨時用的class來確認list是否能正常運作

**Comment by harryteng9527** [comment]
> 它應該在測試scope中建構臨時用的class來確認list是否能正常運作

請問是像 `NonNegativeFieldTest` 中那樣要新增 `FakeParameter` 來做測試嗎？
```java
  private static class FakeParameter {
    @Parameter(
        names = {"--field"},
        validateWith = NonNegativeLongField.class)
    public int value = 1;
  }
```

**Comment by chia7712** [comment]
@harryteng9527 沒錯
