### ISSUE TITLE
補完 consumer metrics

### ISSUE THREAD

**Issue by chia7712** [skiptests/astraea#704]
還有一個類別的 metrics 尚未完成，如下圖

<img width="887" alt="截圖 2022-09-13 上午1 23 08" src="https://user-images.githubusercontent.com/6234750/189717593-1fedc0bb-9dc2-4633-933a-555fb63b45eb.png">

**Comment by chia7712** [comment]
@g1geordie FYI，看你是否有時間幫忙處理

**Comment by g1geordie** [comment]
沒問題交給我吧

**Comment by chia7712** [comment]
@g1geordie 有空處理這個議題嗎？我們需要先完成這個項目來補足 perf 能顯示的統計資訊 (https://github.com/skiptests/astraea/pull/711)

**Comment by g1geordie** [comment]
好的 馬上處理

**Comment by chia7712** [comment]
resolved by #714
