### ISSUE TITLE
Performance tool - file writer 數據不會更新

### ISSUE THREAD

**Issue by harryteng9527** [skiptests/astraea#724]
使用 performance tool 時發現 file writer 紀錄 `consumer bytes consumed` 與 `producer bytes produced` 的數據不會更新。

![image](https://user-images.githubusercontent.com/90374678/190899577-fd15261f-6eed-47b0-aa3d-3c7ad93c74c6.png)

照理來說 `consumer bytes consumed` 與 `producer bytes produced` 會紀錄啟動到當下時間所消費的 records bytes、發送的 records bytes

這可能要修一下。

**Comment by chia7712** [comment]
@harryteng9527 我來處理這個議題
