### ISSUE TITLE
透過 `Balancer` 物件抽換 `BalancerHandler` 內產生計劃的邏輯

### ISSUE THREAD

**Issue by garyparrot** [skiptests/astraea#725]
Context: https://github.com/skiptests/astraea/pull/712#pullrequestreview-1111507545

PR #712 中實作了一個 `Balancer` 物件，能夠依照使用者給定的參數，去產生出一個對叢集有幫助的搬移計劃。
目前 `BalancerHandler` 這個 web API 中也有類似的邏輯，我們應該用 `Balancer` 物件來取代 `BalancerHandler` 中重複的邏輯。

**Comment by Haser0305** [comment]
我來取代看看`BalancerHandler`裡面重複的邏輯

**Comment by chia7712** [comment]
@Haser0305 狀況如何？有需要討論的可以直接在議題上列出來

**Comment by Haser0305** [comment]
> @Haser0305 狀況如何？有需要討論的可以直接在議題上列出來

好的，現在在看裡面的功能後再替換過去
目前預計會把`BalancerBuilder`改為public以便使用

**Comment by chia7712** [comment]
@Haser0305 這隻PR可能比較急一點，看能否這兩天處理完畢，感謝

**Comment by Haser0305** [comment]
了解
