### ISSUE TITLE
Add kafka connector script

### ISSUE THREAD

**Issue by brandboat** [skiptests/astraea#734]
related to https://github.com/skiptests/astraea/issues/586

1. 完成腳本讓我們可以快速建構一個 kafak connector cluster

**Comment by chia7712** [comment]
> 完成腳本讓我們可以快速建構一個 kafak connector cluster

提醒一下，會希望能在同一個 kafka broker 叢集上建構“多個” worker cluster，所以 kafka worker 使用的 internal topics 的名稱要思考一下如何處理才不會彼此混淆

**Comment by brandboat** [comment]
> 提醒一下，會希望能在同一個 kafka broker 叢集上建構“多個” worker cluster，所以 kafka worker 使用的 internal topics 的名稱要思考一下如何處理才不會彼此混淆

這部分用 group.id 的名稱來做區隔如何？

e.g. 以 group.id=connect-1 的 connect 節點們。所用的 internal topics 都帶有 connect-1 前綴 (connect-1-configs, connect-1-status .etc.)。以 group.id=connect-2 的 connect 節點們則用 connect-2 前綴，依此類推

**Comment by chia7712** [comment]
> e.g. 以 group.id=connect-1 的 connect 節點們。所用的 internal topics 都帶有 connect-1 前綴 (connect-1-configs, connect-1-status .etc.)。以 group.id=connect-2 的 connect 節點們則用 connect-2 前綴，依此類推

這部分可以，只要能先產生一個隨機的group id，後面都可以參考 group id 做組合

**Comment by brandboat** [comment]
> 只要能先產生一個隨機的group id

這意思是我們再透過 script 啟動 connect 時，都要給新成立的 connect 一個隨機的 group id，除非使用者自行指定 group id，不然每個 connect 都會是獨立的 connect cluster 是嗎？

**Comment by chia7712** [comment]
> 這意思是我們再透過 script 啟動 connect 時，都要給新成立的 connect 一個隨機的 group id，除非使用者自行指定 group id，不然每個 connect 都會是獨立的 connect cluster 是嗎？

是的，完全沒錯
