### ISSUE TITLE
Wrap kafka connector CRUD api 

### ISSUE THREAD

**Issue by g1geordie** [skiptests/astraea#738]
https://docs.confluent.io/platform/current/connect/references/restapi.html
ref #586

**Comment by chia7712** [comment]
由於 APIs眾多，麻煩先列出第一階段要做的CRUD

**Comment by g1geordie** [comment]
感謝提醒 這支主要會圍繞在connectors 的CRUD
將會實作以下API
```
GET / 
GET /connectors
GET /connectors/(string:name)
POST /connectors
PUT /connectors/(string:name)/config
DELETE /connectors/(string:name)/
```

**Comment by chia7712** [comment]
@g1geordie 目前專案內處理 json 的元件是仰賴 `gson`，可能要請你先看一下目前的 json 功能轉換是否足夠，如果不足夠的話要先開一個議題來增強
