### ISSUE TITLE
[Web APIs] `BalancerHandler` 計劃執行

### ISSUE THREAD

**Issue by garyparrot** [skiptests/astraea#743]
Context: https://github.com/skiptests/astraea/pull/735#discussion_r977775031

實作特定 Web API 能夠讓負載平衡計劃被實現。

**Comment by garyparrot** [comment]
我接下來會接手這個議題，後面會先發 API document 的 PR，之後再推實作的 PR。

**Comment by chia7712** [comment]
感謝，這會是一個很棒的功能
