### ISSUE TITLE
TopicAdmin should be able to change log folder of partitions

### ISSUE THREAD

**Issue by chia7712** [skiptests/astraea#75]
load balance的議題中我們會涉及兩種搬移路徑:

1. 從broker_a到broker_b
2. 從broker的folder_a到folder_b

前者已經有`TopicAdmin#reassign`可以使用，但後者目前尚未有對應的APIs。我們應該給`TopicAdmin`實作該APis，此外，embedded cluster也應該配置多個folders以便驗證相關功能

**Comment by qoo332001** [comment]
@chia7712 學長，這個可以讓我做做看嗎,因為我之前有試著搬移過

**Comment by chia7712** [comment]
@qoo332001 好喔，就麻煩你了
