### ISSUE TITLE
`BalancerBuilder` 能夠支援有 Fetcher 需求的 CostFunction

### ISSUE THREAD

**Issue by garyparrot** [skiptests/astraea#754]
Context: https://github.com/skiptests/astraea/issues/752#issuecomment-1256541966

**Comment by garyparrot** [comment]
我接下來會接手這個議題，不過可能有些技術上的議題需要先討論。

## 撈取 Metrics 到 Metrics 足夠支應 CostFunction 運作的時間

我們的 metrics 可能是從負載平衡計劃被 submit 後才開始攝取。由於 Cost Function 的實作對 Metrics 的需求會不太一樣，我們可能會有這些問題

1. 有個 `CostFunction` 需要過去 24 hour 的 metrics，爲了生成一個計劃我們需要一天的時間

## Metrics 要保留多少

Metrics 的資訊會需要存在 JVM 裏面，隨着時間變長我們可能會累計很多 raw merics，比如上面那個要跑 24 hours 的 metrics。我在想我們是不是需要一個東西把 raw metrics 消化成特定組合後的 metrics，比如 window sum/ window average 這些

這邊另外一個議題是：如果 Cost function 預期要收集 1 hour 的 metrics 才能開始工作，但是內建撈取 metrics 的元件只儲存前 10 minute 的 metrics，這樣計劃永遠無法被生成。

**Comment by chia7712** [comment]
> 有個 CostFunction 需要過去 24 hour 的 metrics，爲了生成一個計劃我們需要一天的時間

想先知道是哪部分的成本需要這個資訊？

> 我接下來會接手這個議題，不過可能有些技術上的議題需要先討論。

或許可以先把介面定好，例如 `Balancer`該如何吃metrics ？究竟是使用者直接傳`HasBeanObject`？或者是只要吃MBeanClient?

**Comment by garyparrot** [comment]
> 想先知道是哪部分的成本需要這個資訊？

其實這部分是舉例，有可能會有這種 Cost Function 存在，不過 `ReplicaDiskInCost` 能做到類似的效果

https://github.com/skiptests/astraea/blob/479f3096f35262f429088efbdc514fc91139df92/common/src/main/java/org/astraea/common/cost/ReplicaDiskInCost.java#L35-L48

`ReplicaDiskInCost` 把 duration 輸入 24h 時可以有類似的效果

> 或許可以先把介面定好，例如 Balancer該如何吃metrics ？究竟是使用者直接傳HasBeanObject？或者是只要吃MBeanClient?

我是想說讓 `BalancerBuilder` 多接受一個 `Supplier<ClusterBean>`

**Comment by chia7712** [comment]
> 我是想說讓 BalancerBuilder 多接受一個 Supplier<ClusterBean>，每次呼叫就是拿到當下最新的 ClusterBean，至於如何索取這個部分交給 Balancer 初始化的人決定。

這個倒是不錯，可以先當第一步

> 其實這部分是舉例，有可能會有這種 Cost Function 存在，不過 ReplicaDiskInCost 能做到類似的效果

說到這個例子，現在 ClusterInfo 也帶有資料量了，`ReplicaDiskInCost` 還需要拉取 metrics 嗎? @qoo332001 ?

**Comment by garyparrot** [comment]
> 其實這部分是舉例，有可能會有這種 Cost Function 存在，不過 ReplicaDiskInCost 能做到類似的效果

不過要 submit 計劃產生請求後才開始撈 metrics 這件事情還蠻尷尬的，一個計劃的生成可能會花上大把的時間。

我剛剛想到一個具體的用途：使用者想產生一個計劃，能極力避免 network congestion 發生於 broker 這端，對此他定義每個 partition 預計會流入的資料量是過去一個禮拜的最尖峰量 * 120%（做最悲觀的假設），這個時候他會需要過去一個禮拜的歷史資訊，他的計劃需要跑一個禮拜，然後 network congestion 可能會在這一個禮拜繼續發生。

不過這個情境可能離我們還比較遠就是了，可能以後再來考慮。

**Comment by chia7712** [comment]
> 不過要 submit 計劃產生請求後才開始撈 metrics 這件事情還蠻尷尬的，一個計劃的生成可能會花上大把的時間。

如果可以的話，我會希望收集大量 metrics 的需求不要發生，因為那是一個挺麻煩的功能。如果我們能盡量重複使用 kafka 累積的各種統計值是最好，但如果有些重大的 cost 真的非要累積一段時間的 metrics 的話，那就真的需要好好討論該如何實作這個功能（例如把現在 dispatcher 在使用的 BeanCollector 移植到 Balancer 端)

**Comment by qoo332001** [comment]
> 說到這個例子，現在 ClusterInfo 也帶有資料量了，ReplicaDiskInCost 還需要拉取 metrics 嗎?

ReplicaDiskInCostk這支會需要帶有`createdTimestamp`的metrics，要用這些metrics來計算一段時間內的replica Log Size變化來算分數，但ClusterInfo似乎沒辦法拿到時間相關的資訊?

**Comment by chia7712** [comment]
> ReplicaDiskInCostk這支會需要帶有createdTimestamp的metrics，要用這些metrics來計算一段時間內的replica Log Size變化來算分數，但ClusterInfo似乎沒辦法拿到時間相關的資訊?

createdTimestamp是 kafka metrics 自帶的？還是我們在拉metrics時壓上去的？如果是後者，或許我們也能給ClusterInfo 押上時間?

**Comment by chia7712** [comment]
> createdTimestamp是我們加的沒錯，要在ClusterInfo加上時間可以，但是主要問題是一個ClusterInfo現在用來表示某個時間的叢集分布與資訊，但要計算ReplicaDiskInCost需要有多個不同時間的資訊，那這如果要用ClusterInfo拿資訊的話是不是就會改ClusterInfo的實作(改成紀錄多個時間的資訊)或是傳入多個ClusterInfo呢?

這個話題先暫緩，我想確定一下`ReplicaDiskInCost`的評斷方式。所謂一段時間內的size變化，這個資訊可否用 [BYTES_IN_PER_SEC](https://github.com/skiptests/astraea/blob/main/common/src/main/java/org/astraea/common/metrics/broker/ServerMetrics.java#L279) 取代？如果只是要算“單位時間內的大小變化”

**Comment by qoo332001** [comment]
> 這個資訊可否用 [BYTES_IN_PER_SEC](https://github.com/skiptests/astraea/blob/main/common/src/main/java/org/astraea/common/metrics/broker/ServerMetrics.java#L279) 取代？

這個之前好像有討論過，現有有關流量的metrics都是以broker為單位去計算，但我們想要拿到的是以replica為單位的流量(透過replica log size增長速度去計算)，所以沒辦法用`BYTES_IN_PER_SEC`取代

**Comment by chia7712** [comment]
> 但我們想要拿到的是以replica為單位的流量(透過replica log size增長速度去計算)

請問為何需要拿到以`Replica`為單位？如果最後都要整合成以`broker`為單位的話？

**Comment by garyparrot** [comment]
剛剛想到別的問題，如果 CostFunction 需要的 metrics 數量不夠，這個時候 `GET /balancer` 應該...

1. Cost Function 會噴錯，而 Balancer Handler 會等一下再重新嘗試生成計劃。
2. 讓使用者指定應該等待 metrics 攝取多久的時間再開始產生計劃
3. 使用者應該自己先註冊 Cost Function，後面產生計劃時再指定要用這些先前註冊的 Cost Function，如果 metrics 不夠產生，則使用者應該等一回兒再 retry `GET /balancer`。

**Comment by chia7712** [comment]
> 剛剛想到別的問題，如果 CostFunction 需要的 metrics 數量不夠，這個時候 GET /balancer 應該..
> Cost Function 會噴錯，而 Balancer Handler 會等一下再重新嘗試生成計劃。
> 1 的話比較簡單，但是這樣 GET /balancer 可能要改成 Async 的形式，因為勢必會跑一段時間。

這個方案可以，簡單明瞭，噴錯倒是無所謂，只要錯誤訊息有明確寫，使用者可以稍後再重新發請求就好

**Comment by chia7712** [comment]
> 因為我們之後在制定搬移計畫會希望不要搬移到寫入流量太大的replica，因為這樣可能會發生搬移的速度<寫入的速度，那就會有永遠搬移不完的機會

這個出發點很好，不過我直覺應該是要看“整體”搬移的量，例如某個broker 總共要花多少頻寬來同步，例如加總要搬移的 replicas 總共有多少量要搬，如果只是避免某個比較大的，然後加總後搬不完是不是還是個問題？

另外，上述討論中的“避免”搬不完這個題目，要否考慮把這個責任移動給 move cost? Broker cost and cluster cost 的目的是要找出做適合的規劃，並不討論“搬移”成本這件事情，如果我們想要做到避免出現一個“無法執行“（搬移不完應該屬於無法執行的一種），那比較好的實作點應該是在 move cost

**Comment by qoo332001** [comment]
> 不過我直覺應該是要看“整體”搬移的量，例如某個broker 總共要花多少頻寬來同步

這個在專案中似乎已經有`BrokerInputCost`了

>上述討論中的“避免”搬不完這個題目，要否考慮把這個責任移動給 move cost?

我覺得可以把`ReplicaDiskInCost`改成`HasMoveCost`，然後把原本的`HasBrokerCost`拿掉,`HasClusterCost`移動到`BrokerInputCost`中(計算方式改成用裡面原本的BrokerCost來算)，然後`ReplicaDiskInCost`的`HasMoveCost`就用來計算搬移計畫中總共會移動多少寫入流量的replica，以及各個broker的寫入流量改變，這樣如何?

**Comment by chia7712** [comment]
> 我覺得可以把ReplicaDiskInCost改成HasMoveCost，然後把原本的HasBrokerCost拿掉,HasClusterCost移動到BrokerInputCost中(計算方式改成用裡面原本的BrokerCost來算)，然後ReplicaDiskInCost的HasMoveCost就用來計算搬移計畫中總共會移動多少寫入流量的replica，以及各個broker的寫入流量改變，這樣如何?

如果問題是放在避免搬不完的話，目前 ReplicaSizeCost 提供的資訊應該足以處理。不過如果是想避免搬移過大的 replica（假設這真的是個需求），那或許可以加一個 Move cost專門描述最大的 replica size，也就是 totalCost 回傳此次搬移中最大的 replica size，changes則是回傳各個broker所負責的範圍中最大的 Replica size

然後類別名稱要調整，很明顯 ReplicaSiskInCost不太符合

最後，等上述成本都到位了，我們再來討論如何處理「自動偵測叢集效能」的題目，我覺得現在這個題目做在某隻 cost 裡面很奇怪，我們應該要有一個獨立的 class 專門描述，就像 ClusterInfo ClusterBean一樣，每個cost function 都可以從中索取需要的資訊，用來幫助判斷
