### ISSUE TITLE
BalancerHandler 應該支援限定時間內產生更佳的配置

### ISSUE THREAD

**Issue by chia7712** [skiptests/astraea#762]
現在 Balancer 已經支援指定時間內產生更好的規劃，我們應該讓 Web APIs端也能享有該功能

**Comment by Haser0305** [comment]
想問一下，這個是指是只說API增加參數來設定 Balancer 裡的 executionTime 嗎？

**Comment by chia7712** [comment]
> 這邊的意思是API增加參數來設定 Balancer 裡的 executionTime 嗎？

是的

**Comment by Haser0305** [comment]
那我把 GET /balancer 的參數名稱設定`execTime`，並且單位設為秒數
這樣子可以嗎

**Comment by chia7712** [comment]
> 那我把 GET /balancer 的參數名稱設定execTime，並且單位設為秒數

聽起來不錯，不過可否看一下能否重複使用 DurationField ? 它能支援帶有單位的描述方式
