### ISSUE TITLE
測試基於過去全局資訊預測未來最佳部署的partitioner實際運行效能

### ISSUE THREAD

**Issue by wycccccc** [skiptests/astraea#78]
我們現在已經有了一個滿足基本功能的partitioner。對此進行效能測試可以使我們更加了解它的運行狀況。幫助我們對其進行改進。這裡將用來記錄一些實際測試的資料，並用來討論。

**Comment by wycccccc** [comment]
LP：我們的partitioner
DP：Default partitioner
第一次測試過程如下：
首先在本機上開了三個docker進行測試，開了一個producer，發現LP相比DPproducer的發送average latency更長，LP平均為1.5ms，而DP為0.5ms，這裡我理解為程式執行所需的時間（因為測試環境是在本機）。

接下來是連接實驗室的三個node。在一個producer的情況下producer的吞吐量LP要低於DP，LP在3.5～4.0MB/second而DP則是在4.5MB/second左右波動。我認為造成這一點的原因在於程式執行所需時間的差異？
然後在這一個producer的情況下數據做出來十分的漂亮，consumer端到端的延遲LP為DP的十分之一。不過我傾向於是因為producer發送資料的頻率較低導致資料沒有積壓所以LP的延遲就很漂亮。

後來我將producer和comsumer都調整為了三個，情況就不是很理想了。在同樣producer thoughput的情況下LP相比與DPconsumer端到端的延遲會略高，相同資料執行完畢的時間也會稍微久一點。

經過反思我認為造成這一點的原因是測試設計的問題。如果只是producer對於所有partition統一發送資料，那麼partitioner之間其實也只是在比較誰能做到均勻分配。那麼使用murmurhash的DP肯定是有優勢的。而我們的LP其實初衷是根據集群狀況進行partition的分配。

為此我認為測試的方式應該改為，先創建一個producer向某一個node發送資料，再創建一個producer向整個cluster發送資料。然後比較後者DP與LP數據上的差異。這樣才比較接近我們預想的使用場景？

第一次測試大概就這些內容，因為測試過程中發現了一些BUG或是值的改進的點，雙休日我會改進一下，星期一會繼續按照上面的改進方式繼續測試。

以下附上其中一次3producer、3consumer的LP與DP對照數據
[record.txt](https://github.com/skiptests/astraea/files/7445982/record.txt)
[record_Link.txt](https://github.com/skiptests/astraea/files/7445983/record_Link.txt)

**Comment by chia7712** [comment]
確認一下，producer的資料分佈長什麼樣子？

> 為此我認為測試的方式應該改為，先創建一個producer向某一個node發送資料，再創建一個producer向整個cluster發送資料。然後比較後者DP與LP數據上的差異。這樣才比較接近我們預想的使用場景？

我覺得一開始至少在「設定的目標」上要能取得明顯的優勢，這樣才算有踏出第一步。而我想像中LP的優勢是在於一個叢集各節點負載是很不均勻的狀況下，能取得較好的效能。

因此測試方式要重新調整，如你所說的方式可以試試看，極端一點讓其中一個節點幾乎忙到沒資源，如此在比較效能應該要有明顯的優勢。

**Comment by wycccccc** [comment]
終於我們的實驗環境算是穩定了，我將每一台機器的網卡限制在100mbps也就是大約10MB/S。然後用我們的partitioner向集群（5台）發送消息，同時再向集群中的其中一台發送消息。通過比較那其中一台消息處理速度的快慢，來進行效能的比較。得出的結果很符合預期


![59644616](https://user-images.githubusercontent.com/43372856/141122183-4433e9f2-19a4-4f71-a0c6-6b8daaa0d7d1.jpg)


![1331963517](https://user-images.githubusercontent.com/43372856/141122509-943cc3b6-7265-439f-809c-54e9b85c4cae.jpg)


第一張圖為使用我們partitioner的情況，第二張圖為default partitioner的情況。
很明顯在相同資料量的大小下，用我們的partitioner向集群發送消息，可以使集中向一台node發送資料的用時從115秒提升到60秒。以此可以判斷thoughput有了巨大提升。

但在調整網絡限制速度的時候我突然想到，是否會有機器間網路傳輸規格不同的情況。因為之前的假設都是每一台機子網路的bandwidth相同。但是如果網路規格是不同的，使用該partitioner可能會產生負收益。即因為網路bandwidth較小導致測到的thoughput較小，而判斷將更多的資料丟給這個網路bandwidth較小的機器，從而導致資料越發阻塞。

如果機器間的網路規格會有存在差異的情況，那麼以作為榨乾網路資源這一基本議題該問題必須被解決。目前有一個可能的想法，是實作一個類似congestion control tcp的機制，對網絡餘力進行推測計算。我認為這是一件對該專案有意義的事，如果確實存在網路差異的情況。

**Comment by chia7712** [comment]
> 在100mbps也就是大約10MB/S

這個數字抓太低了，麻煩至少100MB/s

**Comment by wycccccc** [comment]
因為機器數量有限所以才把數字設成10MB/s，100MB/s的話需要一台機子吃乾淨某一台的的bandwidth，還要有一台發送一定數量能造成壓力的資料給所有集群中所有機器。這樣可能需要七台機器，可是實驗室只有六台獨立的伺服器。想要提升到100MB/s可能需要某一台集群中的節點也擔任發送消息的任務。我感覺這樣會吃掉這台機器幾乎所有的頻寬。影響測試的結果。
我會先嘗試減少集群到三台空出發送資料的機器測試，然後再嘗試五台集群中某一台再擔任發送任務，得出更多的數據結果。

**Comment by wycccccc** [comment]
![2021-11-11 22-26-40 的螢幕擷圖](https://user-images.githubusercontent.com/43372856/141314925-b1341821-5b96-480b-b530-cfc42a3661c7.png)
![2021-11-11 22-28-48 的螢幕擷圖](https://user-images.githubusercontent.com/43372856/141315073-bd69c594-b6d5-45c4-8c22-1a0ae47dc8ee.png)
![2021-11-11 22-41-37 的螢幕擷圖](https://user-images.githubusercontent.com/43372856/141316929-9644c3c9-08be-49ba-9ef1-29419a9795c4.png)
![2021-11-11 22-30-26 的螢幕擷圖](https://user-images.githubusercontent.com/43372856/141315359-8d9a646c-f2d6-406f-a3b5-ac0e1e92c1a3.png)

上述圖片為不限制網絡環境測試得出的結果。一樣是五台機器，我讓集群中性能最好的那一台（它有兩張1000mbps的網卡）擔任向集群中所有機器發送資料的任務（分別進行兩次測試，使用Defalut partitioner與我們的partitioner）。而對照數據為向某一台集群中的機器處理相同資料所需時間。

前兩張圖片為我們的partitioner，可以看出producer完成的時間要早於DP 16秒，而consumer完成時間則提前了34秒。

由計算得出producer效率提升約11%、consumer約30%（測試的計時是臨時加的功能、有四秒無效時間所以數據目前要減四秒）。
另外想問一下學長昨天提到的網路bandwidth各機子間會有不同的差異嘛。

**Comment by chia7712** [comment]
> 另外想問一下學長昨天提到的網路bandwidth各機子間會有不同的差異嘛。

我們可以先以同一個rack來考慮就好，不然越想越遠就要考慮跨地區的叢集了ＸＤＤ

**Comment by chia7712** [comment]
@wycccccc 這些情境下，網路的頻寬有吃光光嗎？我看還是在1x MB左右@@

**Comment by wycccccc** [comment]
如下兩張圖分別為使用不同partitioner向整個集群發送消息
astraea：
![15087195301067](https://user-images.githubusercontent.com/43372856/141820579-0a35b460-8d6c-4caf-a3eb-31c19d4d2889.png)
default partitioner：
![15087195653284](https://user-images.githubusercontent.com/43372856/141820524-fe80d5ec-120e-47e9-a1fa-418fec21adcb.png)

使用default partitioner時向單一節點發送資料完成情況：
consumer完成：
![15087195586015](https://user-images.githubusercontent.com/43372856/141820535-a7a0aec8-764b-4d74-b906-df8234f2f490.png)
producer完成：
![15087195486476](https://user-images.githubusercontent.com/43372856/141820543-019b1cbb-6cbb-47ab-952f-85ed38d266a6.png)
使用astraea時的情況：
consumer完成：
![15087195405171](https://user-images.githubusercontent.com/43372856/141820552-33ed0e0f-cc23-4ae8-8664-214812db63e6.png)
producer完成：
![15087195187412](https://user-images.githubusercontent.com/43372856/141820594-2c72dc94-086c-455a-82b4-56d06489cc42.png)

這是盡力壓榨後的結果，consumer完成時間快了64s，相當於提升了25.4%效能
producer完成時間快了21s，相當於提升了12.9%的效能。

**Comment by chia7712** [comment]
> consumer完成時間快了64s

這是考慮讀寫混合的情境（例如某些partitions正忙著處理fetch）嗎？理想上我們的確要測讀寫混合的情境，不過我們可否先以純寫為主，確認此partitioner針對純寫的環境能達到多高的效能改善？因此可否先把consumers關掉，然後看看吞吐量能否拉到接近100MB (當replica = 1的時候)

**Comment by chia7712** [comment]
另外建議把測試的數據弄成表格（可以用google docs），然後把連結貼到description，這樣會比純圖片好閱讀

**Comment by wycccccc** [comment]
好的 我再針對producer的情況進行測試。

**Comment by chia7712** [comment]
@wycccccc 我條列幾個現階段需要測試的（純寫）變因，該些項目排列組合後就是要測試的情境

1. 節點之間是平衡的/歪斜的
2. 有無key值
3. key的分佈是平均/歪斜的 (例如30% key是類似的，70%key是獨立的)
4. 大/小資料 (例如1KB V.S 1MB)

上述的關於key的部分有描述在https://github.com/skiptests/astraea/issues/26#issuecomment-971319602

@chinghongfang 看看你是否有時間完成，不然我先介入也可以
