### ISSUE TITLE
關於相依性資料partitioner的處理方式

### ISSUE THREAD

**Issue by wycccccc** [skiptests/astraea#79]
目前版本的partitioner並沒有考慮到key值對partition位置的影響，舉個例子：
舉個例子，你遇到第一筆資料後根據分佈得出放到第一個partition最好，但後面連續一千筆因為相依性的關係，通通也要放到同一個partition，這時候第一筆資料就不是一個獨立的事件，而是會產生更長遠的影響。而目前的系統只會將其作為一個獨立事件進行計算。
而Kafka資料在很多情況下都存在相依性，為此能夠處理此種情況的partitioner我認為可以作為下一階段的開發方向。

**Comment by wycccccc** [comment]
想確認一下“使用者會自己指定partition”的意思應該是值不調用我們的partitioner使用者自己指定對嘛。

>這個producer在寫入資料時並非每一筆都會經過partitioner，而是只有其中幾筆，這樣目前的partitioner可以應付嗎？

這沒有問題，已經有了一些初步的測試證明確實可以使負載較重的broker減少partitoer的接受量。（通過向某一個broker不斷發送消息，然後再向所有broker發送消息，最後比較前者狀況得出）明日再經過一些測試就能做一個比較全面的總結了。順便還有一些參數遊戲需要弄一下（possion計算得出結果後換算成最後的權重這一過程的參數），這個也需要更多測試才能有感覺。

**Comment by chia7712** [comment]
> 想確認一下“使用者會自己指定partition”的意思應該是值不調用我們的partitioner使用者自己指定對嘛。

對，使用者自行指定partition後，producer就不會調用partitioner

**Comment by wycccccc** [comment]
需要做到使用者可以決定是否這次producer的資料都需要被傳送到一個partition中，這個partition將由我們來挑選並決定。目標是找到目前狀況較好的partition（通過cpu，內存，thoughput情況進行預測決定）。

**Comment by wycccccc** [comment]
接 #138  討論
之前提到的多執行序呼叫安全問題我想確認一下。
具體可能發生的問題，我能想到的是多個執行序同時呼叫開始或者關閉造成狀態的錯誤轉換。

還是說有多個執行序呼叫同一個producer想要執行dependency，然後其中一個結束了dependency，但其他執行序並沒有要結束dependency。這時候就應該繼續dependency直到所有執行序都發出結束請求。要實現這種情景？

**Comment by chia7712** [comment]
> 還是說有多個執行序呼叫同一個producer想要執行dependency

我講的案例是多個執行緒呼叫“不同的producer"

**Comment by wycccccc** [comment]
> 我講的案例是多個執行緒呼叫“不同的producer"
那就沒有問題，他們彼此獨立不會有干擾

不過我想確認一下，實際會有這種多個執行序呼叫同一個producer想要執行dependency的情況嘛？
如果有的話我，上述我提到的兩點我感覺也會是使用情景中會發生問題的情況，我再去對這些情況進行處理。

**Comment by chia7712** [comment]
> 實際會有這種多個執行序呼叫同一個producer想要執行dependency的情況嘛？

考量kafka producer是thread-safe，因此或許我們應該也要支援，但可以先當作限制等之後再完成

**Comment by chia7712** [comment]
> 那就沒有問題，他們彼此獨立不會有干擾

我不太確定`DependencyManager`的用途，因為現在`DependencyManager`被共用，因此在多執行緒下，它的`currentState`可能會錯亂

**Comment by wycccccc** [comment]
> 我不太確定DependencyManager的用途，因為現在DependencyManager被共用，因此在多執行緒下，它的currentState可能會錯亂

抱歉它不應該是static的，這一定是我半夜寫得代碼，我會在最新的pr中順便修正。

**Comment by chia7712** [comment]
#541 is follow-up
