### ISSUE TITLE
基於過去全局資訊預測未來最佳部署的partitioner

### ISSUE THREAD

**Issue by chia7712** [skiptests/astraea#8]
# 基於過去全局資訊預測未來最佳部署的partitioner

## 研究問題的重要性
隨著kafka在業內的地位愈發提高，隨之帶來的需求也不斷深化。如今越來越多的使用者提出希望Kafka集群能夠有更好的Load balancing。本項目旨在根據集群過去全局資訊對未來partitioner進行預測。幫助集群的每一個node在接受producer資料時能保持一個均衡的負載情況。

## 研究目的
當分區沒有因為使用者需求而被指定時，kafka提供的默認分區器的目的只是為了將相同數量的消息分配給每一個分區。這就會導致一個問題，分區器關注的會是分區間的平衡，如果分區器選擇的partition連續都在同一個node的時候就會導致該node負載上升，影響kafka的效能。同時kafka使用者往往會面臨同時生產和消費數據的情況。當node因consumer消費數據消耗了大量硬體資源，此時如果partitioner再分配給該node下的partition，顯然很有可能造成資源瓶頸使得整個資料生產消費的過程都受到影響。因此基於過去全局資訊預測來進行partitioner的判斷是一種可行的解決方案。 

 

通過監測node的負載情況，根據possion算法預測未來情況，挑選最合適的node

避免以下兩種情況： 

* 單一node在負載高的情況下還會被選擇 
* 避免在短時間內連續選擇同一個node導致他的負載升高過快 

 

要做到以下兩點： 

* 使整個集群中每個node的負載情況與集群的平均值儘量接近 
* 降低node的閒置率 

## 目前的研究方案
![](https://i.imgur.com/ZNHOZ2F.png)

![](https://i.imgur.com/aDzPgz8.png)
負載值：從JMX中獲取producer的metrics
負載均值：根據每個node的metric設立閾值
負載情況：是一個累加的數，當我的負載值超過負載均值會記錄負載情況加一
負載情況均值：集群中負載情況的平均值
n：集群中負載情況的平均值+1
λ：當前node的負載情況

計算得出下一單位時間小於等於負載情況的概率
P(N(1)<n)=1-P(N(1)n-1)...-P(N(1)0)

設立一個閾值（<50%/<60%）滿足這個閾值的情況被歸為符合標準的node，加入到list中。
ADV：每一次發送消息都要計算partition的話，會導致需要的等待從JMX抓到數據再進行計算，會有比較高的latency。
maintain一個數據的話就可以直接從中拿取，但這樣可能無法做到每次發送消息的時候都是最新的狀態，每次都拿最優可能導致集中發到那個node，因此維護一個list從中選取可以避免某一個node在一段時間負載陡然增加。

## 研究方法的改進
* 負載值與負載均值的計算方式：目前的設想是根據BrokerTopicMetrics中的BytesInPerSec（網路流入速率）來進行負載值的計算。
是否可以加入更多的metrics進行負載值的計算。（需要確認我能調取到哪些資料）
均值的計算方式目前為加權平均，對機器1S內，1min內平均速率，5min內平均速率進行加權。（是否有更好的計算方式）
* 閾值的判定範圍對實際效能的影響，找到比較適合的閾值
* 確定node後選擇partition的方式決定（取餘、根據metrics判斷、或是再進行一次poisson）
* 借鑒前人的研究方法也很重要，查閱別人做的有關kafka balance的論文，集思廣益。

## 優化方案
[partitioner進一步優化方案.pdf](https://github.com/skiptests/astraea/files/8051104/partitioner.pdf)

## Tasks

- [x] 實作能夠檢測存儲每一個node的負載量的物件
- [x] 實作以poisson進行預測判斷的partitioner
- [x] 整合Kafka broker metrics完成整個系統
- [ ] 進行效能測試並優化程式

**Comment by chia7712** [comment]
@wycccccc 再麻煩幫忙完成此議題的描述

**Comment by wycccccc** [comment]
> @wycccccc 再麻煩幫忙完成此議題的描述
好 我會在近期完成

**Comment by wycccccc** [comment]
# 基於過去全局資訊預測未來最佳部署的partitioner

## 研究問題的重要性
隨著kafka在業內的地位愈發提高，隨之帶來的需求也不斷深化。如今越來越多的使用者提出希望Kafka集群能夠有更好的Load balancing。本項目旨在根據集群過去全局資訊對未來partitioner進行預測。幫助集群的每一個node在接受producer資料時能保持一個均衡的負載情況。

## 研究目的
當分區沒有因為使用者需求而被指定時，kafka提供的默認分區器的目的只是為了將相同數量的消息分配給每一個分區。這就會導致一個問題，分區器關注的會是分區間的平衡，如果分區器選擇的partition連續都在同一個node的時候就會導致該node負載上升，影響kafka的效能。同時kafka使用者往往會面臨同時生產和消費數據的情況。當node因consumer消費數據消耗了大量硬體資源，此時如果partitioner再分配給該node下的partition，顯然很有可能造成資源瓶頸使得整個資料生產消費的過程都收得影響。因此基於過去全局資訊預測來進行partitioner的判斷是一種可行的解決方案。 

 

通過監測node的負載情況，根據possion算法預測未來情況，挑選最合適的node

避免以下兩種情況： 

* 單一node在負載高的情況下還會被選擇 
* 避免在短時間內連續選擇同一個node導致他的負載升高過快 

 

要做到以下兩點： 

* 使整個集群中每個node的負載情況與集群的平均值儘量接近 
* 降低node的閒置率 

## 目前的研究方案
![](https://i.imgur.com/ZNHOZ2F.png)


![](https://i.imgur.com/aDzPgz8.png)
負載值：從JMX中獲取producer的metrics
負載均值：根據每個node的metric設立閾值
負載情況：是一個累加的數，當我的負載值超過負載均值會記錄負載情況加一
負載情況均值：集群中負載情況的平均值
n：集群中負載情況的平均值+1
λ：當前node的負載情況

計算得出下一單位時間小於等於負載情況的概率
P(N(1)<n)=1-P(N(1)n-1)...-P(N(1)0)

設立一個閾值（<50%/<60%）滿足這個閾值的情況被歸為符合標準的node，加入到list中。
ADV：每一次發送消息都要計算partition的話，會導致需要的等待從JMX抓到數據再進行計算，會有比較高的latency。
maintain一個數據的話就可以直接從中拿取，但這樣可能無法做到每次發送消息的時候都是最新的狀態，每次都拿最優可能導致集中發到那個node，因此維護一個list從中選取可以避免某一個node在一段時間負載陡然增加。



## 研究方法的改進
* 負載值與負載均值的計算方式：目前的設想是根據BrokerTopicMetrics中的BytesInPerSec（網路流入速率）來進行負載值的計算。
是否可以加入更多的metrics進行負載值的計算。（需要確認我能調取到哪些資料）
均值的計算方式目前為加權平均，對機器1S內，1min內平均速率，5min內平均速率進行加權。（是否有更好的計算方式）
* 閾值的判定範圍對實際效能的影響，找到比較適合的閾值
* 確定node後選擇partition的方式決定（取餘、根據metrics判斷、或是再進行一次poisson）
* 借鑒前人的研究方法也很重要，查閱別人做的有關kafka balance的論文，集思廣益。

**Comment by chia7712** [comment]
@wycccccc 再麻煩新增一個欄位用來描述接下來的工作，試著把工作拆分出來看看，謝謝

**Comment by chia7712** [comment]
@wycccccc 另外，麻煩將文字貼到description欄位裡面

**Comment by wycccccc** [comment]
@chia7712 是貼到這裡嗎，好我再創建一個欄位描述下之後的工作。

**Comment by chia7712** [comment]
感謝更新！

**Comment by wycccccc** [comment]
@chia7712 
我在完成程式的過程中產生了一些問題，想要討論得到一些建議。
在目前的設計中我採用了如下步驟計算partitioner：
1.根據所有node流量的平均值+標準差與每一個node當前流量進行比較，判定是否是overload，是的話記錄一次。
2.取一段時間內的結果比如10s，作為某段時間內node，overload的情況
3.將上面的值帶入poisson，lambda 為常數取每個節點的overload的均值 。再分別對每個node的overload進行poisson，K取小於等於每個節點這段時間內（10s）的負載值 
4.最終每個node的possion會得到一個該node的百分數，我再根據這個百分數求得每個node的權數。再根據權數進行平滑加權輪詢(smooth weighted round robin algorithm)得到結果

但在我的視角中這樣會產生一些問題，例如我的第一步是根據當前node流量進行比較的，那如果我從jmx中的數據為一秒更新一次，那麼我10s內最高也只能拿到十次。那相當於我10S內最多也只能判定10次二階段，也就是10次overload。
那麼進入三階段poisson之後，實際上預測值K作為11也是在公式中存在概率的，但是因為實際程序設計問題11次是不存在那麼這樣我還能使用poisson嘛，這樣算出來的概率是否還合理。

**Comment by chia7712** [comment]
> 例如我的第一步是根據當前node流量進行比較的，那如果我jmx中的數據為一秒更新一次，那麼我10s內最高也只能拿到十次有價值的數據。那相當於我10S內最多也只能判定10次二階段

對，這就之前討論說我們到底能拿到”多接近“真實狀況的叢集狀態

> 那麼進入三階段poisson之後，實際上預測值K作為11也是在公式中存在概率的，但是因為實際程序設計問題11次是不存在那麼這樣我還能使用poisson嘛，這樣算出來的概率是否還合理。

我想再釐清一下用possion去算概率的目的：

1. 為何使用概率？考量你假設partitioner可以取得“全局”的資訊，在每次計算的當下誤差會大到需要引入“概率”嗎？

2. 為何選擇poisson去算？partitioner要解決的情境是“系統處於大量資料寫入”的狀況，在概率上的計算會比直接用hash來得好嗎？

3. 為何需要考慮打到哪一個partition? 在同一個節點上的partition選哪一個有何分別？或是這假設該些partition都在不同硬碟上？如果是的話，我們要怎麼去給該些partition“評分”?

**Comment by wycccccc** [comment]
1.應該說我是用權重在決定最後會去哪個node，piosson計算出的概率是我設定權重的指標。

2.我感覺我目前將問題的情景定位在“動態分配每個node寫入的數據，使整個集群的每個node寫入數據的情況儘量接近”。這裡提到的用hash的概率是指碰撞概率嘛，我提到的的概率更像是這之後node會繼續這樣偏離集群平均負載的概率。

3.抱歉，可能是我腦子打結講錯了，目前設想中還不需要給partition評分，給node進行評分就可以了。

現在piosson已經寫完了，我打算先之後試試效果，看情況好懷再做決定。感覺這個問題還牽扯到一些數理，我大概再去找對此很擅長的老闆討論看看。

**Comment by chia7712** [comment]
> poisson計算出的概率是我設定權重的指標

kafka的使用情境中蠻容易遇到資料的發生是有相依性的，例如連續的一千筆資料要放在同一個partition (broker），因此要如何用poison來把這批有關聯的資料對應到獨立的時間區段？換言之，你無法把每個時間區段的事件視為獨立事件而去套用poison 。我舉個例子，你遇到第一筆資料後根據分佈得出放到第一個partition最好，但後面連續一千筆因為相依性的關係，通通也要放到同一個partition，那這個狀況該如何處理？

當然最簡單就是說，使用你的演算法就別去想資料順序了，通通無序且無法設定或調整。不過這樣就是一個蠻大的侷限就是了

**Comment by wycccccc** [comment]
哈哈，這個資料相依性的問題我一開始也想到了。但那時感覺根據key的值去選定partition/node與根據jmx的數據判定該給哪個node有些衝突。或許也有機會將這兩個結合？我會再去思考一下看看這方面的問題。順便我想問一下，有關相依性一般都是根據producer的key來產生的嘛，還會有其他的做法嘛。

**Comment by chia7712** [comment]
> 順便我想問一下，有關相依性一般都是根據producer的key來產生的嘛，還會有其他的做法嘛。

我講的相依性大多是要求happen-before，而kafka這邊能保障happen-before的方式就是仰賴key...

**Comment by wycccccc** [comment]
在實際環境中往往會產生機器間的異格（不同的規格）情況。這會導致不同node的partition所能處理信息的能力存在差異化。添加cpu與jvmUsage進行判斷指標就變得十分有意義。
以此我得出了兩種方法：

理論上cpu與jvmUsage的使用率應該與thoughput是正相關。而cpu與jvmUsage這兩值應該也會隨著處理資料量的增加而增加。因此重新設計overload計算方式，將jvmUsage使用百分率與thoughput進行關聯。例如一台機器50%jvmUsage能處理300MB/s的數據，而另一台50%能處理500MB/s。計算剩餘計算機可能存在的餘力，餘力較少（少於均值一定程度）的觸發overload。
該方法的難點在於，50%jvm使用率可能不全是kafka造成的？可能一個機器裡面裝的不僅僅是kafka？我推測這樣的情況在實際環境中肯定不在少數。這會導致很難去判斷kafka傳輸這些資料究竟會用多少jvmUsage？而且計算得出得餘力可能並不是真正的餘力，因為瓶頸往往出現在網路與disk的thoughput上。可能只是jvmUsage還擁有餘力，網路與disk已經沒有了。

第二種就相對簡單，將我們partitioner的目標指定為榨乾網路與disk。而jvmUsage這類硬體資源設置一個閾值作為警報。超過這個閾值（80%？）將極大的增加權重促使其在短時間內不會被分配到partitioner。

我認為第二種更加合理且可被執行，雖然計算出實際餘力這件事十分誘人。但我感覺生產環境各不相同，實際餘力真的是能夠通過收集jmx mertrics能被計算出來的嘛。這裡我想參考一下學長意見，如果這件事是能被做到的，我會再思考以計算餘力的方式去做。

**Comment by chia7712** [comment]
> 50%jvm使用率可能不全是kafka造成的？可能一個機器裡面裝的不僅僅是kafka？

這兩句有點怪怪的，實務上一個JVM的資源一定都是給一個kafka使用，但一台機器上的確可能不只跑一個JVM，也就是一台機器的硬體資源不一定都是給kafka使用。

但我們可以假設都是給kafka，因為生產環境中kafka為主力服務時不會讓它跟其他服務共享硬體資源

**Comment by wycccccc** [comment]
# 基於過去全局資訊預測未來最佳部署的partitioner優化方案

## though put metrics相關優化
![image](https://user-images.githubusercontent.com/43372856/147770484-b91f4790-f47d-4f40-b2df-d4dcb5090ff0.png)
![image](https://user-images.githubusercontent.com/43372856/147770565-7d691f91-e3ad-4cc7-9da8-a242b0b640dc.png)
![image](https://user-images.githubusercontent.com/43372856/147770612-aed68092-783d-49d4-950b-e9ce75819876.png)
![image](https://user-images.githubusercontent.com/43372856/147770678-8abb5e6a-982b-4e31-9d78-d9692392f41e.png)

## 對於不同規格的機器帶來的though put能力差異進行優化
![image](https://user-images.githubusercontent.com/43372856/147771046-d386f2f9-9d20-46f7-bd71-dcc9e18e7d1b.png)
![image](https://user-images.githubusercontent.com/43372856/147771098-5938f34e-87e2-4737-8472-2554ec8a5375.png)
![image](https://user-images.githubusercontent.com/43372856/147771166-4a9ace44-2e25-4918-a789-3e5d6394d447.png)
![image](https://user-images.githubusercontent.com/43372856/147771196-4a8414e8-f77b-4943-923d-41f3b320a506.png)

## 其他輔助判斷的metrics
![image](https://user-images.githubusercontent.com/43372856/147771252-15e5bd8b-7b99-421e-96cf-3471cd1b19a3.png)

**Comment by wycccccc** [comment]
這是下一步的優化方案，算是一個初步的正式partitioner。我會在完成自動測試內容後開始處理優化邏輯。

**Comment by chia7712** [comment]
> 這是下一步的優化方案，算是一個初步的正式partitioner。我會在完成自動測試內容後開始處理優化邏輯。

可否縮成一份pdf然後當成附檔放在描述裡面？

**Comment by chia7712** [comment]
> 減少load最大和最小間機器的差距

這邊的load是指吞吐量嗎？如果是的話，就只能面對比較單純的問題。但實際上partitioner要考慮的東西不能只有吞吐量，例如三台機器，有兩台忙著應付consumer，只有一台比較閒，因此只看吞吐量就會造成資料都集中往那一台身上集中，這樣之後反而會形成讀取端的hotspot。
像上述這種要考慮多個面向的就剛好可以用cost function的架構去解，套用多個cost function和各自的比重，當資料量逐漸傾斜時負責資料分布量的cost就會逐漸拉高，進而減低吞吐量cost的比重，如此partitioner在分散資料時的考量就會被資料分布而影響

> 但目前這個應該會是研討會文章的題目我會將其作為等同研討會的進度來按照其時限完成上述情景。現在的情況異質的部分應該要暫緩了，五月可以開始處理異質問題，實作驗證我的想法。

就時間來說，異質的優先權沒那麼高。首要目的應該是讓partitioner能適應多種情況，而非只著重在吞吐量

**Comment by chia7712** [comment]
工作已經一個段落，故關閉
