### ISSUE TITLE
協助測試GUI

### ISSUE THREAD

**Issue by chia7712** [skiptests/astraea#824]
Astraea 現在有兩種方式提供使用者來串接方便的功能，一種是 web api (https://github.com/skiptests/astraea/blob/main/docs/web_server/README.md)、另一種是則是透過 GUI (https://github.com/skiptests/astraea/blob/main/docs/run_gui.md)

目前大部分的功能都已經擺放到GUI上面，需要大家提供一些使用反饋和想法

**Comment by chaohengstudent** [comment]
收到

**Comment by chaohengstudent** [comment]
測試後的一些想法：

- 欄位無法完整顯示
  /config tab 的標籤
   ![image](https://user-images.githubusercontent.com/106939297/194049945-65bab4fe-7e1b-4620-9c5f-f724a6c2259f.png)
   
  /partition tab -> max timestamp 內部欄位
   ![image](https://user-images.githubusercontent.com/106939297/194050074-ae32000b-a011-49c6-9143-627c3ef4821e.png)
- 雖然欄位可以拖曳更改排版順序或調整顯示寬度，但每次 search 都會回復初始狀態
- reassign replica tab 和 balance topic tab 操作邏輯不一致，在 reassign replica 選完條件後可能會誤按 search
  reassign replica：1.選擇條件 2.apply 變更     3.search 更新
  balance topic ：1.選擇條件 2.search 更新  3. apply 變更
- bootstrap servers tab 若輸入錯誤必須等到 timeout 才能做下一次搜尋，無法取消
- config tab 如果輸入任意文字會導致結果無法顯示
  ![image](https://user-images.githubusercontent.com/106939297/194057015-f69455bb-df18-4cdb-9819-15496cdd90f6.png)
- 介面位置偏上
  ![image](https://user-images.githubusercontent.com/106939297/194052812-71f27e7f-9616-4099-9e04-a739a636cc17.png)

**Comment by chia7712** [comment]
@Haser0305 感謝協助測試和回饋意見，以下純粹討論～

> 欄位無法完整顯示

搜尋完後直接幫使用者展開會比較方便嗎？

> 雖然欄位可以拖曳更改排版順序或調整顯示寬度，但每次 search 都會回復初始狀態

同上

> reassign replica tab 和 balance topic tab 操作邏輯不一致，在 reassign replica 選完條件後可能會誤按 search

這個很有道理，或者我們改成"reassign replica tab"只有在搜尋完後才會跳出選擇條件如何？

> bootstrap servers tab 若輸入錯誤必須等到 timeout 才能做下一次搜尋，無法取消

這比較是技術問題了，kafka 建構後必須等到 timeout，但或許我們可以假設超過多久沒有成功就直接取消？你覺得如何

> config tab 如果輸入任意文字會導致結果無法顯示

這代表沒有匹配關鍵字的內容

> 介面位置偏上

請問是指哪個部分？表單內容嗎

**Comment by chaohengstudent** [comment]
> 搜尋完後直接幫使用者展開會比較方便嗎？

以 config tab 來說原本標題就有依照標題長度做適應，但好像就差一點點就顯示完畢，因此想說是不是原本希望做展開。
>這個很有道理，或者我們改成"reassign replica tab"只有在搜尋完後才會跳出選擇條件如何？

>這比較是技術問題了，kafka 建構後必須等到 timeout，但或許我們可以假設超過多久沒有成功就直接取消？你覺得如何

聽起來不錯
>請問是指哪個部分？表單內容嗎

表單內容顯示欄位列數會依照頁面上至下長度做適應縮放，但大到一定高度後會固定，感覺版面可以容納更多列數？

**Comment by chia7712** [comment]
> 這個很有道理，或者我們改成"reassign replica tab"只有在搜尋完後才會跳出選擇條件如何？

https://github.com/skiptests/astraea/pull/843 重新排了一下順序， @chaohengstudent 方便的話可否幫忙查看一下

**Comment by chaohengstudent** [comment]
剛剛測試了最新的版本，目前沒有使用上沒有問題。

**Comment by chia7712** [comment]
> 剛剛測試了最新的版本，目前沒有使用上沒有問題。

感謝 等待 https://github.com/skiptests/astraea/pull/879 合併後，可否麻煩你協助更新 GUI docs文件？裡面應該有些圖已經過時，也請你在更新過程中順便再操作看看，給予一些反饋

**Comment by chaohengstudent** [comment]
好的
