### ISSUE TITLE
聖誕節主委加碼送愛心

### ISSUE THREAD

**Issue by chia7712** [skiptests/astraea#830]
這是一個為了聖誕節做準備的議題，Astraea 專案正式迎來第一個聖誕節，因此要來準備第一屆的貢獻者抽獎活動！

**聖誕禮物**

1. iPhone 14 pro 1TB 金色 @wycccccc 
1. MagSafe 行動電源 @garyparrot 
1. Razer雷蛇 無線藍牙耳機 (忘了抽)
1. 全家禮券 1000 元 @g1geordie 
1. 全家禮券 700 元 @chaohengstudent 
1. 日本AWSON歐森 手持式蒸氣熨斗 @garyparrot 
1. 九陽可口可樂多功能煎烤盤 @Haser0305 

**規則辦法**

1. commit 10 ~ 20 次有一支籤、20~30次有兩支籤，以此類推
3. 12/20 (二) 23:59 統計 commits 次數、12/21 (三) 直播抽獎
4. 抽獎順序將由最小獎開始抽
5. 每一支籤只能對應一個獎品，例如你只有一支籤，並且已經抽到三獎，那妳就無法參與二獎和大獎的抽籤。
6. 有意願參加抽獎的貢獻者需要在此議題留言，證明你還是活人一枚

**其他**

1. 獎品以及規則辦法可能視情況微調
3. 中獎者可來現場領取獎品或是透過包裹寄送

抽獎影片

https://m.facebook.com/story.php?story_fbid=602308608367596&id=1757455551&mibextid=qC1gEa

**Comment by chia7712** [comment]
@brandboat @g1geordie @chinghongfang @wycccccc @harryteng9527 @garyparrot @qoo332001  FYI

@Haser0305 @chaohengstudent 希望你們也能獲得一支籤 :)

**Comment by brandboat** [comment]
感恩大大，讚嘆大大，我會開始刷 typo 的！

**Comment by g1geordie** [comment]
WOW YA  聖誕節來了

**Comment by Haser0305** [comment]
會努力試試的

**Comment by chinghongfang** [comment]
感謝主委！！

**Comment by qoo332001** [comment]
感謝主委！！

**Comment by garyparrot** [comment]
感謝主委！！🥳 🎁

**Comment by wycccccc** [comment]
感謝主委的聖誕活動，希望能將禮物帶走

**Comment by harryteng9527** [comment]
謝謝主委，讚讚甲上

**Comment by chaohengstudent** [comment]
會繼續努力

**Comment by douenergy** [comment]
這樣誰會不喜歡開源專案  🎅🏼🎅🏼🎅🏼

**Comment by chia7712** [comment]
2022/10/26 更新抽獎清單如下：

1. iPhone 14 pro 1TB 金色
1. MagSafe 行動電源
1. Razer雷蛇 無線藍牙耳機
1. 全家禮券 1000 元

**Comment by chia7712** [comment]
11/11 新增 九陽可口可樂多功能煎烤盤

**Comment by chia7712** [comment]
活動已經結束，忘了抽的項目會等到明年中再來抽
