### ISSUE TITLE
Strict Cost Dispatcher 優化

### ISSUE THREAD

**Issue by chinghongfang** [skiptests/astraea#836]
https://github.com/skiptests/astraea/pull/816#discussion_r986531076

在測試 Astraea Dispatcher 的 interdependent 功能時，發現到特別的現象，"為 dispatcher 增加 interdependent 的限制延遲反而降低"，這也說明了原本 Strict Cost Dispatcher 做出的選擇不是最佳解，還有進步的空間。

**Comment by chia7712** [comment]
duplicate to #1265
