### ISSUE TITLE
將目前的測試中使用的`Admin`改成用`AsyncAdmin`

### ISSUE THREAD

**Issue by chia7712** [skiptests/astraea#849]
如題，讓我們逐步走向非同步的懷抱

另外這個議題並不用一隻PR完成，反之，我們鼓勵一個一個測試逐一修改，這樣比較不會有重大衝突

related to #837

**Comment by chia7712** [comment]
@chaohengstudent @Haser0305 FYI

如果遇到`AsyncAdmin`尚未支援的功能還請協助開新議題，逐步豐富功能

**Comment by Haser0305** [comment]
了解

**Comment by chaohengstudent** [comment]
了解

**Comment by chia7712** [comment]
fixed by #1020
