### ISSUE TITLE
Introduce jdbc connector

### ISSUE THREAD

**Issue by brandboat** [skiptests/astraea#870]

**Comment by brandboat** [comment]
gentle ping @chia7712

**Comment by chia7712** [comment]
可能有幾件事情要處理：

1. 封裝 kafka source/sink connector/task 作為基本型別，並且加上一些共同的程式碼放在 connector 模組
2. 需要討論一個共同的資料格式，讓 kafka consumer/producer, kafka source/sink, and spark etl 都可以使用。目前 @wycccccc 在處理的 #761 中 key=csv (由pks 組成）value=json (由欄位+值組成），由於 spark 整合kafka這段只支援 bytes and string，因此我們無法用 kafka serializer/deserializer 來處理。也就是說需要大家 (@wycccccc @brandboat ）訂出一個格式彼此遵守，這樣才能確保資料可以暢行無阻。
3. 承接上述， @brandboat 依然需要實作一個 csv serializer/deserializer 和 json serializer/deserializer 並且放在 common 模組，讓 producer/consumer 可以使用，然後 sink/source 在包裝 serializer/deserializer成為 converter，這樣至少確保 kafka 的元件可以使用到共同的轉換邏輯
4. Perf tool 也要能支援上述的資料格式，這樣方便我們後續做壓力測試。 @chaohengstudent @Haser0305 看你們是否有空幫忙
5. Jdbc connector 需要放到一個獨立的模組開發，並且引用 common and connector兩個模組，獨立一個模組的原因是避免dependencies污染，因為不同的connector實作可能會拉進很多不同的專案
6. 還需要研究一下 jdbc connection pool，這邊可以考慮用第三方的元件（例如HikariCP），不過一樣要先定義一個Astraea 獨有的介面，底層的實作再以第三方（或是先自己做一個簡單的版本），這樣方便之後抽換

一些想法，謝謝

**Comment by chia7712** [comment]
@wycccccc @brandboat 我再補充一下現在的狀況，為了讓資料流能在不同的技術中互通 (producer/consumer, connector, spark, streams)，我會建議把 key and value 都使用字串，並且搭配CSV/JSON 等等作為字串格式，然後以UTF8轉換成byte array，這樣在上述已知的技術中都是可以操作，同時也要確保"字串相等=位元組相等"的邏輯，因此我會建議以下規則：

1. key and value 都以 json 字串來存放
2. json 內的順序依照字典排序
3. 元素與元素之間不要有任何多餘字符（例如空白）
4. key 的內容只放 primary key
5. value 的內容放所有資料
6. 要支援 nested type
7. 當兩個json的比對相同時，該兩個Json的byte array比對也要一致

@brandboat @wycccccc 麻煩你們看一下有沒有其他想法？ @wycccccc 雖然 #761已經合併，但如果討論後有其他想法的話還請協助修正

另外 @g1geordie 你在 #848 有做一隻通用的 object <-> json 之間的轉換邏輯，可否協助看看能否達到上述條件的 2), 3) and 7) ? 如果可行的話，後續 json 與物件的轉換就可以套用 #848 的結果

**Comment by chia7712** [comment]
> 如果想要達成7的話 我們是不是需要再訂義一個 特別的物件去包裝 String 來確保他們是一樣的
像是下面這樣


我的想法是盡量不要讓使用者需要去費心這一段，所以我比較偏好是說只要是兩者的json相同，那我們就要確保 byte array 也相同，換言之，我們產生的 json string 要保持一致，舉個例子：
```json
{
  "a": "b",
  "c": "d"
}
```
```json
{
  "c": "d",
  "a": "b"
}
```

上述兩個在 json 的角度來說是等價的，但是以 byte array 來看會不等價，因此我們要確保當使用者輸入 Map.of("a", "b", "c", "d")和Map.of("c", "d", "a", "b")時，會產生一模一樣的 json 字串

**Comment by g1geordie** [comment]
了解  我原本的想法是  
當input 不是我們產生的時候 那json 就有可能不是等價的了

**Comment by chia7712** [comment]
> 當input 不是我們產生的時候 那json 就有可能不是等價的了

我的想像是說 任何的 input 都要透過你開發的 json converter 來轉換成 json string ，因此json字串等價和 byte array 等價是希望由你這邊來保持

**Comment by wycccccc** [comment]
好 1 4 5 我會在json converter完成後再導入，資料的格式也會一併在那時候修改。有關6我認為利用StructType遞歸調用converter應該就行。不過csv似乎不支持nested type，這代表我在讀properties的時候，傳入的`column.name`就要支持進行nested處理。
如果上面那些我沒講錯的話，我會在json converter完成後處理這些內容。

**Comment by chia7712** [comment]
> 不過csv似乎不支持nested type，這代表我在讀properties的時候，傳入的column.name就要支持進行nested處理。

spark 那段目前先處理 csv 作為 input 資料，kafka這邊則是先處理 database (jdbc) 作為輸入，所以 spark 還不會遇到需要處理 nested type

> 如果上面那些我沒講錯的話，我會在json converter完成後處理這些內容。

這邊要研究一下假如 @g1geordie 做完 json converter 後，要如何跟 spark structure streaming 整合

**Comment by wycccccc** [comment]
比較麻煩的地方應該是col name 與col value的配對問題
我目前只想到了一個方法，利用UDF將查詢到的所有數據Column*傳進去，然後在UDF裡面將cols的值Seq[String]與`column.name`一一配對成Map（因為只要不Shuffle，這些數據都是順序的），然後丟給json converter。

> 只要不Shuffle，這些數據都是順序的

我不能百分百確定，如果要這麼做的話，我會再寫測試確認。

**Comment by chia7712** [comment]
> 我目前只想到了一個方法，利用UDF將查詢到的所有數據Column*傳進去，然後在UDF裡面將cols的值Seq[String]與column.name一一配對成Map（因為只要不Shuffle，這些數據都是順序的），然後丟給json converter。

或是用`map`將DataFrame先進行DataSet的操作，然後再重新貼上column轉回DataFrame，這樣在`map`的階段可以套用json converter 把 csv line轉成兩個json string，然後再貼上key and value再塞回Kafka

> 只要不Shuffle，這些數據都是順序的

不好意思，我不太確定這邊指的shuffle是哪一個階段？如果是在講rdd partition的分佈的話，這應該跟我們討論的話題無關，因為 partition 是橫切，不管怎麼分到哪一個節點，該節點都可以看到該line的完整資訊，json內容的順序的話，則是依照key order就好

**Comment by brandboat** [comment]
@chia7712 我這邊還是有些疑問，再麻煩您解惑了 🙏 

在 https://github.com/skiptests/astraea/issues/870#issuecomment-1274060074 中
> 依然需要實作一個 csv serializer/deserializer 和 json serializer/deserializer 並且放在 common 模組，讓 producer/consumer 可以使用，然後 sink/source 在包裝 serializer/deserializer成為 converter，這樣至少確保 kafka 的元件可以使用到共同的轉換邏輯

這邊的 csv, json serializer/deserializer 為的是上面提及的 "定義好的共同格式" 這件事是嗎？csv 為 pks value 為 json 欄位名稱: 值。`然後 sink/source 在包裝 serializer/deserializer成為 converter` 這一句我比較不清楚，converter 會與 connect sink / source api 有關聯嗎？原本的認知是會由我們自己封裝的 key/value converter來處理 csv 形式的 key 以及 json 格式的 value。

然後在 https://github.com/skiptests/astraea/issues/870#issuecomment-1274166642 中
> 1. key and value 都以 json 字串來存放

所以之後都統一是由 json 來處理 key & value ? 而非 key 是由 csv 格式處理是嗎？

**Comment by chia7712** [comment]
> converter 會與 connect sink / source api 有關聯嗎？原本的認知是會由我們自己封裝的 key/value converter來處理 csv 形式的 key 以及 json 格式的 value。

簡單一點的話，就是寫一個 sink/source connector，然後內部都是用 #848 會延生的 json 轉換來處理資料，也就是把資料都先轉成 json string，然後再轉成 byte array，接著我們再啟動 sink/source 的時候都使用 byte array converter 避免被二度封裝，這樣就可以在 spark/producer/consumer 之間轉換

另一個事情則是我提到的封裝，原本是希望能先建構一層 abstract source/sink 把 json 轉換隱藏起來，讓 sub class 只要負責倒轉成 json 就好，達到一些 邏輯隔離的效果，不過或許這可以晚一點再弄

> 所以之後都統一是由 json 來處理 key & value ? 而非 key 是由 csv 格式處理是嗎？

是的，一次面對一種格式就好，等之後有機會再來討論其他資料格式

**Comment by chia7712** [comment]
@g1geordie 有機會回頭看這個題目嗎？一開始大概完成幾個項目：

1. 可以將指定的 database 表格導入指定的表格
2. key, value 都是 json，其中 key 為 pk 組成、value則由所有欄位組成
3. 支援 string, number, boolean 三種格式 (for database)
4. 以 mysql 為主要測試目標
5. 支援斷點續傳（也就是要透過 kafka connector storage 來保存已經處理過的資料紀錄，下次執行時可以接續上次的紀錄)
