### ISSUE TITLE
Support to monitor migration progress 

### ISSUE THREAD

**Issue by chia7712** [skiptests/astraea#89]
This is the follow-up of #88.

The migration procedure is running async. We should offer a way to "monitor" the progress. For example, the expected elapsed time or the percentage of progress.

This function can be implemented in `ReplicaCollie` or another new tool

**Comment by garyparrot** [comment]
@chia7712 學長我遇到一些瓶頸，想問一下

> For example, the expected elapsed time or the percentage of progress.

要如何觀測這個過程，我有看到一些 [KIP](https://cwiki.apache.org/confluence/display/KAFKA/KIP-179+-+Change+ReassignPartitionsCommand+to+use+AdminClient#KIP179ChangeReassignPartitionsCommandtouseAdminClient-RejectedAlternatives) 在討論和監控 progress 相關的議題

> ReassignPartitionsCommand currently has no proper facility to report progress of a reassignment; While --verify can be used periodically to check whether the request assignments have been achieved the tool provides no means of knowing how quickly new replicas are catching up. It would be useful if the tool could report progress better.

文內提到了 `--progress` 但是看起來似乎[沒有被實作](https://github.com/apache/kafka/blob/1d22b0d70686aef5689b775ea2ea7610a37f3e8c/core/src/main/scala/kafka/admin/ReassignPartitionsCommand.scala#L1434-L1498)。

我這幾天試著研究了一下這個議題，發現

* `AdminClient#describeLogDir()` 和 `AdminClient#describeReplicaLogDirs()` 內有提供一些和 `Future` 有關的欄位可供參考 [[1]](https://kafka.apache.org/28/javadoc/org/apache/kafka/clients/admin/ReplicaInfo.html#isFuture()) [[2]](https://kafka.apache.org/30/javadoc/org/apache/kafka/clients/admin/DescribeReplicaLogDirsResult.ReplicaLogDirInfo.html#getFutureReplicaOffsetLag())，但是實際上開始搬移實驗後，這些數據都是一些沒意義的數值，`ReplicaLogDirInfo#getFutureReplicaOffsetLag` 總是 -1， `ReplicaInfo#isFuture` 總是 false
* 嘗試用 `KafkaMetrics::TopicPartition::size` 去索取正在搬移的 partition 目前大小，結果發現在開始搬移的那一瞬間整個 `partition` 直接出現在目的地 JMX server，似乎 5GB 的移動資料在開始的瞬間搬好，但我在背景跑的 `du -cksh` 表示 kafka log 還在搬移（目的地的 log dir 大小在增加）

唯一可行的選項只有 `AdminClient#listPartitionReassignment`，但是透過他我們只能知道 "正在搬移" 或 "已經搬好"，沒有那種 percentage 或是預估完成的時間能夠參考。

我想到的另外一個**也許可行**的方法是直接對搬移目的地的 Broker 打 Raw RPC Request (FetchRequest)，嘗試透過直接讀取搬移到一半的 Log 來得到目前已經完成的進度，不過這個想法建立於我們真的能夠讀取到搬到一半的 Log，我還沒測試過這個方法所以不確定是否可行。

保證成功的方法是直接去看 kafka log dir 大小，但是似乎沒有可靠的方法能夠做到。

**Comment by chia7712** [comment]
@garyparrot 可以考慮我們的`TopicAdmin#replicas` (https://github.com/skiptests/astraea/blob/main/app/src/main/java/org/astraea/topic/TopicAdmin.java#L48)，這隻方法會撈回"所有"partitions的replicas狀態，而此時的replicas會有下列三種:

1. 一般的replica
2. 正在從a_broker到b_broker的replica
3. 正在從a_broker的a_folder到b_folder的replica

上述replicas出現的原因各自不同，但這個題目的重點是要看"同步"的進度，因此我們可以參考下列兩個狀態就好:

1. 是否in-sync，如果沒有，代表這著replica有“進度”需要追蹤
2. size，這代表目前這個replica的大小，也就是可以拿來算進度百分比。那麼我們根據哪一個replica的大小作為參考呢？答案是從"leader replica"的大小做為參考

上述就是我的想法，你看一下是否合理~
