### ISSUE TITLE
service-wide data balancer

### ISSUE THREAD

**Issue by chia7712** [skiptests/astraea#90]
這是此專案最重要的一個項目，`balancer`預期可達成下列工作

1. 根據參數監控叢集狀態是否需要負載平衡
2. 產生多個負載平衡策略，並且計算該些策略成本
3. 根據參數和成本選擇最佳的策略
4. 分階段執行負載平衡策略（一次移動太多partition會造成很高的成本）
5. 分次執行策略時持續監控叢集狀態，並適時調整後續策略
6. 策略執行完後產生報表

這個題目應該在#75, #78, #88 and #89 結束後開始動工

**Comment by chia7712** [comment]
@wycccccc 我先把這個議題指定給你，不過我猜真的執行還有一段時間，到時候看狀況再指定給別人也行

**Comment by wycccccc** [comment]
好 看上去是個很綜合的議題，我先消化一下。

**Comment by chia7712** [comment]
https://docs.confluent.io/platform/current/kafka/sbc/index.html

可以參考一下confluent的版本

**Comment by chia7712** [comment]
close as duplicate to #289
