### ISSUE TITLE
[Web APIs] replace Admin by AsyncAdmin

### ISSUE THREAD

**Issue by chia7712** [skiptests/astraea#920]
如同`GUI`全面改用`AsyncAdmin`，web APIs 的部分也應該要跟進，工作項目大致如下：

1. `Handler`取得`Response`的部分要以`CompletionStage`封裝 (https://github.com/skiptests/astraea/pull/921)
1. BrokerHandler/BeanHandler  https://github.com/skiptests/astraea/pull/923
1. QuotaHandler https://github.com/skiptests/astraea/pull/929
1. GroupHandler #936 
1. PipelineHandler #931 
1. ProducerHandler #938 
1. TopicHandler #942
1. RecordHandler #945
1. TransactionHandler #946
1. RebalancePlanExecutor #989
1. ReassignmentHandler #1009 
1. BalacnerHandler #1033

**Comment by chia7712** [comment]
@Haser0305 @chaohengstudent 同樣也麻煩看一下這隻議題，看能否各自挑選幾隻Handler來試著改改看，謝謝

**Comment by chia7712** [comment]
@Haser0305 @chaohengstudent 你們有想幫忙的地方要記得先留言，我會抽空逐一完成，要避免我們做到重複的 handler

**Comment by chaohengstudent** [comment]
我先試著改RecordHandler

**Comment by Haser0305** [comment]
我先改 BalancerHandler

**Comment by chia7712** [comment]
@Haser0305 @chaohengstudent 如果一次改一整隻 Handler 太難的話，可以一次改一個方法，然後讓 handler 內部同時有 `Admin` and `AsyncAdmin`

@Haser0305 再處理`BalancerHandler`之前，可否先試著將`RebalancePlanExecutor`中的`RebalanceAdmin`取代成為`AsyncAdmin`? 目前大部分的`RebalanceAdmin`功能應該都已經被`AsyncAdmin`取代了，因此我們要先移除`RebalanceAdmin`

**Comment by Haser0305** [comment]
了解
