### ISSUE TITLE
Balancer 應該避免移動特定狀態的 Replica

### ISSUE THREAD

**Issue by chia7712** [skiptests/astraea#934]
Balancer 不應該針對特定狀態的 Replica 做移動，否則可能會造成一些意外

1. `offline` 且只有一個 replica 的 partition：
  當partition 只有一個 replica 而且已經死掉，此時改變配置只會製造更多 zombie replica，因為他們找不到 leader 可以同步資料 ...
2. 沒有 `leader` 的 partition：
   由於 `unclean.leader.election.enable` 參數的影響，當 leader 下線且沒有 ISR follower 能上來頂替時，叢集會因為避免資料遺失而不選舉新的 leader，這個缺乏 leader 的 partition 沒辦法進行資料同步。
3. 正在進行 Data Folder 負載平衡的 Replica
    現在 Data Folder 之間的 replica 移動，在 `Admin#replicas` 的結果下會顯示為兩個獨立的 Replica。從數量上看過去好像 replica factor 會多一，但實際上 `isFuture` 是 false 的那個 replica 不是真的 replica，移動結束後他會消失。這種某個 replica 有 `isFuture` 為 true 的情況下，他的 `isFuture` 為 false 那一份不能視為一個 replica 做移動。

**Comment by chia7712** [comment]
@garyparrot FYI

**Comment by garyparrot** [comment]
我會發一個 PR 處理這個問題。

因為有 [unclean.leader.election.enable](https://kafka.apache.org/documentation/#brokerconfigs_unclean.leader.election.enable) 這類的參數存在，我們可能會出現某個 Partition 有多個 Replica，但是他們都是非 ISR 內的 Replicas 所以沒人可以當上 Leader 的情況。我可能在 ShufflePlanGenerator 內套用『只有有 leader 存在的 topic/partition 能被當做負載平衡對象』這個條件。

執行計劃時可能也有類似問題：負載平衡計劃執行到一半時，遇到 leader 下線且再也上不了線的情況，這個計劃執行可能會沒辦法完成。

**Comment by chia7712** [comment]
> 因為有 [unclean.leader.election.enable](https://kafka.apache.org/documentation/#brokerconfigs_unclean.leader.election.enable) 這類的參數存在，我們可能會出現某個 Partition 有多個 Replica，但是他們都是非 ISR 內的 Replicas 所以沒人可以當上 Leader 的情況。我可能在 ShufflePlanGenerator 內套用『只有有 leader 存在的 topic/partition 能被當做負載平衡對象』這個條件。
執行計劃時可能也有類似問題：負載平衡計劃執行到一半時，遇到 leader 下線且再也上不了線的情況，這個計劃執行可能會沒辦法完成。

這邊要討論的題目是一種“負面列舉”，也就是符合這些條件的 replicas 都要被排除在外，因此可否麻煩你整理有哪些負面列舉？例如我提到一個是 單一 且 offline 的 replica，你提了一個是 all followers are out-of-sync and leader is offline

**Comment by chia7712** [comment]
> 像你提到的例子，我感覺不會有 replica 同時是 offline 又同時是 leader 身份。

我說的不是 leader ，我說的是 partition 只有一個 replica 且又是 offline

> 如果我們做這些檢查是要避免沒有 leader 能同步資料的話

這個也是一種負面列舉，我原本想說的是，我們要先討論一下有”哪些狀況的replicas“是千萬不能動

**Comment by garyparrot** [comment]
> 我們要先討論一下有”哪些狀況的replicas“是千萬不能動

現在 Data Folder 之間的 replica 移動，在 `Admin#replicas` 的結果下會顯示為兩個獨立的 Replica。從數量上看過去好像 replica factor 會多一，但實際上 is future 是 `false` 的那個 replica 不是真的 replica，移動結束後他會消失。這種某個 replica 有 `isFuture` 為 true 的情況下，他的 `isFuture` 為 `false` 那一份不能視為一個 replica 做移動。

**Comment by chia7712** [comment]
> 現在 Data Folder 之間的 replica 移動，在 Admin#replicas 的結果下會顯示為兩個獨立的 Replica。從數量上看過去好像 replica factor 會多一，但實際上 is future 是 false 的那個 replica 不是真的 replica，移動結束後他會消失。這種某個 replica 有 isFuture 為 true 的情況下，他的 isFuture 為 false 那一份不能視為一個 replica 做移動。

很棒，這也是一種負面列舉，麻煩逐一整理到描述裡面，方便討論

**Comment by chia7712** [comment]
@garyparrot 感謝整理，另外也請思考一下程式碼上要怎麼架構才方便我們閱讀出各種條件，同時也方便日後增加更多負面列舉
