### ISSUE TITLE
Replace gson with jackson 

### ISSUE THREAD

**Issue by g1geordie** [skiptests/astraea#974]
> 因為現在執行 gson 沒有問題 有需要在這個時候就把它換成 jackson 嗎

如果會涉及大量變更的話，就在另外一隻PR處理。總之，我們盡可能在整個專案只用一種json工具，如果這邊確定要用jackson的話，那就要後面發PR把gson取代掉

_Originally posted by @chia7712 in https://github.com/skiptests/astraea/pull/848#discussion_r1000687286_

...
**說明** 

- gson : 在反序列化時不需要 default constructor
- jackson : 所有反序列化都需要有 default constructor

**特殊問題**
在兩個框架 在反序列化 `Optional opt;` 的時候 
在 json 中沒有 key(`opt`) 是不會進入反序列話的流程 將導致 opt = null 
所以需要初始化Optioanl

**取代為jackson 的原因 :**  

- gson 不支援 name order 不支援 optional 
- jackson 原生支援以上 

**todo**

1. 確定反序列化沒問題
2. 撰寫test 確定他和他的nested class 都有default constructor  
3. 移除gson dependency

**Comment by g1geordie** [comment]
@chia7712  
 在這個ticket 中我們希望可以 check 所有request 的class 都有implement default constructor 
 想請問
1. 我們 request 怎麼不像 response 一樣直接綁定成物件 要分 key 各別去取得呀
2. 因為目前 request 沒有共通介面。我們是不是要建立一個共通的介面 好讓 test 去識別要檢查哪些class 的default constuctor  呢

**Comment by chia7712** [comment]
> 我們 request 怎麼不像 response 一樣直接綁定成物件 要分 key 各別去取得呀

當時是要方便`List`這個型別裡面可以混合各種型別，所以並沒有要求大家綁定成物件。現在使用jackson應該也會碰到類似的問題，如果沒有方便的解法，我會建議改變APIs的規格，要求使用`array`時綁定的物件都要是同一個類型，也就是下列request視為非法的：
```json
{
  "requests": [
    {
      "a": "b"
    },
    {
      "a": 123
    },
    
  ]
}
```

> 因為目前 request 沒有共通介面。我們是不是要建立一個共通的介面 好讓 test 去識別要檢查哪些class 的default constuctor 呢

yep，可以宣告`Request`和`Response`，並且透過測試來驗證大家都有 default constructor

**Comment by g1geordie** [comment]
根據需求  由於MR 太大 過於容易有衝突 將改為以下幾隻MR


Impl RecordHandler 
>   add json dependency , 
>   add new ` <T> T request(TypeRef<T> typeRef)` to channel  which will replace postReqest
   
impl TopicHandler
impl ThrottleHandler
impl ReassignmentHandler
impl QuotaHandler
impl BalancerHandler
>    remove gson dependency 
>    remove PostReuqest

**Comment by chia7712** [comment]
@g1geordie 感謝，可否把這些題目填寫在描述裡面？看看其他人有沒有機會一起幫忙，在你先完成基礎第一支基礎設施後

**Comment by g1geordie** [comment]
了解  已經補上敘述   要實作的人 
因該可以參考 https://github.com/skiptests/astraea/pull/1128

**Comment by chia7712** [comment]
> 了解 已經補上敘述 要實作的人

主要是 connector client 這個方便的工具還沒合併，需要這個來幫助我們控制 kafka connector

**Comment by chia7712** [comment]
重新開啟此議題，因為尚未完全更新完
