### ISSUE TITLE
在0.1.0 release 之前更新所有GUI的圖片

### ISSUE THREAD

**Issue by chia7712** [skiptests/astraea#998]
由於這段期間我們密集的開發GUI的部分，因此畫面變更得非常快，為了避免REPO膨脹，我們改成在0.1.0釋出前做更新，順便進行手動QA

- 事前準備 (#1194)
- 設定 Astraea GUI (#1294)

**Comment by Haser0305** [comment]
好的，想問一下什麼時候會釋出0.1.0

**Comment by chia7712** [comment]
@Haser0305 https://github.com/skiptests/astraea/issues/885 本來預計是月底，不過看來進度要往後延了 :(

**Comment by chia7712** [comment]
@Haser0305 @chaohengstudent 要麻煩看一下這個議題，剩下兩個禮拜要釋出，應該要開始處理了

**Comment by Haser0305** [comment]
收到

**Comment by chia7712** [comment]
@Haser0305 @chaohengstudent 你們有空協助完成這部分的更新嗎？在12/31之前？

**Comment by Haser0305** [comment]
好的，沒有問題

**Comment by chaohengstudent** [comment]
好的 可以
